//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> InvoiceClassesGenerator.tt
//---
using System;
using System.Threading.Tasks;
using System.Data.Entity.ModelConfiguration;
using POCO = AmitalCloud.Invoice.Domain.EntityPOCOs;
 
namespace AmitalCloud.Invoice.Domain.EntityMapping
{
 
    public class ARInvoiceStockMap : EntityTypeConfiguration<POCO.ARInvoiceStock>
    {
	    string dbms;
        public ARInvoiceStockMap()
        { 
				this.ToTable("ARInvoiceStocks");
		
		    this.HasKey(t => new { t.Id });
	 
            this.Property(t => t.Id).HasColumnName("Id").IsRequired().HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.Tenant).HasColumnName("Tenant").IsRequired();

            this.Property(t => t.CreateDate).HasColumnName("CreateDate").IsRequired();

            this.Property(t => t.CreatedByUserId).HasColumnName("CreatedByUserId").IsRequired().HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.UpdateDate).HasColumnName("UpdateDate").IsRequired();

            this.Property(t => t.UpdatedByUserId).HasColumnName("UpdatedByUserId").IsRequired().HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(40).IsUnicode(false);

            this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(250).IsUnicode(false);

            this.Property(t => t.Inactive).HasColumnName("Inactive").IsRequired();

            this.Property(t => t.StatusCode).HasColumnName("StatusCode").IsRequired().HasMaxLength(2).IsUnicode(false);

            this.Property(t => t.StartDate).HasColumnName("StartDate");

            this.Property(t => t.EndDate).HasColumnName("EndDate");

            this.Property(t => t.Amount).HasColumnName("Amount");

            this.Property(t => t.Remaining).HasColumnName("Remaining");

            this.Property(t => t.Notes).HasColumnName("Notes").HasMaxLength(250).IsUnicode(false);
        }
    }
}
	 