//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> InvoiceClassesGenerator.tt
//---
using System;
using System.Threading.Tasks;
using System.Data.Entity.ModelConfiguration;
using POCO = AmitalCloud.Invoice.Domain.EntityPOCOs;
 
namespace AmitalCloud.Invoice.Domain.EntityMapping
{
 
    public class ExternalSystemsTablesCodeMap : EntityTypeConfiguration<POCO.ExternalSystemsTablesCode>
    {
	    string dbms;
        public ExternalSystemsTablesCodeMap()
        { 
				this.ToTable("ExternalSystemsTablesCodes");
		
		    this.HasKey(t => new { t.Id });
	 
            this.Property(t => t.Id).HasColumnName("Id").IsRequired().HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.Code).HasColumnName("Code").HasMaxLength(40).IsUnicode(false);

            this.Property(t => t.Tenant).HasColumnName("Tenant").IsRequired();

            this.Property(t => t.Name).HasColumnName("Name").HasMaxLength(60).IsUnicode(false);

            this.Property(t => t.LogitudeTable).HasColumnName("LogitudeTable").HasMaxLength(40).IsUnicode(false);

            this.Property(t => t.CreatedDate).HasColumnName("CreatedDate");

            this.Property(t => t.UpdatedDate).HasColumnName("UpdatedDate");

            this.Property(t => t.SearchFields).HasColumnName("SearchFields").HasMaxLength(1000).IsUnicode(true);
        }
    }
}
	 