//------------------------------------------------------------------------------
// <auto-generated>
//     Angular 9.1.1
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { catchError, map } from 'rxjs/operators';
import { defer, of } from 'rxjs';
import {ServiceResponse} from '../../../Infrastructure/DataContracts/ServiceResponse';
import {ClassLevelValidator} from '../../../Infrastructure/Validators/ClassLevelValidator';
import {Guid} from '../../../Infrastructure/Utilities/Guid';
import {InfraSettings} from '../../../Infrastructure/Utilities/InfraSettings';
import {ServiceHelper} from '../../../Infrastructure/Utilities/ServiceHelper';
import {SessionInfo} from '../../../Infrastructure/Utilities/SessionInfo';
import {CustomFieldClass} from '../../../Infrastructure/DataContracts/CustomFieldClass'
import {PerformanceLogger} from '../../../Infrastructure/Utilities/PerformanceLogger';

import {CertificateOfOriginPM} from '../../EntityPMs/CertificateOfOriginPM';

import {CertificateOfOriginInvoicePM} from '../../EntityPMs/CertificateOfOriginInvoicePM';
import {CertificateOfOriginItemPM} from '../../EntityPMs/CertificateOfOriginItemPM';

@Injectable()

export class CertificateOfOriginPMService {
 private _http: HttpClient;
 private _apiUrl: string;
 constructor() {
        this._http = ServiceHelper.HttpClient;
        this._apiUrl = ServiceHelper.GetLogitudeURL() + 'api/certificateoforigins';      
    }

	get(id: string) {       

		var callTime = new Date();		

		return defer(() => {
			return this._http.get(this._apiUrl + '/getsingle?' + 'id=' + id, ServiceHelper.GetHttpFullHeaders())
				.pipe(
					map((response: HttpResponse<any>) => {
						var pm = response.body;
				
						var entity: CertificateOfOriginPM;
						if (pm) {
							entity = this.MapJsonToEntityPM(pm);
						}

						var serviceResponse: ServiceResponse = new ServiceResponse();
						serviceResponse.Result = entity;
              
						var servertime = response.headers.get('ServerExecutionTime');
						PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "CertificateOfOrigin", "GetSinglePM", 'id=' + id);
				 
						return serviceResponse;

					}),
					
					catchError(ServiceHelper.HandleServiceError));
		});                    
	}

	insert(entityPM: CertificateOfOriginPM) {
 
		var callTime = new Date();  
		
		return defer(() => {

			var serviceResponse: ServiceResponse = new ServiceResponse();
			var validator: ClassLevelValidator = new ClassLevelValidator();                
			var errorsArray = validator.Validate("Customs.CertificateOfOrigin", entityPM);


			if (errorsArray.length == 0) {

				var mappedEntity: CertificateOfOriginPM = this.MapJsonToEntityPM(entityPM, false);
				
				return this._http.post(this._apiUrl, JSON.stringify(mappedEntity), ServiceHelper.GetHttpFullHeaders())
					.pipe(
						map((response: HttpResponse<any>) => {

							var pm = response.body;
							if (pm) {
								var mappedResult: CertificateOfOriginPM = this.MapJsonToEntityPM(pm, true, entityPM);
								serviceResponse.Result = mappedResult;
							}						

							var servertime = response.headers.get('ServerExecutionTime');
							PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "CertificateOfOrigin", "SaveChanges", "");                    
												                             
							return serviceResponse;
						}),

						catchError(ServiceHelper.HandleServiceError));
			}

			else {
				serviceResponse.HasError = true;
				serviceResponse.ErrorsArray = errorsArray;
				return of(serviceResponse);
			}
		});
	}

	update(entityPM: CertificateOfOriginPM) {

		var callTime = new Date();     
		
		return defer(() => {

			var serviceResponse: ServiceResponse = new ServiceResponse();
			var validator: ClassLevelValidator = new ClassLevelValidator();               
			var errorsArray = validator.Validate("Customs.CertificateOfOrigin", entityPM);


			if (errorsArray.length == 0) {

				var mappedEntity: CertificateOfOriginPM = this.MapJsonToEntityPM(entityPM, false);
				
				return this._http.put(this._apiUrl, JSON.stringify(mappedEntity), ServiceHelper.GetHttpFullHeaders())
					.pipe(
						map((response: HttpResponse<any>) => {
                 
							var pm = response.body;
							if (pm) {
								var mappedResult: CertificateOfOriginPM = this.MapJsonToEntityPM(pm, true, entityPM);
								serviceResponse.Result = mappedResult;
							}
							 
							var servertime = response.headers.get('ServerExecutionTime');
							PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "CertificateOfOrigin", "SaveChanges", "");                    
					                           
							return serviceResponse;
						}),

						catchError(ServiceHelper.HandleServiceError));
			}

			else {
				serviceResponse.HasError = true;
				serviceResponse.ErrorsArray = errorsArray;
				return of(serviceResponse);
			}
		});
	}

   

	  MapJsonToEntityPM(jsonPM: any, mapParent: boolean = true, entityPM: CertificateOfOriginPM = null) {

         
        if (!entityPM) {
            
            entityPM = new CertificateOfOriginPM();
			entityPM.DisableMarkAsDirty = true;
        }

		var customFields: Array<string> = [];
        for (var i = 1; i < 11; i++) {
            customFields.push("Field" + i);
        }
            var jsonPMKeys = Object.keys(jsonPM);

            for (var key in jsonPMKeys) {
			 if (jsonPMKeys[key] === "UIProperties" || jsonPMKeys[key] === "PropertyChanged") {

                continue;
            }
                var property = jsonPMKeys[key];
				
			  if(customFields.indexOf(property) > -1)
                {
                if (jsonPM[property]) {
                    var customFieldClass: CustomFieldClass = new CustomFieldClass(jsonPM[property].Value, jsonPM[property].FieldName, jsonPM[property].TableName);
                    entityPM[property] = customFieldClass;
                }
            }
            else {
                entityPM[property] = jsonPM[property];
            }
                 
            }
			
               this.MapCertificateOriginInvoiceItems(entityPM, jsonPM, mapParent); // Call composition tables map methods
               this.MapCertificateOriginItemItems(entityPM, jsonPM, mapParent); // Call composition tables map methods
			 
            

		if (mapParent) {
                entityPM.OldEntityPM = this.clone(entityPM);
			   			   
            entityPM.OldEntityPM.CertificateOriginInvoiceItems = [];
            for (var item in entityPM.CertificateOriginInvoiceItems) {
            var myCertificateOfOriginInvoicePM = entityPM.CertificateOriginInvoiceItems[item];
            var newCertificateOfOriginInvoicePM: CertificateOfOriginInvoicePM = this.clone(myCertificateOfOriginInvoicePM);
						
							 
            entityPM.OldEntityPM.CertificateOriginInvoiceItems.push(newCertificateOfOriginInvoicePM);
            }
			   			   			   
            entityPM.OldEntityPM.CertificateOriginItemItems = [];
            for (var item in entityPM.CertificateOriginItemItems) {
            var myCertificateOfOriginItemPM = entityPM.CertificateOriginItemItems[item];
            var newCertificateOfOriginItemPM: CertificateOfOriginItemPM = this.clone(myCertificateOfOriginItemPM);
						
							 
            entityPM.OldEntityPM.CertificateOriginItemItems.push(newCertificateOfOriginItemPM);
            }
			   
		}
        else {

            entityPM.OldEntityPM = null;
        }
		entityPM.IsDirty = false;
	    entityPM.DisableMarkAsDirty = false;

        return entityPM;
    }

    MapCertificateOriginInvoiceItems(entityPM: CertificateOfOriginPM, jsonPM: any, mapParent: boolean = true) {

        var oldCertificateOriginInvoiceItems: CertificateOfOriginInvoicePM[] = [];
        if (entityPM.OldEntityPM && !mapParent) {
            oldCertificateOriginInvoiceItems = entityPM.OldEntityPM.CertificateOriginInvoiceItems;
        }

        entityPM.CertificateOriginInvoiceItems = new Array<CertificateOfOriginInvoicePM>();
        for (var item in jsonPM.CertificateOriginInvoiceItems) {
            var jItem = jsonPM.CertificateOriginInvoiceItems[item];
            if (mapParent && (jItem.ChangeSetOp == "Delete" || jItem.ChangeSetOp == 3)) {
                continue;
            }
            var newCertificateOfOriginInvoicePM: CertificateOfOriginInvoicePM;
	  
            if (mapParent) {
                newCertificateOfOriginInvoicePM = new CertificateOfOriginInvoicePM(entityPM);
            }
            else
            {
                newCertificateOfOriginInvoicePM = new CertificateOfOriginInvoicePM(null);
            }
 			newCertificateOfOriginInvoicePM.DisableMarkAsDirty = true;
               
            var pmKeysArray = Object.keys(jItem);
            for (var pmKey in pmKeysArray) {
                if ((!mapParent && pmKeysArray[pmKey] === "entityParentPM" )|| pmKeysArray[pmKey] === "UIProperties" || pmKeysArray[pmKey] === "PropertyChanged") {
                    continue;
                }
				                  var pmProperty = pmKeysArray[pmKey];
                newCertificateOfOriginInvoicePM[pmProperty] = jItem[pmProperty];
            }
           
			 
            if (mapParent) {
                newCertificateOfOriginInvoicePM.UniqueKey = Guid.newGuid();
                newCertificateOfOriginInvoicePM.ChangeSetOp = "None";
                jItem.ChangeSetOp = "None";
                newCertificateOfOriginInvoicePM.OldEntityPM = this.clone(newCertificateOfOriginInvoicePM);

				
            }
            else {
                if (newCertificateOfOriginInvoicePM.UniqueKey) {

                    if (jItem.IsDirty)
                        newCertificateOfOriginInvoicePM.ChangeSetOp = "Update";
                }
                else {
                        newCertificateOfOriginInvoicePM.ChangeSetOp = "Insert";
                }
 
                newCertificateOfOriginInvoicePM.OldEntityPM = null;
                newCertificateOfOriginInvoicePM.EntityParentPM = null;
            }
			 newCertificateOfOriginInvoicePM.DisableMarkAsDirty = false;
			 newCertificateOfOriginInvoicePM.IsDirty = false;
            entityPM.CertificateOriginInvoiceItems.push(newCertificateOfOriginInvoicePM);
        }
        if (oldCertificateOriginInvoiceItems) {
            
            for (var itemKey in oldCertificateOriginInvoiceItems) {
                if (entityPM.CertificateOriginInvoiceItems.filter(p=> p.UniqueKey === oldCertificateOriginInvoiceItems[itemKey].UniqueKey).length === 0) {
				
                    if (oldCertificateOriginInvoiceItems[itemKey]) {
                        //oldCertificateOriginInvoiceItems[itemKey].ChangeSetOp = "Delete";
                        //entityPM.CertificateOriginInvoiceItems.push(oldCertificateOriginInvoiceItems[itemKey]);
						var oldItemJson = oldCertificateOriginInvoiceItems[itemKey];
                        var deletedPM: CertificateOfOriginInvoicePM = new CertificateOfOriginInvoicePM(null);
						deletedPM.DisableMarkAsDirty = true;
                        var pmKeys = Object.keys(oldItemJson);
                        for (var key in pmKeys) {

                            if ((!mapParent && pmKeys[key] === "entityParentPM") || pmKeys[key] === "UIProperties" || pmKeys[key] === "OldEntityPM" || pmKeys[key] === "PropertyChanged") {
                                continue;
                            }

                            var property = pmKeys[key];
                            deletedPM[property] = oldItemJson[property];
                        }

					    deletedPM.DisableMarkAsDirty = false;
                        deletedPM.IsDirty = false;
                        deletedPM.ChangeSetOp = "Delete";
                        
                        deletedPM.OldEntityPM = null;
                        entityPM.CertificateOriginInvoiceItems.push(deletedPM);
                    }
                }
            }
        }
    }
    MapCertificateOriginItemItems(entityPM: CertificateOfOriginPM, jsonPM: any, mapParent: boolean = true) {

        var oldCertificateOriginItemItems: CertificateOfOriginItemPM[] = [];
        if (entityPM.OldEntityPM && !mapParent) {
            oldCertificateOriginItemItems = entityPM.OldEntityPM.CertificateOriginItemItems;
        }

        entityPM.CertificateOriginItemItems = new Array<CertificateOfOriginItemPM>();
        for (var item in jsonPM.CertificateOriginItemItems) {
            var jItem = jsonPM.CertificateOriginItemItems[item];
            if (mapParent && (jItem.ChangeSetOp == "Delete" || jItem.ChangeSetOp == 3)) {
                continue;
            }
            var newCertificateOfOriginItemPM: CertificateOfOriginItemPM;
	  
            if (mapParent) {
                newCertificateOfOriginItemPM = new CertificateOfOriginItemPM(entityPM);
            }
            else
            {
                newCertificateOfOriginItemPM = new CertificateOfOriginItemPM(null);
            }
 			newCertificateOfOriginItemPM.DisableMarkAsDirty = true;
               
            var pmKeysArray = Object.keys(jItem);
            for (var pmKey in pmKeysArray) {
                if ((!mapParent && pmKeysArray[pmKey] === "entityParentPM" )|| pmKeysArray[pmKey] === "UIProperties" || pmKeysArray[pmKey] === "PropertyChanged") {
                    continue;
                }
				                  var pmProperty = pmKeysArray[pmKey];
                newCertificateOfOriginItemPM[pmProperty] = jItem[pmProperty];
            }
           
			 
            if (mapParent) {
                newCertificateOfOriginItemPM.UniqueKey = Guid.newGuid();
                newCertificateOfOriginItemPM.ChangeSetOp = "None";
                jItem.ChangeSetOp = "None";
                newCertificateOfOriginItemPM.OldEntityPM = this.clone(newCertificateOfOriginItemPM);

				
            }
            else {
                if (newCertificateOfOriginItemPM.UniqueKey) {

                    if (jItem.IsDirty)
                        newCertificateOfOriginItemPM.ChangeSetOp = "Update";
                }
                else {
                        newCertificateOfOriginItemPM.ChangeSetOp = "Insert";
                }
 
                newCertificateOfOriginItemPM.OldEntityPM = null;
                newCertificateOfOriginItemPM.EntityParentPM = null;
            }
			 newCertificateOfOriginItemPM.DisableMarkAsDirty = false;
			 newCertificateOfOriginItemPM.IsDirty = false;
            entityPM.CertificateOriginItemItems.push(newCertificateOfOriginItemPM);
        }
        if (oldCertificateOriginItemItems) {
            
            for (var itemKey in oldCertificateOriginItemItems) {
                if (entityPM.CertificateOriginItemItems.filter(p=> p.UniqueKey === oldCertificateOriginItemItems[itemKey].UniqueKey).length === 0) {
				
                    if (oldCertificateOriginItemItems[itemKey]) {
                        //oldCertificateOriginItemItems[itemKey].ChangeSetOp = "Delete";
                        //entityPM.CertificateOriginItemItems.push(oldCertificateOriginItemItems[itemKey]);
						var oldItemJson = oldCertificateOriginItemItems[itemKey];
                        var deletedPM: CertificateOfOriginItemPM = new CertificateOfOriginItemPM(null);
						deletedPM.DisableMarkAsDirty = true;
                        var pmKeys = Object.keys(oldItemJson);
                        for (var key in pmKeys) {

                            if ((!mapParent && pmKeys[key] === "entityParentPM") || pmKeys[key] === "UIProperties" || pmKeys[key] === "OldEntityPM" || pmKeys[key] === "PropertyChanged") {
                                continue;
                            }

                            var property = pmKeys[key];
                            deletedPM[property] = oldItemJson[property];
                        }

					    deletedPM.DisableMarkAsDirty = false;
                        deletedPM.IsDirty = false;
                        deletedPM.ChangeSetOp = "Delete";
                        
                        deletedPM.OldEntityPM = null;
                        entityPM.CertificateOriginItemItems.push(deletedPM);
                    }
                }
            }
        }
    }

	  public clone(jsonPM: any) {
        var entityPM: any;
        entityPM = {};

        var jsonPMKeys = Object.keys(jsonPM);
        for (var key in jsonPMKeys) {
            
            if ((jsonPMKeys[key] === "entityParentPM") || jsonPMKeys[key] === "UIProperties" || jsonPMKeys[key] === "OldEntityPM" || jsonPMKeys[key] === "PropertyChanged") {
                continue;
            }

            var property = jsonPMKeys[key];
            entityPM[property] = jsonPM[property];

        }
        return entityPM;
    }

	  public GetNewEntityPM() {		 
		    var entityPM: CertificateOfOriginPM;
			entityPM = new CertificateOfOriginPM();
			entityPM.Tenant = InfraSettings.TenantPM.Id;
			return entityPM;
    }
		 

}
