<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- © 2015 Global Logistics System (HK) Company Limited -->
	<!-- GLSHK Cargo Message XML version 2.0.3 -->
	<xs:include schemaLocation="glshk_cargomsg_elements_2_0.xsd"/>
	<xs:element name="Envelope">
		<xs:annotation>
			<xs:documentation>Message Envelope</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SenderID">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="35"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="RecipientID">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="35"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MsgFormat" default="XML">
					<xs:annotation>
						<xs:documentation>XML</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="6"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Password" type="xs:string" minOccurs="0"/>
				<xs:element name="RefID">
					<xs:annotation>
						<xs:documentation>Common Access Reference</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="35"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MsgType">
					<xs:annotation>
						<xs:documentation>CIMFWB,CIMFHL,CIMFSU,CIMFNA or CIMFMA</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="6"/>
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Version">
					<xs:annotation>
						<xs:documentation>Target Message Version</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:totalDigits value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MsgDateTime" type="xs:dateTime"/>
				<xs:choice>
					<xs:annotation>
						<xs:documentation>either EzyCargo agent or Key Coloader</xs:documentation>
					</xs:annotation>
					<xs:element name="CompanyID">
						<xs:annotation>
							<xs:documentation>EzyCargo Company ID</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:maxLength value="20"/>
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="ColoaderKey">
						<xs:annotation>
							<xs:documentation>EzyCargo Coloader Key</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:maxLength value="50"/>
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:choice>
				<xs:element name="Function" type="xs:string" minOccurs="0"/>
				<xs:element name="ReverseRoutingAddr" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="14"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="InterchangeControlRef">
					<xs:annotation>
						<xs:documentation>Interchange Control Reference</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="14"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MessageRefNum">
					<xs:annotation>
						<xs:documentation>Message Reference Number</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="14"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Priority" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Reserved" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Message">
		<xs:annotation>
			<xs:documentation>Transmission Message</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Envelope"/>
				<xs:choice>
					<xs:element ref="FSU"/>
					<xs:element ref="FWB"/>
					<xs:element ref="FHL"/>
					<xs:element ref="FMA"/>
					<xs:element ref="FNA"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:annotation>
					<xs:documentation>XML Schema version</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="2.0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>
