<!ELEMENT LOGISIVUG (SIVUG*)>
<!ELEMENT SIVUG (LOGITUDEFILE?, TENANT?, INVOICE*, CustomsDocuments*)>
<!ELEMENT LOGITUDEFILE (#PCDATA)>
<!ELEMENT TENANT (#PCDATA)>
<!ELEMENT INVOICE (INVOICELINENO?, ACCOUNTTYPE?, INVOICENUMBER?, VENDORNUMBER?, CURRENCYCODE?, INVOICEAMOUNT?, ISSUEDATE?, ISSUECOUNTRYCODE?, SI_COUNTER?, INCOTERM_ID?, INVOICEITEMS*, ChangeInSupplierInvoice?, QUE_TYPE?)>
<!ELEMENT INVOICELINENO (#PCDATA)>
<!ELEMENT ACCOUNTTYPE (#PCDATA)>
<!ELEMENT INVOICENUMBER (#PCDATA)>
<!ELEMENT VENDORNUMBER (#PCDATA)>
<!ELEMENT CURRENCYCODE (#PCDATA)>
<!ELEMENT INVOICEAMOUNT (#PCDATA)>
<!ELEMENT ISSUEDATE (#PCDATA)>
<!ELEMENT ISSUECOUNTRYCODE (#PCDATA)>
<!ELEMENT SI_COUNTER (#PCDATA)>
<!ELEMENT INCOTERM_ID (#PCDATA)>
<!ELEMENT INVOICEITEMS (ITEMLINENO?, CLASSIFICATIONCODE?, TRADEAGREEMENTCODE?, QUANTITY?, ITEMPRICE?, ITEMORIGINCOUNTRY?, ITEMCODE?, ACTUALINVOICELINES?, ITEM_SI_COUNTER?, LINE_ID?, APPROV_TYPE_ID?, CLASIFIEDREMARKS?, UNIT_ID?, TAXEXEMPTCODE?, StatisticQuantity?, StatisticQuantityType?, OcrPageNumber?, OcrTop?, OcrHeight?, AdditionalQuantity?, AdditionalQuantityType?, CERTIFICATES*, EXPENSES*)>
<!ELEMENT ITEMLINENO (#PCDATA)>
<!ELEMENT CLASSIFICATIONCODE (#PCDATA)>
<!ELEMENT TRADEAGREEMENTCODE (#PCDATA)>
<!ELEMENT QUANTITY (#PCDATA)>
<!ELEMENT ITEMPRICE (#PCDATA)>
<!ELEMENT ITEMORIGINCOUNTRY (#PCDATA)>
<!ELEMENT ITEMCODE (#PCDATA)>
<!ELEMENT ACTUALINVOICELINES (#PCDATA)>
<!ELEMENT ITEM_SI_COUNTER (#PCDATA)>
<!ELEMENT LINE_ID (#PCDATA)>
<!ELEMENT APPROV_TYPE_ID (#PCDATA)>
<!ELEMENT CLASIFIEDREMARKS (#PCDATA)>
<!ELEMENT UNIT_ID (#PCDATA)>
<!ELEMENT TAXEXEMPTCODE (#PCDATA)>
<!ELEMENT StatisticQuantity (#PCDATA)>
<!ELEMENT StatisticQuantityType (#PCDATA)>
<!ELEMENT OcrPageNumber (#PCDATA)>
<!ELEMENT OcrTop (#PCDATA)>
<!ELEMENT OcrHeight (#PCDATA)>
<!ELEMENT AdditionalQuantity (#PCDATA)>
<!ELEMENT AdditionalQuantityType (#PCDATA)>
<!ELEMENT CERTIFICATES (REQ_CERT_ID?, GCRCRTF_ID?, CERTIFICATE_NO?, APPROV_CODE?, APPROV_TYPE?, ADD_REQUEST_NO?, REQUEST_NO?)>
<!ELEMENT REQ_CERT_ID (#PCDATA)>
<!ELEMENT GCRCRTF_ID (#PCDATA)>
<!ELEMENT CERTIFICATE_NO (#PCDATA)>
<!ELEMENT APPROV_CODE (#PCDATA)>
<!ELEMENT APPROV_TYPE (#PCDATA)>
<!ELEMENT ADD_REQUEST_NO (#PCDATA)>
<!ELEMENT REQUEST_NO (#PCDATA)>
<!ELEMENT EXPENSES (TypeCode?, Amount?, CurrencyTypeCode?)>
<!ELEMENT TypeCode (#PCDATA)>
<!ELEMENT Amount (#PCDATA)>
<!ELEMENT CurrencyTypeCode (#PCDATA)>
<!ELEMENT ChangeInSupplierInvoice (#PCDATA)>
<!ELEMENT QUE_TYPE (#PCDATA)>
<!ELEMENT CustomsDocuments (Entname?, DocumentTypeCode?, Blocked?, FromDeclartion?, COM_ID?, SerialNum?, UNFINVOICEKEY?, CommChanged?)>
<!ELEMENT Entname (#PCDATA)>
<!ELEMENT DocumentTypeCode (#PCDATA)>
<!ELEMENT Blocked (#PCDATA)>
<!ELEMENT FromDeclartion (#PCDATA)>
<!ELEMENT COM_ID (#PCDATA)>
<!ELEMENT SerialNum (#PCDATA)>
<!ELEMENT UNFINVOICEKEY (#PCDATA)>
<!ELEMENT CommChanged (#PCDATA)>
