//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> Amital\EntityKeysGenerator.tt from AmitalClassesGenerator.tt
//---
using AmitalCloud.Infrastructure.Domain.BaseClasses;
using System;
using System.Collections.Generic;
using System.Linq;  
using System.Linq.Expressions;
namespace AmitalCloud.Infrastructure.Domain.EntityKeys
{
   public class DocumentOutCopyKeys<T> : BaseEntityKeyFields<EntityPOCOs.DocumentOutCopy,T> 
   {
		public DocumentOutCopyKeys() : base() {}
        public DocumentOutCopyKeys(IEnumerable<KeyValuePair<string, string>> paramList) : base(paramList) {}
        public override void Initialize(IEnumerable<KeyValuePair<string, string>> paramList)
        {
			Id = (string)Convert.ChangeType((paramList.Single(t => t.Key == "Id").Value), typeof(string));
        }
   	  public string Id  { get; set; }
	    			   
	  public override T GetFullKey() =>   (T)Convert.ChangeType(Id.ToString(),typeof(T)) ;           
      public override string GetEntityPMName() => "DocumentOutCopysPM";
	  public override Expression<Func<EntityPOCOs.DocumentOutCopy, bool>> Predicate => a => a.Id == Id;
   }
}
	 