  
SET SERVEROUTPUT ON

DECLARE 

   c_id supplierinvoices.DeclarationId%type;
   c_Tenant SupplierInvoices.Tenant%TYPE;

  
  CURSOR SupplierInvoicesCounterKey  is
     SELECT  DeclarationId, Tenant from SupplierInvoices where InvoiceCounterKey =0; 
BEGIN
OPEN SupplierInvoicesCounterKey;
   LOOP
      FETCH SupplierInvoicesCounterKey into c_id, c_Tenant;
      EXIT WHEN SupplierInvoicesCounterKey%notfound;
      
      BEGIN
      
      insert into supplierinvoices ( DECLARATIONID, INVOICECOUNTERKEY, TENANT, SEQUENCENUMERIC, INVOICENUMBER, ISSUEDATE, ACCOUNTTYPECODE, ISPREFERENCE, PREFERENCEDOCUMENTTYPECODE, PAYMENTTYPECODE,
      INVOICECURRENCYTYPECODE, INVOICEAMOUNT, ACTUALPAYEDCURRENCYTYPECODE, ACTUALPAYEDAMOUNT, VENDORID, INCOTERMCODE, ISSUECOUNTRYCODE, PAYMENTTERMSCODE, TOTALFREIGHTINFREIGHTCURRENCY, TOTALFREIGHTINNIS,
      EXCHANGERATE, INSRUANCECURRENCYTYPECODE, INSURANCEAMOUNT, INSRUANCEPERCENTAGE, FREIGHTCURRENCYTYPECODE) (select DECLARATIONID, 1, TENANT, SEQUENCENUMERIC, INVOICENUMBER, ISSUEDATE, ACCOUNTTYPECODE, ISPREFERENCE, PREFERENCEDOCUMENTTYPECODE, PAYMENTTYPECODE,
      INVOICECURRENCYTYPECODE, INVOICEAMOUNT, ACTUALPAYEDCURRENCYTYPECODE, ACTUALPAYEDAMOUNT, VENDORID, INCOTERMCODE, ISSUECOUNTRYCODE, PAYMENTTERMSCODE, TOTALFREIGHTINFREIGHTCURRENCY, TOTALFREIGHTINNIS,
      EXCHANGERATE, INSRUANCECURRENCYTYPECODE, INSURANCEAMOUNT, INSRUANCEPERCENTAGE, FREIGHTCURRENCYTYPECODE from supplierinvoices where declarationid = c_id and INVOICECOUNTERKEY=0);
      
      Insert into supplierinvoiceitems  ( DeclarationId, 
      CounterKey,
      LineNumber,
      ItemCode,
      OriginCountryCode,
      ClassificationCode,
      DangerousClassificationCode,
      DangerousPackingGroupTypeCode,
      ItemPrice,
      NonCustomsItemPrice,
      WholeSaleItemPrice,
      ManufactureIdentifier,
      CustomsBookTypeCode,
      TaxExemptCode,
      OptionalTamaPercentage,
      SalesTaxExemptionTypeCode,
      Tenant,
      ItemPriceCurrencyCode,
      NonCustomsItemPriceCurCode,
      WholeSaleItemPriceCurrencyCode,
      ActualInvoiceLines,
      SequenceNumeric,
      TradeAgreementCode,
      StatisticQuantity,
      InvoiceQuantity,
      AdditionalQuantity,
      InvoiceQuantityType,
      StatisticQuantityType,
      AdditionalQuantityType,
      PreferenceDocumentNumber,
      ItemDescription,
      CertificatesStatusCode,
      IsUsed )  
    (select  DeclarationId,
      1,
      LineNumber,
      ItemCode,
      OriginCountryCode,
      ClassificationCode,
      DangerousClassificationCode,
      DangerousPackingGroupTypeCode,
      ItemPrice,
      NonCustomsItemPrice,
      WholeSaleItemPrice,
      ManufactureIdentifier,
      CustomsBookTypeCode,
      TaxExemptCode,
      OptionalTamaPercentage,
      SalesTaxExemptionTypeCode,
      Tenant,
      ItemPriceCurrencyCode,
      NonCustomsItemPriceCurCode,
      WholeSaleItemPriceCurrencyCode,
      ActualInvoiceLines,
      SequenceNumeric,
      TradeAgreementCode,
      StatisticQuantity,
      InvoiceQuantity,
      AdditionalQuantity,
      InvoiceQuantityType,
      StatisticQuantityType,
      AdditionalQuantityType,
      PreferenceDocumentNumber,
      ItemDescription,
      CertificatesStatusCode,
      IsUsed from  supplierinvoiceitems  where declarationId=c_id and counterkey=0);  
      
      
      insert into SUPPLIERINVIOCEITEMCERTIFICATS (DECLARATIONID,INVOICECOUNTERKEY,LINENUMBER,ITEMCERTIFICATECOUNTERKEY,CERTIFICATENUMBER,TENANT,REQCONFIRMATIONTYPECODE,CERTIFICATEEXEMPTIONTYPECODE,
      ATTACHMENTTYPECODE,RESCONFIRMATIONTYPECODE,CUSTOMSATTACHMENTID,SEQUENCENUMERIC)   ( select DECLARATIONID,1,LINENUMBER,ITEMCERTIFICATECOUNTERKEY,CERTIFICATENUMBER,TENANT,REQCONFIRMATIONTYPECODE,CERTIFICATEEXEMPTIONTYPECODE,
      ATTACHMENTTYPECODE,RESCONFIRMATIONTYPECODE,CUSTOMSATTACHMENTID,SEQUENCENUMERIC from SUPPLIERINVIOCEITEMCERTIFICATS where declarationId =c_id and INVOICECOUNTERKEY =0);
      


 
 insert into SUPPLIERINVOICEFREIGHTAMOUNTS (DECLARATIONID, INVOICECOUNTERKEY,CURRENCYTYPECODE,TENANT,AMOUNT) (select  DECLARATIONID, 1,CURRENCYTYPECODE,TENANT,AMOUNT 
 from SUPPLIERINVOICEFREIGHTAMOUNTS where declarationid =c_id and INVOICECOUNTERKEY=0);

 
 insert into SUPPLIERINVOICEITEMMODVEHICLES (DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, ADJUSTMENTTYPECODE, DEDUCTAMOUNT, TENANT ) (select DECLARATIONID, 1, INVOICEITEMLINENUMBER, ADJUSTMENTTYPECODE, DEDUCTAMOUNT, TENANT
 from SUPPLIERINVOICEITEMMODVEHICLES where declarationid =c_id and INVOICECOUNTERKEY=0);
  


insert into SUPPLIERINVOICEITEMPROCESTYPES (DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, PROCESSTYPECODE  ) (select DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, PROCESSTYPECODE
from SUPPLIERINVOICEITEMPROCESTYPES where declarationid= c_id and INVOICECOUNTERKEY=0);


insert into SUPPLIERINVOICEITEMSCERTEMP (DECLARATIONID, INVOICECOUNTERKEY, LINENUMBER, ITEMCERTIFICATECOUNTERKEY, CERTIFICATENUMBER, TENANT, REQCONFIRMATIONTYPECODE, CERTIFICATEEXEMPTIONTYPECODE, 
ATTACHMENTTYPECODE, RESCONFIRMATIONTYPECODE , CUSTOMSATTACHMENTID, SEQUENCENUMERIC) (select DECLARATIONID, 1, LINENUMBER, ITEMCERTIFICATECOUNTERKEY, CERTIFICATENUMBER, TENANT, REQCONFIRMATIONTYPECODE, CERTIFICATEEXEMPTIONTYPECODE, 
ATTACHMENTTYPECODE, RESCONFIRMATIONTYPECODE , CUSTOMSATTACHMENTID, SEQUENCENUMERIC from SUPPLIERINVOICEITEMSCERTEMP where declarationid= c_id and INVOICECOUNTERKEY =0);



 insert into  SUPPLIERINVOICEITEMSCONDECLARS  (DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, DECLARATIONNUMBER, ITEMSEQUENCE, DECLARATIONTYPECODE, INVOICENUMBER, 
QUANTITY, QUANTITYTYPECODE) (select DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, DECLARATIONNUMBER, ITEMSEQUENCE, DECLARATIONTYPECODE, INVOICENUMBER, 
QUANTITY, QUANTITYTYPECODE from SUPPLIERINVOICEITEMSCONDECLARS where declarationId = c_id and INVOICECOUNTERKEY=0);



  insert into SUPPLIERINVOICEITEMSDESCRIPTS (DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, TYPECODE, DESCRIPTION) 
  (select DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, TYPECODE, DESCRIPTION from SUPPLIERINVOICEITEMSDESCRIPTS where declarationId =c_id and INVOICECOUNTERKEY=0);


 
 insert into SUPPLIERINVOICEITEMSLEVIES ( DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, TRADELEVYEXAMPTCODE, TRADELEVYNUMBER)
  (select DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, TENANT, TRADELEVYEXAMPTCODE, TRADELEVYNUMBER from SUPPLIERINVOICEITEMSLEVIES where declarationid =c_id and INVOICECOUNTERKEY=0);
 
   
 
 
    insert into SUPPLIERINVOICEITEMSMODS  ( DECLARATIONID, INVOICECOUNTERKEY, LINENUMBER, MODIFICATIONCOUNTERKEY,   TYPECODE, TENANT, CURRENCYTYPECODE, AMOUNT)
    (select  DECLARATIONID, 1, LINENUMBER, MODIFICATIONCOUNTERKEY,   TYPECODE, TENANT, CURRENCYTYPECODE, AMOUNT from SUPPLIERINVOICEITEMSMODS where declarationid =c_id and INVOICECOUNTERKEY=0);

  
     
     insert into SUPPLIERINVOICEITEMSPRODIDENTS ( DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, TENANT,TYPECODE, IDENTIFICATION)
     (select  DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, TENANT,TYPECODE, IDENTIFICATION from SUPPLIERINVOICEITEMSPRODIDENTS where declarationid =c_id and INVOICECOUNTERKEY =0);
 
      
       
       insert into SUPPLIERINVOICEITEMSSERIALNUMS ( DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, TENANT,TYPECODE,SERIALNUMBER)
       (select   DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, TENANT,TYPECODE,SERIALNUMBER from SUPPLIERINVOICEITEMSSERIALNUMS where declarationid =c_id and INVOICECOUNTERKEY =0);
 
     
       
       insert into  SUPPLIERINVOICEITEMSTAXES ( DECLARATIONID, INVOICECOUNTERKEY, LINENUMBER , TAXTYPECODE, TENANT, TRADEAGREEMENTTYPECODE, TAXRATE, TAXBASEAMOUNT, TAXAMOUNT, DEFEREDTAXAMOUNT,
       DEFINEDPERUNITMEASURE, ALTERNATEDEFINEDPERUNITMEASURE, DEFINEDPERUNITQUANTITY, ALTERNATEDEFINEDPERUNITQUANT, MEASUREMENTUNITCODE, ALTERNATEMEASUREMENTUNITCODE, TRADELEVYNUMBER, 
       TOTALBTLCOVERAGENIS, ALTERNATERATE) (select DECLARATIONID, 1, LINENUMBER , TAXTYPECODE, TENANT, TRADEAGREEMENTTYPECODE, TAXRATE, TAXBASEAMOUNT, TAXAMOUNT, DEFEREDTAXAMOUNT,
       DEFINEDPERUNITMEASURE, ALTERNATEDEFINEDPERUNITMEASURE, DEFINEDPERUNITQUANTITY, ALTERNATEDEFINEDPERUNITQUANT, MEASUREMENTUNITCODE, ALTERNATEMEASUREMENTUNITCODE, TRADELEVYNUMBER, 
       TOTALBTLCOVERAGENIS, ALTERNATERATE from SUPPLIERINVOICEITEMSTAXES where declarationid =c_id and INVOICECOUNTERKEY =0);
  
  
   
  
   insert into SUPPLIERINVOICEITEMVEHICLES ( DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, SEQUENCENUMERIC, VEHICLETYPECODE, VEHICLECHASSISNUMBER, RICHBITFILENUMBER, 
      VEHICLEID, TENANT ) ( select  DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, SEQUENCENUMERIC, VEHICLETYPECODE, VEHICLECHASSISNUMBER, RICHBITFILENUMBER, 
      VEHICLEID, TENANT from SUPPLIERINVOICEITEMVEHICLES where  declarationid =c_id and INVOICECOUNTERKEY =0);
      
   insert into SUPPLIERINVOICEITEMVEHICLEADDS ( DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, LINENUMBER, VEHICLEMODEL, RICHBITNUMBER, CHASSISNUMBER, ENGINENUMBER, VEHICLEVALUE,
  CHASSISTAX, CHASSISPURCHASETAX, CHASSISVAT, EXEMPT_TYPE, WINDOWNUMBER) (select DECLARATIONID, 1, INVOICEITEMLINENUMBER, LINENUMBER, VEHICLEMODEL, RICHBITNUMBER, CHASSISNUMBER, ENGINENUMBER, VEHICLEVALUE,
  CHASSISTAX, CHASSISPURCHASETAX, CHASSISVAT, EXEMPT_TYPE, WINDOWNUMBER from SUPPLIERINVOICEITEMVEHICLEADDS  where  declarationid =c_id and INVOICECOUNTERKEY =0); 


  
   
    insert into SUPPLIERINVOICEITEMVEHICLEMODS (DECLARATIONID, INVOICECOUNTERKEY, INVOICEITEMLINENUMBER, VEHICLELINENUMBER, LINENUMBER, ADJUSTMENTTYPECODE, DEDUCTAMOUNT, TENANT)
   (select DECLARATIONID, 1, INVOICEITEMLINENUMBER, VEHICLELINENUMBER, LINENUMBER, ADJUSTMENTTYPECODE, DEDUCTAMOUNT, TENANT from SUPPLIERINVOICEITEMVEHICLEMODS 
   where declarationid = c_id and INVOICECOUNTERKEY =0); 
   

    
    insert into SUPPLIERINVOICEMODIFICATIONS (DECLARATIONID, INVOICECOUNTERKEY , MODIFICATIONCOUNTERKEY, TYPECODE, TENANT, CURRENCYTYPECODE, AMOUNT)
    (select DECLARATIONID, 1 , MODIFICATIONCOUNTERKEY, TYPECODE, TENANT, CURRENCYTYPECODE, AMOUNT from SUPPLIERINVOICEMODIFICATIONS where  declarationid = c_id and INVOICECOUNTERKEY =0);
    
    
    
  --Dbms_Output.Put_Line(c_id);
   
      END;
      
      END LOOP;
 
      CLOSE SupplierInvoicesCounterKey;
      
     END;

     
/


/


   delete from SUPPLIERINVIOCEITEMCERTIFICATS where  invoicecounterkey=0;
   delete from SUPPLIERINVOICEFREIGHTAMOUNTS where  invoicecounterkey=0;
   delete from SUPPLIERINVOICEITEMMODVEHICLES where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMPROCESTYPES where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMSCERTEMP where INVOICECOUNTERKEY =0;
   delete from SUPPLIERINVOICEITEMSCONDECLARS where  INVOICECOUNTERKEY =0;
   delete from SUPPLIERINVOICEITEMSDESCRIPTS where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMSLEVIES  where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMSMODS  where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMSPRODIDENTS  where INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMSSERIALNUMS where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMSTAXES where INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMVEHICLEADDS where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEITEMVEHICLEMODS where  INVOICECOUNTERKEY=0;
  delete from SUPPLIERINVOICEITEMVEHICLES  where  INVOICECOUNTERKEY=0;
   delete from SUPPLIERINVOICEMODIFICATIONS where   INVOICECOUNTERKEY=0;
   delete from supplierinvoiceitems where  COUNTERKEY=0;
    delete from supplierinvoices where   INVOICECOUNTERKEY=0;
   
   
   
   

   
   
   
