


CREATE TABLE SupplierInvoiceItemsTemp ( DeclarationId VARCHAR2(15 CHAR) NOT NULL, CounterKey NUMBER(10,0) NOT NULL, LineNumber NUMBER(10,0) NOT NULL, ItemCode VARCHAR2(30 CHAR) , 
OriginCountryCode VARCHAR2(2 CHAR) , ClassificationCode VARCHAR2(11 CHAR) , DangerousClassificationCode VARCHAR2(11 CHAR) , DangerousPackingGroupTypeCode VARCHAR2(3 CHAR) , ItemPrice NUMBER(16,2) , 
NonCustomsItemPrice NUMBER(16,2) , WholeSaleItemPrice NUMBER(16,2) , ManufactureIdentifier VARCHAR2(17 CHAR) , CustomsBookTypeCode VARCHAR2(4 CHAR) , TaxExemptCode VARCHAR2(15 CHAR) , 
OptionalTamaPercentage NUMBER(18,2) , SalesTaxExemptionTypeCode VARCHAR2(4 CHAR) , Tenant NUMBER(10,0) NOT NULL, ItemPriceCurrencyCode VARCHAR2(3 CHAR) , NonCustomsItemPriceCurCode VARCHAR2(3 CHAR) ,
WholeSaleItemPriceCurrencyCode VARCHAR2(3 CHAR) , ActualInvoiceLines VARCHAR2(512 CHAR) , SequenceNumeric NUMBER(10,0) , TradeAgreementCode VARCHAR2(8 CHAR) , 
StatisticQuantity NUMBER(14,3) , InvoiceQuantity NUMBER(14,3) , AdditionalQuantity NUMBER(14,3) , InvoiceQuantityType VARCHAR2(3 CHAR) ,
  StatisticQuantityType VARCHAR2(3 CHAR) , AdditionalQuantityType VARCHAR2(3 CHAR) , PreferenceDocumentNumber VARCHAR2(35 CHAR) , ItemDescription NVARCHAR2(30) ,
  CertificatesStatusCode VARCHAR2(1 CHAR) , IsUsed NUMBER(1,0) NOT NULL );


/


create or replace PROCEDURE usp_CopySupplierInvoiceItems(
    v_SourceDeclarationId IN VARCHAR2,
    v_TargetDeclarationId IN VARCHAR2,
    v_Tenant              IN NUMBER,
    cv_1 OUT SYS_REFCURSOR )
AS
BEGIN
delete from SupplierInvoiceItemsTemp;
  INSERT INTO SupplierInvoiceItemsTemp(
      DeclarationId,
      CounterKey,
      LineNumber,
      ItemCode,
      OriginCountryCode,
      ClassificationCode,
      DangerousClassificationCode,
      DangerousPackingGroupTypeCode,
      ItemPrice,
      NonCustomsItemPrice,
      WholeSaleItemPrice,
      ManufactureIdentifier,
      CustomsBookTypeCode,
      TaxExemptCode,
      OptionalTamaPercentage,
      SalesTaxExemptionTypeCode,
      Tenant,
      ItemPriceCurrencyCode,
      NonCustomsItemPriceCurCode,
      WholeSaleItemPriceCurrencyCode,
      ActualInvoiceLines,
      SequenceNumeric,
      TradeAgreementCode,
      StatisticQuantity,
      InvoiceQuantity,
      AdditionalQuantity,
      InvoiceQuantityType,
      StatisticQuantityType,
      AdditionalQuantityType,
      PreferenceDocumentNumber,
      ItemDescription,
      CertificatesStatusCode,
      IsUsed
    )
    (SELECT  DeclarationId,
      CounterKey,
      LineNumber,
      ItemCode,
      OriginCountryCode,
      ClassificationCode,
      DangerousClassificationCode,
      DangerousPackingGroupTypeCode,
      ItemPrice,
      NonCustomsItemPrice,
      WholeSaleItemPrice,
      ManufactureIdentifier,
      CustomsBookTypeCode,
      TaxExemptCode,
      OptionalTamaPercentage,
      SalesTaxExemptionTypeCode,
      Tenant,
      ItemPriceCurrencyCode,
      NonCustomsItemPriceCurCode,
      WholeSaleItemPriceCurrencyCode,
      ActualInvoiceLines,
      SequenceNumeric,
      TradeAgreementCode,
      StatisticQuantity,
      InvoiceQuantity,
      AdditionalQuantity,
      InvoiceQuantityType,
      StatisticQuantityType,
      AdditionalQuantityType,
      PreferenceDocumentNumber,
      ItemDescription,
      CertificatesStatusCode,
      IsUsed
      FROM SupplierInvoiceItems
      WHERE DeclarationId = v_SourceDeclarationId
      AND Tenant          = v_Tenant
    );
  UPDATE SupplierInvoiceItemsTemp SET DeclarationId = v_TargetDeclarationId;
  OPEN cv_1 FOR SELECT * FROM SupplierInvoiceItemsTemp ;
  INSERT INTO SupplierInvoiceItems(
      DeclarationId,
      CounterKey,
      LineNumber,
      ItemCode,
      OriginCountryCode,
      ClassificationCode,
      DangerousClassificationCode,
      DangerousPackingGroupTypeCode,
      ItemPrice,
      NonCustomsItemPrice,
      WholeSaleItemPrice,
      ManufactureIdentifier,
      CustomsBookTypeCode,
      TaxExemptCode,
      OptionalTamaPercentage,
      SalesTaxExemptionTypeCode,
      Tenant,
      ItemPriceCurrencyCode,
      NonCustomsItemPriceCurCode,
      WholeSaleItemPriceCurrencyCode,
      ActualInvoiceLines,
      SequenceNumeric,
      TradeAgreementCode,
      StatisticQuantity,
      InvoiceQuantity,
      AdditionalQuantity,
      InvoiceQuantityType,
      StatisticQuantityType,
      AdditionalQuantityType,
      PreferenceDocumentNumber,
      ItemDescription,
      CertificatesStatusCode,
      IsUsed
    )
    ( SELECT   DeclarationId,
      CounterKey,
      LineNumber,
      ItemCode,
      OriginCountryCode,
      ClassificationCode,
      DangerousClassificationCode,
      DangerousPackingGroupTypeCode,
      ItemPrice,
      NonCustomsItemPrice,
      WholeSaleItemPrice,
      ManufactureIdentifier,
      CustomsBookTypeCode,
      TaxExemptCode,
      OptionalTamaPercentage,
      SalesTaxExemptionTypeCode,
      Tenant,
      ItemPriceCurrencyCode,
      NonCustomsItemPriceCurCode,
      WholeSaleItemPriceCurrencyCode,
      ActualInvoiceLines,
      SequenceNumeric,
      TradeAgreementCode,
      StatisticQuantity,
      InvoiceQuantity,
      AdditionalQuantity,
      InvoiceQuantityType,
      StatisticQuantityType,
      AdditionalQuantityType,
      PreferenceDocumentNumber,
      ItemDescription,
      CertificatesStatusCode,
      IsUsed  FROM SupplierInvoiceItemsTemp
    );

END;

/
