using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using Simplog.Server.Infrastructure;
using Logitude.Customs.Data.EntityPOCOs;

namespace Logitude.Customs.Data
{

    public partial interface ICustomContext : IContext
    {
   
       	 IDbSet<AcceptanceStatus> AcceptanceStatuses { get; }
		 IDbSet<AccumalationState> AccumalationStates { get; }
		 IDbSet<ActionCode> ActionCodes { get; }
		 IDbSet<AddressContactState> AddressContactStates { get; }
		 IDbSet<AddressPurpose> AddressPurposes { get; }
		 IDbSet<AgentTalkBackType> AgentTalkBackTypes { get; }
		 IDbSet<AmedmentType> AmedmentTypes { get; }
		 IDbSet<AmendCancellRequestInitiator> AmendCancellRequestInitiators { get; }
		 IDbSet<AmendmentFieldReasonType> AmendmentFieldReasonTypes { get; }
		 IDbSet<AmendmentFieldStatusType> AmendmentFieldStatusTypes { get; }
		 IDbSet<AmendmentRequestStatus> AmendmentRequestStatuses { get; }
		 IDbSet<AmendmentStatus> AmendmentStatuses { get; }
		 IDbSet<AmendmentType> AmendmentTypes { get; }
		 IDbSet<AmendRequestRejectReasonType> AmendRequestRejectReasonTypes { get; }
		 IDbSet<AmountType> AmountTypes { get; }
		 IDbSet<ApprovedProfession> ApprovedProfessions { get; }
		 IDbSet<AssigneeNotificationType> AssigneeNotificationTypes { get; }
		 IDbSet<AttachmentType> AttachmentTypes { get; }
		 IDbSet<Authority> Authorities { get; }
		 IDbSet<AuthorizedSignerPermit> AuthorizedSignerPermits { get; }
		 IDbSet<AutonomyRegionType> AutonomyRegionTypes { get; }
		 IDbSet<AutonomyType> AutonomyTypes { get; }
		 IDbSet<Bank> Banks { get; }
		 IDbSet<BuyerRoleType> BuyerRoleTypes { get; }
		 IDbSet<CancellationReasonRequestType> CancellationReasonRequestTypes { get; }
		 IDbSet<CancellationRequestStatus> CancellationRequestStatuses { get; }
		 IDbSet<CancelRequestRejectReasonType> CancelRequestRejectReasonTypes { get; }
		 IDbSet<CarEngineVolume> CarEngineVolumes { get; }
		 IDbSet<CargoIdentifireType> CargoIdentifireTypes { get; }
		 IDbSet<CargoIdentityQualifier> CargoIdentityQualifiers { get; }
		 IDbSet<CargoSeal> CargoSeals { get; }
		 IDbSet<CargoSealIdentifier> CargoSealIdentifiers { get; }
		 IDbSet<CargoSplitRequestStatus> CargoSplitRequestStatuses { get; }
		 IDbSet<CargoStatus> CargoStatuses { get; }
		 IDbSet<CargoType> CargoTypes { get; }
		 IDbSet<CarWeight> CarWeights { get; }
		 IDbSet<CB_AdditionRulesDetailsHistory> CB_AdditionRulesDetailsHistorys { get; }
		 IDbSet<CB_ComputationMethodData> CB_ComputationMethodDatas { get; }
		 IDbSet<CB_CountriesExclusion> CB_CountriesExclusions { get; }
		 IDbSet<CB_CustomsBookAddition> CB_CustomsBookAdditions { get; }
		 IDbSet<CB_CustomsBookAdditionsDetailsHistory> CB_CustomsBookAdditionsDetailsHistorys { get; }
		 IDbSet<CB_CustomsItem> CB_CustomsItems { get; }
		 IDbSet<CB_CustomsItemComputedData> CB_CustomsItemComputedDatas { get; }
		 IDbSet<CB_CustomsItemDetailsHistory> CB_CustomsItemDetailsHistorys { get; }
		 IDbSet<CB_CustomsItemExclusion> CB_CustomsItemExclusion { get; }
		 IDbSet<CB_CustomsItemLinkage> CB_CustomsItemLinkages { get; }
		 IDbSet<CB_LevyCondition> CB_LevyConditions { get; }
		 IDbSet<CB_LevyExclusion> CB_LevyExclusions { get; }
		 IDbSet<CB_PropertiesDetailsHistory> CB_PropertiesDetailsHistorys { get; }
		 IDbSet<CB_Quota> CB_Quotas { get; }
		 IDbSet<CB_QuotaComputedData> CB_QuotaComputedDatas { get; }
		 IDbSet<CB_QuotaDetailsHistory> CB_QuotaDetailsHistorys { get; }
		 IDbSet<CB_QuotaRenewal> CB_QuotaRenewals { get; }
		 IDbSet<CB_RegularityInception> CB_RegularityInceptions { get; }
		 IDbSet<CB_RegularityRequiredCertificate> CB_RegularityRequiredCertificates { get; }
		 IDbSet<CB_RegularityRequirement> CB_RegularityRequirements { get; }
		 IDbSet<CB_RequirementComputedData> CB_RequirementComputedDatas { get; }
		 IDbSet<CB_Rule> CB_Rules { get; }
		 IDbSet<CB_RuleDetailsHistory> CB_RuleDetailsHistorys { get; }
		 IDbSet<CB_Tariff> CB_Tariffs { get; }
		 IDbSet<CB_TariffComputedData> CB_TariffComputedDatas { get; }
		 IDbSet<CB_TariffDetailsHistory> CB_TariffDetailsHistorys { get; }
		 IDbSet<CB_TradeAgreement> CB_TradeAgreements { get; }
		 IDbSet<CB_TradeAgreementHistory> CB_TradeAgreementHistories { get; }
		 IDbSet<CB_TradeLevy> CB_TradeLevys { get; }
		 IDbSet<CB_Vendor> CB_Vendors { get; }
		 IDbSet<CertificateExemptionType> CertificateExemptionTypes { get; }
		 IDbSet<CertificateOfOrigin> CertificateOfOrigins { get; }
		 IDbSet<CertificateOfOriginInvoice> CertificateOfOriginInvoices { get; }
		 IDbSet<CertificateOfOriginItem> CertificateOfOriginItems { get; }
		 IDbSet<CertificateOfOriginMandatoryFields> CertificateOfOriginMandatoryFieldss { get; }
		 IDbSet<CertificateOfOriginStatusCodeEnum> CertificateOfOriginStatusCodeEnums { get; }
		 IDbSet<CertificateOfOriginTypeCodeEnum> CertificateOfOriginTypeCodeEnums { get; }
		 IDbSet<CertificatesStatus> CertificatesStatuses { get; }
		 IDbSet<ChangeType> ChangeTypes { get; }
		 IDbSet<CheckEntityType> CheckEntityTypes { get; }
		 IDbSet<CheckEssenceLookup> CheckEssenceLookups { get; }
		 IDbSet<CheckQueueType> CheckQueueTypes { get; }
		 IDbSet<CheckRepresentativeType> CheckRepresentativeTypes { get; }
		 IDbSet<CheckTypeLookup> CheckTypeLookups { get; }
		 IDbSet<City> Cities { get; }
		 IDbSet<Claim> Claims { get; }
		 IDbSet<ClaimEntity> ClaimEntities { get; }
		 IDbSet<ClaimExplanationCode> ClaimExplanationCodes { get; }
		 IDbSet<ClaimImporterDeclarsP3Loi> ClaimImporterDeclarsP3Lois { get; }
		 IDbSet<ClaimImporterDeclarsPage3> ClaimImporterDeclarsPage3s { get; }
		 IDbSet<ClaimImporterDeclarsPage3A> ClaimImporterDeclarsPage3As { get; }
		 IDbSet<ClaimImporterDeclarsPage3B> ClaimImporterDeclarsPage3Bs { get; }
		 IDbSet<ClaimReasonType> ClaimReasonTypes { get; }
		 IDbSet<ClaimsRelatedEntitiesAmount> ClaimsRelatedEntitiesAmounts { get; }
		 IDbSet<ClaimsRelatedEntitiesReason> ClaimsRelatedEntitiesReasons { get; }
		 IDbSet<ClaimsRelatedEntitiesRefund> ClaimsRelatedEntitiesRefunds { get; }
		 IDbSet<ClaimsRelatedEntitiesSeizure> ClaimsRelatedEntitiesSeizures { get; }
		 IDbSet<ClaimsRelatedEntity> ClaimsRelatedEntities { get; }
		 IDbSet<ClaimsRelatedEntsExpDeclar> ClaimsRelatedEntsExpDeclars { get; }
		 IDbSet<ClaimsRelatedEntsReasonsExp> ClaimsRelatedEntsReasonsExps { get; }
		 IDbSet<ClassificationType> ClassificationTypes { get; }
		 IDbSet<Client> Clients { get; }
		 IDbSet<ClientAddress> ClientAddresses { get; }
		 IDbSet<ClientDrivingLicense> ClientDrivingLicenses { get; }
		 IDbSet<ClientDrivingLicenseType> ClientDrivingLicenseTypes { get; }
		 IDbSet<ClientIndication> ClientIndications { get; }
		 IDbSet<ClientItem> ClientItems { get; }
		 IDbSet<ClientsAddressCommType> ClientsAddressCommTypes { get; }
		 IDbSet<ClientsPoa> ClientsPoas { get; }
		 IDbSet<ClientsTapag> ClientsTapags { get; }
		 IDbSet<ClosedTableStatus> ClosedTableStatus { get; }
		 IDbSet<CollateralAnswerStatus> CollateralAnswerStatus { get; }
		 IDbSet<CollateralAnswerType> CollateralAnswerTypes { get; }
		 IDbSet<CollateralRequestStatus> CollateralRequestStatus { get; }
		 IDbSet<CollateralsRequestFileCond> CollateralsRequestFileConds { get; }
		 IDbSet<CollateralType> CollateralTypes { get; }
		 IDbSet<CommercialSale> CommercialSales { get; }
		 IDbSet<CommunicationType> CommunicationTypes { get; }
		 IDbSet<ComputationMethod> ComputationMethods { get; }
		 IDbSet<ConditionalExemptionType> ConditionalExemptionTypes { get; }
		 IDbSet<ConfirmationNumberTokenLog> ConfirmationNumberTokenLogs { get; }
		 IDbSet<ConfirmationType> ConfirmationTypes { get; }
		 IDbSet<Consignment> Consignments { get; }
		 IDbSet<ConsignmentInternalTransition> ConsignmentInternalTransitions { get; }
		 IDbSet<ConsignmentPackage> ConsignmentPackages { get; }
		 IDbSet<ConsignmentPackDanger> ConsignmentPackDangers { get; }
		 IDbSet<ConstraintApprovalDecision> ConstraintApprovalDecisions { get; }
		 IDbSet<ConstraintProcessType> ConstraintProcessTypes { get; }
		 IDbSet<ConstraintStatus> ConstraintStatuses { get; }
		 IDbSet<ConstraintType> ConstraintTypes { get; }
		 IDbSet<ContactRoleType> ContactRoleTypes { get; }
		 IDbSet<Containerization> Containerizations { get; }
		 IDbSet<ContainerizationHataraStatus> ContainerizationHataraStatuses { get; }
		 IDbSet<ContainerizationStatusCode> ContainerizationStatusCodes { get; }
		 IDbSet<ContainerType> ContainerTypes { get; }
		 IDbSet<ContinuousMessagesTypeCode> ContinuousMessagesTypeCodes { get; }
		 IDbSet<ContinuousRequestType> ContinuousRequestTypes { get; }
		 IDbSet<ConverterType> ConverterTypes { get; }
		 IDbSet<CoolingReportingMethod> CoolingReportingMethods { get; }
		 IDbSet<CountryCurrency> CountryCurrencies { get; }
		 IDbSet<CountryGroup> CountryGroups { get; }
		 IDbSet<CourierCustomStatus> CourierCustomStatuses { get; }
		 IDbSet<CourierDeclaration> CourierDeclarations { get; }
		 IDbSet<CourierDeclarationStatus> CourierDeclarationStatuses { get; }
		 IDbSet<CourierHawbFromExcel> CourierHawbFromExcels { get; }
		 IDbSet<CourierManifestStatus> CourierManifestStatuses { get; }
		 IDbSet<CourierMaster> CourierMasters { get; }
		 IDbSet<CourierPaymentStatus> CourierPaymentStatuses { get; }
		 IDbSet<CourierPendingReason> CourierPendingReasons { get; }
		 IDbSet<CourierStatus> CourierStatuses { get; }
		 IDbSet<CouriersVat> CouriersVats { get; }
		 IDbSet<CourtInstance> CourtInstances { get; }
		 IDbSet<CurrencyType> CurrencyTypes { get; }
		 IDbSet<CurrencyTypeTenant> CurrencyTypeTenants { get; }
		 IDbSet<CustomBank> CustomBanks { get; }
		 IDbSet<CustomBanksCard> CustomBanksCards { get; }
		 IDbSet<CustomDocumentType> CustomDocumentTypes { get; }
		 IDbSet<CustomDocumentTypeMetaData> CustomDocumentTypeMetaData { get; }
		 IDbSet<CustomDocumentTypeTenant> CustomDocumentTypeTenants { get; }
		 IDbSet<CustomerActivityType> CustomerActivityTypes { get; }
		 IDbSet<CustomerClassificationType> CustomerClassificationTypes { get; }
		 IDbSet<CustomerIdentificationType> CustomerIdentificationTypes { get; }
		 IDbSet<CustomerIdentifyType> CustomerIdentifyTypes { get; }
		 IDbSet<CustomerIndicationType> CustomerIndicationTypes { get; }
		 IDbSet<CustomerRoleType> CustomerRoleTypes { get; }
		 IDbSet<CustomerTypeGeneral> CustomerTypeGenerals { get; }
		 IDbSet<CustomMetaDataType> CustomMetaDataTypes { get; }
		 IDbSet<CustomsAddressType> CustomsAddressTypes { get; }
		 IDbSet<CustomsAirline> CustomsAirlines { get; }
		 IDbSet<CustomsAutonomyKeyword> CustomsAutonomyKeywords { get; }
		 IDbSet<CustomsBook> CustomsBooks { get; }
		 IDbSet<CustomsBookType> CustomsBookTypes { get; }
		 IDbSet<CustomsBranch> CustomsBranches { get; }
		 IDbSet<CustomsClosedTable> CustomsClosedTables { get; }
		 IDbSet<CustomsCollateral> CustomsCollaterals { get; }
		 IDbSet<CustomsCollateralsAnswer> CustomsCollateralsAnswers { get; }
		 IDbSet<CustomsCollateralsCondition> CustomsCollateralsConditions { get; }
		 IDbSet<CustomsCountry> CustomsCountries { get; }
		 IDbSet<CustomsCountryTenant> CustomsCountryTenants { get; }
		 IDbSet<CustomsDocument> CustomsDocuments { get; }
		 IDbSet<CustomsDocumentMetaDataValue> CustomsDocumentMetaDataValues { get; }
		 IDbSet<CustomsDocumentPointer> CustomsDocumentPointers { get; }
		 IDbSet<CustomsDocumentsDefinition> CustomsDocumentsDefinitions { get; }
		 IDbSet<CustomsDocumentStatusType> CustomsDocumentStatusTypes { get; }
		 IDbSet<CustomsDocumentsTicket> CustomsDocumentsTickets { get; }
		 IDbSet<CustomsDocumentUpload> CustomsDocumentUploads { get; }
		 IDbSet<CustomsEntityStatus> CustomsEntityStatuses { get; }
		 IDbSet<CustomsEnvironmentSetting> CustomsEnvironmentSettings { get; }
		 IDbSet<CustomsEnvoirmentType> CustomsEnvoirmentTypes { get; }
		 IDbSet<CustomsExchangeRate> CustomsExchangeRates { get; }
		 IDbSet<CustomsGeneral> CustomsGenerals { get; }
		 IDbSet<CustomsHouseType> CustomsHouseTypes { get; }
		 IDbSet<CustomsHouseTypeAdditional> CustomsHouseTypeAdditionals { get; }
		 IDbSet<CustomsHouseTypeTenant> CustomsHouseTypeTenants { get; }
		 IDbSet<CustomsInsuranceCompany> CustomsInsuranceCompanies { get; }
		 IDbSet<CustomsItem> CustomsItems { get; }
		 IDbSet<CustomsItemCategory> CustomsItemCategories { get; }
		 IDbSet<CustomsItemDetailsHistory> CustomsItemDetailsHistorys { get; }
		 IDbSet<CustomsItemGroup> CustomsItemGroups { get; }
		 IDbSet<CustomsItemHierarchicLocation> CustomsItemHierarchicLocations { get; }
		 IDbSet<CustomsPartnerFtp> CustomsPartnerFtps { get; }
		 IDbSet<CustomsPartnersItem> CustomsPartnersItems { get; }
		 IDbSet<CustomsPaymentTerm> CustomsPaymentTerms { get; }
		 IDbSet<CustomsRequestsSheet> CustomsRequestsSheets { get; }
		 IDbSet<CustomsRequestsSheetStatus> CustomsRequestsSheetStatuses { get; }
		 IDbSet<CustomsRequiredField> CustomsRequiredFields { get; }
		 IDbSet<CustomsSetting> CustomsSettings { get; }
		 IDbSet<CustomsShip> CustomsShips { get; }
		 IDbSet<CustomsTransportMode> CustomsTransportModes { get; }
		 IDbSet<CustomsVendor> CustomsVendors { get; }
		 IDbSet<CustomsVerificationStatusType> CustomsVerificationStatusTypes { get; }
		 IDbSet<DangerousGoodsPackingReq> DangerousGoodsPackingReqs { get; }
		 IDbSet<DBMigration> DBMigrations { get; }
		 IDbSet<DBMigrationLine> DBMigrationLines { get; }
		 IDbSet<DebtNotificationType> DebtNotificationTypes { get; }
		 IDbSet<DecCargoSplitCargoIdentifier> DecCargoSplitCargoIdentifiers { get; }
		 IDbSet<DecCargoSplitCon> DecCargoSplitCons { get; }
		 IDbSet<DecCargoSplitConsItem> DecCargoSplitConsItems { get; }
		 IDbSet<DecCargoSplitConsPackDet> DecCargoSplitConsPackDets { get; }
		 IDbSet<DecDangersContact> DecDangersContacts { get; }
		 IDbSet<DecisionType> DecisionTypes { get; }
	