//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logitude.HybridTest.ChargeTypeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChargesTypeList", Namespace="http://schemas.datacontract.org/2004/07/Logitude.BL.CommonDataModel.EntityLists")]
    [System.SerializableAttribute()]
    public partial class ChargesTypeList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AWBPrintDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountingCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AccountingVATSplitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AddedManuallyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargesGroupCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargesGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargesGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerMeasurementCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerMeasurementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IATACodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoDisplayInConsolidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoDisplayInCustomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoDisplayInQuoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoDisplayInShipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBackToBackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCustomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDomesticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDropField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExpenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInlandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOceanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPayableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReceivableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasurementCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasurementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasurementShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayableAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayableDebitAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayableDebitGLAcountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayablesChargesTypeExternalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayablesDefaultCurrencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivableAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivableCreditAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivableCreditGLAccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivablesChargesTypeExternalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivablesDefaultCurrencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SATExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VatIsMultiPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VatTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VatTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VatTypePercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViewOrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AWBPrintDescription {
            get {
                return this.AWBPrintDescriptionField;
            }
            set {
                if ((this.AWBPrintDescriptionField.Equals(value) != true)) {
                    this.AWBPrintDescriptionField = value;
                    this.RaisePropertyChanged("AWBPrintDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountingCard {
            get {
                return this.AccountingCardField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountingCardField, value) != true)) {
                    this.AccountingCardField = value;
                    this.RaisePropertyChanged("AccountingCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AccountingVATSplit {
            get {
                return this.AccountingVATSplitField;
            }
            set {
                if ((this.AccountingVATSplitField.Equals(value) != true)) {
                    this.AccountingVATSplitField = value;
                    this.RaisePropertyChanged("AccountingVATSplit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AddedManually {
            get {
                return this.AddedManuallyField;
            }
            set {
                if ((this.AddedManuallyField.Equals(value) != true)) {
                    this.AddedManuallyField = value;
                    this.RaisePropertyChanged("AddedManually");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChargesGroupCode {
            get {
                return this.ChargesGroupCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargesGroupCodeField, value) != true)) {
                    this.ChargesGroupCodeField = value;
                    this.RaisePropertyChanged("ChargesGroupCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChargesGroupId {
            get {
                return this.ChargesGroupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargesGroupIdField, value) != true)) {
                    this.ChargesGroupIdField = value;
                    this.RaisePropertyChanged("ChargesGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChargesGroupName {
            get {
                return this.ChargesGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargesGroupNameField, value) != true)) {
                    this.ChargesGroupNameField = value;
                    this.RaisePropertyChanged("ChargesGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainerMeasurementCode {
            get {
                return this.ContainerMeasurementCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerMeasurementCodeField, value) != true)) {
                    this.ContainerMeasurementCodeField = value;
                    this.RaisePropertyChanged("ContainerMeasurementCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainerMeasurementId {
            get {
                return this.ContainerMeasurementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerMeasurementIdField, value) != true)) {
                    this.ContainerMeasurementIdField = value;
                    this.RaisePropertyChanged("ContainerMeasurementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueTypeCode {
            get {
                return this.DueTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DueTypeCodeField, value) != true)) {
                    this.DueTypeCodeField = value;
                    this.RaisePropertyChanged("DueTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueTypeName {
            get {
                return this.DueTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DueTypeNameField, value) != true)) {
                    this.DueTypeNameField = value;
                    this.RaisePropertyChanged("DueTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishName {
            get {
                return this.EnglishNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishNameField, value) != true)) {
                    this.EnglishNameField = value;
                    this.RaisePropertyChanged("EnglishName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IATACodeId {
            get {
                return this.IATACodeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IATACodeIdField, value) != true)) {
                    this.IATACodeIdField = value;
                    this.RaisePropertyChanged("IATACodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InActive {
            get {
                return this.InActiveField;
            }
            set {
                if ((this.InActiveField.Equals(value) != true)) {
                    this.InActiveField = value;
                    this.RaisePropertyChanged("InActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAir {
            get {
                return this.IsAirField;
            }
            set {
                if ((this.IsAirField.Equals(value) != true)) {
                    this.IsAirField = value;
                    this.RaisePropertyChanged("IsAir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoDisplayInConsolidation {
            get {
                return this.IsAutoDisplayInConsolidationField;
            }
            set {
                if ((this.IsAutoDisplayInConsolidationField.Equals(value) != true)) {
                    this.IsAutoDisplayInConsolidationField = value;
                    this.RaisePropertyChanged("IsAutoDisplayInConsolidation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoDisplayInCustoms {
            get {
                return this.IsAutoDisplayInCustomsField;
            }
            set {
                if ((this.IsAutoDisplayInCustomsField.Equals(value) != true)) {
                    this.IsAutoDisplayInCustomsField = value;
                    this.RaisePropertyChanged("IsAutoDisplayInCustoms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoDisplayInQuote {
            get {
                return this.IsAutoDisplayInQuoteField;
            }
            set {
                if ((this.IsAutoDisplayInQuoteField.Equals(value) != true)) {
                    this.IsAutoDisplayInQuoteField = value;
                    this.RaisePropertyChanged("IsAutoDisplayInQuote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoDisplayInShipment {
            get {
                return this.IsAutoDisplayInShipmentField;
            }
            set {
                if ((this.IsAutoDisplayInShipmentField.Equals(value) != true)) {
                    this.IsAutoDisplayInShipmentField = value;
                    this.RaisePropertyChanged("IsAutoDisplayInShipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBackToBack {
            get {
                return this.IsBackToBackField;
            }
            set {
                if ((this.IsBackToBackField.Equals(value) != true)) {
                    this.IsBackToBackField = value;
                    this.RaisePropertyChanged("IsBackToBack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustoms {
            get {
                return this.IsCustomsField;
            }
            set {
                if ((this.IsCustomsField.Equals(value) != true)) {
                    this.IsCustomsField = value;
                    this.RaisePropertyChanged("IsCustoms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDomestic {
            get {
                return this.IsDomesticField;
            }
            set {
                if ((this.IsDomesticField.Equals(value) != true)) {
                    this.IsDomesticField = value;
                    this.RaisePropertyChanged("IsDomestic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDrop {
            get {
                return this.IsDropField;
            }
            set {
                if ((this.IsDropField.Equals(value) != true)) {
                    this.IsDropField = value;
                    this.RaisePropertyChanged("IsDrop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExpense {
            get {
                return this.IsExpenseField;
            }
            set {
                if ((this.IsExpenseField.Equals(value) != true)) {
                    this.IsExpenseField = value;
                    this.RaisePropertyChanged("IsExpense");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExport {
            get {
                return this.IsExportField;
            }
            set {
                if ((this.IsExportField.Equals(value) != true)) {
                    this.IsExportField = value;
                    this.RaisePropertyChanged("IsExport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsImport {
            get {
                return this.IsImportField;
            }
            set {
                if ((this.IsImportField.Equals(value) != true)) {
                    this.IsImportField = value;
                    this.RaisePropertyChanged("IsImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInland {
            get {
                return this.IsInlandField;
            }
            set {
                if ((this.IsInlandField.Equals(value) != true)) {
                    this.IsInlandField = value;
                    this.RaisePropertyChanged("IsInland");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOcean {
            get {
                return this.IsOceanField;
            }
            set {
                if ((this.IsOceanField.Equals(value) != true)) {
                    this.IsOceanField = value;
                    this.RaisePropertyChanged("IsOcean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPayable {
            get {
                return this.IsPayableField;
            }
            set {
                if ((this.IsPayableField.Equals(value) != true)) {
                    this.IsPayableField = value;
                    this.RaisePropertyChanged("IsPayable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReceivable {
            get {
                return this.IsReceivableField;
            }
            set {
                if ((this.IsReceivableField.Equals(value) != true)) {
                    this.IsReceivableField = value;
                    this.RaisePropertyChanged("IsReceivable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalName {
            get {
                return this.LocalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalNameField, value) != true)) {
                    this.LocalNameField = value;
                    this.RaisePropertyChanged("LocalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeasurementCode {
            get {
                return this.MeasurementCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementCodeField, value) != true)) {
                    this.MeasurementCodeField = value;
                    this.RaisePropertyChanged("MeasurementCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeasurementId {
            get {
                return this.MeasurementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementIdField, value) != true)) {
                    this.MeasurementIdField = value;
                    this.RaisePropertyChanged("MeasurementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeasurementShortName {
            get {
                return this.MeasurementShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementShortNameField, value) != true)) {
                    this.MeasurementShortNameField = value;
                    this.RaisePropertyChanged("MeasurementShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayableAccountId {
            get {
                return this.PayableAccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayableAccountIdField, value) != true)) {
                    this.PayableAccountIdField = value;
                    this.RaisePropertyChanged("PayableAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayableDebitAccount {
            get {
                return this.PayableDebitAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.PayableDebitAccountField, value) != true)) {
                    this.PayableDebitAccountField = value;
                    this.RaisePropertyChanged("PayableDebitAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayableDebitGLAcountId {
            get {
                return this.PayableDebitGLAcountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayableDebitGLAcountIdField, value) != true)) {
                    this.PayableDebitGLAcountIdField = value;
                    this.RaisePropertyChanged("PayableDebitGLAcountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayablesChargesTypeExternalCode {
            get {
                return this.PayablesChargesTypeExternalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayablesChargesTypeExternalCodeField, value) != true)) {
                    this.PayablesChargesTypeExternalCodeField = value;
                    this.RaisePropertyChanged("PayablesChargesTypeExternalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayablesDefaultCurrencyId {
            get {
                return this.PayablesDefaultCurrencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayablesDefaultCurrencyIdField, value) != true)) {
                    this.PayablesDefaultCurrencyIdField = value;
                    this.RaisePropertyChanged("PayablesDefaultCurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivableAccountId {
            get {
                return this.ReceivableAccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivableAccountIdField, value) != true)) {
                    this.ReceivableAccountIdField = value;
                    this.RaisePropertyChanged("ReceivableAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivableCreditAccount {
            get {
                return this.ReceivableCreditAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivableCreditAccountField, value) != true)) {
                    this.ReceivableCreditAccountField = value;
                    this.RaisePropertyChanged("ReceivableCreditAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivableCreditGLAccountId {
            get {
                return this.ReceivableCreditGLAccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivableCreditGLAccountIdField, value) != true)) {
                    this.ReceivableCreditGLAccountIdField = value;
                    this.RaisePropertyChanged("ReceivableCreditGLAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivablesChargesTypeExternalCode {
            get {
                return this.ReceivablesChargesTypeExternalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivablesChargesTypeExternalCodeField, value) != true)) {
                    this.ReceivablesChargesTypeExternalCodeField = value;
                    this.RaisePropertyChanged("ReceivablesChargesTypeExternalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivablesDefaultCurrencyId {
            get {
                return this.ReceivablesDefaultCurrencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivablesDefaultCurrencyIdField, value) != true)) {
                    this.ReceivablesDefaultCurrencyIdField = value;
                    this.RaisePropertyChanged("ReceivablesDefaultCurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SATExternalId {
            get {
                return this.SATExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SATExternalIdField, value) != true)) {
                    this.SATExternalIdField = value;
                    this.RaisePropertyChanged("SATExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchFields {
            get {
                return this.SearchFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchFieldsField, value) != true)) {
                    this.SearchFieldsField = value;
                    this.RaisePropertyChanged("SearchFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tenant {
            get {
                return this.TenantField;
            }
            set {
                if ((this.TenantField.Equals(value) != true)) {
                    this.TenantField = value;
                    this.RaisePropertyChanged("Tenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VatIsMultiPercentage {
            get {
                return this.VatIsMultiPercentageField;
            }
            set {
                if ((this.VatIsMultiPercentageField.Equals(value) != true)) {
                    this.VatIsMultiPercentageField = value;
                    this.RaisePropertyChanged("VatIsMultiPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VatTypeId {
            get {
                return this.VatTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VatTypeIdField, value) != true)) {
                    this.VatTypeIdField = value;
                    this.RaisePropertyChanged("VatTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VatTypeName {
            get {
                return this.VatTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VatTypeNameField, value) != true)) {
                    this.VatTypeNameField = value;
                    this.RaisePropertyChanged("VatTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VatTypePercentage {
            get {
                return this.VatTypePercentageField;
            }
            set {
                if ((this.VatTypePercentageField.Equals(value) != true)) {
                    this.VatTypePercentageField = value;
                    this.RaisePropertyChanged("VatTypePercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewOrder {
            get {
                return this.ViewOrderField;
            }
            set {
                if ((this.ViewOrderField.Equals(value) != true)) {
                    this.ViewOrderField = value;
                    this.RaisePropertyChanged("ViewOrder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChargeTypeServiceReference.IChargeTypeWcfService")]
    public interface IChargeTypeWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeTypeWcfService/GetChargesTypes", ReplyAction="http://tempuri.org/IChargeTypeWcfService/GetChargesTypesResponse")]
        Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesResponse GetChargesTypes(Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChargeTypeWcfService/GetChargesTypes", ReplyAction="http://tempuri.org/IChargeTypeWcfService/GetChargesTypesResponse")]
        System.Threading.Tasks.Task<Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesResponse> GetChargesTypesAsync(Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChargesTypes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChargesTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int skip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int take;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public Logitude.Server.Tools.Response response;
        
        public GetChargesTypesRequest() {
        }
        
        public GetChargesTypesRequest(int tenant, int skip, int take, Logitude.Server.Tools.Response response) {
            this.tenant = tenant;
            this.skip = skip;
            this.take = take;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChargesTypesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChargesTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Logitude.HybridTest.ChargeTypeServiceReference.ChargesTypeList[] GetChargesTypesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Logitude.Server.Tools.Response response;
        
        public GetChargesTypesResponse() {
        }
        
        public GetChargesTypesResponse(Logitude.HybridTest.ChargeTypeServiceReference.ChargesTypeList[] GetChargesTypesResult, Logitude.Server.Tools.Response response) {
            this.GetChargesTypesResult = GetChargesTypesResult;
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChargeTypeWcfServiceChannel : Logitude.HybridTest.ChargeTypeServiceReference.IChargeTypeWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChargeTypeWcfServiceClient : System.ServiceModel.ClientBase<Logitude.HybridTest.ChargeTypeServiceReference.IChargeTypeWcfService>, Logitude.HybridTest.ChargeTypeServiceReference.IChargeTypeWcfService {
        
        public ChargeTypeWcfServiceClient() {
        }
        
        public ChargeTypeWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChargeTypeWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChargeTypeWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChargeTypeWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesResponse Logitude.HybridTest.ChargeTypeServiceReference.IChargeTypeWcfService.GetChargesTypes(Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesRequest request) {
            return base.Channel.GetChargesTypes(request);
        }
        
        public Logitude.HybridTest.ChargeTypeServiceReference.ChargesTypeList[] GetChargesTypes(int tenant, int skip, int take, ref Logitude.Server.Tools.Response response) {
            Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesRequest inValue = new Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesRequest();
            inValue.tenant = tenant;
            inValue.skip = skip;
            inValue.take = take;
            inValue.response = response;
            Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesResponse retVal = ((Logitude.HybridTest.ChargeTypeServiceReference.IChargeTypeWcfService)(this)).GetChargesTypes(inValue);
            response = retVal.response;
            return retVal.GetChargesTypesResult;
        }
        
        public System.Threading.Tasks.Task<Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesResponse> GetChargesTypesAsync(Logitude.HybridTest.ChargeTypeServiceReference.GetChargesTypesRequest request) {
            return base.Channel.GetChargesTypesAsync(request);
        }
    }
}
