//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Threading.Tasks;
using System.Data.Entity.ModelConfiguration;
using POCO = AmitalCloud.Infrastructure.Domain.EntityPOCOs;
 
namespace AmitalCloud.Infrastructure.Domain.EntityMapping
{
 
    public class ReportMap : EntityTypeConfiguration<POCO.Report>
    {
	    string dbms;
        public ReportMap()
        { 
				this.ToTable("Reports");
		
		    this.HasKey(t => new { t.Id });
	 
            this.Property(t => t.ReportGroupId).HasColumnName("ReportGroupId").HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.FeatureId).HasColumnName("FeatureId").HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.ReportDocumentId).HasColumnName("ReportDocumentId").HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.Id).HasColumnName("Id").HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.Tenant).HasColumnName("Tenant");

            this.Property(t => t.Name).HasColumnName("Name").HasMaxLength(40).IsUnicode(false);

            this.Property(t => t.FilterControlName).HasColumnName("FilterControlName").HasMaxLength(100).IsUnicode(false);

            this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(250).IsUnicode(true);

            this.Property(t => t.SearchFields).HasColumnName("SearchFields").HasMaxLength(1000).IsUnicode(true);

            this.Property(t => t.Code).HasColumnName("Code").HasMaxLength(4).IsUnicode(false);

            this.Property(t => t.InActive).HasColumnName("InActive").IsRequired();

            this.Property(t => t.DefaultTemplateId).HasColumnName("DefaultTemplateId").HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.DefaultMessageTemplateId).HasColumnName("DefaultMessageTemplateId").HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.LocalName).HasColumnName("LocalName").HasMaxLength(60).IsUnicode(true);

            this.Property(t => t.FilterHtmlComponentUrl).HasColumnName("FilterHtmlComponentUrl").HasMaxLength(256).IsUnicode(false);

            this.Property(t => t.FeatureUniqeCode).HasColumnName("FeatureUniqeCode").HasMaxLength(120).IsUnicode(false);

            this.Property(t => t.AvailableForScheduling).HasColumnName("AvailableForScheduling");

            this.Property(t => t.DisablePreview).HasColumnName("DisablePreview");

            this.Property(t => t.DefaultExcelTemplateId).HasColumnName("DefaultExcelTemplateId").HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.IsExcelReportAllowed).HasColumnName("IsExcelReportAllowed");
        }
    }
}
	 