//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Threading.Tasks;
using System.Data.Entity.ModelConfiguration;
using POCO = AmitalCloud.Infrastructure.Domain.EntityPOCOs;
 
namespace AmitalCloud.Infrastructure.Domain.EntityMapping
{
 
    public class SatisfactionSurveyMap : EntityTypeConfiguration<POCO.SatisfactionSurvey>
    {
	    string dbms;
        public SatisfactionSurveyMap()
        { 
				this.ToTable("SatisfactionSurveys");
		
		    this.HasKey(t => new { t.Id });
	 
            this.Property(t => t.Id).HasColumnName("Id").IsRequired().HasMaxLength(40).IsUnicode(false);

            this.Property(t => t.CreateDate).HasColumnName("CreateDate").IsRequired();

            this.Property(t => t.UpdateDate).HasColumnName("UpdateDate").IsRequired();

            this.Property(t => t.SearchFields).HasColumnName("SearchFields").IsMaxLength().IsUnicode(true);

            this.Property(t => t.Rating).HasColumnName("Rating").HasMaxLength(1).IsUnicode(true);

            this.Property(t => t.Comments).HasColumnName("Comments").HasMaxLength(250).IsUnicode(true);

            this.Property(t => t.Tenant).HasColumnName("Tenant");

            this.Property(t => t.IsSync).HasColumnName("IsSync");

            this.Property(t => t.LockedBy).HasColumnName("LockedBy").HasMaxLength(36).IsUnicode(true);

            this.Property(t => t.SyncDate).HasColumnName("SyncDate");
        }
    }
}
	 