<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AmitalCloud.Infrastructure.Model\AmitalCloud.Infrastructure.Model.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="System.ServiceModel.DomainServices.Server">
      <HintPath>..\..\Library\Bin\System.ServiceModel.DomainServices.Server.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
