//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> C:\amital_main\Logitude\Logitude.Accounting.MetaData\AutoGenerators\AccountingClassesGenerator.tt
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

import {GLAccountPM} from './GLAccountPM';
import {UIProperties, UIProperty} from '../../Infrastructure/Components/LogitudeComponents/UIProperties';
import {ServiceHelper} from '../../Infrastructure/Utilities/ServiceHelper';
import {ServiceLocator} from '../../Infrastructure/Locators/ServiceLocator';
import {Output, EventEmitter}  from '@angular/core';
import {PropertyChangedArgs} from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';
import {CustomFieldClass} from '../../Infrastructure/DataContracts/CustomFieldClass';

export class GLAccountInterestPeriodPM {
      
      @Output() PropertyChanged: EventEmitter<PropertyChangedArgs> = new EventEmitter<PropertyChangedArgs>();
      public UIProperties: UIProperties;
	        constructor(_entityParentPM: any) {
	  		                        this.EntityParentPM = _entityParentPM;
                this.UIProperties = new UIProperties(this);
                this.IsDirty = false;
      }

	 
    
    private tenant: number;
    public get Tenant() { return this.tenant; }
    public set Tenant(newValue: number) { if (this.tenant != newValue) { this.tenant = newValue; this.MarkAsDirty("Tenant"); } }
       
	 
    private lineNumber: number;
    public get LineNumber() { return this.lineNumber; }
    public set LineNumber(newValue: number) { if (this.lineNumber != newValue) { this.lineNumber = newValue; this.MarkAsDirty("LineNumber"); } }
       
	 
    private gLAccountId: string;
    public get GLAccountId() { return this.gLAccountId; }
    public set GLAccountId(newValue: string) { if (this.gLAccountId != newValue) { this.gLAccountId = newValue; this.MarkAsDirty("GLAccountId"); } }
       
	 
    private periodStartDate: Date;
    public get PeriodStartDate() { return this.periodStartDate; }
    public set PeriodStartDate(newValue: Date) { if (this.periodStartDate != newValue) { this.periodStartDate = newValue; this.MarkAsDirty("PeriodStartDate"); } }
       
	 
    private standardInterestRateBaseId: string;
    public get StandardInterestRateBaseId() { return this.standardInterestRateBaseId; }
    public set StandardInterestRateBaseId(newValue: string) { if (this.standardInterestRateBaseId != newValue) { this.standardInterestRateBaseId = newValue; this.MarkAsDirty("StandardInterestRateBaseId"); } }
       
	 
    private standardAddInterestPercent: number;
    public get StandardAddInterestPercent() { return this.standardAddInterestPercent; }
    public set StandardAddInterestPercent(newValue: number) { if (this.standardAddInterestPercent != newValue) { this.standardAddInterestPercent = newValue; this.MarkAsDirty("StandardAddInterestPercent"); } }
       
	 
    private exceptionalInterestRateBaseId: string;
    public get ExceptionalInterestRateBaseId() { return this.exceptionalInterestRateBaseId; }
    public set ExceptionalInterestRateBaseId(newValue: string) { if (this.exceptionalInterestRateBaseId != newValue) { this.exceptionalInterestRateBaseId = newValue; this.MarkAsDirty("ExceptionalInterestRateBaseId"); } }
       
	 
    private exceptionalAddInterestPercent: number;
    public get ExceptionalAddInterestPercent() { return this.exceptionalAddInterestPercent; }
    public set ExceptionalAddInterestPercent(newValue: number) { if (this.exceptionalAddInterestPercent != newValue) { this.exceptionalAddInterestPercent = newValue; this.MarkAsDirty("ExceptionalAddInterestPercent"); } }
       
	 
    private creditInterestRateBaseId: string;
    public get CreditInterestRateBaseId() { return this.creditInterestRateBaseId; }
    public set CreditInterestRateBaseId(newValue: string) { if (this.creditInterestRateBaseId != newValue) { this.creditInterestRateBaseId = newValue; this.MarkAsDirty("CreditInterestRateBaseId"); } }
       
	 
    private creditAddInterestPercent: number;
    public get CreditAddInterestPercent() { return this.creditAddInterestPercent; }
    public set CreditAddInterestPercent(newValue: number) { if (this.creditAddInterestPercent != newValue) { this.creditAddInterestPercent = newValue; this.MarkAsDirty("CreditAddInterestPercent"); } }
       
	 
    private updatedByUserId: string;
    public get UpdatedByUserId() { return this.updatedByUserId; }
    public set UpdatedByUserId(newValue: string) { if (this.updatedByUserId != newValue) { this.updatedByUserId = newValue; this.MarkAsDirty("UpdatedByUserId"); } }
       
	 
    private updateDateTime: Date;
    public get UpdateDateTime() { return this.updateDateTime; }
    public set UpdateDateTime(newValue: Date) { if (this.updateDateTime != newValue) { this.updateDateTime = newValue; this.MarkAsDirty("UpdateDateTime"); } }
       
	 
    private createdByUserId: string;
    public get CreatedByUserId() { return this.createdByUserId; }
    public set CreatedByUserId(newValue: string) { if (this.createdByUserId != newValue) { this.createdByUserId = newValue; this.MarkAsDirty("CreatedByUserId"); } }
       
	 
    private createDateTime: Date;
    public get CreateDateTime() { return this.createDateTime; }
    public set CreateDateTime(newValue: Date) { if (this.createDateTime != newValue) { this.createDateTime = newValue; this.MarkAsDirty("CreateDateTime"); } }
       
	 
    private updatedByUserName: string;
    public get UpdatedByUserName() { return this.updatedByUserName; }
    public set UpdatedByUserName(newValue: string) { if (this.updatedByUserName != newValue) { this.updatedByUserName = newValue; this.MarkAsDirty("UpdatedByUserName"); } }
       
	 
    private createdByUserName: string;
    public get CreatedByUserName() { return this.createdByUserName; }
    public set CreatedByUserName(newValue: string) { if (this.createdByUserName != newValue) { this.createdByUserName = newValue; this.MarkAsDirty("CreatedByUserName"); } }
       
	 
    private exceptionalInterestRateName: string;
    public get ExceptionalInterestRateName() { return this.exceptionalInterestRateName; }
    public set ExceptionalInterestRateName(newValue: string) { if (this.exceptionalInterestRateName != newValue) { this.exceptionalInterestRateName = newValue; this.MarkAsDirty("ExceptionalInterestRateName"); } }
       
	 
    private creditInterestRateBaseName: string;
    public get CreditInterestRateBaseName() { return this.creditInterestRateBaseName; }
    public set CreditInterestRateBaseName(newValue: string) { if (this.creditInterestRateBaseName != newValue) { this.creditInterestRateBaseName = newValue; this.MarkAsDirty("CreditInterestRateBaseName"); } }
       
	 
    private standardInterestRateBaseName: string;
    public get StandardInterestRateBaseName() { return this.standardInterestRateBaseName; }
    public set StandardInterestRateBaseName(newValue: string) { if (this.standardInterestRateBaseName != newValue) { this.standardInterestRateBaseName = newValue; this.MarkAsDirty("StandardInterestRateBaseName"); } }
       
	 

    public OldEntityPM: GLAccountInterestPeriodPM;
	
    private entityParentPM: any;
    public get EntityParentPM() { return this.entityParentPM; }
    public set EntityParentPM(newValue: any) { this.entityParentPM = newValue; }

    private changeSetOp: string;
    public get ChangeSetOp() { return this.changeSetOp; }
    public set ChangeSetOp(newValue: string) { this.changeSetOp = newValue;  }//this.MarkAsDirty(); mohammad removed it because it sets the dirty bool to true when there is no changes.

    public UniqueKey: string;
	 	
    public IsDirty: boolean;
    public DisableMarkAsDirty: boolean = false;
    MarkAsDirty(propertyName:string = null) {
       if(!this.DisableMarkAsDirty)
       {
        this.IsDirty = true;
		  if (this.EntityParentPM) {
            this.EntityParentPM.MarkAsDirty();
        }	
        if (propertyName != null) {
            this.PropertyChanged.emit(new PropertyChangedArgs(propertyName,this));
            ServiceLocator.RulesValidator.ApplyEntityChangedRules(propertyName, this, "GLAccountInterestPeriod");
           
        }
       }
    }

    private MyClone: GLAccountInterestPeriodPM;

    public CloneMe() {
        ServiceHelper.CloneEntityPM(this);
    }

    public RejectChanges() {
        ServiceHelper.RejectEntityPMChanges(this);
    }

}