<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <Configurations>All Projects;Debug;None;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Library\Bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>AmitalCloud.Infrastructure.Domain</AssemblyTitle>
    <Product>AmitalCloud.Infrastructure.Domain</Product>
    <Copyright>Copyright ©  2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="EntityKeys\Manual\" />
    <Folder Include="EntityPOCOs\Manual\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="EntityKeys\Manual\AdvancedQueryFilterKeys.cs" />
    <Compile Remove="EntityKeys\Manual\GlobalContactKeys.cs" />
    <Compile Remove="EntityKeys\Manual\ScreenFieldKeys.cs" />
    <Compile Remove="EntityKeys\Manual\ScreenKeys.cs" />
    <Compile Remove="EntityKeys\Manual\TenantSettingKeys.cs" />
    <Compile Remove="EntityMapping\Manual\AdvancedQueryFilterMap.cs" />
    <Compile Remove="EntityMapping\Manual\AutoSignupEmailMap.cs" />
    <Compile Remove="EntityMapping\Manual\BatchServicesDefinitionModsMap.cs" />
    <Compile Remove="EntityMapping\Manual\CaptchaKeyMap.cs" />
    <Compile Remove="EntityMapping\Manual\CardContactMap.cs" />
    <Compile Remove="EntityMapping\Manual\CategoryTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\ChangePasswordLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\CommunicationAttachmentMap.cs" />
    <Compile Remove="EntityMapping\Manual\CommunicationLogStepMap.cs" />
    <Compile Remove="EntityMapping\Manual\ConactLastLoginMap.cs" />
    <Compile Remove="EntityMapping\Manual\ContactActivityLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\ContactLoginLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\ContactMobileDeviceMap.cs" />
    <Compile Remove="EntityMapping\Manual\ContactPasswordMap.cs" />
    <Compile Remove="EntityMapping\Manual\ContactTenantMap.cs" />
    <Compile Remove="EntityMapping\Manual\ConvertProgramInfoMap.cs" />
    <Compile Remove="EntityMapping\Manual\CounterLastNumberMap.cs" />
    <Compile Remove="EntityMapping\Manual\CounterMap.cs" />
    <Compile Remove="EntityMapping\Manual\CounterStatMap.cs" />
    <Compile Remove="EntityMapping\Manual\CustomerCompetitorMap.cs" />
    <Compile Remove="EntityMapping\Manual\CustomerCompetitorProductMap.cs" />
    <Compile Remove="EntityMapping\Manual\CustomerProductLocationActualDataMap.cs" />
    <Compile Remove="EntityMapping\Manual\CustomPickListMap.cs" />
    <Compile Remove="EntityMapping\Manual\CustomTableMap.cs" />
    <Compile Remove="EntityMapping\Manual\DataBasePropertyMap.cs" />
    <Compile Remove="EntityMapping\Manual\DBIdCounterMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentOutCopyMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentOutMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentsDataProviderMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentsFilingMetaDataValueMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentsFilingsViewMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentsMetaDataTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentStatusMap.cs" />
    <Compile Remove="EntityMapping\Manual\DocumentTypeMetaDataMap.cs" />
    <Compile Remove="EntityMapping\Manual\EntityDateMap.cs" />
    <Compile Remove="EntityMapping\Manual\EntityLastActivityMap.cs" />
    <Compile Remove="EntityMapping\Manual\EntityLastActivityTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\EntityLastUpdateMap.cs" />
    <Compile Remove="EntityMapping\Manual\EventRemarkMap.cs" />
    <Compile Remove="EntityMapping\Manual\FailedLoginLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\FailedTokenLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\FeatureMap.cs" />
    <Compile Remove="EntityMapping\Manual\FeatureTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\FieldDataTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\GlobalContactMap.cs" />
    <Compile Remove="EntityMapping\Manual\GlobalDBMap.cs" />
    <Compile Remove="EntityMapping\Manual\GlobalTenantCounterMap.cs" />
    <Compile Remove="EntityMapping\Manual\GlobalTenantMap.cs" />
    <Compile Remove="EntityMapping\Manual\ImageDetailMap.cs" />
    <Compile Remove="EntityMapping\Manual\InvalidEmailResetPasswordMap.cs" />
    <Compile Remove="EntityMapping\Manual\MenuButtonGroupMap.cs" />
    <Compile Remove="EntityMapping\Manual\MenuButtonMap.cs" />
    <Compile Remove="EntityMapping\Manual\MenusTableMap.cs" />
    <Compile Remove="EntityMapping\Manual\MenuTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\MobileNotificationLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\MonitorServiceLastUpdateMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectFieldModificationMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectFieldValidationMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectTableHelperControlMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectTableLastUpdateMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectTableRuleFieldMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectTableRuleMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectTableTabMap.cs" />
    <Compile Remove="EntityMapping\Manual\ObjectTableTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\OneTimePasswordMap.cs" />
    <Compile Remove="EntityMapping\Manual\PackageFeatureMap.cs" />
    <Compile Remove="EntityMapping\Manual\PasswordResetRequestMap.cs" />
    <Compile Remove="EntityMapping\Manual\PerformanceLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\PermissionTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\QueryColumnMap.cs" />
    <Compile Remove="EntityMapping\Manual\QueryGroupMap.cs" />
    <Compile Remove="EntityMapping\Manual\QueryMap.cs" />
    <Compile Remove="EntityMapping\Manual\ReportGroupMap.cs" />
    <Compile Remove="EntityMapping\Manual\RoleFeatureMap.cs" />
    <Compile Remove="EntityMapping\Manual\RoleTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\RuleConditionFieldMap.cs" />
    <Compile Remove="EntityMapping\Manual\RuleNotificationTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\RuleTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\ScreenFieldMap.cs" />
    <Compile Remove="EntityMapping\Manual\ScreenMap.cs" />
    <Compile Remove="EntityMapping\Manual\ScreenModificationMap.cs" />
    <Compile Remove="EntityMapping\Manual\SessionPolicyMap.cs" />
    <Compile Remove="EntityMapping\Manual\SettingMap.cs" />
    <Compile Remove="EntityMapping\Manual\SmallDocumentMap.cs" />
    <Compile Remove="EntityMapping\Manual\SpecialServiceMap.cs" />
    <Compile Remove="EntityMapping\Manual\SystemMetadataLastUpdateMap.cs" />
    <Compile Remove="EntityMapping\Manual\TenantSettingMap.cs" />
    <Compile Remove="EntityMapping\Manual\TextCodeTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\TipMap.cs" />
    <Compile Remove="EntityMapping\Manual\TipsVisibilityMap.cs" />
    <Compile Remove="EntityMapping\Manual\TranslationHeaderMap.cs" />
    <Compile Remove="EntityMapping\Manual\TranslationMap.cs" />
    <Compile Remove="EntityMapping\Manual\TriggerTypeMap.cs" />
    <Compile Remove="EntityMapping\Manual\UserLastLoginMap.cs" />
    <Compile Remove="EntityMapping\Manual\UserLoginLogMap.cs" />
    <Compile Remove="EntityMapping\Manual\UserPermittedBranchMap.cs" />
    <Compile Remove="EntityMapping\Manual\UserPermittedProductMap.cs" />
    <Compile Remove="EntityMapping\Manual\ValidationTypeMap.cs" />
    <Compile Remove="EntityPMs\Manual\AdvancedQueryFilterPM.cs" />
    <Compile Remove="EntityPMs\Manual\CardContactPM.cs" />
    <Compile Remove="EntityPMs\Manual\ColorIndexPM.cs" />
    <Compile Remove="EntityPMs\Manual\CommunicationLogStepPM.cs" />
    <Compile Remove="EntityPMs\Manual\ContactTenantPM.cs" />
    <Compile Remove="EntityPMs\Manual\ContactTenantRolePM.cs" />
    <Compile Remove="EntityPMs\Manual\CounterPM.cs" />
    <Compile Remove="EntityPMs\Manual\CustomerCompetitorPM.cs" />
    <Compile Remove="EntityPMs\Manual\CustomerCompetitorProductPM.cs" />
    <Compile Remove="EntityPMs\Manual\CustomerProductLocationActualDataPM.cs" />
    <Compile Remove="EntityPMs\Manual\CustomPickListPM.cs" />
    <Compile Remove="EntityPMs\Manual\CustomTablePM.cs" />
    <Compile Remove="EntityPMs\Manual\DocumentOutPM.cs" />
    <Compile Remove="EntityPMs\Manual\DocumentPM.cs" />
    <Compile Remove="EntityPMs\Manual\DocumentsFilingMetaDataValuePM.cs" />
    <Compile Remove="EntityPMs\Manual\DocumentStatusPM.cs" />
    <Compile Remove="EntityPMs\Manual\DWQueryPM.cs" />
    <Compile Remove="EntityPMs\Manual\EntityLastAccessPM.cs" />
    <Compile Remove="EntityPMs\Manual\EventRemarkPM.cs" />
    <Compile Remove="EntityPMs\Manual\ExtendedContactPM.cs" />
    <Compile Remove="EntityPMs\Manual\FeaturePM.cs" />
    <Compile Remove="EntityPMs\Manual\FieldDataTypePM.cs" />
    <Compile Remove="EntityPMs\Manual\FollowUpPM.cs" />
    <Compile Remove="EntityPMs\Manual\GlobalContactPM.cs" />
    <Compile Remove="EntityPMs\Manual\GlobalTenantPM.cs" />
    <Compile Remove="EntityPMs\Manual\ImageDetailPM.cs" />
    <Compile Remove="EntityPMs\Manual\MenuButtonGroupPM.cs" />
    <Compile Remove="EntityPMs\Manual\MenuButtonPM.cs" />
    <Compile Remove="EntityPMs\Manual\MenusTablePM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectCustomFieldPM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectFieldValidationPM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectTableHelperControlPM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectTableLastUpdatePM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectTableRuleFieldPM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectTableRulePM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectTableTabPM.cs" />
    <Compile Remove="EntityPMs\Manual\ObjectTableTypePM.cs" />
    <Compile Remove="EntityPMs\Manual\PackageFeaturePM.cs" />
    <Compile Remove="EntityPMs\Manual\PermissionTypePM.cs" />
    <Compile Remove="EntityPMs\Manual\QueryColumnPM.cs" />
    <Compile Remove="EntityPMs\Manual\QueryGroupPM.cs" />
    <Compile Remove="EntityPMs\Manual\QueryPM.cs" />
    <Compile Remove="EntityPMs\Manual\ReportGroupPM.cs" />
    <Compile Remove="EntityPMs\Manual\RoleFeaturePM.cs" />
    <Compile Remove="EntityPMs\Manual\RoleTypePM.cs" />
    <Compile Remove="EntityPMs\Manual\RuleConditionFieldPM.cs" />
    <Compile Remove="EntityPMs\Manual\ScreenFieldPM.cs" />
    <Compile Remove="EntityPMs\Manual\ScreenPM.cs" />
    <Compile Remove="EntityPMs\Manual\SharedUserQueryPM.cs" />
    <Compile Remove="EntityPMs\Manual\TenantSettingPM.cs" />
    <Compile Remove="EntityPMs\Manual\TermsofUsePM.cs" />
    <Compile Remove="EntityPMs\Manual\TextCodeTypePM.cs" />
    <Compile Remove="EntityPMs\Manual\TipPM.cs" />
    <Compile Remove="EntityPMs\Manual\UserLastLoginPM.cs" />
    <Compile Remove="EntityPMs\Manual\UserLoginLogPM.cs" />
    <Compile Remove="EntityPMs\Manual\UserPermittedBranchPM.cs" />
    <Compile Remove="EntityPMs\Manual\UserPermittedProductPM.cs" />
    <Compile Remove="EntityPOCOs\Manual\AdvancedQueryFilter.cs" />
    <Compile Remove="EntityPOCOs\Manual\AgentSharedLogisticsKey.cs" />
    <Compile Remove="EntityPOCOs\Manual\AllActiveGLAccountsView.cs" />
    <Compile Remove="EntityPOCOs\Manual\AnalyzeQueueStatus.cs" />
    <Compile Remove="EntityPOCOs\Manual\AuthenticationToken.cs" />
    <Compile Remove="EntityPOCOs\Manual\AutomationHistory.cs" />
    <Compile Remove="EntityPOCOs\Manual\AutomationLastUpdate.cs" />
    <Compile Remove="EntityPOCOs\Manual\AutoSignupEmail.cs" />
    <Compile Remove="EntityPOCOs\Manual\BatchServicesDefinitionMods.cs" />
    <Compile Remove="EntityPOCOs\Manual\BlobFile.cs" />
    <Compile Remove="EntityPOCOs\Manual\CaptchaKey.cs" />
    <Compile Remove="EntityPOCOs\Manual\Card.cs" />
    <Compile Remove="EntityPOCOs\Manual\CardContact.cs" />
    <Compile Remove="EntityPOCOs\Manual\Carrier.cs" />
    <Compile Remove="EntityPOCOs\Manual\CategoryType.cs" />
    <Compile Remove="EntityPOCOs\Manual\ChangePasswordLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\ColorIndex.cs" />
    <Compile Remove="EntityPOCOs\Manual\CommunicationAttachment.cs" />
    <Compile Remove="EntityPOCOs\Manual\CommunicationLogStep.cs" />
    <Compile Remove="EntityPOCOs\Manual\Contact.cs" />
    <Compile Remove="EntityPOCOs\Manual\ContactActivityLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\ContactLastLogin.cs" />
    <Compile Remove="EntityPOCOs\Manual\ContactLoginLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\ContactMobileDevice.cs" />
    <Compile Remove="EntityPOCOs\Manual\ContactPassword.cs" />
    <Compile Remove="EntityPOCOs\Manual\ContactTenant.cs" />
    <Compile Remove="EntityPOCOs\Manual\ContactTenantRole.cs" />
    <Compile Remove="EntityPOCOs\Manual\ConvertProgramInfo.cs" />
    <Compile Remove="EntityPOCOs\Manual\Counter.cs" />
    <Compile Remove="EntityPOCOs\Manual\CounterLastNumber.cs" />
    <Compile Remove="EntityPOCOs\Manual\CounterStat.cs" />
    <Compile Remove="EntityPOCOs\Manual\CustomerCompetitor.cs" />
    <Compile Remove="EntityPOCOs\Manual\CustomerCompetitorProduct.cs" />
    <Compile Remove="EntityPOCOs\Manual\CustomerProductLocationActualData.cs" />
    <Compile Remove="EntityPOCOs\Manual\CustomMetaDataTypesAdditional.cs" />
    <Compile Remove="EntityPOCOs\Manual\CustomPickList.cs" />
    <Compile Remove="EntityPOCOs\Manual\CustomTable.cs" />
    <Compile Remove="EntityPOCOs\Manual\DataBaseProperty.cs" />
    <Compile Remove="EntityPOCOs\Manual\DataProvider.cs" />
    <Compile Remove="EntityPOCOs\Manual\DBIdCounter.cs" />
    <Compile Remove="EntityPOCOs\Manual\DigitalContactLastSetting.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocsIn.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocsOut.cs" />
    <Compile Remove="EntityPOCOs\Manual\Document.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentOut.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentOutCopy.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentsDataProvider.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentsFilingMetaDataValue.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentsFilingsView.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentsMetaDataType.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentStatus.cs" />
    <Compile Remove="EntityPOCOs\Manual\DocumentTypeMetaData.cs" />
    <Compile Remove="EntityPOCOs\Manual\DWHBuildStatus.cs" />
    <Compile Remove="EntityPOCOs\Manual\DWHEnvironmentSetting.cs" />
    <Compile Remove="EntityPOCOs\Manual\DWObjectFieldCategories.cs" />
    <Compile Remove="EntityPOCOs\Manual\DWQuery.cs" />
    <Compile Remove="EntityPOCOs\Manual\DWQueryColumn.cs" />
    <Compile Remove="EntityPOCOs\Manual\DWQueryFilter.cs" />
    <Compile Remove="EntityPOCOs\Manual\DWSubQuery.cs" />
    <Compile Remove="EntityPOCOs\Manual\EmailProvider.cs" />
    <Compile Remove="EntityPOCOs\Manual\EntityCasualData.cs" />
    <Compile Remove="EntityPOCOs\Manual\EntityChange.cs" />
    <Compile Remove="EntityPOCOs\Manual\EntityDate.cs" />
    <Compile Remove="EntityPOCOs\Manual\EntityLastActivity.cs" />
    <Compile Remove="EntityPOCOs\Manual\EntityLastActivityType.cs" />
    <Compile Remove="EntityPOCOs\Manual\EntityLastUpdate.cs" />
    <Compile Remove="EntityPOCOs\Manual\EntityPartner.cs" />
    <Compile Remove="EntityPOCOs\Manual\EventRemark.cs" />
    <Compile Remove="EntityPOCOs\Manual\FailedLoginLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\FailedTokenLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\Feature.cs" />
    <Compile Remove="EntityPOCOs\Manual\FeatureChange.cs" />
    <Compile Remove="EntityPOCOs\Manual\FeatureType.cs" />
    <Compile Remove="EntityPOCOs\Manual\FieldDataType.cs" />
    <Compile Remove="EntityPOCOs\Manual\FieldsTranslations.cs" />
    <Compile Remove="EntityPOCOs\Manual\FormCustomField.cs" />
    <Compile Remove="EntityPOCOs\Manual\GeneralLock.cs" />
    <Compile Remove="EntityPOCOs\Manual\GlobalContact.cs" />
    <Compile Remove="EntityPOCOs\Manual\GlobalDB.cs" />
    <Compile Remove="EntityPOCOs\Manual\GlobalTenant.cs" />
    <Compile Remove="EntityPOCOs\Manual\GlobalTenantCounter.cs" />
    <Compile Remove="EntityPOCOs\Manual\HybridPartnersPermission.cs" />
    <Compile Remove="EntityPOCOs\Manual\ImageDetail.cs" />
    <Compile Remove="EntityPOCOs\Manual\InvalidEmailResetPassword.cs" />
    <Compile Remove="EntityPOCOs\Manual\LogBoxTenantSetting.cs" />
    <Compile Remove="EntityPOCOs\Manual\MenuButton.cs" />
    <Compile Remove="EntityPOCOs\Manual\MenuButtonGroup.cs" />
    <Compile Remove="EntityPOCOs\Manual\MenusTable.cs" />
    <Compile Remove="EntityPOCOs\Manual\MenuType.cs" />
    <Compile Remove="EntityPOCOs\Manual\MobileNotificationLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\MonitorServiceLastUpdate.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectFieldModification.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectFieldValidation.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectTableHelperControl.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectTableLastUpdate.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectTableRule.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectTableRuleField.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectTableTab.cs" />
    <Compile Remove="EntityPOCOs\Manual\ObjectTableType.cs" />
    <Compile Remove="EntityPOCOs\Manual\OneTimePassword.cs" />
    <Compile Remove="EntityPOCOs\Manual\PackageFeature.cs" />
    <Compile Remove="EntityPOCOs\Manual\PasswordResetRequest.cs" />
    <Compile Remove="EntityPOCOs\Manual\PerformanceLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\PermissionType.cs" />
    <Compile Remove="EntityPOCOs\Manual\Query.cs" />
    <Compile Remove="EntityPOCOs\Manual\QueryColumn.cs" />
    <Compile Remove="EntityPOCOs\Manual\QueryGroup.cs" />
    <Compile Remove="EntityPOCOs\Manual\QueueDefinition.cs" />
    <Compile Remove="EntityPOCOs\Manual\QueueMessage.cs" />
    <Compile Remove="EntityPOCOs\Manual\ReportGroup.cs" />
    <Compile Remove="EntityPOCOs\Manual\RoleFeature.cs" />
    <Compile Remove="EntityPOCOs\Manual\RoleType.cs" />
    <Compile Remove="EntityPOCOs\Manual\RuleConditionField.cs" />
    <Compile Remove="EntityPOCOs\Manual\RuleNotificationType.cs" />
    <Compile Remove="EntityPOCOs\Manual\RuleType.cs" />
    <Compile Remove="EntityPOCOs\Manual\Screen.cs" />
    <Compile Remove="EntityPOCOs\Manual\ScreenField.cs" />
    <Compile Remove="EntityPOCOs\Manual\ScreenModification.cs" />
    <Compile Remove="EntityPOCOs\Manual\SessionPolicy.cs" />
    <Compile Remove="EntityPOCOs\Manual\Setting.cs" />
    <Compile Remove="EntityPOCOs\Manual\SharedLogistics.cs" />
    <Compile Remove="EntityPOCOs\Manual\SharedUserQuery.cs" />
    <Compile Remove="EntityPOCOs\Manual\SmallDocument.cs" />
    <Compile Remove="EntityPOCOs\Manual\SpecialService.cs" />
    <Compile Remove="EntityPOCOs\Manual\SystemMetadataLastUpdate.cs" />
    <Compile Remove="EntityPOCOs\Manual\TenantSetting.cs" />
    <Compile Remove="EntityPOCOs\Manual\TermsofUse.cs" />
    <Compile Remove="EntityPOCOs\Manual\TextCodeType.cs" />
    <Compile Remove="EntityPOCOs\Manual\Tip.cs" />
    <Compile Remove="EntityPOCOs\Manual\TipsVisibility.cs" />
    <Compile Remove="EntityPOCOs\Manual\Translation.cs" />
    <Compile Remove="EntityPOCOs\Manual\TranslationHeader.cs" />
    <Compile Remove="EntityPOCOs\Manual\TriggerType.cs" />
    <Compile Remove="EntityPOCOs\Manual\UserLastLogin.cs" />
    <Compile Remove="EntityPOCOs\Manual\UserLoginLog.cs" />
    <Compile Remove="EntityPOCOs\Manual\UserPermittedBranch.cs" />
    <Compile Remove="EntityPOCOs\Manual\UserPermittedProduct.cs" />
    <Compile Remove="EntityPOCOs\Manual\UsersReleaseNotesDisplay.cs" />
    <Compile Remove="EntityPOCOs\Manual\ValidationType.cs" />
  </ItemGroup>
</Project>