--create or replace PROCEDURE USP_SSO(
--    P_EMAIL    IN AUTHENTICATIONTOKENS.EMAIL%TYPE ,
--    P_PASSHASH IN AUTHENTICATIONTOKENS.PASSWORD%TYPE ,
--    P_TENANT   IN AUTHENTICATIONTOKENS.TENANT%TYPE ,
--    P_TOKEN IN AUTHENTICATIONTOKENS.TOKEN%TYPE ,
    
--    P_MOREPS_IN  IN VARCHAR2 ,
--    P_MOREPS_OUT OUT VARCHAR2 ,
--    P_STATUS OUT VARCHAR2 ,
--    P_MESS OUT VARCHAR2 , 
--    P_LOG OUT VARCHAR2 )
--AS
--  v_Current     NUMBER(10,0);
--  v_LOGIN_EMAIL VARCHAR2(70) :='';
--  --V_ TOKEN VARCHAR2(100):='';
--BEGIN
--  NULL; 
  
--    P_MOREPS_OUT := '-1';
--    P_STATUS := '-1';
--    P_MESS := '-1';
--    P_LOG := '-1';
  
--  P_STATUS  := '-1';
--  P_LOG            := 'STAR';
  
--  IF P_EMAIL IS NULL THEN
--    P_MESS         := 'v_LOGIN_EMAIL is null';
--    RETURN;
--  END IF;
--  IF P_EMAIL ='' THEN
--    P_MESS        := 'v_LOGIN_EMAIL is null';
--    RETURN;
--  END IF;
--IF P_TOKEN ='' THEN
--    P_MESS        := 'P_LOGIN_TOKEN is null';
--    RETURN;
--  END IF;
--    IF P_TOKEN IS NULL THEN
--    P_MESS        := 'P_LOGIN_TOKEN is null';
--    RETURN;
--  END IF;
  
  
--  --V_ TOKEN := SYS_GUID(); GET 3C0D01FB87B74D228B29D4D37552C5E9  LENGTH =32 
--  --CREATE TABLE "LOGITUDE_MAIN"."AUTHENTICATIONTOKENS"
----- ( "TOKEN" VARCHAR2(100 CHAR) NOT NULL ENABLE,
----"TENANT" NUMBER(10,0) NOT NULL ENABLE,
----"EMAIL" VARCHAR2(70 CHAR) NOT NULL ENABLE,
----"PASSWORD" VARCHAR2(40 CHAR) NOT NULL ENABLE,
----"CREATEDATE" TIMESTAMP (7) NOT NULL ENABLE,
 
--  INSERT INTO AUTHENTICATIONTOKENS  (TOKEN, TENANT, EMAIL, PASSWORD , CREATEDATE)    VALUES (  P_TOKEN, P_TENANT   ,  P_EMAIL    ,P_PASSHASH ,SYSDATE );
   
--   commit;
--  P_STATUS  := '0';    
--EXCEPTION

-- WHEN OTHERS THEN
-- P_MESS:= 'LOGITUDE_MAIN SP_SSO Error: ' || SQLERRM;
-- P_STATUS:=-1;
-- dbms_output.put_line ( P_STATUS ) ;
   
--END USP_SSO;
