-- Change Size From -1 To 250 For Column USEDFOR
ALTER TABLE "APICREDINTIALS" ADD "TEMP_USEDFOR" NVARCHAR2(250) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_USEDFOR" = "USEDFOR";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "USEDFOR" TO "CDROP_USEDFOR";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_USEDFOR" TO "USEDFOR";


-- Change Size From -1 To 40 For Column HASHEDPRIMARYACCESSKEY
ALTER TABLE "APICREDINTIALS" ADD "TEMP_HASHEDPRIMARYACCESSKEY" NVARCHAR2(40) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_HASHEDPRIMARYACCESSKEY" = "HASHEDPRIMARYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "HASHEDPRIMARYACCESSKEY" TO "CDROP_HASHEDPRIMARYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_HASHEDPRIMARYACCESSKEY" TO "HASHEDPRIMARYACCESSKEY";


-- Change Size From -1 To 40 For Column HASHEDSECONDERYACCESSKEY
ALTER TABLE "APICREDINTIALS" ADD "TEMP_HASHEDSECONDERYACCESSKEY" NVARCHAR2(40) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_HASHEDSECONDERYACCESSKEY" = "HASHEDSECONDERYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "HASHEDSECONDERYACCESSKEY" TO "CDROP_HASHEDSECONDERYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_HASHEDSECONDERYACCESSKEY" TO "HASHEDSECONDERYACCESSKEY";


-- Change Size From -1 To 1000 For Column ALLOWEDIPS
ALTER TABLE "APICREDINTIALS" ADD "TEMP_ALLOWEDIPS" NVARCHAR2(1000) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_ALLOWEDIPS" = "ALLOWEDIPS";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "ALLOWEDIPS" TO "CDROP_ALLOWEDIPS";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_ALLOWEDIPS" TO "ALLOWEDIPS";


-- Change Size From -1 To 100 For Column CREATEDBY
ALTER TABLE "APICREDINTIALS" ADD "TEMP_CREATEDBY" VARCHAR2(100 CHAR) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_CREATEDBY" = "CREATEDBY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "CREATEDBY" TO "CDROP_CREATEDBY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_CREATEDBY" TO "CREATEDBY";


-- Change Size From -1 To 100 For Column UPDATEDBY
ALTER TABLE "APICREDINTIALS" ADD "TEMP_UPDATEDBY" VARCHAR2(100 CHAR) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_UPDATEDBY" = "UPDATEDBY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "UPDATEDBY" TO "CDROP_UPDATEDBY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_UPDATEDBY" TO "UPDATEDBY";


-- Change Size From -1 To 40 For Column MASKEDPRIMARYACCESSKEY
ALTER TABLE "APICREDINTIALS" ADD "TEMP_MASKEDPRIMARYACCESSKEY" NVARCHAR2(40) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_MASKEDPRIMARYACCESSKEY" = "MASKEDPRIMARYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "MASKEDPRIMARYACCESSKEY" TO "CDROP_MASKEDPRIMARYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_MASKEDPRIMARYACCESSKEY" TO "MASKEDPRIMARYACCESSKEY";


-- Change Size From -1 To 40 For Column MASKEDSECONDERYACCESSKEY
ALTER TABLE "APICREDINTIALS" ADD "TEMP_MASKEDSECONDERYACCESSKEY" NVARCHAR2(40) NULL;
UPDATE "APICREDINTIALS" SET "TEMP_MASKEDSECONDERYACCESSKEY" = "MASKEDSECONDERYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "MASKEDSECONDERYACCESSKEY" TO "CDROP_MASKEDSECONDERYACCESSKEY";
ALTER TABLE "APICREDINTIALS" RENAME COLUMN "TEMP_MASKEDSECONDERYACCESSKEY" TO "MASKEDSECONDERYACCESSKEY";



-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "BATCHSERVICESDEFINITIONS" ADD "TEMP_CODE" VARCHAR2(128 CHAR) NULL;
UPDATE "BATCHSERVICESDEFINITIONS" SET "TEMP_CODE" = "CODE";
ALTER TABLE "BATCHSERVICESDEFINITIONS" MODIFY "TEMP_CODE" NOT NULL;
ALTER TABLE "BATCHSERVICESDEFINITIONS" MODIFY "CODE" NULL;
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "CODE" TO "CDROP_CODE";
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "TEMP_CODE" TO "CODE";


-- Change Size From -1 To 100 For Column CLASSNAME
ALTER TABLE "BATCHSERVICESDEFINITIONS" ADD "TEMP_CLASSNAME" VARCHAR2(100 CHAR) NULL;
UPDATE "BATCHSERVICESDEFINITIONS" SET "TEMP_CLASSNAME" = "CLASSNAME";
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "CLASSNAME" TO "CDROP_CLASSNAME";
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "TEMP_CLASSNAME" TO "CLASSNAME";


-- Change Size From -1 To 25 For Column PARAMETER1
ALTER TABLE "BATCHSERVICESDEFINITIONS" ADD "TEMP_PARAMETER1" VARCHAR2(25 CHAR) NULL;
UPDATE "BATCHSERVICESDEFINITIONS" SET "TEMP_PARAMETER1" = "PARAMETER1";
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "PARAMETER1" TO "CDROP_PARAMETER1";
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "TEMP_PARAMETER1" TO "PARAMETER1";


-- Change Size From -1 To 25 For Column PARAMETER2
ALTER TABLE "BATCHSERVICESDEFINITIONS" ADD "TEMP_PARAMETER2" VARCHAR2(25 CHAR) NULL;
UPDATE "BATCHSERVICESDEFINITIONS" SET "TEMP_PARAMETER2" = "PARAMETER2";
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "PARAMETER2" TO "CDROP_PARAMETER2";
ALTER TABLE "BATCHSERVICESDEFINITIONS" RENAME COLUMN "TEMP_PARAMETER2" TO "PARAMETER2";



-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" ADD "TEMP_CODE" VARCHAR2(128 CHAR) NULL;
UPDATE "BATCHSERVICESDEFINITIONMODS" SET "TEMP_CODE" = "CODE";
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" MODIFY "TEMP_CODE" NOT NULL;
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" MODIFY "CODE" NULL;
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" RENAME COLUMN "CODE" TO "CDROP_CODE";
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" RENAME COLUMN "TEMP_CODE" TO "CODE";



-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "BLUESNAPCONTRACTTYPES" ADD "TEMP_CODE" VARCHAR2(128 CHAR) NULL;
UPDATE "BLUESNAPCONTRACTTYPES" SET "TEMP_CODE" = "CODE";
ALTER TABLE "BLUESNAPCONTRACTTYPES" MODIFY "TEMP_CODE" NOT NULL;
ALTER TABLE "BLUESNAPCONTRACTTYPES" MODIFY "CODE" NULL;
ALTER TABLE "BLUESNAPCONTRACTTYPES" RENAME COLUMN "CODE" TO "CDROP_CODE";
ALTER TABLE "BLUESNAPCONTRACTTYPES" RENAME COLUMN "TEMP_CODE" TO "CODE";


-- Change Size From -1 To 40 For Column NAME
ALTER TABLE "BLUESNAPCONTRACTTYPES" ADD "TEMP_NAME" VARCHAR2(40 CHAR) NULL;
UPDATE "BLUESNAPCONTRACTTYPES" SET "TEMP_NAME" = "NAME";
ALTER TABLE "BLUESNAPCONTRACTTYPES" RENAME COLUMN "NAME" TO "CDROP_NAME";
ALTER TABLE "BLUESNAPCONTRACTTYPES" RENAME COLUMN "TEMP_NAME" TO "NAME";


-- Change Size From -1 To 1000 For Column SEARCHFIELDS
ALTER TABLE "BLUESNAPCONTRACTTYPES" ADD "TEMP_SEARCHFIELDS" NVARCHAR2(1000) NULL;
UPDATE "BLUESNAPCONTRACTTYPES" SET "TEMP_SEARCHFIELDS" = "SEARCHFIELDS";
ALTER TABLE "BLUESNAPCONTRACTTYPES" RENAME COLUMN "SEARCHFIELDS" TO "CDROP_SEARCHFIELDS";
ALTER TABLE "BLUESNAPCONTRACTTYPES" RENAME COLUMN "TEMP_SEARCHFIELDS" TO "SEARCHFIELDS";



-- Change Size From -1 To 120 For Column COUNTRYNAME
ALTER TABLE "TENANTMANAGEMENTS" ADD "TEMP_COUNTRYNAME" VARCHAR2(120 CHAR) NULL;
UPDATE "TENANTMANAGEMENTS" SET "TEMP_COUNTRYNAME" = "COUNTRYNAME";
ALTER TABLE "TENANTMANAGEMENTS" RENAME COLUMN "COUNTRYNAME" TO "CDROP_COUNTRYNAME";
ALTER TABLE "TENANTMANAGEMENTS" RENAME COLUMN "TEMP_COUNTRYNAME" TO "COUNTRYNAME";


-- Change Size From -1 To 33 For Column TTY
ALTER TABLE "TENANTMANAGEMENTS" ADD "TEMP_TTY" VARCHAR2(33 CHAR) NULL;
UPDATE "TENANTMANAGEMENTS" SET "TEMP_TTY" = "TTY";
ALTER TABLE "TENANTMANAGEMENTS" RENAME COLUMN "TTY" TO "CDROP_TTY";
ALTER TABLE "TENANTMANAGEMENTS" RENAME COLUMN "TEMP_TTY" TO "TTY";



