-- Set Nullable For Column CHAMPURL
ALTER TABLE "SETTINGS" MODIFY "CHAMPURL" NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Set Nullable For Column CHAMPURL
ALTER TABLE "SETTINGS" MODIFY "CHAMPURL" NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('950fa10a-b94b-4cdd-9c11-431710d84e38', 'Setting.dxml', 'SETTINGS', 'CHAMPURL', 'Set Column Nullable', SYSDATE, ScriptText); END;


-- Create New Table With Name TENANTMANAGEMENTLICENSES
CREATE TABLE "TENANTMANAGEMENTLICENSES"(
"ID" VARCHAR2(15 CHAR) NOT NULL,
"TENANT" NUMBER(10, 0) NOT NULL,
"PACKAGECODE" VARCHAR2(5 CHAR) NOT NULL,
"NUMBEROFUSERS" NUMBER(10, 0) NULL,
"FREEUSERS" NUMBER(10, 0) NULL,
"PRICE" NUMBER NULL,
"TOTALPRICE" NUMBER NULL,
CONSTRAINT "PK_TENANTMANAGEMENTLICENSES" PRIMARY KEY("ID")
);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create New Table With Name TENANTMANAGEMENTLICENSES
CREATE TABLE "TENANTMANAGEMENTLICENSES"(
"ID" VARCHAR2(15 CHAR) NOT NULL,
"TENANT" NUMBER(10, 0) NOT NULL,
"PACKAGECODE" VARCHAR2(5 CHAR) NOT NULL,
"NUMBEROFUSERS" NUMBER(10, 0) NULL,
"FREEUSERS" NUMBER(10, 0) NULL,
"PRICE" NUMBER NULL,
"TOTALPRICE" NUMBER NULL,
CONSTRAINT "PK_TENANTMANAGEMENTLICENSES" PRIMARY KEY("ID")
);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('46f9faac-06d5-4e35-8a6e-f157142736ef', 'TenantManagementLicense.dxml', 'TENANTMANAGEMENTLICENSES', NULL, 'Create Table', SYSDATE, ScriptText); END;


-- Create New Table With Name TENANTMANAGMENTPRIVATELABELS
CREATE TABLE "TENANTMANAGMENTPRIVATELABELS"(
"ID" VARCHAR2(15 CHAR) NOT NULL,
"PRIVATELABELNAME" NVARCHAR2(60) NOT NULL,
"PRIVATELABELSHORTNAME" VARCHAR2(60 CHAR) NOT NULL,
"PRIVATELABELURL" VARCHAR2(100 CHAR) NOT NULL,
"MAINLOGO" BLOB NULL,
"SMALLLOGO" BLOB NULL,
"CONTACTUSEMAIL" NVARCHAR2(70) NOT NULL,
"RECEIVEALLSTATUSES" NUMBER(1, 0) DEFAULT 0 NOT NULL,
"HYBRIDPARTNERID" NVARCHAR2(15) NOT NULL,
"SEARCHFIELDS" NVARCHAR2(500) NULL,
"INACTIVE" NUMBER(1, 0) DEFAULT 0 NOT NULL,
"TENANT" NUMBER(10, 0) DEFAULT 0 NOT NULL,
CONSTRAINT "PK_TENANTMANAGMENTPRIVAT_AOHVK" PRIMARY KEY("ID")
);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create New Table With Name TENANTMANAGMENTPRIVATELABELS
CREATE TABLE "TENANTMANAGMENTPRIVATELABELS"(
"ID" VARCHAR2(15 CHAR) NOT NULL,
"PRIVATELABELNAME" NVARCHAR2(60) NOT NULL,
"PRIVATELABELSHORTNAME" VARCHAR2(60 CHAR) NOT NULL,
"PRIVATELABELURL" VARCHAR2(100 CHAR) NOT NULL,
"MAINLOGO" BLOB NULL,
"SMALLLOGO" BLOB NULL,
"CONTACTUSEMAIL" NVARCHAR2(70) NOT NULL,
"RECEIVEALLSTATUSES" NUMBER(1, 0) DEFAULT 0 NOT NULL,
"HYBRIDPARTNERID" NVARCHAR2(15) NOT NULL,
"SEARCHFIELDS" NVARCHAR2(500) NULL,
"INACTIVE" NUMBER(1, 0) DEFAULT 0 NOT NULL,
"TENANT" NUMBER(10, 0) DEFAULT 0 NOT NULL,
CONSTRAINT "PK_TENANTMANAGMENTPRIVAT_AOHVK" PRIMARY KEY("ID")
);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('83e3ac96-4ea8-4d35-b9bb-e39544d6743c', 'TenantManagmentPrivateLabels.dxml', 'TENANTMANAGMENTPRIVATELABELS', NULL, 'Create Table', SYSDATE, ScriptText); END;


-- Create New Table With Name WEBHOOKKEYS
CREATE TABLE "WEBHOOKKEYS"(
"ID" VARCHAR2(15 CHAR) DEFAULT '' NOT NULL,
"ACCESSKEY" VARCHAR2(200 CHAR) NULL,
"TENANT" NUMBER(10, 0) NOT NULL,
"PARTNERNAME" VARCHAR2(150 CHAR) NOT NULL,
"INACTIVE" NUMBER(1, 0) DEFAULT 0 NOT NULL,
"CREATEDBYUSERNAME" VARCHAR2(150 CHAR) NOT NULL,
"CREATEDATE" TIMESTAMP(7) NOT NULL,
"UPDATEDBYUSERNAME" VARCHAR2(150 CHAR) NOT NULL,
"UPDATEDATE" TIMESTAMP(7) NOT NULL,
"DESCRIPTION" VARCHAR2(200 CHAR) NULL,
"SEARCHFIELDS" NVARCHAR2(1000) NULL,
CONSTRAINT "PK_WEBHOOKKEYS" PRIMARY KEY("ID")
);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create New Table With Name WEBHOOKKEYS
CREATE TABLE "WEBHOOKKEYS"(
"ID" VARCHAR2(15 CHAR) DEFAULT '''' NOT NULL,
"ACCESSKEY" VARCHAR2(200 CHAR) NULL,
"TENANT" NUMBER(10, 0) NOT NULL,
"PARTNERNAME" VARCHAR2(150 CHAR) NOT NULL,
"INACTIVE" NUMBER(1, 0) DEFAULT 0 NOT NULL,
"CREATEDBYUSERNAME" VARCHAR2(150 CHAR) NOT NULL,
"CREATEDATE" TIMESTAMP(7) NOT NULL,
"UPDATEDBYUSERNAME" VARCHAR2(150 CHAR) NOT NULL,
"UPDATEDATE" TIMESTAMP(7) NOT NULL,
"DESCRIPTION" VARCHAR2(200 CHAR) NULL,
"SEARCHFIELDS" NVARCHAR2(1000) NULL,
CONSTRAINT "PK_WEBHOOKKEYS" PRIMARY KEY("ID")
);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('2bc5e686-31d8-480c-a0c2-d59df59286ee', 'WebhookKeys.dxml', 'WEBHOOKKEYS', NULL, 'Create Table', SYSDATE, ScriptText); END;


-- Add Foreign Key Constraint For Column STATUS In Table ANALYZEQUEUES As Reference To Column CODE In Table ANALYZEQUEUESTATUS
ALTER TABLE "ANALYZEQUEUES" ADD CONSTRAINT "FK_ANALYZEQUEUES_ANALYZE_SJPVD" FOREIGN KEY("STATUS") REFERENCES "ANALYZEQUEUESTATUS"("CODE");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column STATUS In Table ANALYZEQUEUES As Reference To Column CODE In Table ANALYZEQUEUESTATUS
ALTER TABLE "ANALYZEQUEUES" ADD CONSTRAINT "FK_ANALYZEQUEUES_ANALYZE_SJPVD" FOREIGN KEY("STATUS") REFERENCES "ANALYZEQUEUESTATUS"("CODE");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('9b6bfbbd-49bd-4471-a32a-2d11d0c3a540', 'AnalyzeQueue.dxml', 'ANALYZEQUEUES', 'STATUS', 'Create Relation', SYSDATE, ScriptText); END;

-- Create Index On ANALYZEQUEUES Table
CREATE INDEX "IX_ANALYZEQUEUES_STATUS" ON "ANALYZEQUEUES"("STATUS");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On ANALYZEQUEUES Table
CREATE INDEX "IX_ANALYZEQUEUES_STATUS" ON "ANALYZEQUEUES"("STATUS");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('5b1e0ba3-16db-43e7-a9fb-ea9361915179', 'AnalyzeQueue.dxml', 'ANALYZEQUEUES', 'STATUS', 'Create Index', SYSDATE, ScriptText); END;

-- Add Foreign Key Constraint For Column TENANT In Table ANALYZEQUEUES As Reference To Column ID In Table TENANTMANAGEMENTS
ALTER TABLE "ANALYZEQUEUES" ADD CONSTRAINT "FK_ANALYZEQUEUES_TENANTM_OBWKX" FOREIGN KEY("TENANT") REFERENCES "TENANTMANAGEMENTS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column TENANT In Table ANALYZEQUEUES As Reference To Column ID In Table TENANTMANAGEMENTS
ALTER TABLE "ANALYZEQUEUES" ADD CONSTRAINT "FK_ANALYZEQUEUES_TENANTM_OBWKX" FOREIGN KEY("TENANT") REFERENCES "TENANTMANAGEMENTS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('9c8fc446-d2a3-4566-958a-f5c306ea1174', 'AnalyzeQueue.dxml', 'ANALYZEQUEUES', 'TENANT', 'Create Relation', SYSDATE, ScriptText); END;

-- Create Index On ANALYZEQUEUES Table
CREATE INDEX "IX_ANALYZEQUEUES_TENANT" ON "ANALYZEQUEUES"("TENANT");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On ANALYZEQUEUES Table
CREATE INDEX "IX_ANALYZEQUEUES_TENANT" ON "ANALYZEQUEUES"("TENANT");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('2b37423f-24df-45a1-8a11-b64912a6ada7', 'AnalyzeQueue.dxml', 'ANALYZEQUEUES', 'TENANT', 'Create Index', SYSDATE, ScriptText); END;


-- Add Foreign Key Constraint For Column CODE In Table BATCHSERVICESDEFINITIONMODS As Reference To Column CODE In Table BATCHSERVICESDEFINITIONS
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" ADD CONSTRAINT "FK_BATCHSERVICESDEFINITI_YSIKO" FOREIGN KEY("CODE") REFERENCES "BATCHSERVICESDEFINITIONS"("CODE");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column CODE In Table BATCHSERVICESDEFINITIONMODS As Reference To Column CODE In Table BATCHSERVICESDEFINITIONS
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" ADD CONSTRAINT "FK_BATCHSERVICESDEFINITI_YSIKO" FOREIGN KEY("CODE") REFERENCES "BATCHSERVICESDEFINITIONS"("CODE");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('560536ed-05f6-4dcd-b341-a001a4d8a2df', 'BatchServicesDefinitionMods.dxml', 'BATCHSERVICESDEFINITIONMODS', 'CODE', 'Create Relation', SYSDATE, ScriptText); END;


-- Add Foreign Key Constraint For Column BLUESNAPCONTRACTTYPECODE In Table BLUESNAPCONTRACTS As Reference To Column CODE In Table BLUESNAPCONTRACTTYPES
ALTER TABLE "BLUESNAPCONTRACTS" ADD CONSTRAINT "FK_BLUESNAPCONTRACTS_BLU_XGFH7" FOREIGN KEY("BLUESNAPCONTRACTTYPECODE") REFERENCES "BLUESNAPCONTRACTTYPES"("CODE");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column BLUESNAPCONTRACTTYPECODE In Table BLUESNAPCONTRACTS As Reference To Column CODE In Table BLUESNAPCONTRACTTYPES
ALTER TABLE "BLUESNAPCONTRACTS" ADD CONSTRAINT "FK_BLUESNAPCONTRACTS_BLU_XGFH7" FOREIGN KEY("BLUESNAPCONTRACTTYPECODE") REFERENCES "BLUESNAPCONTRACTTYPES"("CODE");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('19df7ba9-d465-443e-bcac-827d9eec9f6b', 'BluesnapContract.dxml', 'BLUESNAPCONTRACTS', 'BLUESNAPCONTRACTTYPECODE', 'Create Relation', SYSDATE, ScriptText); END;

-- Create Index On BLUESNAPCONTRACTS Table
CREATE INDEX "IX_BLUESNAPCONTRACTS_BLU_ZPHAB" ON "BLUESNAPCONTRACTS"("BLUESNAPCONTRACTTYPECODE");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On BLUESNAPCONTRACTS Table
CREATE INDEX "IX_BLUESNAPCONTRACTS_BLU_ZPHAB" ON "BLUESNAPCONTRACTS"("BLUESNAPCONTRACTTYPECODE");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('c21322f5-3d1b-4587-a3f9-ca4cd3421546', 'BluesnapContract.dxml', 'BLUESNAPCONTRACTS', 'BLUESNAPCONTRACTTYPECODE', 'Create Index', SYSDATE, ScriptText); END;


-- Add Foreign Key Constraint For Column GLOBALDBID In Table CONVERTPROGRAMINFOES As Reference To Column ID In Table GLOBALDBS
ALTER TABLE "CONVERTPROGRAMINFOES" ADD CONSTRAINT "FK_CONVERTPROGRAMINFOES_RZEPL2" FOREIGN KEY("GLOBALDBID") REFERENCES "GLOBALDBS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column GLOBALDBID In Table CONVERTPROGRAMINFOES As Reference To Column ID In Table GLOBALDBS
ALTER TABLE "CONVERTPROGRAMINFOES" ADD CONSTRAINT "FK_CONVERTPROGRAMINFOES_RZEPL2" FOREIGN KEY("GLOBALDBID") REFERENCES "GLOBALDBS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('ba2b5ded-6f99-4716-a67e-0c769a9ea779', 'ConvertProgramInfo.dxml', 'CONVERTPROGRAMINFOES', 'GLOBALDBID', 'Create Relation', SYSDATE, ScriptText); END;

-- Create Index On CONVERTPROGRAMINFOES Table
CREATE INDEX "IX_CONVERTPROGRAMINFOES_NYHWCR" ON "CONVERTPROGRAMINFOES"("GLOBALDBID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On CONVERTPROGRAMINFOES Table
CREATE INDEX "IX_CONVERTPROGRAMINFOES_NYHWCR" ON "CONVERTPROGRAMINFOES"("GLOBALDBID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('3f317861-7244-4c07-bde3-9e4e6fcab4a2', 'ConvertProgramInfo.dxml', 'CONVERTPROGRAMINFOES', 'GLOBALDBID', 'Create Index', SYSDATE, ScriptText); END;


-- Add Foreign Key Constraint For Column PRIVATELABELID In Table GLOBALTENANTS As Reference To Column ID In Table TENANTMANAGMENTPRIVATELABELS
ALTER TABLE "GLOBALTENANTS" ADD CONSTRAINT "FK_GLOBALTENANTS_TENANTM_JIRR9" FOREIGN KEY("PRIVATELABELID") REFERENCES "TENANTMANAGMENTPRIVATELABELS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column PRIVATELABELID In Table GLOBALTENANTS As Reference To Column ID In Table TENANTMANAGMENTPRIVATELABELS
ALTER TABLE "GLOBALTENANTS" ADD CONSTRAINT "FK_GLOBALTENANTS_TENANTM_JIRR9" FOREIGN KEY("PRIVATELABELID") REFERENCES "TENANTMANAGMENTPRIVATELABELS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('be93716a-1d8f-4031-a21d-9b0258e43b0d', 'GlobalTenant.dxml', 'GLOBALTENANTS', 'PRIVATELABELID', 'Create Relation', SYSDATE, ScriptText); END;


-- Add Foreign Key Constraint For Column BLUESNAPCRMCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_4Z7O8" FOREIGN KEY("BLUESNAPCRMCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column BLUESNAPCRMCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_4Z7O8" FOREIGN KEY("BLUESNAPCRMCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('dcbbefda-b874-4e17-b140-8cb89bf027c2', 'TenantManagement.dxml', 'TENANTMANAGEMENTS', 'BLUESNAPCRMCONTRACTID', 'Create Relation', SYSDATE, ScriptText); END;

-- Add Foreign Key Constraint For Column BLUESNAPEAWBCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_UCTXH" FOREIGN KEY("BLUESNAPEAWBCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column BLUESNAPEAWBCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_UCTXH" FOREIGN KEY("BLUESNAPEAWBCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('f0a55780-11db-42ee-af87-58cd51552729', 'TenantManagement.dxml', 'TENANTMANAGEMENTS', 'BLUESNAPEAWBCONTRACTID', 'Create Relation', SYSDATE, ScriptText); END;

-- Add Foreign Key Constraint For Column BLUESNAPEAWBSCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_QYBRF" FOREIGN KEY("BLUESNAPEAWBSCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column BLUESNAPEAWBSCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_QYBRF" FOREIGN KEY("BLUESNAPEAWBSCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('12456caf-5013-4b88-ba78-9d22efca1779', 'TenantManagement.dxml', 'TENANTMANAGEMENTS', 'BLUESNAPEAWBSCONTRACTID', 'Create Relation', SYSDATE, ScriptText); END;

-- Add Foreign Key Constraint For Column BLUESNAPCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_YBDMU" FOREIGN KEY("BLUESNAPCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column BLUESNAPCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_YBDMU" FOREIGN KEY("BLUESNAPCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('bfec93b7-b8f0-4450-9687-d0dfa3d28d44', 'TenantManagement.dxml', 'TENANTMANAGEMENTS', 'BLUESNAPCONTRACTID', 'Create Relation', SYSDATE, ScriptText); END;

-- Add Foreign Key Constraint For Column BLUESNAPINTTRASTOCKCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_UAAGJ" FOREIGN KEY("BLUESNAPINTTRASTOCKCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column BLUESNAPINTTRASTOCKCONTRACTID In Table TENANTMANAGEMENTS As Reference To Column ID In Table BLUESNAPCONTRACTS
ALTER TABLE "TENANTMANAGEMENTS" ADD CONSTRAINT "FK_TENANTMANAGEMENTS_BLU_UAAGJ" FOREIGN KEY("BLUESNAPINTTRASTOCKCONTRACTID") REFERENCES "BLUESNAPCONTRACTS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('db3bfaed-1f90-4a6e-b870-15d1afc9c468', 'TenantManagement.dxml', 'TENANTMANAGEMENTS', 'BLUESNAPINTTRASTOCKCONTRACTID', 'Create Relation', SYSDATE, ScriptText); END;


