-- Add New Column With Name ISIMPORT
ALTER TABLE "CUSTOMSREQUIREDFIELDS" ADD "ISIMPORT" NUMBER(1, 0) NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add New Column With Name ISIMPORTALTER TABLE "CUSTOMSREQUIREDFIELDS" ADD "ISIMPORT" NUMBER(1, 0) NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('a3ee0211-b913-4906-9337-e8e61d0dcd59', 'CustomsRequiredField.dxml', 'CUSTOMSREQUIREDFIELDS', 'ISIMPORT', 'Add Column', SYSDATE, ScriptText); END;

-- Add New Column With Name ISEXPORT
ALTER TABLE "CUSTOMSREQUIREDFIELDS" ADD "ISEXPORT" NUMBER(1, 0) NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add New Column With Name ISEXPORTALTER TABLE "CUSTOMSREQUIREDFIELDS" ADD "ISEXPORT" NUMBER(1, 0) NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('0ba83666-380e-482c-bda8-a5114a73be56', 'CustomsRequiredField.dxml', 'CUSTOMSREQUIREDFIELDS', 'ISEXPORT', 'Add Column', SYSDATE, ScriptText); END;


-- Drop Column TOTALINVOICEAMOUNTINUSD
ALTER TABLE "CUSTOMSSETTINGS" RENAME COLUMN "TOTALINVOICEAMOUNTINUSD" TO "DROP_TOTALINVOICEAMOUNTINUSD";

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Drop Column TOTALINVOICEAMOUNTINUSDALTER TABLE "CUSTOMSSETTINGS" RENAME COLUMN "TOTALINVOICEAMOUNTINUSD" TO "DROP_TOTALINVOICEAMOUNTINUSD";'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('2b0e1739-b4cd-43a0-b32e-1809b0e2c417', 'CustomsSetting.dxml', 'CUSTOMSSETTINGS', 'TOTALINVOICEAMOUNTINUSD', 'Drop Column', SYSDATE, ScriptText); END;


-- Set Nullable For Column ADDITIONALPRICETYPECODE
ALTER TABLE "SUPPLIERINVOICEITEMSPRICES" MODIFY "ADDITIONALPRICETYPECODE" NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Set Nullable For Column ADDITIONALPRICETYPECODEALTER TABLE "SUPPLIERINVOICEITEMSPRICES" MODIFY "ADDITIONALPRICETYPECODE" NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('2340fa0a-135b-4b1f-9a0f-16b43e803ec5', 'SupplierInvoiceItemsPrice.dxml', 'SUPPLIERINVOICEITEMSPRICES', 'ADDITIONALPRICETYPECODE', 'Set Column Nullable', SYSDATE, ScriptText); END;

-- Set Nullable For Column ADDITIONALPRICE
ALTER TABLE "SUPPLIERINVOICEITEMSPRICES" MODIFY "ADDITIONALPRICE" NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Set Nullable For Column ADDITIONALPRICEALTER TABLE "SUPPLIERINVOICEITEMSPRICES" MODIFY "ADDITIONALPRICE" NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('5268a7e5-1981-41a9-9f05-46e5c6495689', 'SupplierInvoiceItemsPrice.dxml', 'SUPPLIERINVOICEITEMSPRICES', 'ADDITIONALPRICE', 'Set Column Nullable', SYSDATE, ScriptText); END;


-- Add Foreign Key Constraint For Column OBJECTFIELDID In Table CUSTOMSREQUIREDFIELDS As Reference To Column ID In Table OBJECTFIELDS
ALTER TABLE "CUSTOMSREQUIREDFIELDS" ADD CONSTRAINT "FK_CUSTOMSREQUIREDFIELDS_QOHFZ" FOREIGN KEY("OBJECTFIELDID") REFERENCES "OBJECTFIELDS"("ID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Foreign Key Constraint For Column OBJECTFIELDID In Table CUSTOMSREQUIREDFIELDS As Reference To Column ID In Table OBJECTFIELDSALTER TABLE "CUSTOMSREQUIREDFIELDS" ADD CONSTRAINT "FK_CUSTOMSREQUIREDFIELDS_QOHFZ" FOREIGN KEY("OBJECTFIELDID") REFERENCES "OBJECTFIELDS"("ID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('09989487-a585-4487-a389-4769147b35b5', 'CustomsRequiredField.dxml', 'CUSTOMSREQUIREDFIELDS', 'OBJECTFIELDID', 'Create Relation', SYSDATE, ScriptText); END;

-- Create Index On CUSTOMSREQUIREDFIELDS Table
CREATE INDEX "IX_CUSTOMSREQUIREDFIELDS_SFZIT" ON "CUSTOMSREQUIREDFIELDS"("OBJECTFIELDID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On CUSTOMSREQUIREDFIELDS TableCREATE INDEX "IX_CUSTOMSREQUIREDFIELDS_SFZIT" ON "CUSTOMSREQUIREDFIELDS"("OBJECTFIELDID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('8448bec5-4526-423e-aa44-b04aa0aebfb8', 'CustomsRequiredField.dxml', 'CUSTOMSREQUIREDFIELDS', 'OBJECTFIELDID', 'Create Index', SYSDATE, ScriptText); END;


