-- Add New Column With Name ISMESSAGESPENDING
ALTER TABLE "CUSTOMSSETTINGS" ADD "ISMESSAGESPENDING" NUMBER(1, 0) NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add New Column With Name ISMESSAGESPENDINGALTER TABLE "CUSTOMSSETTINGS" ADD "ISMESSAGESPENDING" NUMBER(1, 0) NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('4d83923c-84eb-4d23-b8ee-e06b32070ff9', 'CustomsSetting.dxml', 'CUSTOMSSETTINGS', 'ISMESSAGESPENDING', 'Add Column', SYSDATE, ScriptText); END;

-- Add New Column With Name QTYFEEDBACKINPENDINGMESSAGE
ALTER TABLE "CUSTOMSSETTINGS" ADD "QTYFEEDBACKINPENDINGMESSAGE" NUMBER(10, 0) DEFAULT 100 NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add New Column With Name QTYFEEDBACKINPENDINGMESSAGEALTER TABLE "CUSTOMSSETTINGS" ADD "QTYFEEDBACKINPENDINGMESSAGE" NUMBER(10, 0) DEFAULT 100 NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('4fcdd39b-36a2-4e9f-8d69-08c81b948ebe', 'CustomsSetting.dxml', 'CUSTOMSSETTINGS', 'QTYFEEDBACKINPENDINGMESSAGE', 'Add Column', SYSDATE, ScriptText); END;


