-- Add New Column With Name AMENDMENTERRORXML
ALTER TABLE "DECLARATIONS" ADD "AMENDMENTERRORXML" NCLOB NULL;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add New Column With Name AMENDMENTERRORXMLALTER TABLE "DECLARATIONS" ADD "AMENDMENTERRORXML" NCLOB NULL;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('0e58ef83-cabe-44a7-941f-3afe29f1c61a', 'Declaration.dxml', 'DECLARATIONS', 'AMENDMENTERRORXML', 'Add Column', SYSDATE, ScriptText); END;


