-- For Global
-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "BATCHSERVICESDEFINITIONS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 40 For Column CODE
ALTER TABLE "BATCHSERVICESDEFINITIONS" MODIFY "CODE" VARCHAR2(40 CHAR)

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 40 For Column CODE
ALTER TABLE "BATCHSERVICESDEFINITIONMODS" MODIFY "CODE" VARCHAR2(40 CHAR)

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "BLUESNAPCONTRACTTYPES" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 4 For Column CODE
ALTER TABLE "BLUESNAPCONTRACTTYPES" MODIFY "CODE" VARCHAR2(4 CHAR)

-- Unset Nullable For Column SECONDARYAZUREDBCONNECTION
ALTER TABLE "GLOBALDBS" MODIFY "SECONDARYAZUREDBCONNECTION" NOT NULL

-- Unset Nullable For Column METHODPARAMETERS
ALTER TABLE "PERFORMANCELOGS" MODIFY "METHODPARAMETERS" NOT NULL

-- Unset Nullable For Column CHAMPTESTAPIURL
ALTER TABLE "SETTINGS" MODIFY "CHAMPTESTAPIURL" NOT NULL

-- Unset Nullable For Column CHAMPTESTAPIPASSWORD
ALTER TABLE "SETTINGS" MODIFY "CHAMPTESTAPIPASSWORD" NOT NULL

-- Unset Nullable For Column CHAMPPRODAPIURL
ALTER TABLE "SETTINGS" MODIFY "CHAMPPRODAPIURL" NOT NULL

-- Unset Nullable For Column CHAMPPRODAPIPASSWORD
ALTER TABLE "SETTINGS" MODIFY "CHAMPPRODAPIPASSWORD" NOT NULL


-- Add Foreign Key Constraint For Column BLUESNAPCONTRACTTYPECODE In Table BLUESNAPCONTRACTS As Reference To Column CODE In Table BLUESNAPCONTRACTTYPES
ALTER TABLE "BLUESNAPCONTRACTS" ADD CONSTRAINT "FK_BLUESNAPCONTRACTS_BLU_BG8WC" FOREIGN KEY("BLUESNAPCONTRACTTYPECODE") REFERENCES "BLUESNAPCONTRACTTYPES"("CODE")

-- For Main

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "APPROVEDPROFESSIONS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 2 For Column CODE
ALTER TABLE "APPROVEDPROFESSIONS" MODIFY "CODE" VARCHAR2(2 CHAR)


-- Change Precision And Scale From (15, 10) To (12, 10) For Column EXCHANGERATE
ALTER TABLE "CUSTOMSEXCHANGERATES" MODIFY "EXCHANGERATE" NUMBER(12, 10)

-- Add New Column With Name DECLARATIONTAXES
ALTER TABLE "DECLARATIONS" ADD "DECLARATIONTAXES" VARCHAR2(0 CHAR) NULL

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "FACILITATIONTYPES" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 15 For Column CODE
ALTER TABLE "FACILITATIONTYPES" MODIFY "CODE" VARCHAR2(15 CHAR)

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "CHECKDIGITCONTROLALGORITHMS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 4 For Column CODE
ALTER TABLE "CHECKDIGITCONTROLALGORITHMS" MODIFY "CODE" VARCHAR2(4 CHAR)

-- Change Type From nvarchar To varchar For Column ID
ALTER TABLE "CONTACTLOGINLOGS" MODIFY "ID" VARCHAR2(128 CHAR)

-- Change Size From 128 To 15 For Column ID
ALTER TABLE "CONTACTLOGINLOGS" MODIFY "ID" VARCHAR2(15 CHAR)


-- Create Unique Constraint On COUNTRIES Table
ALTER TABLE "COUNTRIES" ADD CONSTRAINT "UQ_COUNTRIES_TENANT_CODE" UNIQUE("TENANT","CODE")


-- Create Unique Constraint On COUNTRYCITIES Table
ALTER TABLE "COUNTRYCITIES" ADD CONSTRAINT "UQ_COUNTRYCITIES_COUNTRY_8QVTS" UNIQUE("COUNTRYID","CODE","TENANT")


-- Create Unique Constraint On INCOTERMS Table
ALTER TABLE "INCOTERMS" ADD CONSTRAINT "UQ_INCOTERMS_TENANT_CODE" UNIQUE("TENANT","CODE")

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "METODOPAGOS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 3 For Column CODE
ALTER TABLE "METODOPAGOS" MODIFY "CODE" VARCHAR2(3 CHAR)

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "NUMBERFORMATS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 4 For Column CODE
ALTER TABLE "NUMBERFORMATS" MODIFY "CODE" VARCHAR2(4 CHAR)

-- Unset Nullable For Column PRINTAS
ALTER TABLE "PACKAGETYPES" MODIFY "PRINTAS" NOT NULL

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "PAYMENTGATEWAYPARTNERS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 15 For Column CODE
ALTER TABLE "PAYMENTGATEWAYPARTNERS" MODIFY "CODE" VARCHAR2(15 CHAR)


-- Create Unique Constraint On PORTS Table
ALTER TABLE "PORTS" ADD CONSTRAINT "UQ_PORTS_TENANT_CODE_COUNTRYID" UNIQUE("TENANT","CODE","COUNTRYID")

-- Change Type From nvarchar To varchar For Column REPORTGROUPID
ALTER TABLE "REPORTS" MODIFY "REPORTGROUPID" VARCHAR2(128 CHAR)

-- Change Size From 128 To 15 For Column REPORTGROUPID
ALTER TABLE "REPORTS" MODIFY "REPORTGROUPID" VARCHAR2(15 CHAR)

-- Change Type From nvarchar To varchar For Column DESCRIPTION
ALTER TABLE "REPORTS" MODIFY "DESCRIPTION" VARCHAR2(250 CHAR)

-- Change Type From nvarchar To varchar For Column SEARCHFIELDS
ALTER TABLE "REPORTS" MODIFY "SEARCHFIELDS" VARCHAR2(1000 CHAR)

-- Change Type From nvarchar To varchar For Column ID
ALTER TABLE "REPORTGROUPS" MODIFY "ID" VARCHAR2(128 CHAR)

-- Change Size From 128 To 15 For Column ID
ALTER TABLE "REPORTGROUPS" MODIFY "ID" VARCHAR2(15 CHAR)


-- Create New Table With Name SHAREDLOGISTICSCONTACTLASTLOGINS
CREATE TABLE "SHAREDLOGISTICSCONTACTLASTLOGINS"(
"CONTACTID" VARCHAR2(15 CHAR) NOT NULL,
"CARDID" VARCHAR2(15 CHAR) NOT NULL,
"PARTNERTYPEID" VARCHAR2(2 CHAR) NOT NULL,
"VIA" VARCHAR2(20 CHAR) DEFAULT '' NOT NULL,
"LOGINDATETIME" TIMESTAMP(7) NULL,
"TENANT" NUMBER(10, 0) NOT NULL,
CONSTRAINT "PK_SHAREDLOGISTICSCONTAC_SGJGA" PRIMARY KEY("CONTACTID","CARDID","PARTNERTYPEID","VIA")
)


-- Create Unique Constraint On STATES Table
ALTER TABLE "STATES" ADD CONSTRAINT "UQ_STATES_TENANT_CODE_CO_A8S2J" UNIQUE("TENANT","CODE","COUNTRYID")

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "TEMPERATUREUNITS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 3 For Column CODE
ALTER TABLE "TEMPERATUREUNITS" MODIFY "CODE" VARCHAR2(3 CHAR)

-- Change Type From nvarchar To varchar For Column CHECKDIGITCONTROLALGORITHMCODE
ALTER TABLE "TENANTS" MODIFY "CHECKDIGITCONTROLALGORITHMCODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 4 For Column CHECKDIGITCONTROLALGORITHMCODE
ALTER TABLE "TENANTS" MODIFY "CHECKDIGITCONTROLALGORITHMCODE" VARCHAR2(4 CHAR)

-- Unset Nullable For Column CHECKDIGITCONTROLALGORITHMCODE
ALTER TABLE "TENANTS" MODIFY "CHECKDIGITCONTROLALGORITHMCODE" NOT NULL

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "USOCFDIS" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 3 For Column CODE
ALTER TABLE "USOCFDIS" MODIFY "CODE" VARCHAR2(3 CHAR)

-- Change Type From nvarchar To varchar For Column CODE
ALTER TABLE "WAREHOUSETYPES" MODIFY "CODE" VARCHAR2(128 CHAR)

-- Change Size From 128 To 4 For Column CODE
ALTER TABLE "WAREHOUSETYPES" MODIFY "CODE" VARCHAR2(4 CHAR)

-- Change Type From nvarchar To varchar For Column GENERALKEY
ALTER TABLE "GENERALLOCKS" MODIFY "GENERALKEY" VARCHAR2(128 CHAR)


-- Create Unique Constraint On OBJECTTABLETABS Table
ALTER TABLE "OBJECTTABLETABS" ADD CONSTRAINT "UQ_OBJECTTABLETABS_CODE_TENANT" UNIQUE("CODE","TENANT")


-- Create Unique Constraint On QUERIES Table
ALTER TABLE "QUERIES" ADD CONSTRAINT "UQ_QUERIES_CODE_OBJECTTA_LQUSD" UNIQUE("CODE","OBJECTTABLEID","USERID","TENANT")

-- Create Unique Constraint On QUERIES Table
ALTER TABLE "QUERIES" ADD CONSTRAINT "UQ_QUERIES_UNIQUECODE" UNIQUE("UNIQUECODE")

-- Add Foreign Key Constraint For Column FACILITATIONTYPECODE In Table CLIENTS As Reference To Column CODE In Table FACILITATIONTYPES
ALTER TABLE "CLIENTS" ADD CONSTRAINT "FK_CLIENTS_FACILITATIONT_3WFXB" FOREIGN KEY("FACILITATIONTYPECODE") REFERENCES "FACILITATIONTYPES"("CODE")


-- Add Foreign Key Constraint For Column OBJECTFIELDID In Table CUSTOMSREQUIREDFIELDS As Reference To Column ID In Table OBJECTFIELDS
ALTER TABLE "CUSTOMSREQUIREDFIELDS" ADD CONSTRAINT "FK_CUSTOMSREQUIREDFIELDS_BHQDM" FOREIGN KEY("OBJECTFIELDID") REFERENCES "OBJECTFIELDS"("ID")

-- Add Foreign Key Constraint For Column APPROVEDPROFESSIONCODE In Table DEFICITDECISIONS As Reference To Column CODE In Table APPROVEDPROFESSIONS
ALTER TABLE "DEFICITDECISIONS" ADD CONSTRAINT "FK_DEFICITDECISIONS_APPR_NDS1G" FOREIGN KEY("APPROVEDPROFESSIONCODE") REFERENCES "APPROVEDPROFESSIONS"("CODE")

-- Add Foreign Key Constraint For Column METODOPAGOCODE In Table CARDS As Reference To Column CODE In Table METODOPAGOS
ALTER TABLE "CARDS" ADD CONSTRAINT "FK_CARDS_METODOPAGOS_MET_93PQJ" FOREIGN KEY("METODOPAGOCODE") REFERENCES "METODOPAGOS"("CODE")

-- Add Foreign Key Constraint For Column USOCFDICODE In Table CARDS As Reference To Column CODE In Table USOCFDIS
ALTER TABLE "CARDS" ADD CONSTRAINT "FK_CARDS_USOCFDIS_USOCFDICODE" FOREIGN KEY("USOCFDICODE") REFERENCES "USOCFDIS"("CODE")

-- Add Foreign Key Constraint For Column INDEXCOLOR In Table CONTACTS As Reference To Column INDEXNUMBER In Table COLORINDEXS
ALTER TABLE "CONTACTS" ADD CONSTRAINT "FK_CONTACTS_COLORINDEXS_6UQAWX" FOREIGN KEY("INDEXCOLOR") REFERENCES "COLORINDEXS"("INDEXNUMBER")


-- Add Foreign Key Constraint For Column CONTACTID In Table SHAREDLOGISTICSCONTACTLASTLOGINS As Reference To Column ID In Table CONTACTS
ALTER TABLE "SHAREDLOGISTICSCONTACTLASTLOGINS" ADD CONSTRAINT "FK_SHAREDLOGISTICSCONTAC_URLQF" FOREIGN KEY("CONTACTID") REFERENCES "CONTACTS"("ID")

-- Create Index On SHAREDLOGISTICSCONTACTLASTLOGINS Table
CREATE INDEX "IX_SHAREDLOGISTICSCONTAC_P6EGW" ON "SHAREDLOGISTICSCONTACTLASTLOGINS"("CONTACTID")

-- Add Foreign Key Constraint For Column TEMPERATUREUNITCODE In Table TENANTS As Reference To Column CODE In Table TEMPERATUREUNITS
ALTER TABLE "TENANTS" ADD CONSTRAINT "FK_TENANTS_TEMPERATUREUN_3VOOU" FOREIGN KEY("TEMPERATUREUNITCODE") REFERENCES "TEMPERATUREUNITS"("CODE")

-- Add Foreign Key Constraint For Column NUMBERFORMATCODE In Table TENANTS As Reference To Column CODE In Table NUMBERFORMATS
ALTER TABLE "TENANTS" ADD CONSTRAINT "FK_TENANTS_NUMBERFORMATS_E12XA" FOREIGN KEY("NUMBERFORMATCODE") REFERENCES "NUMBERFORMATS"("CODE")


-- Add Foreign Key Constraint For Column PAYMENTGATEWAYPARTNERCODE In Table TENANTADDITIONALDATAS As Reference To Column CODE In Table PAYMENTGATEWAYPARTNERS
ALTER TABLE "TENANTADDITIONALDATAS" ADD CONSTRAINT "FK_TENANTADDITIONALDATAS_IPRIY" FOREIGN KEY("PAYMENTGATEWAYPARTNERCODE") REFERENCES "PAYMENTGATEWAYPARTNERS"("CODE")

-- Add Foreign Key Constraint For Column TYPECODE In Table WAREHOUSES As Reference To Column CODE In Table WAREHOUSETYPES
ALTER TABLE "WAREHOUSES" ADD CONSTRAINT "FK_WAREHOUSES_WAREHOUSET_2WKSF" FOREIGN KEY("TYPECODE") REFERENCES "WAREHOUSETYPES"("CODE")

-- For SystemLogs

