-- Create New Table With Name DBMIGRATIONSHISTORY
CREATE TABLE "DBMIGRATIONSHISTORY"(
"ID" NVARCHAR2(128) NOT NULL,
"DXMLFILENAME" VARCHAR2(500 CHAR) NOT NULL,
"TABLENAME" VARCHAR2(500 CHAR) NOT NULL,
"COLUMNNAME" CLOB NULL,
"MIGRATIONTYPE" VARCHAR2(50 CHAR) NOT NULL,
"EXECUTIONDATE" TIMESTAMP(7) NOT NULL,
"MIGRATIONSCRIPT" NCLOB NOT NULL,
CONSTRAINT "PK_DBMIGRATIONSHISTORY" PRIMARY KEY("ID")
);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create New Table With Name DBMIGRATIONSHISTORY
CREATE TABLE "DBMIGRATIONSHISTORY"(
"ID" NVARCHAR2(128) NOT NULL,
"DXMLFILENAME" VARCHAR2(500 CHAR) NOT NULL,
"TABLENAME" VARCHAR2(500 CHAR) NOT NULL,
"COLUMNNAME" CLOB NULL,
"MIGRATIONTYPE" VARCHAR2(50 CHAR) NOT NULL,
"EXECUTIONDATE" TIMESTAMP(7) NOT NULL,
"MIGRATIONSCRIPT" NCLOB NOT NULL,
CONSTRAINT "PK_DBMIGRATIONSHISTORY" PRIMARY KEY("ID")
);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('68dc75d8-efc8-48b3-bee8-963844e37f6e', 'DBMigrationsHistory.dxml', 'DBMIGRATIONSHISTORY', NULL, 'Create Table', SYSDATE, ScriptText); END;


-- Create New Table With Name DBSCRIPTSHISTORY
CREATE TABLE "DBSCRIPTSHISTORY"(
"SXMLFILENAME" VARCHAR2(500 CHAR) NOT NULL,
"EXECUTIONDATE" TIMESTAMP(7) NOT NULL,
"SCRIPTBODY" NCLOB NOT NULL,
"ELAPSEDTIMEINMS" NUMBER(18, 0) NOT NULL,
"HASHVALUE" NCLOB NOT NULL,
"VERSION" NUMBER(10, 0) NOT NULL,
CONSTRAINT "PK_DBSCRIPTSHISTORY" PRIMARY KEY("SXMLFILENAME")
);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create New Table With Name DBSCRIPTSHISTORY
CREATE TABLE "DBSCRIPTSHISTORY"(
"SXMLFILENAME" VARCHAR2(500 CHAR) NOT NULL,
"EXECUTIONDATE" TIMESTAMP(7) NOT NULL,
"SCRIPTBODY" NCLOB NOT NULL,
"ELAPSEDTIMEINMS" NUMBER(18, 0) NOT NULL,
"HASHVALUE" NCLOB NOT NULL,
"VERSION" NUMBER(10, 0) NOT NULL,
CONSTRAINT "PK_DBSCRIPTSHISTORY" PRIMARY KEY("SXMLFILENAME")
);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('1d5d59eb-c2ff-4b06-acf9-de56a6f7d588', 'DBScriptsHistory.dxml', 'DBSCRIPTSHISTORY', NULL, 'Create Table', SYSDATE, ScriptText); END;


-- Add Default Value For Column DONEITEMSINONEMINUTE
ALTER TABLE "BATCHSERVICESLOGS" MODIFY "DONEITEMSINONEMINUTE" DEFAULT 0;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Default Value For Column DONEITEMSINONEMINUTE
ALTER TABLE "BATCHSERVICESLOGS" MODIFY "DONEITEMSINONEMINUTE" DEFAULT 0;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('a06a7f9e-7b2a-4d06-9d14-5b50e742cd04', 'BatchServicesLog.dxml', 'BATCHSERVICESLOGS', 'DONEITEMSINONEMINUTE', 'Add Default Value', SYSDATE, ScriptText); END;

-- Add Default Value For Column DONEITEMSINFIVEMINUTES
ALTER TABLE "BATCHSERVICESLOGS" MODIFY "DONEITEMSINFIVEMINUTES" DEFAULT 0;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Default Value For Column DONEITEMSINFIVEMINUTES
ALTER TABLE "BATCHSERVICESLOGS" MODIFY "DONEITEMSINFIVEMINUTES" DEFAULT 0;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('53482076-9022-462f-9c58-e3996a37fd93', 'BatchServicesLog.dxml', 'BATCHSERVICESLOGS', 'DONEITEMSINFIVEMINUTES', 'Add Default Value', SYSDATE, ScriptText); END;

-- Add Default Value For Column DONEITEMSINONEHOUR
ALTER TABLE "BATCHSERVICESLOGS" MODIFY "DONEITEMSINONEHOUR" DEFAULT 0;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Default Value For Column DONEITEMSINONEHOUR
ALTER TABLE "BATCHSERVICESLOGS" MODIFY "DONEITEMSINONEHOUR" DEFAULT 0;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('3c79577f-cdb0-46fd-bb69-4cefdbb42370', 'BatchServicesLog.dxml', 'BATCHSERVICESLOGS', 'DONEITEMSINONEHOUR', 'Add Default Value', SYSDATE, ScriptText); END;


-- Add Default Value For Column ISSHAREDLOGISTICSCONTACT
ALTER TABLE "CONTACTACTIVITYLOGS" MODIFY "ISSHAREDLOGISTICSCONTACT" DEFAULT 0;

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Add Default Value For Column ISSHAREDLOGISTICSCONTACT
ALTER TABLE "CONTACTACTIVITYLOGS" MODIFY "ISSHAREDLOGISTICSCONTACT" DEFAULT 0;'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('d2e374ee-a1b8-4dd4-b880-e47595bf154d', 'ContactActivityLog.dxml', 'CONTACTACTIVITYLOGS', 'ISSHAREDLOGISTICSCONTACT', 'Add Default Value', SYSDATE, ScriptText); END;


-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_T_N9KJH" ON "CONTACTACTIVITYLOGS"("TENANT","GMTLOGDATETIME");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_T_N9KJH" ON "CONTACTACTIVITYLOGS"("TENANT","GMTLOGDATETIME");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('906c5d85-e162-4006-9d55-15beec7a0cba', 'ContactActivityLog.dxml', 'CONTACTACTIVITYLOGS', 'TENANT,GMTLOGDATETIME', 'Create Index', SYSDATE, ScriptText); END;

-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_T_GCZVP" ON "CONTACTACTIVITYLOGS"("TENANT","ISSHAREDLOGISTICSCONTACT");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_T_GCZVP" ON "CONTACTACTIVITYLOGS"("TENANT","ISSHAREDLOGISTICSCONTACT");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('c78e5dac-dc7b-4838-b37c-086e4b6f54e4', 'ContactActivityLog.dxml', 'CONTACTACTIVITYLOGS', 'TENANT,ISSHAREDLOGISTICSCONTACT', 'Create Index', SYSDATE, ScriptText); END;

-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_G_54SL9" ON "CONTACTACTIVITYLOGS"("GMTLOGDATETIME");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_G_54SL9" ON "CONTACTACTIVITYLOGS"("GMTLOGDATETIME");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('f61d04ec-3633-476c-aa85-7bf9af263b12', 'ContactActivityLog.dxml', 'CONTACTACTIVITYLOGS', 'GMTLOGDATETIME', 'Create Index', SYSDATE, ScriptText); END;

-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_T_LUNIX" ON "CONTACTACTIVITYLOGS"("TENANT","LOGDATETIME","PARTNERTYPEID");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On CONTACTACTIVITYLOGS Table
CREATE INDEX "IX_CONTACTACTIVITYLOGS_T_LUNIX" ON "CONTACTACTIVITYLOGS"("TENANT","LOGDATETIME","PARTNERTYPEID");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('72ecd2d3-ac31-4e4a-ba35-fe91bd04133f', 'ContactActivityLog.dxml', 'CONTACTACTIVITYLOGS', 'TENANT,LOGDATETIME,PARTNERTYPEID', 'Create Index', SYSDATE, ScriptText); END;


-- Change Size From -1 To 7000 For Column EXCEPTION
ALTER TABLE "ERRORLOGS" MODIFY "EXCEPTION" VARCHAR2(2000 CHAR);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Change Size From -1 To 7000 For Column EXCEPTION
ALTER TABLE "ERRORLOGS" MODIFY "EXCEPTION" VARCHAR2(2000 CHAR);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('2251fdd3-ddef-4a82-8376-d3fb6ac07377', 'ErrorLog.dxml', 'ERRORLOGS', 'EXCEPTION', 'Alter Column Size', SYSDATE, ScriptText); END;

-- Change Size From -1 To 7000 For Column STACKTRACE
ALTER TABLE "ERRORLOGS" MODIFY "STACKTRACE" VARCHAR2(2000 CHAR);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Change Size From -1 To 7000 For Column STACKTRACE
ALTER TABLE "ERRORLOGS" MODIFY "STACKTRACE" VARCHAR2(2000 CHAR);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('d9e3bedc-09fa-4d3b-915b-e22420010d87', 'ErrorLog.dxml', 'ERRORLOGS', 'STACKTRACE', 'Alter Column Size', SYSDATE, ScriptText); END;

-- Change Size From -1 To 8000 For Column SEARCHFIELDS
ALTER TABLE "ERRORLOGS" MODIFY "SEARCHFIELDS" VARCHAR2(2000 CHAR);

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Change Size From -1 To 8000 For Column SEARCHFIELDS
ALTER TABLE "ERRORLOGS" MODIFY "SEARCHFIELDS" VARCHAR2(2000 CHAR);'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('0f7b9073-0b7e-4ea9-b46b-e0c2f62bed76', 'ErrorLog.dxml', 'ERRORLOGS', 'SEARCHFIELDS', 'Alter Column Size', SYSDATE, ScriptText); END;


-- Create Index On ERRORLOGS Table
CREATE INDEX "IX_ERRORLOGS_LOGDATE" ON "ERRORLOGS"("LOGDATE");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On ERRORLOGS Table
CREATE INDEX "IX_ERRORLOGS_LOGDATE" ON "ERRORLOGS"("LOGDATE");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('22ce4e1d-4d4b-412b-99ee-47634d83aeda', 'ErrorLog.dxml', 'ERRORLOGS', 'LOGDATE', 'Create Index', SYSDATE, ScriptText); END;

-- Create Index On ERRORLOGS Table
CREATE INDEX "IX_ERRORLOGS_TENANT" ON "ERRORLOGS"("TENANT");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On ERRORLOGS Table
CREATE INDEX "IX_ERRORLOGS_TENANT" ON "ERRORLOGS"("TENANT");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('810e6584-8b17-4e0a-9149-5189990d8653', 'ErrorLog.dxml', 'ERRORLOGS', 'TENANT', 'Create Index', SYSDATE, ScriptText); END;


-- Create Index On FAILEDLOGINLOGS Table
CREATE INDEX "IX_FAILEDLOGINLOGS_GMTDATETIME" ON "FAILEDLOGINLOGS"("GMTDATETIME");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On FAILEDLOGINLOGS Table
CREATE INDEX "IX_FAILEDLOGINLOGS_GMTDATETIME" ON "FAILEDLOGINLOGS"("GMTDATETIME");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('9707e53b-77ff-4215-aefe-71175d1aae88', 'FailedLoginLog.dxml', 'FAILEDLOGINLOGS', 'GMTDATETIME', 'Create Index', SYSDATE, ScriptText); END;


-- Create Index On FAILEDTOKENLOGS Table
CREATE INDEX "IX_FAILEDTOKENLOGS_GMTDATETIME" ON "FAILEDTOKENLOGS"("GMTDATETIME");

DECLARE ScriptText NCLOB; BEGIN ScriptText := '-- Create Index On FAILEDTOKENLOGS Table
CREATE INDEX "IX_FAILEDTOKENLOGS_GMTDATETIME" ON "FAILEDTOKENLOGS"("GMTDATETIME");'; INSERT INTO "DBMIGRATIONSHISTORY"("ID", "DXMLFILENAME", "TABLENAME", "COLUMNNAME", "MIGRATIONTYPE", "EXECUTIONDATE", "MIGRATIONSCRIPT")VALUES('60f02f8a-bb98-43b2-9f1b-5c24c0632d12', 'FailedTokenLog.dxml', 'FAILEDTOKENLOGS', 'GMTDATETIME', 'Create Index', SYSDATE, ScriptText); END;


