<!ELEMENT CFIDATA (CFIDATA_DATA*)>
<!ELEMENT CFIDATA_DATA (ImporterName?, ImporterAddress?, ImporterId?, CasualSupplierName?, CasualSupplierAddress?, ManifestNumber?, ThirdCargoID?, AirlineId?, MAWB?, HAWB?, COUWTVAL?, UNLOADDATE?, CasualImporterAddress1?, CasualImporterAddress2?, CasualImporterCity?, CasualImporterZipCode?, CasualImporterFax?, CasualImporterEmail?, CasualImportelTel?, CasualImporterContact?, VALUE_IN_USD?)>
<!ELEMENT ImporterName (#PCDATA)>
<!ELEMENT ImporterAddress (#PCDATA)>
<!ELEMENT ImporterId (#PCDATA)>
<!ELEMENT CasualSupplierName (#PCDATA)>
<!ELEMENT CasualSupplierAddress (#PCDATA)>
<!ELEMENT ManifestNumber (#PCDATA)>
<!ELEMENT ThirdCargoID (#PCDATA)>
<!ELEMENT AirlineId (#PCDATA)>
<!ELEMENT MAWB (#PCDATA)>
<!ELEMENT HAWB (#PCDATA)>
<!ELEMENT COUWTVAL (#PCDATA)>
<!ELEMENT UNLOADDATE (#PCDATA)>
<!ELEMENT CasualImporterAddress1 (#PCDATA)>
<!ELEMENT CasualImporterAddress2 (#PCDATA)>
<!ELEMENT CasualImporterCity (#PCDATA)>
<!ELEMENT CasualImporterZipCode (#PCDATA)>
<!ELEMENT CasualImporterFax (#PCDATA)>
<!ELEMENT CasualImporterEmail (#PCDATA)>
<!ELEMENT CasualImportelTel (#PCDATA)>
<!ELEMENT CasualImporterContact (#PCDATA)>
<!ELEMENT VALUE_IN_USD (#PCDATA)>