//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CFIData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/CFIData", IsNullable=false)]
public partial class CFIDATA {
    
    private CFIDATA_DATA[] cFIDATA_DATAField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CFIDATA_DATA")]
    public CFIDATA_DATA[] CFIDATA_DATA {
        get {
            return this.cFIDATA_DATAField;
        }
        set {
            this.cFIDATA_DATAField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/CFIData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/CFIData", IsNullable=false)]
public partial class CFIDATA_DATA {
    
    private string importerNameField;
    
    private string importerAddressField;
    
    private string importerIdField;
    
    private string casualSupplierNameField;
    
    private string casualSupplierAddressField;
    
    private string manifestNumberField;
    
    private string thirdCargoIDField;
    
    private string airlineIdField;
    
    private string mAWBField;
    
    private string hAWBField;

    private string cOUWTVALField;

    private string uNLOADDATEField;

    /// <remarks/>
    public string ImporterName {
        get {
            return this.importerNameField;
        }
        set {
            this.importerNameField = value;
        }
    }
    
    /// <remarks/>
    public string ImporterAddress {
        get {
            return this.importerAddressField;
        }
        set {
            this.importerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ImporterId {
        get {
            return this.importerIdField;
        }
        set {
            this.importerIdField = value;
        }
    }
    
    /// <remarks/>
    public string CasualSupplierName {
        get {
            return this.casualSupplierNameField;
        }
        set {
            this.casualSupplierNameField = value;
        }
    }
    
    /// <remarks/>
    public string CasualSupplierAddress {
        get {
            return this.casualSupplierAddressField;
        }
        set {
            this.casualSupplierAddressField = value;
        }
    }
    
    /// <remarks/>
    public string ManifestNumber {
        get {
            return this.manifestNumberField;
        }
        set {
            this.manifestNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ThirdCargoID {
        get {
            return this.thirdCargoIDField;
        }
        set {
            this.thirdCargoIDField = value;
        }
    }
    
    /// <remarks/>
    public string AirlineId {
        get {
            return this.airlineIdField;
        }
        set {
            this.airlineIdField = value;
        }
    }
    
    /// <remarks/>
    public string MAWB {
        get {
            return this.mAWBField;
        }
        set {
            this.mAWBField = value;
        }
    }
    
    /// <remarks/>
    public string HAWB {
        get {
            return this.hAWBField;
        }
        set {
            this.hAWBField = value;
        }
    }

    /// <remarks/>
    public string COUWTVAL
    {
        get
        {
            return this.cOUWTVALField;
        }
        set
        {
            this.cOUWTVALField = value;
        }
    }

    /// <remarks/>
    public string UNLOADDATE
    {
        get
        {
            return this.uNLOADDATEField;
        }
        set
        {
            this.uNLOADDATEField = value;
        }
    }
}
