<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/LOGIGENREQ" elementFormDefault="qualified" targetNamespace="http://tempuri.org/LOGIGENREQ" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LOGIGENREQ">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="LogitudeGeneralRequest" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LogitudeGeneralRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="Code" />
        <xs:element minOccurs="0" maxOccurs="1" ref="Date1" />
        <xs:element minOccurs="0" maxOccurs="1" ref="Date2" />
        <xs:element minOccurs="0" maxOccurs="1" ref="Param1" />
        <xs:element minOccurs="0" maxOccurs="1" ref="Param2" />
        <xs:element minOccurs="0" maxOccurs="1" ref="More_Param" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Code" type="xs:string" />
  <xs:element name="Date1" type="xs:string" />
  <xs:element name="Date2" type="xs:string" />
  <xs:element name="Param1" type="xs:string" />
  <xs:element name="Param2" type="xs:string" />
  <xs:element name="More_Param" type="xs:string" />
</xs:schema>