<!ELEMENT CUSTOMS_TABLE (TABLECODE*)>
<!ELEMENT TABLECODE (TABLECODE_ID?, TABLEDATA*)>
<!ELEMENT TABLECODE_ID (#PCDATA)>
<!ELEMENT TABLEDATA (TABLEDATA_ID?, TABLEDATA_NAME_HEB?, TABLEDATA_NAME_ENG?, TABLEDATA_BLOCKED?, TABLEDATA_ADDITIONALCODE1?, TABLEDATA_ADDITIONALCODE2?, TABLEDATA_REMARKS?, TABLEDATA_UNF_TABLE?)>
<!ELEMENT TABLEDATA_ID (#PCDATA)>
<!ELEMENT TABLEDATA_NAME_HEB (#PCDATA)>
<!ELEMENT TABLEDATA_NAME_ENG (#PCDATA)>
<!ELEMENT TABLEDATA_BLOCKED (#PCDATA)>
<!ELEMENT TABLEDATA_ADDITIONALCODE1 (#PCDATA)>
<!ELEMENT TABLEDATA_ADDITIONALCODE2 (#PCDATA)>
<!ELEMENT TABLEDATA_REMARKS (#PCDATA)>
<!ELEMENT TABLEDATA_UNF_TABLE (#PCDATA)>
