export enum FieldTypes {
    LookUp = "LookUp",
    NText = "nText",
    Text = "Text",
    Boolean = "Boolean",
    DateTime = "DateTime",
    Date = "Date",
    BigInteger = "BigInteger",
    Decimal = "Decimal",
    Double = "Double",
    Integer = "Integer",
    SigDouble = "SigDouble",
    UnsDecimal = "UnsDecimal",
    UnsInteger = "UnsInteger",
}