<!ELEMENT LOGICELLFILE (LogitudeCellularFile*)>
<!ELEMENT LogitudeCellularFile (LOGITUDEFILE?, TENANT?, INVOICE*)>
<!ELEMENT LOGITUDEFILE (#PCDATA)>
<!ELEMENT TENANT (#PCDATA)>
<!ELEMENT INVOICE (INVOICELINENO?, ACCOUNTTYPE?, INVOICENUMBER?, VENDORNUMBER?, CURRENCYCODE?, INVOICEAMOUNT?, ISSUEDATE?, ISSUECOUNTRYCODE?, INVOICEITEMS*)>
<!ELEMENT INVOICELINENO (#PCDATA)>
<!ELEMENT ACCOUNTTYPE (#PCDATA)>
<!ELEMENT INVOICENUMBER (#PCDATA)>
<!ELEMENT VENDORNUMBER (#PCDATA)>
<!ELEMENT CURRENCYCODE (#PCDATA)>
<!ELEMENT INVOICEAMOUNT (#PCDATA)>
<!ELEMENT ISSUEDATE (#PCDATA)>
<!ELEMENT ISSUECOUNTRYCODE (#PCDATA)>
<!ELEMENT INVOICEITEMS (ITEMLINENO?, CLASSIFICATIONCODE?, TRADEAGREEMENTCODE?, QUANTITY?, ITEMPRICE?, ITEMORIGINCOUNTRY?, ITEMCODE?, ACTUALINVOICELINES?,UNIT?, CARS*)>
<!ELEMENT ITEMLINENO (#PCDATA)>
<!ELEMENT CLASSIFICATIONCODE (#PCDATA)>
<!ELEMENT TRADEAGREEMENTCODE (#PCDATA)>
<!ELEMENT QUANTITY (#PCDATA)>
<!ELEMENT ITEMPRICE (#PCDATA)>
<!ELEMENT ITEMORIGINCOUNTRY (#PCDATA)>
<!ELEMENT ITEMCODE (#PCDATA)>
<!ELEMENT ACTUALINVOICELINES (#PCDATA)>
<!ELEMENT UNIT (#PCDATA)>
<!ELEMENT CARS (SITEM_LINE?, COUNTER?, MODEL?, CHASSIS?)>
<!ELEMENT SITEM_LINE (#PCDATA)>
<!ELEMENT COUNTER (#PCDATA)>
<!ELEMENT MODEL (#PCDATA)>
<!ELEMENT CHASSIS (#PCDATA)>
