<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/LOGIDECREFERANTDATA" elementFormDefault="qualified" targetNamespace="http://tempuri.org/LOGIDECREFERANTDATA" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LOGIDECREFERANTDATA">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="LogitudeDeclarationReferantData" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LogitudeDeclarationReferantData">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="Id" />
        <xs:element minOccurs="0" maxOccurs="1" ref="CustomsFile" />
        <xs:element minOccurs="0" maxOccurs="1" ref="QueueType" />
        <xs:element minOccurs="0" maxOccurs="1" ref="QueueStatus" />
        <xs:element minOccurs="0" maxOccurs="1" ref="QueueRemarks" />
        <xs:element minOccurs="0" maxOccurs="1" ref="FollowUpStatus" />
        <xs:element minOccurs="0" maxOccurs="1" ref="PreClassification" />
        <xs:element minOccurs="0" maxOccurs="1" ref="Tenant" />
        <xs:element minOccurs="0" maxOccurs="1" ref="ClassifiedUserId" />
        <xs:element minOccurs="0" maxOccurs="1" ref="ControllerUserId" />
        <xs:element minOccurs="0" maxOccurs="1" ref="FileStatus" />
        <xs:element minOccurs="0" maxOccurs="1" ref="LastStatusName" />
        <xs:element minOccurs="0" maxOccurs="1" ref="LastStatusDate" />
        <xs:element minOccurs="0" maxOccurs="1" ref="OrderMoney" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Id" type="xs:string" />
  <xs:element name="CustomsFile" type="xs:string" />
  <xs:element name="QueueType" type="xs:string" />
  <xs:element name="QueueStatus" type="xs:string" />
  <xs:element name="QueueRemarks" type="xs:string" />
  <xs:element name="FollowUpStatus" type="xs:string" />
  <xs:element name="PreClassification" type="xs:string" />
  <xs:element name="Tenant" type="xs:string" />
  <xs:element name="ClassifiedUserId" type="xs:string" />
  <xs:element name="ControllerUserId" type="xs:string" />
  <xs:element name="FileStatus" type="xs:string" />
  <xs:element name="LastStatusName" type="xs:string" />
  <xs:element name="LastStatusDate" type="xs:string" />
  <xs:element name="OrderMoney" type="xs:string" />
</xs:schema>