<!ELEMENT LOGIDECREFERANTDATA (LogitudeDeclarationReferantData*)>
<!ELEMENT LogitudeDeclarationReferantData (Id?, CustomsFile?, QueueType?, QueueStatus?, QueueRemarks?, FollowUpStatus?, PreClassification?, Tenant?, ClassifiedUserId?, ControllerUserId?, FileStatus?)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT CustomsFile (#PCDATA)>
<!ELEMENT QueueType (#PCDATA)>
<!ELEMENT QueueStatus (#PCDATA)>
<!ELEMENT QueueRemarks (#PCDATA)>
<!ELEMENT FollowUpStatus (#PCDATA)>
<!ELEMENT PreClassification (#PCDATA)>
<!ELEMENT Tenant (#PCDATA)>
<!ELEMENT ClassifiedUserId (#PCDATA)>
<!ELEMENT ControllerUserId (#PCDATA)>
<!ELEMENT FileStatus (#PCDATA)>