export class ContainerFollowUpList {
    public Id: string;
    public Tenant: number;
    public ShipmentId: string;
    public ShipmentNumber: string;
    public CustomerId: string;
    public CustomerName: string;
    public CustomerContactName: string;
    public CarrierId: string;
    public CarrierName: string;
    public VesselName: string
    public ShipmentNotes: string;
    public ShipperId: string;
    public ShipperName: string;
    public ConsigneeId: string;
    public ConsigneeName: string;
    public ConsigneeReference: string;
    public LongMaster: string;
    public House: string;
    public DirectionId: string;
    public DirectionName: string;
    public TransportModeId: string;
    public TransportModeName: string;
    public ShipmentType: string;
    public ShipmentLevelCode: string;
    public ShipmentLevelName: string;
    public StatusId: string;
    public SearchFields: string;

    public ContainerTypeName: string;
    public ContainerNumber: string;
    public ShipperSeal: string;
    public Volume: number;
    public IsDangerous: boolean;
    public Description: string;
    public MarksAndNumbers: string;

    public IsDeliveryFU: boolean;
    public DeliveryId: string;
    public DeliveryETD: Date;
    public DeliveryATD: Date;
    public DeliveryETA: Date;
    public DeliveryATA: Date;
    public DeliveryDeparture: Date;
    public DeliveryArrival: Date;
    public DeliveryFrom: string;
    public DeliveryTo: string;
    public IsEmptyContainerReturnFU: boolean;
    public EmptyContainerReturnId: string;
    public EmptyContainerReturnETD: Date;
    public EmptyContainerReturnATD: Date;
    public EmptyContainerReturnETA: Date;
    public EmptyContainerReturnATA: Date;
    public ReturnDeparture: Date;
    public ReturnArrival: Date;
    public EmptyContainerReturnFrom: string;
    public EmptyContainerReturnTo: string;
}