//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class HarmonizeCodeList {
   		Code: string;
		Description: string;
		ChapterCode: string;
		ChapterDescription: string;
		SubChapterCode: string;
		SubChapterDescription: string;
		SearchFields: string;
	
}