//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> Amital\EntityKeysGenerator.tt from AmitalClassesGenerator.tt
//---
using AmitalCloud.Infrastructure.Domain.BaseClasses;
using System;
using System.Collections.Generic;
using System.Linq;  
using System.Linq.Expressions;
using ENTITIES = AmitalCloud.Infrastructure.Model.EntityClasses;
namespace AmitalCloud.Infrastructure.Domain.EntityKeys
{
   public class TipKeys<T> : BaseEntityKeyFields<ENTITIES.Tip,T> 
   {
		public TipKeys() : base() {}
        public TipKeys(IEnumerable<KeyValuePair<string, string>> paramList) : base(paramList) {}
        public override void Initialize(IEnumerable<KeyValuePair<string, string>> paramList)
        {
			Code = (string)Convert.ChangeType((paramList.Single(t => t.Key == "Code").Value), typeof(string));
        }
   	  public string Code  { get; set; }
	    			   
	  public override T GetFullKey() =>   (T)Convert.ChangeType(Code.ToString(),typeof(T)) ;           
      public override string GetEntityPMName() => "TipsPM";
	  public override Expression<Func<ENTITIES.Tip, bool>> Predicate => a => a.Code == Code;
   }
}
	 