

DROP INDEX "IX_COMMUNICATIONLOGS_ENTITYID";

/

CREATE TABLE "AMINETCST_MAIN"."DBMIGRATIONSETTINGS"
(
"MODE" VARCHAR2(10 CHAR) NOT NULL,
"MODULESLIST" VARCHAR2(1000 CHAR) NOT NULL
);
/


INSERT INTO "AMINETCST_MAIN"."DBMIGRATIONSETTINGS"("MODE", "MODULESLIST") VALUES('Include', 'Customs,Common,Infrastructure');
/