update QuoteTemplateTextCodes set OriginalEnglishName = 'Charge Code' , OriginalLocalName = 'Charge Code' where TextCode = 'CHARGECODEPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Charge Code' , OriginalLocalName = 'Charge Code' where TextCode = 'CHARGECODECONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Charge Description' , OriginalLocalName = 'Charge Description' where TextCode = 'CHARGEDESCRIPTIONPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Charge Description' , OriginalLocalName = 'Charge Description' where TextCode = 'CHARGEDESCRIPTIONCONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Charge' , OriginalLocalName = 'Charge' where TextCode = 'CHARGEPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Charge' , OriginalLocalName = 'Charge' where TextCode = 'CHARGECONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Units' , OriginalLocalName = 'Units' where TextCode = 'UNITSPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Unit Price' , OriginalLocalName = 'Unit Price' where TextCode = 'UNITPRICEPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Measurement' , OriginalLocalName = 'Measurement' where TextCode = 'MEASUREMENTPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Measurement' , OriginalLocalName = 'Measurement' where TextCode = 'MEASUREMENTCONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Total' , OriginalLocalName = 'Total' where TextCode = 'TOTALPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Total' , OriginalLocalName = 'Total' where TextCode = 'TOTALCONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Local Amount' , OriginalLocalName = 'Local Amount' where TextCode = 'LOCALAMOUNTPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Local Amount' , OriginalLocalName = 'Local Amount' where TextCode = 'LOCALAMOUNTCONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Fixed Price' , OriginalLocalName = 'Fixed Price' where TextCode = 'FIXEDPRICECONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Estimated total based on the above weight/volume' , OriginalLocalName = 'Estimated total based on the above weight/volume' where TextCode = 'TOTALAMOUNTS'    
update QuoteTemplateTextCodes set OriginalEnglishName = 'Quote Date' , OriginalLocalName = 'Quote Date' where TextCode = 'QUOTEDATE'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Expiration Date' , OriginalLocalName = 'Expiration Date' where TextCode = 'EXPIRATIONDATE'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Quote Number' , OriginalLocalName = 'Quote Number' where TextCode = 'QUOTENUMBER'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Customer' , OriginalLocalName = 'Customer' where TextCode = 'CUSTOMER'
update QuoteTemplateTextCodes set OriginalEnglishName = 'ATTN' , OriginalLocalName = 'ATTN' where TextCode = 'ATTN' 
update QuoteTemplateTextCodes set OriginalEnglishName = 'Expiration Date' , OriginalLocalName = 'Expiration Date' where TextCode = 'EXPIRATIONDATE'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Expiration Days' , OriginalLocalName = 'Expiration Days' where TextCode = 'EXPIRATIONDAYS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Shipper Name' , OriginalLocalName = 'Shipper Name' where TextCode = 'SHIPPERNAME'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Shipper Address' , OriginalLocalName = 'Shipper Address' where TextCode = 'SHIPPERADDRESS' 
update QuoteTemplateTextCodes set OriginalEnglishName = 'Shipper Contact' , OriginalLocalName = 'Shipper Contact' where TextCode = 'SHIPPERCONTACT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Shipper References' , OriginalLocalName = 'Shipper References' where TextCode = 'SHIPPERREFERENCES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Consignee Name' , OriginalLocalName = 'Consignee Name' where TextCode = 'CONSIGNEENAME'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Consignee Address' , OriginalLocalName = 'Consignee Address' where TextCode = 'CONSIGNEEADDRESS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Consignee Contact' , OriginalLocalName = 'Consignee Contact' where TextCode = 'CONSIGNEECONTACT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Consignee References' , OriginalLocalName = 'Consignee References' where TextCode = 'CONSIGNEEREFERENCES' 
update QuoteTemplateTextCodes set OriginalEnglishName = 'Customer Name' , OriginalLocalName = 'Customer Name' where TextCode = 'CUSTOMERNAME'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Customer Address' , OriginalLocalName = 'Customer Address' where TextCode = 'CUSTOMERADDRESS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Customer Contact' , OriginalLocalName = 'Customer Contact' where TextCode = 'CUSTOMERCONTACT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Customer References' , OriginalLocalName = 'Customer References' where TextCode = 'CUSTOMERREFERENCES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Pickup From' , OriginalLocalName = 'Pickup From' where TextCode = 'PICKUPFROM'
update QuoteTemplateTextCodes set OriginalEnglishName = 'From Port' , OriginalLocalName = 'From Port' where TextCode = 'FROMPORT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Delivery To' , OriginalLocalName = 'Delivery To' where TextCode = 'DELIVERYTO'
update QuoteTemplateTextCodes set OriginalEnglishName = 'To Port' , OriginalLocalName = 'To Port' where TextCode = 'TOPORT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Incoterms' , OriginalLocalName = 'Incoterms' where TextCode = 'INCOTERMS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Service' , OriginalLocalName = 'Service' where TextCode = 'SERVICE'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Sales Man' , OriginalLocalName = 'Sales Man' where TextCode = 'SALESMAN'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Description Of Goods' , OriginalLocalName = 'Description Of Goods' where TextCode = 'DESCRIPTIONOFGOODS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Dangerous Goods' , OriginalLocalName = 'Dangerous Goods' where TextCode = 'DANGEROUSGOODS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'General Details' , OriginalLocalName = 'General Details' where TextCode = 'GENERALDETAILS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Quote Number' , OriginalLocalName = 'Quote Number' where TextCode = 'QUOTENUMBER'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Shipingline' , OriginalLocalName = 'Shipingline' where TextCode = 'SHIPINFLINE'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Trucker' , OriginalLocalName = 'Trucker' where TextCode = 'TRUCKER'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Airline' , OriginalLocalName = 'Airline' where TextCode = 'AIRLINE'
update QuoteTemplateTextCodes set OriginalEnglishName = 'From Location' , OriginalLocalName = 'From Location' where TextCode = 'FROMLOCATION'
update QuoteTemplateTextCodes set OriginalEnglishName = 'To Location' , OriginalLocalName = 'To Location' where TextCode = 'TOLOCATION' 	
update QuoteTemplateTextCodes set OriginalEnglishName = 'Pricing Packages' , OriginalLocalName = 'Pricing Packages' where TextCode = 'PRICINGPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Pricing Containers' , OriginalLocalName = 'Pricing Containers' where TextCode = 'PRICINGCONTAINERS'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Chargeable Weight' , OriginalLocalName = 'Chargeable Weight' where TextCode = 'CHARGEABLEWEIGHT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Gross Weight' , OriginalLocalName = 'Gross Weight' where TextCode = 'GROSSWEIGHT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Volume' , OriginalLocalName = 'Volume' where TextCode = 'VOLUME'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Volumetric Weight' , OriginalLocalName = 'Volumetric Weight' where TextCode = 'VOLUMETRICWEIGHT'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Number Of Packages' , OriginalLocalName = 'Number Of Packages' where TextCode = 'NUMBEROFPACKAGES'
update QuoteTemplateTextCodes set OriginalEnglishName = 'Number Of Containers' , OriginalLocalName = 'Number Of Containers' where TextCode = 'NUMBEROFCONTAINERS'
	  
			
			

         
      