//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using AmitalCloud.Infrastructure.Model.BaseClasses;
using AmitalCloud.Infrastructure.Model.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AmitalCloud.Infrastructure.Model.EntityClasses
{
	[DataBase(AmitalCloudDBSchema.AMITAL_GLOBAL)]
	[Table("OneTimePasswords")]
    public class OneTimePassword : BaseEntity
	{
		
        [Key]
        [Column("Id")]
	    public string Id { get; set; }
        [Column("Tenant")]
	    public int Tenant { get; set; }
        [Column("UserId")]
	    public string UserId { get; set; }
        [Column("UserEmail")]
	    public string UserEmail { get; set; }
        [Column("CreateDate")]
	    public DateTime CreateDate { get; set; }
        [Column("UsageDate")]
	    public DateTime? UsageDate { get; set; }
        [Column("ExpirationDate")]
	    public DateTime ExpirationDate { get; set; }
        [Column("IsUsed")]
	    public bool IsUsed { get; set; }
    }
}
	 