//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using AmitalCloud.Infrastructure.Model.BaseClasses;
using AmitalCloud.Infrastructure.Model.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AmitalCloud.Infrastructure.Model.EntityClasses
{
	[DataBase(AmitalCloudDBSchema.AMITAL_MAIN)]
	[Table("QuoteTemplateTableDesigns")]
    public class QuoteTemplateTableDesign : BaseEntity
	{
		
        [Key]
        [Column("Id")]
	    public string Id { get; set; }
        [Column("Tenant")]
	    public int Tenant { get; set; }
        [ForeignKey("BorderType")]
        [Column("BorderTypeCode")]
	    public string BorderTypeCode { get; set; }
	      
        public virtual BorderType BorderType { get; set; }
        [Column("BorderColor")]
	    public string BorderColor { get; set; }
        [Column("BorderThickness")]
	    public int BorderThickness { get; set; }
        [ForeignKey("HeaderDesign")]
        [Column("HeaderDesignId")]
	    public string HeaderDesignId { get; set; }
	      
        public virtual QuoteTemplateTextDesign HeaderDesign { get; set; }
        [ForeignKey("LinesDesign")]
        [Column("LinesDesignId")]
	    public string LinesDesignId { get; set; }
	      
        public virtual QuoteTemplateTextDesign LinesDesign { get; set; }
        [ForeignKey("GroupDesign")]
        [Column("GroupByDesignId")]
	    public string GroupByDesignId { get; set; }
	      
        public virtual QuoteTemplateTextDesign GroupDesign { get; set; }
    }
}
	 