//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using AmitalCloud.Infrastructure.Domain.BaseClasses;
using AmitalCloud.Infrastructure.Domain.EntityPOCOs;
namespace AmitalCloud.Infrastructure.Domain.EntityPOCOs
{
    public class CardExternalAccountsByProduct : BaseEntity
	{
		
        [Key]
        [Column("Id")]
	    public string Id { get; set; }
        [Column("Tenant")]
	    public int Tenant { get; set; }
        [Column("GLAccount")]
	    public string GLAccount { get; set; }
        [Column("CostCenter")]
	    public string CostCenter { get; set; }
        [Column("UpdateDate")]
	    public DateTime? UpdateDate { get; set; }
        [ForeignKey("Card")]
        [Column("CardId")]
	    public string CardId { get; set; }
	      
        public virtual Card Card { get; set; }
        [ForeignKey("ProductType")]
        [Column("ProductTypeCode")]
	    public string ProductTypeCode { get; set; }
	      
        public virtual ProductType ProductType { get; set; }
        [ForeignKey("UpdatedByUser")]
        [Column("UpdatedByUserId")]
	    public string UpdatedByUserId { get; set; }
	      
        public virtual User UpdatedByUser { get; set; }
    }
}
	 