//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using AmitalCloud.Infrastructure.Domain.BaseClasses;
using AmitalCloud.Infrastructure.Domain.EntityPOCOs;
namespace AmitalCloud.Infrastructure.Domain.EntityPOCOs
{
    public class DocumentStatus : BaseEntity
	{
	        new const bool hasTenant = false;  
		
        [Key]
        [Column("Code")]
	    public string Code { get; set; }
        [Column("DropCdropName")]
	    public string DropCdropName { get; set; }
        [Column("DropCdropSearchfields")]
	    public string DropCdropSearchfields { get; set; }
        [Column("Name")]
	    public string Name { get; set; }
        [Column("SearchFields")]
	    public string SearchFields { get; set; }
		public virtual ICollection<DocumentsFiling> DocumentsFilings { get; set; }
    }
}
	 