//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> C:\LWC\Logitude\Logitude.Customs.MetaData\AutoGenerators\CustomClassesGenerator.tt
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

import {UIProperties, UIProperty} from '../../Infrastructure/Components/LogitudeComponents/UIProperties';
import {ServiceHelper} from '../../Infrastructure/Utilities/ServiceHelper';
import {ServiceLocator} from '../../Infrastructure/Locators/ServiceLocator';
import {Output, EventEmitter}  from '@angular/core';
import {PropertyChangedArgs} from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';
import {CustomFieldClass} from '../../Infrastructure/DataContracts/CustomFieldClass';

export class CB_TradeLevyPM {
      
      @Output() PropertyChanged: EventEmitter<PropertyChangedArgs> = new EventEmitter<PropertyChangedArgs>();
      public UIProperties: UIProperties;
	  constructor() {
                    this.UIProperties = new UIProperties(this); 
          this.IsDirty = false;
      }
 	 
    
    private iD: number;
    public get ID() { return this.iD; }
    public set ID(newValue: number) { if (this.iD != newValue) { this.iD = newValue; this.MarkAsDirty("ID"); } }
       
	 
    private createDate: Date;
    public get CreateDate() { return this.createDate; }
    public set CreateDate(newValue: Date) { if (this.createDate != newValue) { this.createDate = newValue; this.MarkAsDirty("CreateDate"); } }
       
	 
    private updateDate: Date;
    public get UpdateDate() { return this.updateDate; }
    public set UpdateDate(newValue: Date) { if (this.updateDate != newValue) { this.updateDate = newValue; this.MarkAsDirty("UpdateDate"); } }
       
	 
    private customsBookTypeID: string;
    public get CustomsBookTypeID() { return this.customsBookTypeID; }
    public set CustomsBookTypeID(newValue: string) { if (this.customsBookTypeID != newValue) { this.customsBookTypeID = newValue; this.MarkAsDirty("CustomsBookTypeID"); } }
       
	 
    private levyNumber: string;
    public get LevyNumber() { return this.levyNumber; }
    public set LevyNumber(newValue: string) { if (this.levyNumber != newValue) { this.levyNumber = newValue; this.MarkAsDirty("LevyNumber"); } }
       
	 
    private endOfInquiryDate: Date;
    public get EndOfInquiryDate() { return this.endOfInquiryDate; }
    public set EndOfInquiryDate(newValue: Date) { if (this.endOfInquiryDate != newValue) { this.endOfInquiryDate = newValue; this.MarkAsDirty("EndOfInquiryDate"); } }
       
	 
    private endOfLevyDate: Date;
    public get EndOfLevyDate() { return this.endOfLevyDate; }
    public set EndOfLevyDate(newValue: Date) { if (this.endOfLevyDate != newValue) { this.endOfLevyDate = newValue; this.MarkAsDirty("EndOfLevyDate"); } }
       
	 
    private inceptionCodeID: string;
    public get InceptionCodeID() { return this.inceptionCodeID; }
    public set InceptionCodeID(newValue: string) { if (this.inceptionCodeID != newValue) { this.inceptionCodeID = newValue; this.MarkAsDirty("InceptionCodeID"); } }
       
	 
    private startDate: Date;
    public get StartDate() { return this.startDate; }
    public set StartDate(newValue: Date) { if (this.startDate != newValue) { this.startDate = newValue; this.MarkAsDirty("StartDate"); } }
       
	 
    private tradeLevyStatusID: string;
    public get TradeLevyStatusID() { return this.tradeLevyStatusID; }
    public set TradeLevyStatusID(newValue: string) { if (this.tradeLevyStatusID != newValue) { this.tradeLevyStatusID = newValue; this.MarkAsDirty("TradeLevyStatusID"); } }
       
	 
    private computationMethodDataID: number;
    public get ComputationMethodDataID() { return this.computationMethodDataID; }
    public set ComputationMethodDataID(newValue: number) { if (this.computationMethodDataID != newValue) { this.computationMethodDataID = newValue; this.MarkAsDirty("ComputationMethodDataID"); } }
       
	 
    private levyTrustID: string;
    public get LevyTrustID() { return this.levyTrustID; }
    public set LevyTrustID(newValue: string) { if (this.levyTrustID != newValue) { this.levyTrustID = newValue; this.MarkAsDirty("LevyTrustID"); } }
       
	 
    private paragraphTypeID: string;
    public get ParagraphTypeID() { return this.paragraphTypeID; }
    public set ParagraphTypeID(newValue: string) { if (this.paragraphTypeID != newValue) { this.paragraphTypeID = newValue; this.MarkAsDirty("ParagraphTypeID"); } }
       
	 
    private cB_ID: string;
    public get CB_ID() { return this.cB_ID; }
    public set CB_ID(newValue: string) { if (this.cB_ID != newValue) { this.cB_ID = newValue; this.MarkAsDirty("CB_ID"); } }
       
	 

    public OldEntityPM: CB_TradeLevyPM;
		
    public IsDirty: boolean;
    public DisableMarkAsDirty: boolean = false;
    MarkAsDirty(propertyName:string = null) {
       if(!this.DisableMarkAsDirty)
       {
        this.IsDirty = true;
		  	
        if (propertyName != null) {
            this.PropertyChanged.emit(new PropertyChangedArgs(propertyName,this));
            ServiceLocator.RulesValidator.ApplyEntityChangedRules(propertyName, this, "Customs.CB_TradeLevy");
           
        }
       }
    }

    private MyClone: CB_TradeLevyPM;

    public CloneMe() {
        ServiceHelper.CloneEntityPM(this);
    }

    public RejectChanges() {
        ServiceHelper.RejectEntityPMChanges(this);
    }

}