//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------


import {CardExternalCodeByCurrencyPM} from './CardExternalCodeByCurrencyPM';
import {UIProperties, UIProperty} from '../../Infrastructure/Components/LogitudeComponents/UIProperties';
import {ServiceHelper} from '../../Infrastructure/Utilities/ServiceHelper';
import {ServiceLocator} from '../../Infrastructure/Locators/ServiceLocator';
import {Output, EventEmitter}  from '@angular/core';
import {PropertyChangedArgs} from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';
import {CustomFieldClass} from '../../Infrastructure/DataContracts/CustomFieldClass';


export class ShippingLinePM {

      @Output() PropertyChanged: EventEmitter<PropertyChangedArgs> = new EventEmitter<PropertyChangedArgs>();
      public UIProperties: UIProperties;
	  constructor() {
          this.UIProperties = new UIProperties(this); 
          this.IsDirty = false;
      }
 	 
    
    private id: string;
    public get Id() { return this.id; }
    public set Id(newValue: string) { if (this.id != newValue) { this.id = newValue; this.MarkAsDirty("Id"); } }
       
	 
    private tenant: number;
    public get Tenant() { return this.tenant; }
    public set Tenant(newValue: number) { if (this.tenant != newValue) { this.tenant = newValue; this.MarkAsDirty("Tenant"); } }
       
	 
    private isSecured: boolean;
    public get IsSecured() { return this.isSecured; }
    public set IsSecured(newValue: boolean) { if (this.isSecured != newValue) { this.isSecured = newValue; this.MarkAsDirty("IsSecured"); } }
       
	 
    private bankName: string;
    public get BankName() { return this.bankName; }
    public set BankName(newValue: string) { if (this.bankName != newValue) { this.bankName = newValue; this.MarkAsDirty("BankName"); } }
       
	 
    private bankAddress: string;
    public get BankAddress() { return this.bankAddress; }
    public set BankAddress(newValue: string) { if (this.bankAddress != newValue) { this.bankAddress = newValue; this.MarkAsDirty("BankAddress"); } }
       
	 
    private swift: string;
    public get Swift() { return this.swift; }
    public set Swift(newValue: string) { if (this.swift != newValue) { this.swift = newValue; this.MarkAsDirty("Swift"); } }
       
	 
    private accountNumber: string;
    public get AccountNumber() { return this.accountNumber; }
    public set AccountNumber(newValue: string) { if (this.accountNumber != newValue) { this.accountNumber = newValue; this.MarkAsDirty("AccountNumber"); } }
       
	 
    private iBANNumber: string;
    public get IBANNumber() { return this.iBANNumber; }
    public set IBANNumber(newValue: string) { if (this.iBANNumber != newValue) { this.iBANNumber = newValue; this.MarkAsDirty("IBANNumber"); } }
       
	 
    private code: string;
    public get Code() { return this.code; }
    public set Code(newValue: string) { if (this.code != newValue) { this.code = newValue; this.MarkAsDirty("Code"); } }
       
	 
    private createDate: Date;
    public get CreateDate() { return this.createDate; }
    public set CreateDate(newValue: Date) { if (this.createDate != newValue) { this.createDate = newValue; this.MarkAsDirty("CreateDate"); } }
       
	 
    private updateDate: Date;
    public get UpdateDate() { return this.updateDate; }
    public set UpdateDate(newValue: Date) { if (this.updateDate != newValue) { this.updateDate = newValue; this.MarkAsDirty("UpdateDate"); } }
       
	 
    private createdByUserId: string;
    public get CreatedByUserId() { return this.createdByUserId; }
    public set CreatedByUserId(newValue: string) { if (this.createdByUserId != newValue) { this.createdByUserId = newValue; this.MarkAsDirty("CreatedByUserId"); } }
       
	 
    private updatedByUserId: string;
    public get UpdatedByUserId() { return this.updatedByUserId; }
    public set UpdatedByUserId(newValue: string) { if (this.updatedByUserId != newValue) { this.updatedByUserId = newValue; this.MarkAsDirty("UpdatedByUserId"); } }
       
	 
    private sCACCode: string;
    public get SCACCode() { return this.sCACCode; }
    public set SCACCode(newValue: string) { if (this.sCACCode != newValue) { this.sCACCode = newValue; this.MarkAsDirty("SCACCode"); } }
       
	 
    private englishName: string;
    public get EnglishName() { return this.englishName; }
    public set EnglishName(newValue: string) { if (this.englishName != newValue) { this.englishName = newValue; this.MarkAsDirty("EnglishName"); } }
       
	 
    private localName: string;
    public get LocalName() { return this.localName; }
    public set LocalName(newValue: string) { if (this.localName != newValue) { this.localName = newValue; this.MarkAsDirty("LocalName"); } }
       
	 
    private shippingAgentId: string;
    public get ShippingAgentId() { return this.shippingAgentId; }
    public set ShippingAgentId(newValue: string) { if (this.shippingAgentId != newValue) { this.shippingAgentId = newValue; this.MarkAsDirty("ShippingAgentId"); } }
       
	 
    private website: string;
    public get Website() { return this.website; }
    public set Website(newValue: string) { if (this.website != newValue) { this.website = newValue; this.MarkAsDirty("Website"); } }
       
	 
    private inActive: boolean;
    public get InActive() { return this.inActive; }
    public set InActive(newValue: boolean) { if (this.inActive != newValue) { this.inActive = newValue; this.MarkAsDirty("InActive"); } }
       
	 
    private notes: string;
    public get Notes() { return this.notes; }
    public set Notes(newValue: string) { if (this.notes != newValue) { this.notes = newValue; this.MarkAsDirty("Notes"); } }
       
	 
    private ourCreditNumber: string;
    public get OurCreditNumber() { return this.ourCreditNumber; }
    public set OurCreditNumber(newValue: string) { if (this.ourCreditNumber != newValue) { this.ourCreditNumber = newValue; this.MarkAsDirty("OurCreditNumber"); } }
       
	 
    private vatNumber: string;
    public get VatNumber() { return this.vatNumber; }
    public set VatNumber(newValue: string) { if (this.vatNumber != newValue) { this.vatNumber = newValue; this.MarkAsDirty("VatNumber"); } }
       
	 
    private receivablesAccountingCard: string;
    public get ReceivablesAccountingCard() { return this.receivablesAccountingCard; }
    public set ReceivablesAccountingCard(newValue: string) { if (this.receivablesAccountingCard != newValue) { this.receivablesAccountingCard = newValue; this.MarkAsDirty("ReceivablesAccountingCard"); } }
       
	 
    private payablesAccountingCard: string;
    public get PayablesAccountingCard() { return this.payablesAccountingCard; }
    public set PayablesAccountingCard(newValue: string) { if (this.payablesAccountingCard != newValue) { this.payablesAccountingCard = newValue; this.MarkAsDirty("PayablesAccountingCard"); } }
       
	 
    private invoiceCurrencyId: string;
    public get InvoiceCurrencyId() { return this.invoiceCurrencyId; }
    public set InvoiceCurrencyId(newValue: string) { if (this.invoiceCurrencyId != newValue) { this.invoiceCurrencyId = newValue; this.MarkAsDirty("InvoiceCurrencyId"); } }
       
	 
    private paymentTermId: string;
    public get PaymentTermId() { return this.paymentTermId; }
    public set PaymentTermId(newValue: string) { if (this.paymentTermId != newValue) { this.paymentTermId = newValue; this.MarkAsDirty("PaymentTermId"); } }
       
	 
    private remark: string;
    public get Remark() { return this.remark; }
    public set Remark(newValue: string) { if (this.remark != newValue) { this.remark = newValue; this.MarkAsDirty("Remark"); } }
       
	 
    private carrierTypeId: string;
    public get CarrierTypeId() { return this.carrierTypeId; }
    public set CarrierTypeId(newValue: string) { if (this.carrierTypeId != newValue) { this.carrierTypeId = newValue; this.MarkAsDirty("CarrierTypeId"); } }
       
	 
    private vatTypeId: string;
    public get VatTypeId() { return this.vatTypeId; }
    public set VatTypeId(newValue: string) { if (this.vatTypeId != newValue) { this.vatTypeId = newValue; this.MarkAsDirty("VatTypeId"); } }
       
	 
    private fieldsChanged: boolean;
    public get FieldsChanged() { return this.fieldsChanged; }
    public set FieldsChanged(newValue: boolean) { if (this.fieldsChanged != newValue) { this.fieldsChanged = newValue; this.MarkAsDirty("FieldsChanged"); } }
       
	 
    private computedLocalName: string;
    public get ComputedLocalName() { return this.computedLocalName; }
    public set ComputedLocalName(newValue: string) { if (this.computedLocalName != newValue) { this.computedLocalName = newValue; this.MarkAsDirty("ComputedLocalName"); } }
       
	 
    private addedManually: boolean;
    public get AddedManually() { return this.addedManually; }
    public set AddedManually(newValue: boolean) { if (this.addedManually != newValue) { this.addedManually = newValue; this.MarkAsDirty("AddedManually"); } }
       
	 
    private transportModeId: string;
    public get TransportModeId() { return this.transportModeId; }
    public set TransportModeId(newValue: string) { if (this.transportModeId != newValue) { this.transportModeId = newValue; this.MarkAsDirty("TransportModeId"); } }
       
	 
    private shippingAgentName: string;
    public get ShippingAgentName() { return this.shippingAgentName; }
    public set ShippingAgentName(newValue: string) { if (this.shippingAgentName != newValue) { this.shippingAgentName = newValue; this.MarkAsDirty("ShippingAgentName"); } }
       
	 
    private cityName: string;
    public get CityName() { return this.cityName; }
    public set CityName(newValue: string) { if (this.cityName != newValue) { this.cityName = newValue; this.MarkAsDirty("CityName"); } }
       
	 
    private countryId: string;
    public get CountryId() { return this.countryId; }
    public set CountryId(newValue: string) { if (this.countryId != newValue) { this.countryId = newValue; this.MarkAsDirty("CountryId"); } }
       
	 
    private countryCode: string;
    public get CountryCode() { return this.countryCode; }
    public set CountryCode(newValue: string) { if (this.countryCode != newValue) { this.countryCode = newValue; this.MarkAsDirty("CountryCode"); } }
       
	 
    private countryName: string;
    public get CountryName() { return this.countryName; }
    public set CountryName(newValue: string) { if (this.countryName != newValue) { this.countryName = newValue; this.MarkAsDirty("CountryName"); } }
       
	 
    private searchFields: string;
    public get SearchFields() { return this.searchFields; }
    public set SearchFields(newValue: string) { if (this.searchFields != newValue) { this.searchFields = newValue; this.MarkAsDirty("SearchFields"); } }
       
	 
    private isHybrid: boolean;
    public get IsHybrid() { return this.isHybrid; }
    public set IsHybrid(newValue: boolean) { if (this.isHybrid != newValue) { this.isHybrid = newValue; this.MarkAsDirty("IsHybrid"); } }
       
	 
    private isExternal: boolean;
    public get IsExternal() { return this.isExternal; }
    public set IsExternal(newValue: boolean) { if (this.isExternal != newValue) { this.isExternal = newValue; this.MarkAsDirty("IsExternal"); } }
       
	 
    private primaryContactId: string;
    public get PrimaryContactId() { return this.primaryContactId; }
    public set PrimaryContactId(newValue: string) { if (this.primaryContactId != newValue) { this.primaryContactId = newValue; this.MarkAsDirty("PrimaryContactId"); } }
       
	 
    private isFirstContactToAdd: boolean;
    public get IsFirstContactToAdd() { return this.isFirstContactToAdd; }
    public set IsFirstContactToAdd(newValue: boolean) { if (this.isFirstContactToAdd != newValue) { this.isFirstContactToAdd = newValue; this.MarkAsDirty("IsFirstContactToAdd"); } }
       
	 
    private enableConsolidationInvoices: boolean;
    public get EnableConsolidationInvoices() { return this.enableConsolidationInvoices; }
    public set EnableConsolidationInvoices(newValue: boolean) { if (this.enableConsolidationInvoices != newValue) { this.enableConsolidationInvoices = newValue; this.MarkAsDirty("EnableConsolidationInvoices"); } }
       
	 
    private iRSPlace: string;
    public get IRSPlace() { return this.iRSPlace; }
    public set IRSPlace(newValue: string) { if (this.iRSPlace != newValue) { this.iRSPlace = newValue; this.MarkAsDirty("IRSPlace"); } }
       
	 
    private iRSNumber: string;
    public get IRSNumber() { return this.iRSNumber; }
    public set IRSNumber(newValue: string) { if (this.iRSNumber != newValue) { this.iRSNumber = newValue; this.MarkAsDirty("IRSNumber"); } }
       
	 
    private isINTTRARegistered: boolean;
    public get IsINTTRARegistered() { return this.isINTTRARegistered; }
    public set IsINTTRARegistered(newValue: boolean) { if (this.isINTTRARegistered != newValue) { this.isINTTRARegistered = newValue; this.MarkAsDirty("IsINTTRARegistered"); } }
       
	 
    private iNTTRARegistrationNotes: string;
    public get INTTRARegistrationNotes() { return this.iNTTRARegistrationNotes; }
    public set INTTRARegistrationNotes(newValue: string) { if (this.iNTTRARegistrationNotes != newValue) { this.iNTTRARegistrationNotes = newValue; this.MarkAsDirty("INTTRARegistrationNotes"); } }
       
	 
    private iNTTRAUpdatesShipment: boolean;
    public get INTTRAUpdatesShipment() { return this.iNTTRAUpdatesShipment; }
    public set INTTRAUpdatesShipment(newValue: boolean) { if (this.iNTTRAUpdatesShipment != newValue) { this.iNTTRAUpdatesShipment = newValue; this.MarkAsDirty("INTTRAUpdatesShipment"); } }
       
	 
    private primaryContactName: string;
    public get PrimaryContactName() { return this.primaryContactName; }
    public set PrimaryContactName(newValue: string) { if (this.primaryContactName != newValue) { this.primaryContactName = newValue; this.MarkAsDirty("PrimaryContactName"); } }
       
	 
    private primaryContactEmail: string;
    public get PrimaryContactEmail() { return this.primaryContactEmail; }
    public set PrimaryContactEmail(newValue: string) { if (this.primaryContactEmail != newValue) { this.primaryContactEmail = newValue; this.MarkAsDirty("PrimaryContactEmail"); } }
       
	 
    private primaryContactPhone: string;
    public get PrimaryContactPhone() { return this.primaryContactPhone; }
    public set PrimaryContactPhone(newValue: string) { if (this.primaryContactPhone != newValue) { this.primaryContactPhone = newValue; this.MarkAsDirty("PrimaryContactPhone"); } }
       
	 
    private card: any;
    public get Card() { return this.card; }
    public set Card(newValue: any) { if (this.card != newValue) { this.card = newValue; this.MarkAsDirty("Card"); } }
       
	 
     
	private cardExternalCodeByCurrencies: CardExternalCodeByCurrencyPM[];
    get  CardExternalCodeByCurrencies() {
        if (this.cardExternalCodeByCurrencies == null) {
            this.cardExternalCodeByCurrencies = [];
        }

        return this.cardExternalCodeByCurrencies;
    }
    set  CardExternalCodeByCurrencies(newValue: CardExternalCodeByCurrencyPM[]) {
        if (this.cardExternalCodeByCurrencies != newValue) {
            this.cardExternalCodeByCurrencies = newValue;
        }
    }
    public AddCardExternalCodeByCurrencyPM(item: CardExternalCodeByCurrencyPM) {
        if (item != null) {
            var index = this.CardExternalCodeByCurrencies.indexOf(item);
            if (index == -1) {

                item.EntityParentPM = this;

                this. CardExternalCodeByCurrencies.push(item);
                this.MarkAsDirty();
            }
        }
    }
    public RemoveCardExternalCodeByCurrencyPM(item: CardExternalCodeByCurrencyPM) {
        if (item != null) {
            var index = this.CardExternalCodeByCurrencies.indexOf(item);
            if (index > -1) {
                this. CardExternalCodeByCurrencies.splice(index, 1);
                this.MarkAsDirty();
            }
        }
    }
	    //public CardExternalCodeByCurrencies: Array<CardExternalCodeByCurrencyPMPM>= [];
     private externalAccountingBusinessArea: string;
    public get ExternalAccountingBusinessArea() { return this.externalAccountingBusinessArea; }
    public set ExternalAccountingBusinessArea(newValue: string) { if (this.externalAccountingBusinessArea != newValue) { this.externalAccountingBusinessArea = newValue; this.MarkAsDirty("ExternalAccountingBusinessArea"); } }
       
	 
    private paymentMethodCode: string;
    public get PaymentMethodCode() { return this.paymentMethodCode; }
    public set PaymentMethodCode(newValue: string) { if (this.paymentMethodCode != newValue) { this.paymentMethodCode = newValue; this.MarkAsDirty("PaymentMethodCode"); } }
       
	 
    private externalId2: string;
    public get ExternalId2() { return this.externalId2; }
    public set ExternalId2(newValue: string) { if (this.externalId2 != newValue) { this.externalId2 = newValue; this.MarkAsDirty("ExternalId2"); } }
       
	 
    private sATForeignRFC: string;
    public get SATForeignRFC() { return this.sATForeignRFC; }
    public set SATForeignRFC(newValue: string) { if (this.sATForeignRFC != newValue) { this.sATForeignRFC = newValue; this.MarkAsDirty("SATForeignRFC"); } }
       
	 
    private metodoPagoCode: string;
    public get MetodoPagoCode() { return this.metodoPagoCode; }
    public set MetodoPagoCode(newValue: string) { if (this.metodoPagoCode != newValue) { this.metodoPagoCode = newValue; this.MarkAsDirty("MetodoPagoCode"); } }
       
	 
    private usoCFDICode: string;
    public get UsoCFDICode() { return this.usoCFDICode; }
    public set UsoCFDICode(newValue: string) { if (this.usoCFDICode != newValue) { this.usoCFDICode = newValue; this.MarkAsDirty("UsoCFDICode"); } }
       
	 
    private imageDetailId: string;
    public get ImageDetailId() { return this.imageDetailId; }
    public set ImageDetailId(newValue: string) { if (this.imageDetailId != newValue) { this.imageDetailId = newValue; this.MarkAsDirty("ImageDetailId"); } }
       
	 
    private cBSA: string;
    public get CBSA() { return this.cBSA; }
    public set CBSA(newValue: string) { if (this.cBSA != newValue) { this.cBSA = newValue; this.MarkAsDirty("CBSA"); } }
       
	 
    private cAAT: string;
    public get CAAT() { return this.cAAT; }
    public set CAAT(newValue: string) { if (this.cAAT != newValue) { this.cAAT = newValue; this.MarkAsDirty("CAAT"); } }
       
	 
    private gLAccountId: string;
    public get GLAccountId() { return this.gLAccountId; }
    public set GLAccountId(newValue: string) { if (this.gLAccountId != newValue) { this.gLAccountId = newValue; this.MarkAsDirty("GLAccountId"); } }
       
	 
    private accountingVATSplit: boolean;
    public get AccountingVATSplit() { return this.accountingVATSplit; }
    public set AccountingVATSplit(newValue: boolean) { if (this.accountingVATSplit != newValue) { this.accountingVATSplit = newValue; this.MarkAsDirty("AccountingVATSplit"); } }
       
	 
    private uploadingUniqueKey: string;
    public get UploadingUniqueKey() { return this.uploadingUniqueKey; }
    public set UploadingUniqueKey(newValue: string) { if (this.uploadingUniqueKey != newValue) { this.uploadingUniqueKey = newValue; this.MarkAsDirty("UploadingUniqueKey"); } }
       
	 
    private gLAccountNumber: string;
    public get GLAccountNumber() { return this.gLAccountNumber; }
    public set GLAccountNumber(newValue: string) { if (this.gLAccountNumber != newValue) { this.gLAccountNumber = newValue; this.MarkAsDirty("GLAccountNumber"); } }
       
	 
    private billToId: string;
    public get BillToId() { return this.billToId; }
    public set BillToId(newValue: string) { if (this.billToId != newValue) { this.billToId = newValue; this.MarkAsDirty("BillToId"); } }
       
	 

    public OldEntityPM: ShippingLinePM;
		
    public IsDirty: boolean;
    public DisableMarkAsDirty: boolean = false;
    MarkAsDirty(propertyName:string = null) {
       if(!this.DisableMarkAsDirty)
       {
        this.IsDirty = true;
		  	
        if (propertyName != null) {
            this.PropertyChanged.emit(new PropertyChangedArgs(propertyName,this));
            ServiceLocator.RulesValidator.ApplyEntityChangedRules(propertyName, this, "ShippingLine");
           
        }
	 }
    }
    private MyClone: ShippingLinePM;

    public CloneMe() {
        ServiceHelper.CloneEntityPM(this);
    }

    public RejectChanges() {
        ServiceHelper.RejectEntityPMChanges(this);
    }

}