
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
 
namespace AmitalCloud.Infrastructure.Application.CloseTables
{
    public struct DirectionValues
    {
        public const string CustomsImport = "C";
        public const string Domestic = "D";
        public const string Drop = "R";
        public const string Export = "E";
        public const string Import = "I";
    }
 }
 
