//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TariffVersionList {
   
	TariffId: string;
	Tenant: number;
	CreatedByUserId: string;
	SearchFields: string;
	StartDate: Date;
	ExpirationDate: Date;
	Version: number;
	IsDraft: boolean;
	ApproveDate: Date;
	
}
 