//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> C:\amital_main\Logitude\Logitude.Accounting.MetaData\AutoGenerators\AccountingClassesGenerator.tt
//---
using Simplog.Data.CommonDataModel.EntityPOCOs;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Simplog.Data.InfrastructureModel.EntityPOCOs;
using System.Data.Entity.ModelConfiguration;
using POCO = Logitude.Accounting.Data.EntityPOCOs;
using Logitude.Accounting.Data;
 
namespace Logitude.Accounting.Data.EntityMapping
{
 
    public class InterestReportLineMap : EntityTypeConfiguration<POCO.InterestReportLine>
    {
	    string dbms;
        public InterestReportLineMap()
        { 
				this.ToTable("InterestReportLines");
		
		    this.HasKey(t => new { t.InterestReportId, t.InterestTransactionId });
	 
            this.Property(t => t.Tenant).HasColumnName("Tenant");

            this.Property(t => t.InterestReportId).HasColumnName("InterestReportId").IsRequired().HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.InterestTransactionId).HasColumnName("InterestTransactionId").IsRequired().HasMaxLength(15).IsUnicode(false);
        }
    }
}
	 