<xs:schema
  attributeFormDefault="unqualified"
  elementFormDefault="qualified"
  xmlns:GCCSCargoImp="http://www.champ.aero/GCCS/CargoXML"
  targetNamespace="http://www.champ.aero/GCCS/CargoXML"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  version="1.0"
  >
  
  <xs:include schemaLocation="common_avail.xsd"/>

  <xs:complexType name="ScheduleAndAvailabilityInformationAnswer">
    <xs:sequence>
      <xs:element name="StandardMessageIdentification" type="GCCSCargoImp:StandardMessageIdentification"/>
      <xs:element name="ScheduleAndAvailabilityInformationRequestDetails" type="GCCSCargoImp:ScheduleAndAvailabilityInformationRequestDetails"/>
      <xs:element name="ScheduleInformationAnswerHeader" type="GCCSCargoImp:ScheduleInformationAnswerHeader" minOccurs="0"/>
      <xs:element name="ScheduleInformation" type="GCCSCargoImp:ScheduleInformation" maxOccurs="99"/>
      <xs:element name="ReasonForNoDisplay" type="GCCSCargoImp:ReasonForNoDisplay" minOccurs="0"/>
      <xs:element name="OtherServiceInformation" type="GCCSCargoImp:OtherServiceInformationEntry" minOccurs="0" maxOccurs="2"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScheduleInformation">
    <xs:sequence>
      <xs:element name="ScheduleAndAvailabilityInformationAnswerDetails" type="GCCSCargoImp:ScheduleAndAvailabilityInformationAnswerDetails"/>
      <xs:element name="AvailabilitySupplementaryDetails" type="GCCSCargoImp:AvailabilitySupplementaryDetails" minOccurs="0" maxOccurs="10"/>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

