using Logitude.BL.CommonDataModel.EntityQueries;
using Logitude.BL.ShipmentsModel.EntityPMs;
using Logitude.Server.Tools.Helpers;
using Simplog.Data.ShipmentsModel.EntityPOCOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Logitude.BL.ShipmentsModel.Tools.DataMapping
{
    public partial class ShipmentMapping
    {
        private static CardQuery cardQuery;
        public static void MapContainer(ContainerPM containerPM, Container container, bool isNewEntity)
        {
            if (isNewEntity)
            {
                container.Id = containerPM.Id;
                container.Tenant = containerPM.Tenant;
                container.CreateDate = containerPM.CreateDate;
                container.CreatedByUserId = containerPM.CreatedByUserId;
            }

            container.UpdateDate = containerPM.UpdateDate;
            container.UpdatedByUserId = containerPM.UpdatedByUserId;
            container.MainCarriageCarrierId = containerPM.MainCarriageCarrierId;
            container.MainCarriageCarrierNumber = containerPM.MainCarriageCarrierNumber;
            container.MainCarriageATA = containerPM.MainCarriageATA;
            container.MainCarriageATD = containerPM.MainCarriageATD;
            container.MainCarriageETA = containerPM.MainCarriageETA;
            container.MainCarriageETD = containerPM.MainCarriageETD;
            container.MainCarriageVesselId = containerPM.MainCarriageVesselId;
            container.DischargeDate = containerPM.DischargeDate;
            container.Master = containerPM.Master;
            container.ShipmentPackagesId = containerPM.ShipmentPackagesId;
            container.ContainerNumber = containerPM.ContainerNumber;
            container.ShipmentId = containerPM.ShipmentId;
            container.ActualEmptyPickupDate = containerPM.ActualEmptyPickupDate;
            container.EstimatedEmptyPickupDate = containerPM.EstimatedEmptyPickupDate;
            container.CurrentStatus = containerPM.CurrentStatus;
            container.CurrentStatusDate = containerPM.CurrentStatusDate;
            container.HasContainerException = containerPM.HasContainerException;
            container.CurrentLocation = containerPM.CurrentLocation;
            container.EmptyPickupLocation = containerPM.EmptyPickupLocation;
            container.DepartureLocation = containerPM.DepartureLocation;
            container.DestinationLocation = containerPM.DestinationLocation;
            container.ShipmentFirstPickupFrom = containerPM.ShipmentFirstPickupFrom;
            container.ShipmentFirstPickupTo = containerPM.ShipmentFirstPickupTo;
            container.ShipmentPreCarriageFromId = containerPM.ShipmentPreCarriageFromId;
            container.ShipmentPreCarriageToId = containerPM.ShipmentPreCarriageToId;
            container.ShipmentMainCarriageFromId = containerPM.ShipmentMainCarriageFromId;
            container.ShipmentMainCarriageToId = containerPM.ShipmentMainCarriageToId;
            container.ShipmentTransshipment1FromId = containerPM.ShipmentTransshipment1FromId;
            container.ShipmentTransshipment1ToId = containerPM.ShipmentTransshipment1ToId;
            container.ShipmentTransshipment2FromId = containerPM.ShipmentTransshipment2FromId;
            container.ShipmentTransshipment2ToId = containerPM.ShipmentTransshipment2ToId;
            container.ShipmentTransshipment3FromId = containerPM.ShipmentTransshipment3FromId;
            container.ShipmentTransshipment3ToId = containerPM.ShipmentTransshipment3ToId;
            container.ShipmentOnCarriageFromId = containerPM.ShipmentOnCarriageFromId;
            container.ShipmentOnCarriageToId = containerPM.ShipmentOnCarriageToId;
            container.ShipmentLastDeliveryFrom = containerPM.ShipmentLastDeliveryFrom;
            container.ShipmentLastDeliveryTo = containerPM.ShipmentLastDeliveryTo;
            container.OnCarriageLocation = containerPM.OnCarriageLocation;
            container.OnCarriageETD = containerPM.OnCarriageETD;
            container.OnCarriageATD = containerPM.OnCarriageATD;
            container.POLLocation = containerPM.POLLocation;
            container.EstimatedPOLArrival = containerPM.EstimatedPOLArrival;
            container.ActualPOLArrival = containerPM.ActualPOLArrival;
            container.EstimatedPOLLoaded = containerPM.EstimatedPOLLoaded;
            container.ActualPOLLoaded = containerPM.ActualPOLLoaded;
            container.EstimatedPOLVesselDeparture = containerPM.EstimatedPOLVesselDeparture;
            container.ActualPOLVesselDeparture = containerPM.ActualPOLVesselDeparture;
            container.TransshipmentCount = containerPM.TransshipmentCount;
            container.Transshipment1Location = containerPM.Transshipment1Location;
            container.EstimatedTrans1VesselArrival = containerPM.EstimatedTrans1VesselArrival;
            container.ActualTransshipment1VesselArrival = containerPM.ActualTransshipment1VesselArrival;
            container.EstimatedTransshipment1Discharge = containerPM.EstimatedTransshipment1Discharge;
            container.ActualTransshipment1Discharge = containerPM.ActualTransshipment1Discharge;
            container.EstimatedTransshipment1Loaded = containerPM.EstimatedTransshipment1Loaded;
            container.ActualTransshipment1Loaded = containerPM.ActualTransshipment1Loaded;
            container.EstimatedTrans1VesselDeparture = containerPM.EstimatedTrans1VesselDeparture;
            container.ActualTrans1VesselDeparture = containerPM.ActualTrans1VesselDeparture;
            container.Transshipment2Location = containerPM.Transshipment2Location;
            container.EstimatedTrans2VesselArrival = containerPM.EstimatedTrans2VesselArrival;
            container.ActualTransshipment2VesselArrival = containerPM.ActualTransshipment2VesselArrival;
            container.EstimatedTransshipment2Discharge = containerPM.EstimatedTransshipment2Discharge;
            container.ActualTransshipment2Discharge = containerPM.ActualTransshipment2Discharge;
            container.EstimatedTransshipment2Loaded = containerPM.EstimatedTransshipment2Loaded;
            container.ActualTransshipment2Loaded = containerPM.ActualTransshipment2Loaded;
            container.EstimatedTrans2VesselDeparture = containerPM.EstimatedTrans2VesselDeparture;
            container.ActualTrans2VesselDeparture = containerPM.ActualTrans2VesselDeparture;
            container.Transshipment3Location = containerPM.Transshipment3Location;
            container.EstimatedTrans3VesselArrival = containerPM.EstimatedTrans3VesselArrival;
            container.ActualTransshipment3VesselArrival = containerPM.ActualTransshipment3VesselArrival;
            container.EstimatedTransshipment3Discharge = containerPM.EstimatedTransshipment3Discharge;
            container.ActualTransshipment3Discharge = containerPM.ActualTransshipment3Discharge;
            container.EstimatedTransshipment3Loaded = containerPM.EstimatedTransshipment3Loaded;
            container.ActualTransshipment3Loaded = containerPM.ActualTransshipment3Loaded;
            container.EstimatedTrans3VesselDeparture = containerPM.EstimatedTrans3VesselDeparture;
            container.ActualTrans3VesselDeparture = containerPM.ActualTrans3VesselDeparture;
            container.Transshipment4Location = containerPM.Transshipment4Location;
            container.EstimatedTrans4VesselArrival = containerPM.EstimatedTrans4VesselArrival;
            container.ActualTransshipment4VesselArrival = containerPM.ActualTransshipment4VesselArrival;
            container.EstimatedTransshipment4Discharge = containerPM.EstimatedTransshipment4Discharge;
            container.ActualTransshipment4Discharge = containerPM.ActualTransshipment4Discharge;
            container.EstimatedTransshipment4Loaded = containerPM.EstimatedTransshipment4Loaded;
            container.ActualTransshipment4Loaded = containerPM.ActualTransshipment4Loaded;
            container.EstimatedTrans4VesselDeparture = containerPM.EstimatedTrans4VesselDeparture;
            container.ActualTrans4VesselDeparture = containerPM.ActualTrans4VesselDeparture;
            container.Leg1Vessel = containerPM.Leg1Vessel;
            container.Leg1Voyage = containerPM.Leg1Voyage;
            container.Leg2Vessel = containerPM.Leg2Vessel;
            container.Leg2Voyage = containerPM.Leg2Voyage;
            container.Leg3Vessel = containerPM.Leg3Vessel;
            container.Leg3Voyage = containerPM.Leg3Voyage;
            container.Leg4Vessel = containerPM.Leg4Vessel;
            container.Leg4Voyage = containerPM.Leg4Voyage;
            container.Leg5Vessel = containerPM.Leg5Vessel;
            container.Leg5Voyage = containerPM.Leg5Voyage;
            container.PODLocation = containerPM.PODLocation;
            container.EstimatedPODVesselArrival = containerPM.EstimatedPODVesselArrival;
            container.ActualPODVesselArrival = containerPM.ActualPODVesselArrival;
            container.EstimatedPODDischarge = containerPM.EstimatedPODDischarge;
            container.ActualPODDischarge = containerPM.ActualPODDischarge;
            container.EstimatedPODDeparture = containerPM.EstimatedPODDeparture;
            container.ActualPODDeparture = containerPM.ActualPODDeparture;
            container.PreCarriageLocation = containerPM.PreCarriageLocation;
            container.PreCarriageATD = containerPM.PreCarriageATD;
            container.PreCarriageETD = containerPM.PreCarriageETD;
            container.LIFLocation = containerPM.LIFLocation;
            container.EstimatedLIFArrival = containerPM.EstimatedLIFArrival;
            container.ActualLIFArrival = containerPM.ActualLIFArrival;
            container.EstimatedOnCarriageDeparture = containerPM.EstimatedOnCarriageDeparture;
            container.ActualOnCarriageDeparture = containerPM.ActualOnCarriageDeparture;
            container.GateIn = containerPM.GateIn;
            container.GateOut = containerPM.GateOut;
            container.EmptyReturnLocation = containerPM.EmptyReturnLocation;
            container.EstimatedEmptyReturn = containerPM.EstimatedEmptyReturn;
            container.ActualEmptyReturn = containerPM.ActualEmptyReturn;
            container.CustomsReleaseState = containerPM.CustomsReleaseState;
            container.CustomsReleaseDate = containerPM.CustomsReleaseDate;
            container.CarrierReleaseState = containerPM.CarrierReleaseState;
            container.CarrierReleaseDate = containerPM.CarrierReleaseDate;
            container.AvailablityDate = containerPM.AvailablityDate;
            container.AvailabilityLocation = containerPM.AvailabilityLocation;
            container.FreeDays = containerPM.FreeDays;
            container.LastFreeDayDate = containerPM.LastFreeDayDate;
            container.ShipmentStatusId = containerPM.ShipmentStatusId;
            container.EmptyPickupLocationPortId = containerPM.EmptyPickupLocationPortId;
            container.PreCarriageLocationPortId = containerPM.PreCarriageLocationPortId;
            container.EmptyReturnLocationPortId = containerPM.EmptyReturnLocationPortId;
            container.AvailabilityLocationPortId = containerPM.AvailabilityLocationPortId;
            container.OnCarriageLocationPortId = containerPM.OnCarriageLocationPortId;
            container.LIFLocationPortId = containerPM.LIFLocationPortId;
            container.POLLocationPortId = containerPM.POLLocationPortId;
            container.PODLocationPortId = containerPM.PODLocationPortId;
            container.Transshipment1LocationPortId = containerPM.Transshipment1LocationPortId;
            container.Transshipment2LocationPortId = containerPM.Transshipment2LocationPortId;
            container.Transshipment3LocationPortId = containerPM.Transshipment3LocationPortId;
            container.Transshipment4LocationPortId = containerPM.Transshipment4LocationPortId;
            container.Field1 = containerPM.Field1 != null ? containerPM.Field1.Value : null;
            container.Field2 = containerPM.Field2 != null ? containerPM.Field2.Value : null;
            container.Field3 = containerPM.Field3 != null ? containerPM.Field3.Value : null;
            container.Field4 = containerPM.Field4 != null ? containerPM.Field4.Value : null;
            container.Field5 = containerPM.Field5 != null ? containerPM.Field5.Value : null;
            container.Field6 = containerPM.Field6 != null ? containerPM.Field6.Value : null;
            container.Field7 = containerPM.Field7 != null ? containerPM.Field7.Value : null;
            container.Field8 = containerPM.Field8 != null ? containerPM.Field8.Value : null;
            container.Field9 = containerPM.Field9 != null ? containerPM.Field9.Value : null;
            container.Field10 = containerPM.Field10 != null ? containerPM.Field10.Value : null;
            container.TerminalId = containerPM.TerminalId;
            container.TerminalAddress = containerPM.TerminalAddress; 
            container.TerminalPhone = containerPM.TerminalPhone;
            container.TerminalAddressId = containerPM.TerminalAddressId;
            container.ShipmentPickupETA = containerPM.ShipmentPickupETA;
            container.ShipmentPickupETD = containerPM.ShipmentPickupETD;
            container.ShipmentPickupATA = containerPM.ShipmentPickupATA;
            container.ShipmentPickupATD = containerPM.ShipmentPickupATD;
            container.ShipmentPreCarriageETA = containerPM.ShipmentPreCarriageETA;
            container.ShipmentPreCarriageETD = containerPM.ShipmentPreCarriageETD;
            container.ShipmentPreCarriageATA = containerPM.ShipmentPreCarriageATA;
            container.ShipmentPreCarriageATD = containerPM.ShipmentPreCarriageATD;
            container.ShipmentMainCarriageETA = containerPM.ShipmentMainCarriageETA;
            container.ShipmentMainCarriageETD = containerPM.ShipmentMainCarriageETD;
            container.ShipmentMainCarriageATA = containerPM.ShipmentMainCarriageATA;
            container.ShipmentMainCarriageATD = containerPM.ShipmentMainCarriageATD;
            container.ShipmentTransshipment1ETA = containerPM.ShipmentTransshipment1ETA;
            container.ShipmentTransshipment1ETD = containerPM.ShipmentTransshipment1ETD;
            container.ShipmentTransshipment1ATA = containerPM.ShipmentTransshipment1ATA;
            container.ShipmentTransshipment1ATD = containerPM.ShipmentTransshipment1ATD;
            container.ShipmentTransshipment2ETA = containerPM.ShipmentTransshipment2ETA;
            container.ShipmentTransshipment2ETD = containerPM.ShipmentTransshipment2ETD;
            container.ShipmentTransshipment2ATA = containerPM.ShipmentTransshipment2ATA;
            container.ShipmentTransshipment2ATD = containerPM.ShipmentTransshipment2ATD;
            container.ShipmentTransshipment3ETA = containerPM.ShipmentTransshipment3ETA;
            container.ShipmentTransshipment3ETD = containerPM.ShipmentTransshipment3ETD;
            container.ShipmentTransshipment3ATA = containerPM.ShipmentTransshipment3ATA;
            container.ShipmentTransshipment3ATD = containerPM.ShipmentTransshipment3ATD;
            container.ShipmentOnCarriageETA = containerPM.ShipmentOnCarriageETA;
            container.ShipmentOnCarriageETD = containerPM.ShipmentOnCarriageETD;
            container.ShipmentOnCarriageATA = containerPM.ShipmentOnCarriageATA;
            container.ShipmentOnCarriageATD = containerPM.ShipmentOnCarriageATD;
            container.ShipmentDeliveryETA = containerPM.ShipmentDeliveryETA;
            container.ShipmentDeliveryETD = containerPM.ShipmentDeliveryETD;
            container.ShipmentDeliveryATA = containerPM.ShipmentDeliveryATA;
            container.ShipmentDeliveryATD = containerPM.ShipmentDeliveryATD;
            container.ShipmentOriginAgentId = containerPM.ShipmentOriginAgentId;
            container.ShipmentDestinationAgentId = containerPM.ShipmentDestinationAgentId;
            container.ShipmentNumber = containerPM.ShipmentNumber;
            container.ContainersCount = containerPM.ContainersCount;
            container.HandlerId = containerPM.HandlerId;
            container.CustomerId = containerPM.CustomerId;
            container.OPClosed = containerPM.OPClosed;
            container.ShipmentTypeId = containerPM.ShipmentTypeId;
            container.ShipmentCreateDate = containerPM.ShipmentCreateDate;
            container.PODReceivedOnDate = containerPM.PODReceivedOnDate;
            container.IsAutomaticUpdates = containerPM.IsAutomaticUpdates;
            container.IsClosed = containerPM.IsClosed;
            container.ClosedDate = containerPM.ClosedDate;
            container.StatusId = containerPM.StatusId;
            container.IsCancelled = containerPM.IsCancelled;
            container.CancelledDate = containerPM.CancelledDate;

            BuildSearchField(containerPM, container);
        }

        public static void BuildSearchField(ContainerPM containerPM, Container container)
        {
            string mySearchFields = "";

            MethodHelper.AddToSearchFields(ref mySearchFields, containerPM.ContainerNumber);
            MethodHelper.AddToSearchFields(ref mySearchFields, containerPM.Master);
            MethodHelper.AddToSearchFields(ref mySearchFields, containerPM.MainCarriageCarrierNumber);
            MethodHelper.AddToSearchFields(ref mySearchFields, containerPM.CarrierName);

            containerPM.SearchFields = mySearchFields;
            container.SearchFields = mySearchFields;
        }
    }
}
