
--Apply It OnlY if Not Exist
ALTER TABLE [dbo].[Queries] ADD  CONSTRAINT [UQ_UniqueCode] UNIQUE NONCLUSTERED ([UniqueCode] ASC)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]

