export interface AirLineDetails {
    Code: string,
    ICAO: string,
    Name: string,
    Prefix: string,
    LocalName: string,
    Notes: string,
    InactiveAirline: string,
    AddressName: string,
    AddressCity: string,
    AddressCountry: string,
    AddressState: string,
    TariffPartnerCode: string,
    TariffPort: string,
    SurchargeTariffFromDate: string,
    SurchargeTariffToDate: string,
    TariffChargeType: string,
    TariffChargeUnitPrice: string,
    AdaptionSpecialHandlingCode: string,
    AdaptionSpecialHandlingName: string
}