//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Threading.Tasks;
using System.Data.Entity.ModelConfiguration;
using POCO = AmitalCloud.Infrastructure.Domain.EntityPOCOs;
 
namespace AmitalCloud.Infrastructure.Domain.EntityMapping
{
 
    public class DWObjectTableMap : EntityTypeConfiguration<POCO.DWObjectTable>
    {
	    string dbms;
        public DWObjectTableMap()
        { 
				this.ToTable("DWObjectTables");
		
		    this.HasKey(t => new { t.Code });
	 
            this.Property(t => t.Id).HasColumnName("Id").IsRequired().HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.Tenant).HasColumnName("Tenant");

            this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(50).IsUnicode(false);

            this.Property(t => t.Code).HasColumnName("Code").IsRequired().HasMaxLength(50).IsUnicode(false);

            this.Property(t => t.TypeCode).HasColumnName("TypeCode").IsRequired().HasMaxLength(15).IsUnicode(false);

            this.Property(t => t.IsClosed).HasColumnName("IsClosed");

            this.Property(t => t.DefaultFilterBy).HasColumnName("DefaultFilterBy").HasMaxLength(50).IsUnicode(false);

            this.Property(t => t.DataViewName).HasColumnName("DataViewName").HasMaxLength(200).IsUnicode(true);

            this.Property(t => t.HasPivotColumn).HasColumnName("HasPivotColumn");

            this.Property(t => t.PivotFieldCode).HasColumnName("PivotFieldCode").HasMaxLength(50).IsUnicode(false);

            this.Property(t => t.AdditionalFactCode).HasColumnName("AdditionalFactCode").HasMaxLength(50).IsUnicode(false);

            this.Property(t => t.AdditionalFactForeignKey).HasColumnName("AdditionalFactForeignKey").HasMaxLength(100).IsUnicode(false);

            this.Property(t => t.RecordType).HasColumnName("RecordType").HasMaxLength(100).IsUnicode(false);

            this.Property(t => t.ParentFactCode).HasColumnName("ParentFactCode").HasMaxLength(50).IsUnicode(false);

            this.Property(t => t.DisplayName).HasColumnName("DisplayName").HasMaxLength(100).IsUnicode(false);

            this.Property(t => t.IndexesXml).HasColumnName("IndexesXml").IsMaxLength().IsUnicode(true);

            this.Property(t => t.ObjectTableName).HasColumnName("ObjectTableName").HasMaxLength(50).IsUnicode(false);

            this.Property(t => t.MaxNumberOfCustomFields).HasColumnName("MaxNumberOfCustomFields");

            this.Property(t => t.HasCustomFields).HasColumnName("HasCustomFields");

            this.Property(t => t.AdditionalFactRelationType).HasColumnName("AdditionalFactRelationType").HasMaxLength(100).IsUnicode(false);

            this.Property(t => t.AdditionalConditions).HasColumnName("AdditionalConditions").HasMaxLength(200).IsUnicode(false);

            this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(2000).IsUnicode(true);
        }
    }
}
	 