<!ELEMENT LOGIMASTERCOUR (LogitudeMasterCourier*)>
<!ELEMENT LogitudeMasterCourier (AirlineId?, MAWB?, HAWB?, EstimatedArrivalDate?, DepartureDate?, GatewayPortCode?, OriginPortCode?, PackageQuantityTy?, GrossMassMeasure?, Tenant?, FlightNumber?, WeightValueCode?, StorageSiteCode?, IntegratorIndex?, NoOfCourierHawb?)>
<!ELEMENT AirlineId (#PCDATA)>
<!ELEMENT MAWB (#PCDATA)>
<!ELEMENT HAWB (#PCDATA)>
<!ELEMENT EstimatedArrivalDate (#PCDATA)>
<!ELEMENT DepartureDate (#PCDATA)>
<!ELEMENT GatewayPortCode (#PCDATA)>
<!ELEMENT OriginPortCode (#PCDATA)>
<!ELEMENT PackageQuantityTy (#PCDATA)>
<!ELEMENT GrossMassMeasure (#PCDATA)>
<!ELEMENT Tenant (#PCDATA)>
<!ELEMENT FlightNumber (#PCDATA)>
<!ELEMENT WeightValueCode (#PCDATA)>
<!ELEMENT StorageSiteCode (#PCDATA)>
<!ELEMENT IntegratorIndex (#PCDATA)>
<!ELEMENT NoOfCourierHawb (#PCDATA)>