<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/LOGIMASTERCOUR" elementFormDefault="qualified" targetNamespace="http://tempuri.org/LOGIMASTERCOUR" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LOGIMASTERCOUR">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="LogitudeMasterCourier" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="WAYBILLS" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LogitudeMasterCourier">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="AirlineId" />
        <xs:element minOccurs="0" maxOccurs="1" ref="MAWB" />
        <xs:element minOccurs="0" maxOccurs="1" ref="HAWB" />
        <xs:element minOccurs="0" maxOccurs="1" ref="EstimatedArrivalDate" />
        <xs:element minOccurs="0" maxOccurs="1" ref="DepartureDate" />
        <xs:element minOccurs="0" maxOccurs="1" ref="GatewayPortCode" />
        <xs:element minOccurs="0" maxOccurs="1" ref="OriginPortCode" />
        <xs:element minOccurs="0" maxOccurs="1" ref="PackageQuantityTy" />
        <xs:element minOccurs="0" maxOccurs="1" ref="GrossMassMeasure" />
        <xs:element minOccurs="0" maxOccurs="1" ref="Tenant" />
        <xs:element minOccurs="0" maxOccurs="1" ref="FlightNumber" />
        <xs:element minOccurs="0" maxOccurs="1" ref="WeightValueCode" />
        <xs:element minOccurs="0" maxOccurs="1" ref="StorageSiteCode" />
        <xs:element minOccurs="0" maxOccurs="1" ref="IntegratorIndex" />
        <xs:element minOccurs="0" maxOccurs="1" ref="NoOfCourierHawb" />
        <xs:element minOccurs="0" maxOccurs="1" ref="TruckerId" />
        <xs:element minOccurs="0" maxOccurs="1" ref="PackageQuantityInMAWB" />
        <xs:element minOccurs="0" maxOccurs="1" ref="UnifreightLeadingFile" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="AirlineId" type="xs:string" />
  <xs:element name="MAWB" type="xs:string" />
  <xs:element name="HAWB" type="xs:string" />
  <xs:element name="EstimatedArrivalDate" type="xs:string" />
  <xs:element name="DepartureDate" type="xs:string" />
  <xs:element name="GatewayPortCode" type="xs:string" />
  <xs:element name="OriginPortCode" type="xs:string" />
  <xs:element name="PackageQuantityTy" type="xs:string" />
  <xs:element name="GrossMassMeasure" type="xs:string" />
  <xs:element name="Tenant" type="xs:string" />
  <xs:element name="FlightNumber" type="xs:string" />
  <xs:element name="WeightValueCode" type="xs:string" />
  <xs:element name="StorageSiteCode" type="xs:string" />
  <xs:element name="IntegratorIndex" type="xs:string" />
  <xs:element name="NoOfCourierHawb" type="xs:string" />
  <xs:element name="TruckerId" type="xs:string" />
  <xs:element name="PackageQuantityInMAWB" type="xs:string" />
  <xs:element name="UnifreightLeadingFile" type="xs:string" />
  <xs:element name="WAYBILLS">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="wb" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="wb" type="xs:string" />
</xs:schema>