<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <BaseOutputPath>..\Library\Bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AmitalCloud.Infrastructure.Model\AmitalCloud.Infrastructure.Model.csproj" />
    <ProjectReference Include="..\AmitalCloud.Infrastructure.Domain\AmitalCloud.Infrastructure.Domain.csproj" />
    <ProjectReference Include="..\AmitalCloud.Invoice.Domain\AmitalCloud.Invoice.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.ServiceModel.DomainServices.Server">
      <HintPath>..\..\packages\RIAServices.Server.4.2.0\lib\Net40\System.ServiceModel.DomainServices.Server.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
