using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Simplog.Data.ShipmentsModel.Repositories;
using Logitude.BL.ShipmentsModel.EntityLists;
using Logitude.BL.ShipmentsModel.EntityPMs;
using Simplog.Data.ShipmentsModel.EntityPOCOs;
using Logitude.BL.CommonDataModel.EntityPMs;
using Logitude.BL.CommonDataModel.EntityQueries;
using System.Data.Entity;

namespace Logitude.BL.ShipmentsModel.EntityQueries
{
    public class ContainerQuery
    {
        ContainerRepository repository;
        public ContainerQuery(int tenant)
        {
            repository = new ContainerRepository(tenant);
        }
        public ContainerQuery(ContainerRepository myRepository)
        {
            this.repository = myRepository;
        }

        public ContainerPM GetSinglePM(string id, int tenant)
        {
            ContainerPM result = null;
            Container entityPoco = repository.GetSingleContainer(id, tenant);
            if (entityPoco != null)
            {
                result = new ContainerPM()
                {
                    Id = entityPoco.Id,
                    Tenant = entityPoco.Tenant,
                    CreateDate = entityPoco.CreateDate,
                    CreatedByUserId = entityPoco.CreatedByUserId,
                    UpdateDate = entityPoco.UpdateDate,
                    UpdatedByUserId = entityPoco.UpdatedByUserId,
                    MainCarriageCarrierId = entityPoco.MainCarriageCarrierId,
                    MainCarriageCarrierNumber = entityPoco.MainCarriageCarrierNumber,
                    MainCarriageATA = entityPoco.MainCarriageATA,
                    MainCarriageATD = entityPoco.MainCarriageATD,
                    MainCarriageETA = entityPoco.MainCarriageETA,
                    MainCarriageETD = entityPoco.MainCarriageETD,
                    ContainerNumber = entityPoco.ContainerNumber,
                    MainCarriageVesselId = entityPoco.MainCarriageVesselId,
                    ShipmentPackagesId = entityPoco.ShipmentPackagesId,
                    SearchFields = entityPoco.SearchFields,
                    DischargeDate = entityPoco.DischargeDate,
                    Master = entityPoco.Master,
                    CarrierName = entityPoco.CarrierCard != null ? entityPoco.CarrierCard.EnglishName : "",
                    VesselName = entityPoco.VesselCard != null ? entityPoco.VesselCard.EnglishName : "",
                    ShipmentId = entityPoco.ShipmentId,
                    ActualEmptyPickupDate = entityPoco.ActualEmptyPickupDate,
                    EstimatedEmptyPickupDate = entityPoco.EstimatedEmptyPickupDate,
                    CurrentStatus = entityPoco.CurrentStatus,
                    CurrentStatusDate = entityPoco.CurrentStatusDate,
                    HasContainerException = entityPoco.HasContainerException,
                    CurrentLocation = entityPoco.CurrentLocation,
                    EmptyPickupLocation = entityPoco.EmptyPickupLocation,
                    DepartureLocation = entityPoco.DepartureLocation,
                    DestinationLocation = entityPoco.DestinationLocation,
                    ShipmentFirstPickupFrom = entityPoco.ShipmentFirstPickupFrom,
                    ShipmentFirstPickupTo = entityPoco.ShipmentFirstPickupTo,
                    ShipmentPreCarriageFromId = entityPoco.ShipmentPreCarriageFromId,
                    ShipmentPreCarriageToId = entityPoco.ShipmentPreCarriageToId,
                    ShipmentMainCarriageFromId = entityPoco.ShipmentMainCarriageFromId,
                    ShipmentMainCarriageToId = entityPoco.ShipmentMainCarriageToId,
                    ShipmentTransshipment1FromId = entityPoco.ShipmentTransshipment1FromId,
                    ShipmentTransshipment1ToId = entityPoco.ShipmentTransshipment1ToId,
                    ShipmentTransshipment2FromId = entityPoco.ShipmentTransshipment2FromId,
                    ShipmentTransshipment2ToId = entityPoco.ShipmentTransshipment2ToId,
                    ShipmentTransshipment3FromId = entityPoco.ShipmentTransshipment3FromId,
                    ShipmentTransshipment3ToId = entityPoco.ShipmentTransshipment3ToId,
                    ShipmentOnCarriageFromId = entityPoco.ShipmentOnCarriageFromId,
                    ShipmentOnCarriageToId = entityPoco.ShipmentOnCarriageToId,
                    ShipmentPreCarriageFrom = entityPoco.ShipmentPreCarriageFromPort != null ? entityPoco.ShipmentPreCarriageFromPort.CombinedCode : "",
                    ShipmentPreCarriageTo = entityPoco.ShipmentPreCarriageToPort != null ? entityPoco.ShipmentPreCarriageToPort.CombinedCode : "",
                    ShipmentMainCarriageFrom = entityPoco.ShipmentMainCarriageFromPort != null ? entityPoco.ShipmentMainCarriageFromPort.CombinedCode : "",
                    ShipmentMainCarriageTo = entityPoco.ShipmentMainCarriageToPort != null ? entityPoco.ShipmentMainCarriageToPort.CombinedCode : "",
                    ShipmentTransshipment1From = entityPoco.ShipmentTransshipment1FromPort != null ? entityPoco.ShipmentTransshipment1FromPort.CombinedCode : "",
                    ShipmentTransshipment1To = entityPoco.ShipmentTransshipment1ToPort != null ? entityPoco.ShipmentTransshipment1ToPort.CombinedCode : "",
                    ShipmentTransshipment2From = entityPoco.ShipmentTransshipment2FromPort != null ? entityPoco.ShipmentTransshipment2FromPort.CombinedCode : "",
                    ShipmentTransshipment2To = entityPoco.ShipmentTransshipment2ToPort != null ? entityPoco.ShipmentTransshipment2ToPort.CombinedCode : "",
                    ShipmentTransshipment3From = entityPoco.ShipmentTransshipment3FromPort != null ? entityPoco.ShipmentTransshipment3FromPort.CombinedCode : "",
                    ShipmentTransshipment3To = entityPoco.ShipmentTransshipment3ToPort != null ? entityPoco.ShipmentTransshipment3ToPort.CombinedCode : "",
                    ShipmentOnCarriageFrom = entityPoco.ShipmentOnCarriageFromPort != null ? entityPoco.ShipmentOnCarriageFromPort.CombinedCode : "",
                    ShipmentOnCarriageTo = entityPoco.ShipmentOnCarriageToPort != null ? entityPoco.ShipmentOnCarriageToPort.CombinedCode : "",
                    ShipmentLastDeliveryFrom = entityPoco.ShipmentLastDeliveryFrom,
                    ShipmentLastDeliveryTo = entityPoco.ShipmentLastDeliveryTo,
                    OriginLocation = entityPoco.OriginLocation,
                    EstimatedOriginPickup = entityPoco.EstimatedOriginPickup,
                    ActualOriginPickup = entityPoco.ActualOriginPickup,
                    POLLocation = entityPoco.POLLocation,
                    EstimatedPOLArrival = entityPoco.EstimatedPOLArrival,
                    ActualPOLArrival = entityPoco.ActualPOLArrival,
                    EstimatedPOLLoaded = entityPoco.EstimatedPOLLoaded,
                    ActualPOLLoaded = entityPoco.ActualPOLLoaded,
                    EstimatedPOLVesselDeparture = entityPoco.EstimatedPOLVesselDeparture,
                    ActualPOLVesselDeparture = entityPoco.ActualPOLVesselDeparture,
                    TransshipmentCount = entityPoco.TransshipmentCount,
                    Transshipment1Location = entityPoco.Transshipment1Location,
                    EstimatedTrans1VesselArrival = entityPoco.EstimatedTrans1VesselArrival,
                    ActualTransshipment1VesselArrival = entityPoco.ActualTransshipment1VesselArrival,
                    EstimatedTransshipment1Discharge = entityPoco.EstimatedTransshipment1Discharge,
                    ActualTransshipment1Discharge = entityPoco.ActualTransshipment1Discharge,
                    EstimatedTransshipment1Loaded = entityPoco.EstimatedTransshipment1Loaded,
                    ActualTransshipment1Loaded = entityPoco.ActualTransshipment1Loaded,
                    EstimatedTrans1VesselDeparture = entityPoco.EstimatedTrans1VesselDeparture,
                    ActualTrans1VesselDeparture = entityPoco.ActualTrans1VesselDeparture,
                    Transshipment2Location = entityPoco.Transshipment2Location,
                    EstimatedTrans2VesselArrival = entityPoco.EstimatedTrans2VesselArrival,
                    ActualTransshipment2VesselArrival = entityPoco.ActualTransshipment2VesselArrival,
                    EstimatedTransshipment2Discharge = entityPoco.EstimatedTransshipment2Discharge,
                    ActualTransshipment2Discharge = entityPoco.ActualTransshipment2Discharge,
                    EstimatedTransshipment2Loaded = entityPoco.EstimatedTransshipment2Loaded,
                    ActualTransshipment2Loaded = entityPoco.ActualTransshipment2Loaded,
                    EstimatedTrans2VesselDeparture = entityPoco.EstimatedTrans2VesselDeparture,
                    ActualTrans2VesselDeparture = entityPoco.ActualTrans2VesselDeparture,
                    Transshipment3Location = entityPoco.Transshipment3Location,
                    EstimatedTrans3VesselArrival = entityPoco.EstimatedTrans3VesselArrival,
                    ActualTransshipment3VesselArrival = entityPoco.ActualTransshipment3VesselArrival,
                    EstimatedTransshipment3Discharge = entityPoco.EstimatedTransshipment3Discharge,
                    ActualTransshipment3Discharge = entityPoco.ActualTransshipment3Discharge,
                    EstimatedTransshipment3Loaded = entityPoco.EstimatedTransshipment3Loaded,
                    ActualTransshipment3Loaded = entityPoco.ActualTransshipment3Loaded,
                    EstimatedTrans3VesselDeparture = entityPoco.EstimatedTrans3VesselDeparture,
                    ActualTrans3VesselDeparture = entityPoco.ActualTrans3VesselDeparture,
                    Transshipment4Location = entityPoco.Transshipment4Location,
                    EstimatedTrans4VesselArrival = entityPoco.EstimatedTrans4VesselArrival,
                    ActualTransshipment4VesselArrival = entityPoco.ActualTransshipment4VesselArrival,
                    EstimatedTransshipment4Discharge = entityPoco.EstimatedTransshipment4Discharge,
                    ActualTransshipment4Discharge = entityPoco.ActualTransshipment4Discharge,
                    EstimatedTransshipment4Loaded = entityPoco.EstimatedTransshipment4Loaded,
                    ActualTransshipment4Loaded = entityPoco.ActualTransshipment4Loaded,
                    EstimatedTrans4VesselDeparture = entityPoco.EstimatedTrans4VesselDeparture,
                    ActualTrans4VesselDeparture = entityPoco.ActualTrans4VesselDeparture,
                    Leg1Vessel = entityPoco.Leg1Vessel,
                    Leg1Voyage = entityPoco.Leg1Voyage,
                    Leg2Vessel = entityPoco.Leg2Vessel,
                    Leg2Voyage = entityPoco.Leg2Voyage,
                    Leg3Vessel = entityPoco.Leg3Vessel,
                    Leg3Voyage = entityPoco.Leg3Voyage,
                    Leg4Vessel = entityPoco.Leg4Vessel,
                    Leg4Voyage = entityPoco.Leg4Voyage,
                    Leg5Vessel = entityPoco.Leg5Vessel,
                    Leg5Voyage = entityPoco.Leg5Voyage,
                    PODLocation = entityPoco.PODLocation,
                    EstimatedPODVesselArrival = entityPoco.EstimatedPODVesselArrival,
                    ActualPODVesselArrival = entityPoco.ActualPODVesselArrival,
                    EstimatedPODDischarge = entityPoco.EstimatedPODDischarge,
                    ActualPODDischarge = entityPoco.ActualPODDischarge,
                    EstimatedPODDeparture = entityPoco.EstimatedPODDeparture,
                    ActualPODDeparture = entityPoco.ActualPODDeparture,
                    DeliveryLocation = entityPoco.DeliveryLocation,
                    EstimatedDelivery = entityPoco.EstimatedDelivery,
                    ActualDelivery = entityPoco.ActualDelivery,
                    LIFLocation = entityPoco.LIFLocation,
                    EstimatedLIFArrival = entityPoco.EstimatedLIFArrival,
                    ActualLIFArrival = entityPoco.ActualLIFArrival,
                    EstimatedLIFDeparture = entityPoco.EstimatedLIFDeparture,
                    ActualLIFDeparture = entityPoco.ActualLIFDeparture,
                    GateIn = entityPoco.GateIn,
                    GateOut = entityPoco.GateOut,
                    EmptyReturnLocation = entityPoco.EmptyReturnLocation,
                    EstimatedEmptyReturn = entityPoco.EstimatedEmptyReturn,
                    ActualEmptyReturn = entityPoco.ActualEmptyReturn,
                    CustomsReleaseState = entityPoco.CustomsReleaseState,
                    CustomsReleaseDate = entityPoco.CustomsReleaseDate,
                    CarrierReleaseState = entityPoco.CarrierReleaseState,
                    CarrierReleaseDate = entityPoco.CarrierReleaseDate,
                    AvailablityDate = entityPoco.AvailablityDate,
                    AvailabilityLocation = entityPoco.AvailabilityLocation,
                    FreeDays = entityPoco.FreeDays,
                    LastFreeDayDate = entityPoco.LastFreeDayDate,
                    ShipmentStatusId = entityPoco.ShipmentStatusId,
                    ShipmentStatusName = entityPoco.ShipmentEntityStatus?.Name,
                };
            }

            return result;
        }

        public List<ContainerPM> GetContainers(string id , int tenant)
        {
            return (from a in repository.context.Containers.Include("CarrierCard").Include("VesselCard").Include("ShipmentOnCarriageToPort").Include("ShipmentOnCarriageFromPort").
                    Include("ShipmentTransshipment3ToPort").Include("ShipmentTransshipment3FromPort").Include("ShipmentTransshipment2ToPort").Include("ShipmentTransshipment2FromPort")
                    .Include("ShipmentTransshipment1ToPort").Include("ShipmentTransshipment1FromPort").Include("ShipmentMainCarriageToPort").Include("ShipmentMainCarriageFromPort")
                    .Include("ShipmentPreCarriageToPort").Include("ShipmentPreCarriageFromPort").Include("ShipmentEntityStatus")
                    where a.Id == id && a.Tenant == tenant
                    select new ContainerPM()
                    {
                        Id = a.Id,
                        Tenant = a.Tenant,
                        CreateDate = a.CreateDate,
                        CreatedByUserId = a.CreatedByUserId,
                        UpdateDate = a.UpdateDate,
                        UpdatedByUserId = a.UpdatedByUserId,
                        MainCarriageCarrierId = a.MainCarriageCarrierId,
                        MainCarriageCarrierNumber = a.MainCarriageCarrierNumber,
                        MainCarriageATA = a.MainCarriageATA,
                        MainCarriageATD = a.MainCarriageATD,
                        MainCarriageETA = a.MainCarriageETA,
                        MainCarriageETD = a.MainCarriageETD,
                        ContainerNumber = a.ContainerNumber,
                        MainCarriageVesselId = a.MainCarriageVesselId,
                        ShipmentPackagesId = a.ShipmentPackagesId,
                        SearchFields = a.SearchFields,
                        DischargeDate = a.DischargeDate,
                        Master = a.Master,
                        CarrierName = a.CarrierCard != null ? a.CarrierCard.EnglishName : "",
                        VesselName = a.VesselCard != null ? a.VesselCard.EnglishName : "",
                        ShipmentId = a.ShipmentId,
                        ActualEmptyPickupDate = a.ActualEmptyPickupDate,
                        EstimatedEmptyPickupDate = a.EstimatedEmptyPickupDate,
                        CurrentStatus = a.CurrentStatus,
                        CurrentStatusDate = a.CurrentStatusDate,
                        HasContainerException = a.HasContainerException,
                        CurrentLocation = a.CurrentLocation,
                        EmptyPickupLocation = a.EmptyPickupLocation,
                        DepartureLocation = a.DepartureLocation,
                        DestinationLocation = a.DestinationLocation,
                        ShipmentFirstPickupFrom = a.ShipmentFirstPickupFrom,
                        ShipmentFirstPickupTo = a.ShipmentFirstPickupTo,
                        ShipmentPreCarriageFromId = a.ShipmentPreCarriageFromId,
                        ShipmentPreCarriageToId = a.ShipmentPreCarriageToId,
                        ShipmentMainCarriageFromId = a.ShipmentMainCarriageFromId,
                        ShipmentMainCarriageToId = a.ShipmentMainCarriageToId,
                        ShipmentTransshipment1FromId = a.ShipmentTransshipment1FromId,
                        ShipmentTransshipment1ToId = a.ShipmentTransshipment1ToId,
                        ShipmentTransshipment2FromId = a.ShipmentTransshipment2FromId,
                        ShipmentTransshipment2ToId = a.ShipmentTransshipment2ToId,
                        ShipmentTransshipment3FromId = a.ShipmentTransshipment3FromId,
                        ShipmentTransshipment3ToId = a.ShipmentTransshipment3ToId,
                        ShipmentOnCarriageFromId = a.ShipmentOnCarriageFromId,
                        ShipmentOnCarriageToId = a.ShipmentOnCarriageToId,
                        ShipmentLastDeliveryFrom = a.ShipmentLastDeliveryFrom,
                        ShipmentLastDeliveryTo = a.ShipmentLastDeliveryTo,
                        ShipmentPreCarriageFrom = a.ShipmentPreCarriageFromPort != null ? a.ShipmentPreCarriageFromPort.CombinedCode : "",
                        ShipmentPreCarriageTo = a.ShipmentPreCarriageToPort != null ? a.ShipmentPreCarriageToPort.CombinedCode : "",
                        ShipmentMainCarriageFrom = a.ShipmentMainCarriageFromPort != null ? a.ShipmentMainCarriageFromPort.CombinedCode : "",
                        ShipmentMainCarriageTo = a.ShipmentMainCarriageToPort != null ? a.ShipmentMainCarriageToPort.CombinedCode : "",
                        ShipmentTransshipment1From = a.ShipmentTransshipment1FromPort != null ? a.ShipmentTransshipment1FromPort.CombinedCode : "",
                        ShipmentTransshipment1To = a.ShipmentTransshipment1ToPort != null ? a.ShipmentTransshipment1ToPort.CombinedCode : "",
                        ShipmentTransshipment2From = a.ShipmentTransshipment2FromPort != null ? a.ShipmentTransshipment2FromPort.CombinedCode : "",
                        ShipmentTransshipment2To = a.ShipmentTransshipment2ToPort != null ? a.ShipmentTransshipment2ToPort.CombinedCode : "",
                        ShipmentTransshipment3From = a.ShipmentTransshipment3FromPort != null ? a.ShipmentTransshipment3FromPort.CombinedCode : "",
                        ShipmentTransshipment3To = a.ShipmentTransshipment3ToPort != null ? a.ShipmentTransshipment3ToPort.CombinedCode : "",
                        ShipmentOnCarriageFrom = a.ShipmentOnCarriageFromPort != null ? a.ShipmentOnCarriageFromPort.CombinedCode : "",
                        ShipmentOnCarriageTo = a.ShipmentOnCarriageToPort != null ? a.ShipmentOnCarriageToPort.CombinedCode : "",
                        OriginLocation = a.OriginLocation,
                        EstimatedOriginPickup = a.EstimatedOriginPickup,
                        ActualOriginPickup = a.ActualOriginPickup,
                        POLLocation = a.POLLocation,
                        EstimatedPOLArrival = a.EstimatedPOLArrival,
                        ActualPOLArrival = a.ActualPOLArrival,
                        EstimatedPOLLoaded = a.EstimatedPOLLoaded,
                        ActualPOLLoaded = a.ActualPOLLoaded,
                        EstimatedPOLVesselDeparture = a.EstimatedPOLVesselDeparture,
                        ActualPOLVesselDeparture = a.ActualPOLVesselDeparture,
                        TransshipmentCount = a.TransshipmentCount,
                        Transshipment1Location = a.Transshipment1Location,
                        EstimatedTrans1VesselArrival = a.EstimatedTrans1VesselArrival,
                        ActualTransshipment1VesselArrival = a.ActualTransshipment1VesselArrival,
                        EstimatedTransshipment1Discharge = a.EstimatedTransshipment1Discharge,
                        ActualTransshipment1Discharge = a.ActualTransshipment1Discharge,
                        EstimatedTransshipment1Loaded = a.EstimatedTransshipment1Loaded,
                        ActualTransshipment1Loaded = a.ActualTransshipment1Loaded,
                        EstimatedTrans1VesselDeparture = a.EstimatedTrans1VesselDeparture,
                        ActualTrans1VesselDeparture = a.ActualTrans1VesselDeparture,
                        Transshipment2Location = a.Transshipment2Location,
                        EstimatedTrans2VesselArrival = a.EstimatedTrans2VesselArrival,
                        ActualTransshipment2VesselArrival = a.ActualTransshipment2VesselArrival,
                        EstimatedTransshipment2Discharge = a.EstimatedTransshipment2Discharge,
                        ActualTransshipment2Discharge = a.ActualTransshipment2Discharge,
                        EstimatedTransshipment2Loaded = a.EstimatedTransshipment2Loaded,
                        ActualTransshipment2Loaded = a.ActualTransshipment2Loaded,
                        EstimatedTrans2VesselDeparture = a.EstimatedTrans2VesselDeparture,
                        ActualTrans2VesselDeparture = a.ActualTrans2VesselDeparture,
                        Transshipment3Location = a.Transshipment3Location,
                        EstimatedTrans3VesselArrival = a.EstimatedTrans3VesselArrival,
                        ActualTransshipment3VesselArrival = a.ActualTransshipment3VesselArrival,
                        EstimatedTransshipment3Discharge = a.EstimatedTransshipment3Discharge,
                        ActualTransshipment3Discharge = a.ActualTransshipment3Discharge,
                        EstimatedTransshipment3Loaded = a.EstimatedTransshipment3Loaded,
                        ActualTransshipment3Loaded = a.ActualTransshipment3Loaded,
                        EstimatedTrans3VesselDeparture = a.EstimatedTrans3VesselDeparture,
                        ActualTrans3VesselDeparture = a.ActualTrans3VesselDeparture,
                        Transshipment4Location = a.Transshipment4Location,
                        EstimatedTrans4VesselArrival = a.EstimatedTrans4VesselArrival,
                        ActualTransshipment4VesselArrival = a.ActualTransshipment4VesselArrival,
                        EstimatedTransshipment4Discharge = a.EstimatedTransshipment4Discharge,
                        ActualTransshipment4Discharge = a.ActualTransshipment4Discharge,
                        EstimatedTransshipment4Loaded = a.EstimatedTransshipment4Loaded,
                        ActualTransshipment4Loaded = a.ActualTransshipment4Loaded,
                        EstimatedTrans4VesselDeparture = a.EstimatedTrans4VesselDeparture,
                        ActualTrans4VesselDeparture = a.ActualTrans4VesselDeparture,
                        Leg1Vessel = a.Leg1Vessel,
                        Leg1Voyage = a.Leg1Voyage,
                        Leg2Vessel = a.Leg2Vessel,
                        Leg2Voyage = a.Leg2Voyage,
                        Leg3Vessel = a.Leg3Vessel,
                        Leg3Voyage = a.Leg3Voyage,
                        Leg4Vessel = a.Leg4Vessel,
                        Leg4Voyage = a.Leg4Voyage,
                        Leg5Vessel = a.Leg5Vessel,
                        Leg5Voyage = a.Leg5Voyage,
                        PODLocation = a.PODLocation,
                        EstimatedPODVesselArrival = a.EstimatedPODVesselArrival,
                        ActualPODVesselArrival = a.ActualPODVesselArrival,
                        EstimatedPODDischarge = a.EstimatedPODDischarge,
                        ActualPODDischarge = a.ActualPODDischarge,
                        EstimatedPODDeparture = a.EstimatedPODDeparture,
                        ActualPODDeparture = a.ActualPODDeparture,
                        DeliveryLocation = a.DeliveryLocation,
                        EstimatedDelivery = a.EstimatedDelivery,
                        ActualDelivery = a.ActualDelivery,
                        LIFLocation = a.LIFLocation,
                        EstimatedLIFArrival = a.EstimatedLIFArrival,
                        ActualLIFArrival = a.ActualLIFArrival,
                        EstimatedLIFDeparture = a.EstimatedLIFDeparture,
                        ActualLIFDeparture = a.ActualLIFDeparture,
                        GateIn = a.GateIn,
                        GateOut = a.GateOut,
                        EmptyReturnLocation = a.EmptyReturnLocation,
                        EstimatedEmptyReturn = a.EstimatedEmptyReturn,
                        ActualEmptyReturn = a.ActualEmptyReturn,
                        CustomsReleaseState = a.CustomsReleaseState,
                        CustomsReleaseDate = a.CustomsReleaseDate,
                        CarrierReleaseState = a.CarrierReleaseState,
                        CarrierReleaseDate = a.CarrierReleaseDate,
                        AvailablityDate = a.AvailablityDate,
                        AvailabilityLocation = a.AvailabilityLocation,
                        FreeDays = a.FreeDays,
                        LastFreeDayDate = a.LastFreeDayDate,
                        ShipmentStatusId = a.ShipmentStatusId,
                        ShipmentStatusName = a.ShipmentEntityStatus != null ? a.ShipmentEntityStatus.Name: null,
                    }).ToList();
        }

        public IQueryable<ContainerList> GetIQueryableEntityList(IQueryable<Container> iQueryable)
        {
            IQueryable<ContainerList> result = from entity in iQueryable.Include("CarrierCard").Include("VesselCard").Include("ShipmentOnCarriageToPort").Include("ShipmentOnCarriageFromPort").
                    Include("ShipmentTransshipment3ToPort").Include("ShipmentTransshipment3FromPort").Include("ShipmentTransshipment2ToPort").Include("ShipmentTransshipment2FromPort")
                    .Include("ShipmentTransshipment1ToPort").Include("ShipmentTransshipment1FromPort").Include("ShipmentMainCarriageToPort").Include("ShipmentMainCarriageFromPort")
                    .Include("ShipmentPreCarriageToPort").Include("ShipmentPreCarriageFromPort").Include("ShipmentPreCarriageFromPort").Include("ShipmentEntityStatus")
                                               select new ContainerList()
                                               {
                                                   Id = entity.Id,
                                                   Tenant = entity.Tenant,
                                                   CreateDate = entity.CreateDate,
                                                   CreatedByUserId = entity.CreatedByUserId,
                                                   UpdateDate = entity.UpdateDate,
                                                   UpdatedByUserId = entity.UpdatedByUserId,
                                                   MainCarriageCarrierId = entity.MainCarriageCarrierId,
                                                   MainCarriageCarrierNumber = entity.MainCarriageCarrierNumber,
                                                   MainCarriageATA = entity.MainCarriageATA,
                                                   MainCarriageATD = entity.MainCarriageATD,
                                                   MainCarriageETA = entity.MainCarriageETA,
                                                   MainCarriageETD = entity.MainCarriageETD,
                                                   ContainerNumber = entity.ContainerNumber,
                                                   MainCarriageVesselId = entity.MainCarriageVesselId,
                                                   ShipmentPackagesId = entity.ShipmentPackagesId,
                                                   SearchFields = entity.SearchFields,
                                                   DischargeDate = entity.DischargeDate,
                                                   Master = entity.Master,
                                                   CarrierName = entity.CarrierCard != null ? entity.CarrierCard.EnglishName : "",
                                                   VesselName = entity.VesselCard != null ? entity.VesselCard.EnglishName : "",
                                                   ShipmentId = entity.ShipmentId,
                                                   ActualEmptyPickupDate = entity.ActualEmptyPickupDate,
                                                   EstimatedEmptyPickupDate = entity.EstimatedEmptyPickupDate,
                                                   CurrentStatus = entity.CurrentStatus,
                                                   CurrentStatusDate = entity.CurrentStatusDate,
                                                   HasContainerException = entity.HasContainerException,
                                                   CurrentLocation = entity.CurrentLocation,
                                                   EmptyPickupLocation = entity.EmptyPickupLocation,
                                                   DepartureLocation = entity.DepartureLocation,
                                                   DestinationLocation = entity.DestinationLocation,
                                                   ShipmentFirstPickupFrom = entity.ShipmentFirstPickupFrom,
                                                   ShipmentFirstPickupTo = entity.ShipmentFirstPickupTo,
                                                   ShipmentPreCarriageFromId = entity.ShipmentPreCarriageFromId,
                                                   ShipmentPreCarriageToId = entity.ShipmentPreCarriageToId,
                                                   ShipmentMainCarriageFromId = entity.ShipmentMainCarriageFromId,
                                                   ShipmentMainCarriageToId = entity.ShipmentMainCarriageToId,
                                                   ShipmentTransshipment1FromId = entity.ShipmentTransshipment1FromId,
                                                   ShipmentTransshipment1ToId = entity.ShipmentTransshipment1ToId,
                                                   ShipmentTransshipment2FromId = entity.ShipmentTransshipment2FromId,
                                                   ShipmentTransshipment2ToId = entity.ShipmentTransshipment2ToId,
                                                   ShipmentTransshipment3FromId = entity.ShipmentTransshipment3FromId,
                                                   ShipmentTransshipment3ToId = entity.ShipmentTransshipment3ToId,
                                                   ShipmentOnCarriageFromId = entity.ShipmentOnCarriageFromId,
                                                   ShipmentOnCarriageToId = entity.ShipmentOnCarriageToId,
                                                   ShipmentLastDeliveryFrom = entity.ShipmentLastDeliveryFrom,
                                                   ShipmentLastDeliveryTo = entity.ShipmentLastDeliveryTo,
                                                   ShipmentPreCarriageFrom = entity.ShipmentPreCarriageFromPort != null ? entity.ShipmentPreCarriageFromPort.CombinedCode : "",
                                                   ShipmentPreCarriageTo = entity.ShipmentPreCarriageToPort != null ? entity.ShipmentPreCarriageToPort.CombinedCode : "",
                                                   ShipmentMainCarriageFrom = entity.ShipmentMainCarriageFromPort != null ? entity.ShipmentMainCarriageFromPort.CombinedCode : "",
                                                   ShipmentMainCarriageTo = entity.ShipmentMainCarriageToPort != null ? entity.ShipmentMainCarriageToPort.CombinedCode : "",
                                                   ShipmentTransshipment1From = entity.ShipmentTransshipment1FromPort != null ? entity.ShipmentTransshipment1FromPort.CombinedCode : "",
                                                   ShipmentTransshipment1To = entity.ShipmentTransshipment1ToPort != null ? entity.ShipmentTransshipment1ToPort.CombinedCode : "",
                                                   ShipmentTransshipment2From = entity.ShipmentTransshipment2FromPort != null ? entity.ShipmentTransshipment2FromPort.CombinedCode : "",
                                                   ShipmentTransshipment2To = entity.ShipmentTransshipment2ToPort != null ? entity.ShipmentTransshipment2ToPort.CombinedCode : "",
                                                   ShipmentTransshipment3From = entity.ShipmentTransshipment3FromPort != null ? entity.ShipmentTransshipment3FromPort.CombinedCode : "",
                                                   ShipmentTransshipment3To = entity.ShipmentTransshipment3ToPort != null ? entity.ShipmentTransshipment3ToPort.CombinedCode : "",
                                                   ShipmentOnCarriageFrom = entity.ShipmentOnCarriageFromPort != null ? entity.ShipmentOnCarriageFromPort.CombinedCode : "",
                                                   ShipmentOnCarriageTo = entity.ShipmentOnCarriageToPort != null ? entity.ShipmentOnCarriageToPort.CombinedCode : "",
                                                   OriginLocation = entity.OriginLocation,
                                                   EstimatedOriginPickup = entity.EstimatedOriginPickup,
                                                   ActualOriginPickup = entity.ActualOriginPickup,
                                                   POLLocation = entity.POLLocation,
                                                   EstimatedPOLArrival = entity.EstimatedPOLArrival,
                                                   ActualPOLArrival = entity.ActualPOLArrival,
                                                   EstimatedPOLLoaded = entity.EstimatedPOLLoaded,
                                                   ActualPOLLoaded = entity.ActualPOLLoaded,
                                                   EstimatedPOLVesselDeparture = entity.EstimatedPOLVesselDeparture,
                                                   ActualPOLVesselDeparture = entity.ActualPOLVesselDeparture,
                                                   TransshipmentCount = entity.TransshipmentCount,
                                                   Transshipment1Location = entity.Transshipment1Location,
                                                   EstimatedTrans1VesselArrival = entity.EstimatedTrans1VesselArrival,
                                                   ActualTransshipment1VesselArrival = entity.ActualTransshipment1VesselArrival,
                                                   EstimatedTransshipment1Discharge = entity.EstimatedTransshipment1Discharge,
                                                   ActualTransshipment1Discharge = entity.ActualTransshipment1Discharge,
                                                   EstimatedTransshipment1Loaded = entity.EstimatedTransshipment1Loaded,
                                                   ActualTransshipment1Loaded = entity.ActualTransshipment1Loaded,
                                                   EstimatedTrans1VesselDeparture = entity.EstimatedTrans1VesselDeparture,
                                                   ActualTrans1VesselDeparture = entity.ActualTrans1VesselDeparture,
                                                   Transshipment2Location = entity.Transshipment2Location,
                                                   EstimatedTrans2VesselArrival = entity.EstimatedTrans2VesselArrival,
                                                   ActualTransshipment2VesselArrival = entity.ActualTransshipment2VesselArrival,
                                                   EstimatedTransshipment2Discharge = entity.EstimatedTransshipment2Discharge,
                                                   ActualTransshipment2Discharge = entity.ActualTransshipment2Discharge,
                                                   EstimatedTransshipment2Loaded = entity.EstimatedTransshipment2Loaded,
                                                   ActualTransshipment2Loaded = entity.ActualTransshipment2Loaded,
                                                   EstimatedTrans2VesselDeparture = entity.EstimatedTrans2VesselDeparture,
                                                   ActualTrans2VesselDeparture = entity.ActualTrans2VesselDeparture,
                                                   Transshipment3Location = entity.Transshipment3Location,
                                                   EstimatedTrans3VesselArrival = entity.EstimatedTrans3VesselArrival,
                                                   ActualTransshipment3VesselArrival = entity.ActualTransshipment3VesselArrival,
                                                   EstimatedTransshipment3Discharge = entity.EstimatedTransshipment3Discharge,
                                                   ActualTransshipment3Discharge = entity.ActualTransshipment3Discharge,
                                                   EstimatedTransshipment3Loaded = entity.EstimatedTransshipment3Loaded,
                                                   ActualTransshipment3Loaded = entity.ActualTransshipment3Loaded,
                                                   EstimatedTrans3VesselDeparture = entity.EstimatedTrans3VesselDeparture,
                                                   ActualTrans3VesselDeparture = entity.ActualTrans3VesselDeparture,
                                                   Transshipment4Location = entity.Transshipment4Location,
                                                   EstimatedTrans4VesselArrival = entity.EstimatedTrans4VesselArrival,
                                                   ActualTransshipment4VesselArrival = entity.ActualTransshipment4VesselArrival,
                                                   EstimatedTransshipment4Discharge = entity.EstimatedTransshipment4Discharge,
                                                   ActualTransshipment4Discharge = entity.ActualTransshipment4Discharge,
                                                   EstimatedTransshipment4Loaded = entity.EstimatedTransshipment4Loaded,
                                                   ActualTransshipment4Loaded = entity.ActualTransshipment4Loaded,
                                                   EstimatedTrans4VesselDeparture = entity.EstimatedTrans4VesselDeparture,
                                                   ActualTrans4VesselDeparture = entity.ActualTrans4VesselDeparture,
                                                   Leg1Vessel = entity.Leg1Vessel,
                                                   Leg1Voyage = entity.Leg1Voyage,
                                                   Leg2Vessel = entity.Leg2Vessel,
                                                   Leg2Voyage = entity.Leg2Voyage,
                                                   Leg3Vessel = entity.Leg3Vessel,
                                                   Leg3Voyage = entity.Leg3Voyage,
                                                   Leg4Vessel = entity.Leg4Vessel,
                                                   Leg4Voyage = entity.Leg4Voyage,
                                                   Leg5Vessel = entity.Leg5Vessel,
                                                   Leg5Voyage = entity.Leg5Voyage,
                                                   PODLocation = entity.PODLocation,
                                                   EstimatedPODVesselArrival = entity.EstimatedPODVesselArrival,
                                                   ActualPODVesselArrival = entity.ActualPODVesselArrival,
                                                   EstimatedPODDischarge = entity.EstimatedPODDischarge,
                                                   ActualPODDischarge = entity.ActualPODDischarge,
                                                   EstimatedPODDeparture = entity.EstimatedPODDeparture,
                                                   ActualPODDeparture = entity.ActualPODDeparture,
                                                   DeliveryLocation = entity.DeliveryLocation,
                                                   EstimatedDelivery = entity.EstimatedDelivery,
                                                   ActualDelivery = entity.ActualDelivery,
                                                   LIFLocation = entity.LIFLocation,
                                                   EstimatedLIFArrival = entity.EstimatedLIFArrival,
                                                   ActualLIFArrival = entity.ActualLIFArrival,
                                                   EstimatedLIFDeparture = entity.EstimatedLIFDeparture,
                                                   ActualLIFDeparture = entity.ActualLIFDeparture,
                                                   GateIn = entity.GateIn,
                                                   GateOut = entity.GateOut,
                                                   EmptyReturnLocation = entity.EmptyReturnLocation,
                                                   EstimatedEmptyReturn = entity.EstimatedEmptyReturn,
                                                   ActualEmptyReturn = entity.ActualEmptyReturn,
                                                   CustomsReleaseState = entity.CustomsReleaseState,
                                                   CustomsReleaseDate = entity.CustomsReleaseDate,
                                                   CarrierReleaseState = entity.CarrierReleaseState,
                                                   CarrierReleaseDate = entity.CarrierReleaseDate,
                                                   AvailablityDate = entity.AvailablityDate,
                                                   AvailabilityLocation = entity.AvailabilityLocation,
                                                   FreeDays = entity.FreeDays,
                                                   LastFreeDayDate = entity.LastFreeDayDate,
                                                   ShipmentStatusId = entity.ShipmentStatusId,
                                                   ShipmentStatusName = entity.ShipmentEntityStatus != null ? entity.ShipmentEntityStatus.Name : null,
                                               };
            return result;
        }

        public ContainerPM GetContainerByShipmentPackagesId(string shipmentPackageId, int tenant)
        {
            ContainerPM containerPM = null;
            Container container = repository.GetContainerByShipmentPackagesId(shipmentPackageId, tenant);
            if (container != null)
            {
                containerPM = new ContainerPM()
                {
                    Id = container.Id,
                    Tenant = container.Tenant,
                    CreateDate = container.CreateDate,
                    CreatedByUserId = container.CreatedByUserId,
                    UpdateDate = container.UpdateDate,
                    UpdatedByUserId = container.UpdatedByUserId,
                    MainCarriageCarrierId = container.MainCarriageCarrierId,
                    MainCarriageCarrierNumber = container.MainCarriageCarrierNumber,
                    MainCarriageATA = container.MainCarriageATA,
                    MainCarriageATD = container.MainCarriageATD,
                    MainCarriageETA = container.MainCarriageETA,
                    MainCarriageETD = container.MainCarriageETD,
                    ContainerNumber = container.ContainerNumber,
                    MainCarriageVesselId = container.MainCarriageVesselId,
                    ShipmentPackagesId = container.ShipmentPackagesId,
                    SearchFields = container.SearchFields,
                    DischargeDate = container.DischargeDate,
                    Master = container.Master,
                    ShipmentId = container.ShipmentId,
                    ActualEmptyPickupDate = container.ActualEmptyPickupDate,
                    EstimatedEmptyPickupDate = container.EstimatedEmptyPickupDate,
                    CurrentStatus = container.CurrentStatus,
                    CurrentStatusDate = container.CurrentStatusDate,
                    HasContainerException = container.HasContainerException,
                    CurrentLocation = container.CurrentLocation,
                    EmptyPickupLocation = container.EmptyPickupLocation,
                    DepartureLocation = container.DepartureLocation,
                    DestinationLocation = container.DestinationLocation,
                    ShipmentFirstPickupFrom = container.ShipmentFirstPickupFrom,
                    ShipmentFirstPickupTo = container.ShipmentFirstPickupTo,
                    ShipmentPreCarriageFromId = container.ShipmentPreCarriageFromId,
                    ShipmentPreCarriageToId = container.ShipmentPreCarriageToId,
                    ShipmentMainCarriageFromId = container.ShipmentMainCarriageFromId,
                    ShipmentMainCarriageToId = container.ShipmentMainCarriageToId,
                    ShipmentTransshipment1FromId = container.ShipmentTransshipment1FromId,
                    ShipmentTransshipment1ToId = container.ShipmentTransshipment1ToId,
                    ShipmentTransshipment2FromId = container.ShipmentTransshipment2FromId,
                    ShipmentTransshipment2ToId = container.ShipmentTransshipment2ToId,
                    ShipmentTransshipment3FromId = container.ShipmentTransshipment3FromId,
                    ShipmentTransshipment3ToId = container.ShipmentTransshipment3ToId,
                    ShipmentOnCarriageFromId = container.ShipmentOnCarriageFromId,
                    ShipmentOnCarriageToId = container.ShipmentOnCarriageToId,
                    ShipmentLastDeliveryFrom = container.ShipmentLastDeliveryFrom,
                    ShipmentLastDeliveryTo = container.ShipmentLastDeliveryTo,
                    ShipmentPreCarriageFrom = container.ShipmentPreCarriageFromPort != null ? container.ShipmentPreCarriageFromPort.CombinedCode : "",
                    ShipmentPreCarriageTo = container.ShipmentPreCarriageToPort != null ? container.ShipmentPreCarriageToPort.CombinedCode : "",
                    ShipmentMainCarriageFrom = container.ShipmentMainCarriageFromPort != null ? container.ShipmentMainCarriageFromPort.CombinedCode : "",
                    ShipmentMainCarriageTo = container.ShipmentMainCarriageToPort != null ? container.ShipmentMainCarriageToPort.CombinedCode : "",
                    ShipmentTransshipment1From = container.ShipmentTransshipment1FromPort != null ? container.ShipmentTransshipment1FromPort.CombinedCode : "",
                    ShipmentTransshipment1To = container.ShipmentTransshipment1ToPort != null ? container.ShipmentTransshipment1ToPort.CombinedCode : "",
                    ShipmentTransshipment2From = container.ShipmentTransshipment2FromPort != null ? container.ShipmentTransshipment2FromPort.CombinedCode : "",
                    ShipmentTransshipment2To = container.ShipmentTransshipment2ToPort != null ? container.ShipmentTransshipment2ToPort.CombinedCode : "",
                    ShipmentTransshipment3From = container.ShipmentTransshipment3FromPort != null ? container.ShipmentTransshipment3FromPort.CombinedCode : "",
                    ShipmentTransshipment3To = container.ShipmentTransshipment3ToPort != null ? container.ShipmentTransshipment3ToPort.CombinedCode : "",
                    ShipmentOnCarriageFrom = container.ShipmentOnCarriageFromPort != null ? container.ShipmentOnCarriageFromPort.CombinedCode : "",
                    ShipmentOnCarriageTo = container.ShipmentOnCarriageToPort != null ? container.ShipmentOnCarriageToPort.CombinedCode : "",
                    OriginLocation = container.OriginLocation,
                    EstimatedOriginPickup = container.EstimatedOriginPickup,
                    ActualOriginPickup = container.ActualOriginPickup,
                    POLLocation = container.POLLocation,
                    EstimatedPOLArrival = container.EstimatedPOLArrival,
                    ActualPOLArrival = container.ActualPOLArrival,
                    EstimatedPOLLoaded = container.EstimatedPOLLoaded,
                    ActualPOLLoaded = container.ActualPOLLoaded,
                    EstimatedPOLVesselDeparture = container.EstimatedPOLVesselDeparture,
                    ActualPOLVesselDeparture = container.ActualPOLVesselDeparture,
                    TransshipmentCount = container.TransshipmentCount,
                    Transshipment1Location = container.Transshipment1Location,
                    EstimatedTrans1VesselArrival = container.EstimatedTrans1VesselArrival,
                    ActualTransshipment1VesselArrival = container.ActualTransshipment1VesselArrival,
                    EstimatedTransshipment1Discharge = container.EstimatedTransshipment1Discharge,
                    ActualTransshipment1Discharge = container.ActualTransshipment1Discharge,
                    EstimatedTransshipment1Loaded = container.EstimatedTransshipment1Loaded,
                    ActualTransshipment1Loaded = container.ActualTransshipment1Loaded,
                    EstimatedTrans1VesselDeparture = container.EstimatedTrans1VesselDeparture,
                    ActualTrans1VesselDeparture = container.ActualTrans1VesselDeparture,
                    Transshipment2Location = container.Transshipment2Location,
                    EstimatedTrans2VesselArrival = container.EstimatedTrans2VesselArrival,
                    ActualTransshipment2VesselArrival = container.ActualTransshipment2VesselArrival,
                    EstimatedTransshipment2Discharge = container.EstimatedTransshipment2Discharge,
                    ActualTransshipment2Discharge = container.ActualTransshipment2Discharge,
                    EstimatedTransshipment2Loaded = container.EstimatedTransshipment2Loaded,
                    ActualTransshipment2Loaded = container.ActualTransshipment2Loaded,
                    EstimatedTrans2VesselDeparture = container.EstimatedTrans2VesselDeparture,
                    ActualTrans2VesselDeparture = container.ActualTrans2VesselDeparture,
                    Transshipment3Location = container.Transshipment3Location,
                    EstimatedTrans3VesselArrival = container.EstimatedTrans3VesselArrival,
                    ActualTransshipment3VesselArrival = container.ActualTransshipment3VesselArrival,
                    EstimatedTransshipment3Discharge = container.EstimatedTransshipment3Discharge,
                    ActualTransshipment3Discharge = container.ActualTransshipment3Discharge,
                    EstimatedTransshipment3Loaded = container.EstimatedTransshipment3Loaded,
                    ActualTransshipment3Loaded = container.ActualTransshipment3Loaded,
                    EstimatedTrans3VesselDeparture = container.EstimatedTrans3VesselDeparture,
                    ActualTrans3VesselDeparture = container.ActualTrans3VesselDeparture,
                    Transshipment4Location = container.Transshipment4Location,
                    EstimatedTrans4VesselArrival = container.EstimatedTrans4VesselArrival,
                    ActualTransshipment4VesselArrival = container.ActualTransshipment4VesselArrival,
                    EstimatedTransshipment4Discharge = container.EstimatedTransshipment4Discharge,
                    ActualTransshipment4Discharge = container.ActualTransshipment4Discharge,
                    EstimatedTransshipment4Loaded = container.EstimatedTransshipment4Loaded,
                    ActualTransshipment4Loaded = container.ActualTransshipment4Loaded,
                    EstimatedTrans4VesselDeparture = container.EstimatedTrans4VesselDeparture,
                    ActualTrans4VesselDeparture = container.ActualTrans4VesselDeparture,
                    Leg1Vessel = container.Leg1Vessel,
                    Leg1Voyage = container.Leg1Voyage,
                    Leg2Vessel = container.Leg2Vessel,
                    Leg2Voyage = container.Leg2Voyage,
                    Leg3Vessel = container.Leg3Vessel,
                    Leg3Voyage = container.Leg3Voyage,
                    Leg4Vessel = container.Leg4Vessel,
                    Leg4Voyage = container.Leg4Voyage,
                    Leg5Vessel = container.Leg5Vessel,
                    Leg5Voyage = container.Leg5Voyage,
                    PODLocation = container.PODLocation,
                    EstimatedPODVesselArrival = container.EstimatedPODVesselArrival,
                    ActualPODVesselArrival = container.ActualPODVesselArrival,
                    EstimatedPODDischarge = container.EstimatedPODDischarge,
                    ActualPODDischarge = container.ActualPODDischarge,
                    EstimatedPODDeparture = container.EstimatedPODDeparture,
                    ActualPODDeparture = container.ActualPODDeparture,
                    DeliveryLocation = container.DeliveryLocation,
                    EstimatedDelivery = container.EstimatedDelivery,
                    ActualDelivery = container.ActualDelivery,
                    LIFLocation = container.LIFLocation,
                    EstimatedLIFArrival = container.EstimatedLIFArrival,
                    ActualLIFArrival = container.ActualLIFArrival,
                    EstimatedLIFDeparture = container.EstimatedLIFDeparture,
                    ActualLIFDeparture = container.ActualLIFDeparture,
                    GateIn = container.GateIn,
                    GateOut = container.GateOut,
                    EmptyReturnLocation = container.EmptyReturnLocation,
                    EstimatedEmptyReturn = container.EstimatedEmptyReturn,
                    ActualEmptyReturn = container.ActualEmptyReturn,
                    CustomsReleaseState = container.CustomsReleaseState,
                    CustomsReleaseDate = container.CustomsReleaseDate,
                    CarrierReleaseState = container.CarrierReleaseState,
                    CarrierReleaseDate = container.CarrierReleaseDate,
                    AvailablityDate = container.AvailablityDate,
                    AvailabilityLocation = container.AvailabilityLocation,
                    FreeDays = container.FreeDays,
                    LastFreeDayDate = container.LastFreeDayDate,
                    ShipmentStatusId = container.ShipmentStatusId,
                    ShipmentStatusName = container.ShipmentEntityStatus != null ? container.ShipmentEntityStatus.Name : null,
                };
            }
            return containerPM;
        }

        public ContainerPM GetContainerByNumberAndShipmentIdAndTenant(string containerNumber, string shipmentId, int tenant)
        {
            ContainerPM result = null;
            Container entityPoco = (from container in repository.context.Containers
                                    where container.Tenant == tenant && container.ContainerNumber == containerNumber && container.ShipmentId == shipmentId
                                    select container).FirstOrDefault();

            if(entityPoco != null)
            {
                result = new ContainerPM()
                {
                    Id = entityPoco.Id,
                    Tenant = entityPoco.Tenant,
                    CreateDate = entityPoco.CreateDate,
                    CreatedByUserId = entityPoco.CreatedByUserId,
                    UpdateDate = entityPoco.UpdateDate,
                    UpdatedByUserId = entityPoco.UpdatedByUserId,
                    MainCarriageCarrierId = entityPoco.MainCarriageCarrierId,
                    MainCarriageCarrierNumber = entityPoco.MainCarriageCarrierNumber,
                    MainCarriageATA = entityPoco.MainCarriageATA,
                    MainCarriageATD = entityPoco.MainCarriageATD,
                    MainCarriageETA = entityPoco.MainCarriageETA,
                    MainCarriageETD = entityPoco.MainCarriageETD,
                    ContainerNumber = entityPoco.ContainerNumber,
                    MainCarriageVesselId = entityPoco.MainCarriageVesselId,
                    ShipmentPackagesId = entityPoco.ShipmentPackagesId,
                    SearchFields = entityPoco.SearchFields,
                    DischargeDate = entityPoco.DischargeDate,
                    Master = entityPoco.Master,
                    CarrierName = entityPoco.CarrierCard != null ? entityPoco.CarrierCard.EnglishName : "",
                    VesselName = entityPoco.VesselCard != null ? entityPoco.VesselCard.EnglishName : "",
                    ShipmentId = entityPoco.ShipmentId,
                    ActualEmptyPickupDate = entityPoco.ActualEmptyPickupDate,
                    EstimatedEmptyPickupDate = entityPoco.EstimatedEmptyPickupDate,
                    CurrentStatus = entityPoco.CurrentStatus,
                    CurrentStatusDate = entityPoco.CurrentStatusDate,
                    HasContainerException = entityPoco.HasContainerException,
                    CurrentLocation = entityPoco.CurrentLocation,
                    EmptyPickupLocation = entityPoco.EmptyPickupLocation,
                    DepartureLocation = entityPoco.DepartureLocation,
                    DestinationLocation = entityPoco.DestinationLocation,
                    ShipmentFirstPickupFrom = entityPoco.ShipmentFirstPickupFrom,
                    ShipmentFirstPickupTo = entityPoco.ShipmentFirstPickupTo,
                    ShipmentPreCarriageFromId = entityPoco.ShipmentPreCarriageFromId,
                    ShipmentPreCarriageToId = entityPoco.ShipmentPreCarriageToId,
                    ShipmentMainCarriageFromId = entityPoco.ShipmentMainCarriageFromId,
                    ShipmentMainCarriageToId = entityPoco.ShipmentMainCarriageToId,
                    ShipmentTransshipment1FromId = entityPoco.ShipmentTransshipment1FromId,
                    ShipmentTransshipment1ToId = entityPoco.ShipmentTransshipment1ToId,
                    ShipmentTransshipment2FromId = entityPoco.ShipmentTransshipment2FromId,
                    ShipmentTransshipment2ToId = entityPoco.ShipmentTransshipment2ToId,
                    ShipmentTransshipment3FromId = entityPoco.ShipmentTransshipment3FromId,
                    ShipmentTransshipment3ToId = entityPoco.ShipmentTransshipment3ToId,
                    ShipmentOnCarriageFromId = entityPoco.ShipmentOnCarriageFromId,
                    ShipmentOnCarriageToId = entityPoco.ShipmentOnCarriageToId,
                    ShipmentLastDeliveryFrom = entityPoco.ShipmentLastDeliveryFrom,
                    ShipmentLastDeliveryTo = entityPoco.ShipmentLastDeliveryTo,
                    ShipmentPreCarriageFrom = entityPoco.ShipmentPreCarriageFromPort != null ? entityPoco.ShipmentPreCarriageFromPort.CombinedCode : "",
                    ShipmentPreCarriageTo = entityPoco.ShipmentPreCarriageToPort != null ? entityPoco.ShipmentPreCarriageToPort.CombinedCode : "",
                    ShipmentMainCarriageFrom = entityPoco.ShipmentMainCarriageFromPort != null ? entityPoco.ShipmentMainCarriageFromPort.CombinedCode : "",
                    ShipmentMainCarriageTo = entityPoco.ShipmentMainCarriageToPort != null ? entityPoco.ShipmentMainCarriageToPort.CombinedCode : "",
                    ShipmentTransshipment1From = entityPoco.ShipmentTransshipment1FromPort != null ? entityPoco.ShipmentTransshipment1FromPort.CombinedCode : "",
                    ShipmentTransshipment1To = entityPoco.ShipmentTransshipment1ToPort != null ? entityPoco.ShipmentTransshipment1ToPort.CombinedCode : "",
                    ShipmentTransshipment2From = entityPoco.ShipmentTransshipment2FromPort != null ? entityPoco.ShipmentTransshipment2FromPort.CombinedCode : "",
                    ShipmentTransshipment2To = entityPoco.ShipmentTransshipment2ToPort != null ? entityPoco.ShipmentTransshipment2ToPort.CombinedCode : "",
                    ShipmentTransshipment3From = entityPoco.ShipmentTransshipment3FromPort != null ? entityPoco.ShipmentTransshipment3FromPort.CombinedCode : "",
                    ShipmentTransshipment3To = entityPoco.ShipmentTransshipment3ToPort != null ? entityPoco.ShipmentTransshipment3ToPort.CombinedCode : "",
                    ShipmentOnCarriageFrom = entityPoco.ShipmentOnCarriageFromPort != null ? entityPoco.ShipmentOnCarriageFromPort.CombinedCode : "",
                    ShipmentOnCarriageTo = entityPoco.ShipmentOnCarriageToPort != null ? entityPoco.ShipmentOnCarriageToPort.CombinedCode : "",
                    OriginLocation = entityPoco.OriginLocation,
                    EstimatedOriginPickup = entityPoco.EstimatedOriginPickup,
                    ActualOriginPickup = entityPoco.ActualOriginPickup,
                    POLLocation = entityPoco.POLLocation,
                    EstimatedPOLArrival = entityPoco.EstimatedPOLArrival,
                    ActualPOLArrival = entityPoco.ActualPOLArrival,
                    EstimatedPOLLoaded = entityPoco.EstimatedPOLLoaded,
                    ActualPOLLoaded = entityPoco.ActualPOLLoaded,
                    EstimatedPOLVesselDeparture = entityPoco.EstimatedPOLVesselDeparture,
                    ActualPOLVesselDeparture = entityPoco.ActualPOLVesselDeparture,
                    TransshipmentCount = entityPoco.TransshipmentCount,
                    Transshipment1Location = entityPoco.Transshipment1Location,
                    EstimatedTrans1VesselArrival = entityPoco.EstimatedTrans1VesselArrival,
                    ActualTransshipment1VesselArrival = entityPoco.ActualTransshipment1VesselArrival,
                    EstimatedTransshipment1Discharge = entityPoco.EstimatedTransshipment1Discharge,
                    ActualTransshipment1Discharge = entityPoco.ActualTransshipment1Discharge,
                    EstimatedTransshipment1Loaded = entityPoco.EstimatedTransshipment1Loaded,
                    ActualTransshipment1Loaded = entityPoco.ActualTransshipment1Loaded,
                    EstimatedTrans1VesselDeparture = entityPoco.EstimatedTrans1VesselDeparture,
                    ActualTrans1VesselDeparture = entityPoco.ActualTrans1VesselDeparture,
                    Transshipment2Location = entityPoco.Transshipment2Location,
                    EstimatedTrans2VesselArrival = entityPoco.EstimatedTrans2VesselArrival,
                    ActualTransshipment2VesselArrival = entityPoco.ActualTransshipment2VesselArrival,
                    EstimatedTransshipment2Discharge = entityPoco.EstimatedTransshipment2Discharge,
                    ActualTransshipment2Discharge = entityPoco.ActualTransshipment2Discharge,
                    EstimatedTransshipment2Loaded = entityPoco.EstimatedTransshipment2Loaded,
                    ActualTransshipment2Loaded = entityPoco.ActualTransshipment2Loaded,
                    EstimatedTrans2VesselDeparture = entityPoco.EstimatedTrans2VesselDeparture,
                    ActualTrans2VesselDeparture = entityPoco.ActualTrans2VesselDeparture,
                    Transshipment3Location = entityPoco.Transshipment3Location,
                    EstimatedTrans3VesselArrival = entityPoco.EstimatedTrans3VesselArrival,
                    ActualTransshipment3VesselArrival = entityPoco.ActualTransshipment3VesselArrival,
                    EstimatedTransshipment3Discharge = entityPoco.EstimatedTransshipment3Discharge,
                    ActualTransshipment3Discharge = entityPoco.ActualTransshipment3Discharge,
                    EstimatedTransshipment3Loaded = entityPoco.EstimatedTransshipment3Loaded,
                    ActualTransshipment3Loaded = entityPoco.ActualTransshipment3Loaded,
                    EstimatedTrans3VesselDeparture = entityPoco.EstimatedTrans3VesselDeparture,
                    ActualTrans3VesselDeparture = entityPoco.ActualTrans3VesselDeparture,
                    Transshipment4Location = entityPoco.Transshipment4Location,
                    EstimatedTrans4VesselArrival = entityPoco.EstimatedTrans4VesselArrival,
                    ActualTransshipment4VesselArrival = entityPoco.ActualTransshipment4VesselArrival,
                    EstimatedTransshipment4Discharge = entityPoco.EstimatedTransshipment4Discharge,
                    ActualTransshipment4Discharge = entityPoco.ActualTransshipment4Discharge,
                    EstimatedTransshipment4Loaded = entityPoco.EstimatedTransshipment4Loaded,
                    ActualTransshipment4Loaded = entityPoco.ActualTransshipment4Loaded,
                    EstimatedTrans4VesselDeparture = entityPoco.EstimatedTrans4VesselDeparture,
                    ActualTrans4VesselDeparture = entityPoco.ActualTrans4VesselDeparture,
                    Leg1Vessel = entityPoco.Leg1Vessel,
                    Leg1Voyage = entityPoco.Leg1Voyage,
                    Leg2Vessel = entityPoco.Leg2Vessel,
                    Leg2Voyage = entityPoco.Leg2Voyage,
                    Leg3Vessel = entityPoco.Leg3Vessel,
                    Leg3Voyage = entityPoco.Leg3Voyage,
                    Leg4Vessel = entityPoco.Leg4Vessel,
                    Leg4Voyage = entityPoco.Leg4Voyage,
                    Leg5Vessel = entityPoco.Leg5Vessel,
                    Leg5Voyage = entityPoco.Leg5Voyage,
                    PODLocation = entityPoco.PODLocation,
                    EstimatedPODVesselArrival = entityPoco.EstimatedPODVesselArrival,
                    ActualPODVesselArrival = entityPoco.ActualPODVesselArrival,
                    EstimatedPODDischarge = entityPoco.EstimatedPODDischarge,
                    ActualPODDischarge = entityPoco.ActualPODDischarge,
                    EstimatedPODDeparture = entityPoco.EstimatedPODDeparture,
                    ActualPODDeparture = entityPoco.ActualPODDeparture,
                    DeliveryLocation = entityPoco.DeliveryLocation,
                    EstimatedDelivery = entityPoco.EstimatedDelivery,
                    ActualDelivery = entityPoco.ActualDelivery,
                    LIFLocation = entityPoco.LIFLocation,
                    EstimatedLIFArrival = entityPoco.EstimatedLIFArrival,
                    ActualLIFArrival = entityPoco.ActualLIFArrival,
                    EstimatedLIFDeparture = entityPoco.EstimatedLIFDeparture,
                    ActualLIFDeparture = entityPoco.ActualLIFDeparture,
                    GateIn = entityPoco.GateIn,
                    GateOut = entityPoco.GateOut,
                    EmptyReturnLocation = entityPoco.EmptyReturnLocation,
                    EstimatedEmptyReturn = entityPoco.EstimatedEmptyReturn,
                    ActualEmptyReturn = entityPoco.ActualEmptyReturn,
                    CustomsReleaseState = entityPoco.CustomsReleaseState,
                    CustomsReleaseDate = entityPoco.CustomsReleaseDate,
                    CarrierReleaseState = entityPoco.CarrierReleaseState,
                    CarrierReleaseDate = entityPoco.CarrierReleaseDate,
                    AvailablityDate = entityPoco.AvailablityDate,
                    AvailabilityLocation = entityPoco.AvailabilityLocation,
                    FreeDays = entityPoco.FreeDays,
                    LastFreeDayDate = entityPoco.LastFreeDayDate,
                    ShipmentStatusId = entityPoco.ShipmentStatusId,
                    ShipmentStatusName = entityPoco.ShipmentEntityStatus != null ? entityPoco.ShipmentEntityStatus.Name : null,
                };
            }

            return result;
        }
    }
}
