//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using AmitalCloud.Infrastructure.Model.BaseClasses;
using AmitalCloud.Infrastructure.Model.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AmitalCloud.Infrastructure.Model.EntityClasses
{
	[DataBase(AmitalCloudDBSchema.AMITAL_MAIN)]
	[Table("QUERIES")]
    public class Query : BaseEntity
	{
		
        [Key]
        [Column("Id")]
	    public string Id { get; set; }
        [Column("Tenant")]
	    public int Tenant { get; set; }
        [Column("Code")]
	    public string Code { get; set; }
        [ForeignKey("User")]
        [Column("UserId")]
	    public string UserId { get; set; }
	      
        public virtual User User { get; set; }
        [ForeignKey("ObjectTable")]
        [Column("ObjectTableId")]
	    public string ObjectTableId { get; set; }
	      
        public virtual ObjectTable ObjectTable { get; set; }
        [Column("SystemLevel")]
	    public bool SystemLevel { get; set; }
        [Column("TenantLevel")]
	    public bool TenantLevel { get; set; }
        [Column("OriginalQueryId")]
	    public string OriginalQueryId { get; set; }
        [Column("QuerySection")]
	    public string QuerySection { get; set; }
        [Column("IndexOrder")]
	    public int IndexOrder { get; set; }
        [Column("DisplayCount")]
	    public bool DisplayCount { get; set; }
        [Column("IsAddNewEntityEnabled")]
	    public bool IsAddNewEntityEnabled { get; set; }
        [ForeignKey("QueryGroup")]
        [Column("QueryGroupCode")]
	    public string QueryGroupCode { get; set; }
	      
        public virtual QueryGroup QueryGroup { get; set; }
        [ForeignKey("NameTextCode")]
        [Column("NameTextCodeId")]
	    public string NameTextCodeId { get; set; }
	      
        public virtual TextCode NameTextCode { get; set; }
        [Column("DefaultSortDirection")]
	    public string DefaultSortDirection { get; set; }
        [Column("DefaultSortColumn")]
	    public string DefaultSortColumn { get; set; }
        [Column("SpotlightDataTemplate")]
	    public string SpotlightDataTemplate { get; set; }
        [Column("Internal")]
	    public bool Internal { get; set; }
        [Column("Customer")]
	    public bool Customer { get; set; }
        [Column("Agent")]
	    public bool Agent { get; set; }
        [Column("FeatureId")]
	    public string FeatureId { get; set; }
        [Column("EditWizardName")]
	    public string EditWizardName { get; set; }
        [Column("Perspective")]
	    public string Perspective { get; set; }
        [Column("IsHiddenFromView")]
	    public bool IsHiddenFromView { get; set; }
        [Column("IsNewFromTenantZeroOnly")]
	    public bool IsNewFromTenantZeroOnly { get; set; }
        [Column("EditWizardComponentPath")]
	    public string EditWizardComponentPath { get; set; }
        [Column("SharedWithAll")]
	    public bool SharedWithAll { get; set; }
        [Column("SharedWithSpecificUsers")]
	    public bool SharedWithSpecificUsers { get; set; }
        [ForeignKey("SharedByUserIdUser")]
        [Column("SharedByUserId")]
	    public string SharedByUserId { get; set; }
	      
        public virtual User SharedByUserIdUser { get; set; }
        [Column("SpotlightModeActivated")]
	    public bool SpotlightModeActivated { get; set; }
        [Column("UniqueCode")]
	    public string UniqueCode { get; set; }
        [Column("OriginalQueryCode")]
	    public string OriginalQueryCode { get; set; }
        [Column("NameTextCodeCode")]
	    public string NameTextCodeCode { get; set; }
        [Column("FeatureUniqeCode")]
	    public string FeatureUniqeCode { get; set; }
        [Column("IsViewOnly")]
	    public bool IsViewOnly { get; set; }
        [Column("IsDefault")]
	    public bool IsDefault { get; set; }
    }
}
	 