import { RegexSelectors } from '../RegexSelectors';

export class SharedManifestsSelectors extends RegexSelectors {

    public static readonly OperationsTab='[id="GeneralMHOperations"]'
    public static readonly SharedManifests='[id="SHMA"]'
    public static readonly DocumentsPermissions='[data-cy="Documents Permissions"]'
    public static readonly AirManifest='Air Manifest'
    public static readonly AirwaybillLabels='Air waybill- Labels'
    public static readonly ArrivalNotice='Arrival Notice'
    public static readonly AgentTHSharedLogistics='[id="AgentTHSharedLogistics"]'
    public static readonly SendInvitation='[data-cy="Send Invitation"]'
    public static readonly Email='[data-cy="Email"]'
    public static readonly Send='[data-cy="Send"]'
    public static readonly SharedKey='input[data-cy="SharedKey"]'
    public static readonly Cancel='[data-cy="Cancel"]'
    public static readonly AcceptInvitation='[data-cy="Accept invitation"]'
    public static readonly Key='[data-cy="Key"]'
    public static readonly SignOut="img[src='./Images/Icons/Signout.png']"
    public static readonly SharingActions='[data-cy="Sharing Actions"]'
    public static readonly ShareManifest='[data-cy="Share Manifest"]'
    public static readonly ShareDocuments='[data-cy="Share Documents"]'
    public static readonly ShareDocumentsViaEmail='[data-cy="Share Documents Via Email"]'
    public static readonly UpdateSharedAgent='[data-cy="Update Shared Agent"]'
    public static readonly ShipmentRoutings='[id="ShipmentTHRoutings"]'
    public static readonly MainCarriage='[id="Edit-MainCarriage"]'
    public static readonly MainCarriageCarrier='[id="Shipment_MainCarriageCarrierId"]'
    public static readonly ShipmentMasterNo='[id="Shipment_Master"]'
    public static readonly ShipmentPartners='[id="ShipmentTHPartners"]'
    public static readonly DeleteConsignee='[id="Delete-Consignee"]'
    public static readonly ShipmentSave='[id="Shipment-Save"]'
    public static readonly AddPartner='[id="PartnerToggle"]'
    public static readonly AddConsignee= '[id="CONSI"]'
    public static readonly ConsigneeId='[id="Shipment_ConsigneeId"]'
    public static readonly BackBottonBody='[class="BackBottonBody"]'
    public static readonly Close='[data-cy="Close"]'
}