// <auto-generated />
namespace Logitude.DatabaseMigration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Khalid_AirlinePortArea_Delete_DescriptionColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Khalid_AirlinePortArea_Delete_DescriptionColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201906270832436_Khalid_AirlinePortArea_Delete_DescriptionColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
