// <auto-generated />
namespace Logitude.DatabaseMigration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFTPDeatilsPropertiesForAccountingTransfer_Samar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFTPDeatilsPropertiesForAccountingTransfer_Samar));
        
        string IMigrationMetadata.Id
        {
            get { return "202003301631528_AddFTPDeatilsPropertiesForAccountingTransfer_Samar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
