//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

import {
    UIProperties,
    UIProperty,
} from '../../Infrastructure/Components/LogitudeComponents/UIProperties';
import { ServiceHelper } from '../../Infrastructure/Utilities/ServiceHelper';
import { ServiceLocator } from '../../Infrastructure/Locators/ServiceLocator';
import { Output, EventEmitter } from '@angular/core';
import { PropertyChangedArgs } from '../../Infrastructure/EventEmitterArgs/PropertyChangedArgs';

export class ExpenseAllocationSettingPM {
    @Output() PropertyChanged: EventEmitter<PropertyChangedArgs> =
        new EventEmitter<PropertyChangedArgs>();
    public UIProperties: UIProperties;
    constructor() {
        this.UIProperties = new UIProperties(this);
        this.IsDirty = false;
    }

    private id: string;
    public get Id() {
        return this.id;
    }
    public set Id(newValue: string) {
        if (this.id != newValue) {
            this.id = newValue;
            this.MarkAsDirty('Id');
        }
    }

    private tenant: number;
    public get Tenant() {
        return this.tenant;
    }
    public set Tenant(newValue: number) {
        if (this.tenant != newValue) {
            this.tenant = newValue;
            this.MarkAsDirty('Tenant');
        }
    }

    private createDate: Date;
    public get CreateDate() {
        return this.createDate;
    }
    public set CreateDate(newValue: Date) {
        if (this.createDate != newValue) {
            this.createDate = newValue;
            this.MarkAsDirty('CreateDate');
        }
    }
    private updateDate: Date;
    public get UpdateDate() {
        return this.updateDate;
    }
    public set UpdateDate(newValue: Date) {
        if (this.updateDate != newValue) {
            this.updateDate = newValue;
            this.MarkAsDirty('UpdateDate');
        }
    }
    private entityId: string;
    public get EntityId() {
        return this.entityId;
    }
    public set EntityId(newValue: string) {
        if (this.entityId != newValue) {
            this.entityId = newValue;
            this.MarkAsDirty('EntityId');
        }
    }
    private objectTableId: string;
    public get ObjectTableId() {
        return this.objectTableId;
    }
    public set ObjectTableId(newValue: string) {
        if (this.objectTableId != newValue) {
            this.objectTableId = newValue;
            this.MarkAsDirty('ObjectTableId');
        }
    }
    private startDateTime: Date;
    public get StartDateTime() {
        return this.startDateTime;
    }
    public set StartDateTime(newValue: Date) {
        if (this.startDateTime != newValue) {
            this.startDateTime = newValue;
            this.MarkAsDirty('StartDateTime');
        }
    }
    private endDateTime: Date;
    public get EndDateTime() {
        return this.endDateTime;
    }
    public set EndDateTime(newValue: Date) {
        if (this.endDateTime != newValue) {
            this.endDateTime = newValue;
            this.MarkAsDirty('EndDateTime');
        }
    }
    private numberOfPayments: number;
    public get NumberOfPayments() {
        return this.numberOfPayments;
    }
    public set NumberOfPayments(newValue: number) {
        if (this.numberOfPayments != newValue) {
            this.numberOfPayments = newValue;
            this.MarkAsDirty('NumberOfPayments');
        }
    }
    private monthInterval: number;
    public get MonthInterval() {
        return this.monthInterval;
    }
    public set MonthInterval(newValue: number) {
        if (this.monthInterval != newValue) {
            this.monthInterval = newValue;
            this.MarkAsDirty('MonthInterval');
        }
    }

    private paymentDateType: string;
    public get PaymentDateType() {
        return this.paymentDateType;
    }
    public set PaymentDateType(newValue: string) {
        if (this.paymentDateType != newValue) {
            this.paymentDateType = newValue;
            this.MarkAsDirty('PaymentDateType');
        }
    }
    private createdByUserId: string;
    public get CreatedByUserId() {
        return this.createdByUserId;
    }
    public set CreatedByUserId(newValue: string) {
        if (this.createdByUserId != newValue) {
            this.createdByUserId = newValue;
            this.MarkAsDirty('CreatedByUserId');
        }
    }

    private updatedByUserId: string;
    public get UpdatedByUserId() {
        return this.updatedByUserId;
    }
    public set UpdatedByUserId(newValue: string) {
        if (this.updatedByUserId != newValue) {
            this.updatedByUserId = newValue;
            this.MarkAsDirty('UpdatedByUserId');
        }
    }

    public OldEntityPM: ExpenseAllocationSettingPM;

    public IsDirty: boolean;
    public DisableMarkAsDirty: boolean = false;
    MarkAsDirty(propertyName: string = null) {
        if (!this.DisableMarkAsDirty) {
            this.IsDirty = true;

            if (propertyName != null) {
                this.PropertyChanged.emit(
                    new PropertyChangedArgs(propertyName, this)
                );
                ServiceLocator.RulesValidator.ApplyEntityChangedRules(
                    propertyName,
                    this,
                    'ExpenseAllocationSetting'
                );
            }
        }
    }
    private MyClone: ExpenseAllocationSettingPM;

    public CloneMe() {
        ServiceHelper.CloneEntityPM(this);
    }

    public RejectChanges() {
        ServiceHelper.RejectEntityPMChanges(this);
    }
}
