//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { Http, Headers } from '@angular/http';
import { Observable } from 'rxjs/Rx';
import { ApiQueryFilters } from '../../DataContracts/ApiQueryFilters';
import { ServiceResponse } from '../../DataContracts/ServiceResponse';
import { InfraGenericFilter } from '../../Utilities/InfraGenericFilter';
import { CachedDataManager } from '../../Utilities/CachedDataManager';
import { ServiceHelper } from '../../Utilities/ServiceHelper';
import { SessionLocator } from '../../Utilities/SessionLocator';
import { SessionInfo } from '../../Utilities/SessionInfo';
import { LocalStorageManager } from '../../Utilities/LocalStorageManager';
import { PerformanceLogger } from '../../Utilities/PerformanceLogger';
import { BluesnapContractTypeList } from '../../EntityLists/BluesnapContractTypeList';

@Injectable()

export class BluesnapContractTypeListService {
    private _http: Http;
    private _apiUrl: string;
    public static CachedData: Array<BluesnapContractTypeList> = [];
    constructor() {
        this._http = ServiceHelper.Http;
        this._apiUrl = ServiceHelper.GetLogitudeURL() + 'api/bluesnapcontracttypeviews';
    }

    getSingle(code: string) {

        var authHeader = new Headers();
        authHeader.append('Token', SessionInfo.Token);
        var callTime = new Date();
        return Observable.defer(() => {
            return this._http.get(this._apiUrl + '/getsingle/?' + 'code=' + code, { headers: authHeader }).map(response => {

                var list = response.json();

                var entity: BluesnapContractTypeList;
                if (list) {
                    entity = this.MapJsonToEntityList(list);
                }

                var serviceResponse: ServiceResponse;
                serviceResponse = new ServiceResponse();
                serviceResponse.Result = entity;
                serviceResponse.CallTime = callTime;
                var servertime = response.headers.get('ServerExecutionTime');
                PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BluesnapContractType", "GetSingleList", 'code=' + code);

                return serviceResponse;
            }).catch(ServiceHelper.HandleServiceError);
        });
    }

    getAll() {

        var authHeader = new Headers();
        authHeader.append('Token', SessionInfo.Token);
        var callTime = new Date();
        return Observable.defer(() => {
            return this._http.get(this._apiUrl + '/getall', { headers: authHeader }).map(response => {

                var allLists = response.json();
                var _mappedListsArray: Array<BluesnapContractTypeList> = [];
                if (allLists) {
                    for (var key in allLists) {
                        var entity: BluesnapContractTypeList;
                        entity = this.MapJsonToEntityList(allLists[key]);
                        _mappedListsArray.push(entity);
                    }
                }

                var serviceResponse: ServiceResponse;
                serviceResponse = new ServiceResponse();
                serviceResponse.Result = _mappedListsArray;
                serviceResponse.CallTime = callTime;
                var servertime = response.headers.get('ServerExecutionTime');
                PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BluesnapContractType", "GetAllLists", "");

                return serviceResponse;
            }).catch(ServiceHelper.HandleServiceError);
        });
    }

    getByFilters(filters: ApiQueryFilters) {

        var callTime = new Date();

        var urlparameters = '/getbyfilters?';
        var mykeys = Object.keys(filters);
        var addtionalFiltersValues = null;
        for (var i in mykeys) {
            var propName = mykeys[i];
            var propValue = filters[propName];

            var ignoreFilter = ((propName.indexOf("Operator") > 0 && propValue == "Equals") || propName == "AdditionalFilters");

            if (urlparameters != "?") {
                urlparameters = urlparameters.concat('&');
            }
            if (!ignoreFilter) {
                propValue = encodeURIComponent(propValue);
                urlparameters = urlparameters.concat(propName.concat('=').concat(propValue));
            }

            if (propName == "AdditionalFilters" && propValue.length > 0)
                addtionalFiltersValues = JSON.stringify(propValue);


        }
        if (addtionalFiltersValues) {
            urlparameters = urlparameters.concat("&AdditionalFilters=").concat(addtionalFiltersValues);
        }

        var authHeader = new Headers();
        authHeader.append('Token', SessionInfo.Token);
        var callUrl = this._apiUrl.concat(urlparameters);//


        return Observable.defer(() => {
            return this._http.get(callUrl, {
                headers: authHeader
            }).map(response => {

                var serviceResponse: ServiceResponse;
                serviceResponse = response.json();
                var _mappedListsArray: Array<BluesnapContractTypeList> = [];
                if (serviceResponse.Result) {
                    for (var key in serviceResponse.Result) {

                        var entity: BluesnapContractTypeList;
                        entity = this.MapJsonToEntityList(serviceResponse.Result[key]);
                        _mappedListsArray.push(entity);

                    }
                }

                serviceResponse.Result = _mappedListsArray;
                serviceResponse.CallTime = callTime;
                var servertime = response.headers.get('ServerExecutionTime');
                PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BluesnapContractType", "GetByFilters", "PageIndex:" + filters.PageIndex + ", PageSize:" + filters.PageSize + ", GetAll:" + filters.GetAll);

                return serviceResponse;
            }).catch(ServiceHelper.HandleServiceError);
        });
    }

    getSingleFromCache(code: string) {

        var callTime = new Date();
        if (!SessionLocator.UseCachedData) {
            return this.getSingle(code);
        }

        var authHeader = new Headers();
        authHeader.append('Token', SessionInfo.Token);
        var exists = BluesnapContractTypeListService.CachedData.filter(a => a.Code === code).length;

        var serviceResponse: ServiceResponse;
        serviceResponse = new ServiceResponse();
        if (exists === 0) {
            return Observable.defer(() => {
                var cacheKey = "BluesnapContractType_CachedData_" + SessionLocator.Tenant;
                var _mappedListsArray: Array<BluesnapContractTypeList> = [];
                var cachedString = LocalStorageManager.GetItem(cacheKey);
                if (cachedString) {
                    var cachedJson = JSON.parse(cachedString);
                    for (var key in cachedJson) {

                        var entity: BluesnapContractTypeList;
                        entity = this.MapJsonToEntityList(cachedJson[key]);
                        _mappedListsArray.push(entity);
                    }

                    BluesnapContractTypeListService.CachedData = _mappedListsArray;
                    serviceResponse = new ServiceResponse();

                    var filteredData = BluesnapContractTypeListService.CachedData.filter(a => a.Code === code)[0];
                    serviceResponse.Result = filteredData;
                    serviceResponse.CallTime = callTime;

                    PerformanceLogger.InsertPerformanceLog(callTime, new Date(), 0, "BluesnapContractType", "GetSingleListFromCache", 'code=' + code);


                    return Observable.of(serviceResponse);


                }
                else {

                    return this._http.get(this._apiUrl + '/getsingle/?' + 'code=' + code, {
                        headers: authHeader
                    }).map(response => {
                        var list = response.json();

                        var entity: BluesnapContractTypeList;
                        if (list) {
                            entity = this.MapJsonToEntityList(list);
                        }

                        serviceResponse.Result = entity;
                        serviceResponse.CallTime = callTime;
                        var servertime = response.headers.get('ServerExecutionTime');
                        PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BluesnapContractType", "GetSingleList", 'code=' + code);

                        return serviceResponse;
                    }).catch(ServiceHelper.HandleServiceError);
                }
            }

            );
        }
        else {
            var filteredData = BluesnapContractTypeListService.CachedData.filter(a => a.Code === code)[0];
            serviceResponse.Result = filteredData;
            serviceResponse.CallTime = callTime;
            return Observable.of(serviceResponse);
        }
    }

    getAllFromCache(filters: ApiQueryFilters = new ApiQueryFilters(true)) {

        var callTime = new Date();
        if (!SessionLocator.UseCachedData) {
            return this.getByFilters(filters);
        }

        var exists = BluesnapContractTypeListService.CachedData.length;
        var urlparameters = '/getbyfilters?';
        var mykeys = Object.keys(filters);
        var addtionalFiltersValues = null;
        for (var i in mykeys) {
            var propName = mykeys[i];
            var propValue = filters[propName];

            var ignoreFilter = ((propName.indexOf("Operator") > 0 && propValue == "Equals") || propName == "AdditionalFilters");

            if (urlparameters != "?") {
                urlparameters = urlparameters.concat('&');
            }
            if (!ignoreFilter) {
                if (exists === 0 || filters.ForceCacheRefresh) {
                    propValue = encodeURIComponent(propValue);
                }

                urlparameters = urlparameters.concat(propName.concat('=').concat(propValue));
            }

            if (propName == "AdditionalFilters" && propValue.length > 0)
                addtionalFiltersValues = JSON.stringify(propValue);


        }
        if (addtionalFiltersValues) {
            urlparameters = urlparameters.concat("&AdditionalFilters=").concat(addtionalFiltersValues);
        }



        var authHeader = new Headers();
        authHeader.append('Token', SessionInfo.Token);
        var callUrl = this._apiUrl.concat(urlparameters);//


        if (exists === 0 || filters.ForceCacheRefresh) {
            var cacheKey = "BluesnapContractType_CachedData_" + filters.Tenant;
            var _mappedListsArray: Array<BluesnapContractTypeList> = [];
            var serviceResponse: ServiceResponse;

            if (!filters.ForceCacheRefresh) {
                var cachedString = LocalStorageManager.GetItem(cacheKey);
                if (cachedString) {
                    var cachedJson = JSON.parse(cachedString);
                    for (var key in cachedJson) {

                        var entity: BluesnapContractTypeList;
                        entity = this.MapJsonToEntityList(cachedJson[key]);
                        _mappedListsArray.push(entity);
                    }

                    BluesnapContractTypeListService.CachedData = _mappedListsArray;
                    serviceResponse = new ServiceResponse();
                    if (!filters.GetAll) {
                        _mappedListsArray = InfraGenericFilter.GetFilteredArray(_mappedListsArray, filters);
                    }
                    serviceResponse.Result = _mappedListsArray;
                    serviceResponse.CallTime = callTime;

                    PerformanceLogger.InsertPerformanceLog(callTime, new Date(), 0, "BluesnapContractType", "GetAllFromCache", "");


                }
            }
            if (serviceResponse) {
                return Observable.of(serviceResponse);
            }
            else {
                return Observable.defer(() => {
                    return this._http.get(callUrl, {
                        headers: authHeader
                    }).map(response => {

                        var serviceResponse: ServiceResponse;
                        serviceResponse = response.json();

                        if (serviceResponse.Result) {
                            for (var key in serviceResponse.Result) {

                                var entity: BluesnapContractTypeList;
                                entity = this.MapJsonToEntityList(serviceResponse.Result[key]);
                                _mappedListsArray.push(entity);

                            }
                        }
                        if (filters.GetAll) {
                            LocalStorageManager.SetItem(cacheKey, JSON.stringify(_mappedListsArray))
                            BluesnapContractTypeListService.CachedData = _mappedListsArray;
                        }
                        else {

                            _mappedListsArray = InfraGenericFilter.GetFilteredArray(_mappedListsArray, filters);
                        }
                        serviceResponse.Result = _mappedListsArray;
                        serviceResponse.CallTime = callTime;

                        var servertime = response.headers.get('ServerExecutionTime');
                        PerformanceLogger.InsertPerformanceLog(callTime, new Date(), Number(servertime), "BluesnapContractType", "GetAll", "");

                        return serviceResponse;
                    }).catch(ServiceHelper.HandleServiceError);
                });
            }
        }
        else {
            var filteredData = BluesnapContractTypeListService.CachedData;
            if (!filters.GetAll) {

                filteredData = InfraGenericFilter.GetFilteredArray(filteredData, filters);
            }
            var serviceResponse: ServiceResponse;
            serviceResponse = new ServiceResponse();
            serviceResponse.Result = filteredData;
            serviceResponse.CallTime = callTime;

            return Observable.of(serviceResponse);
        }
    }

    MapJsonToEntityList(jsonList: any) {

        var entityList: BluesnapContractTypeList;
        entityList = new BluesnapContractTypeList();
        var jsonListKeys = Object.keys(jsonList);

        for (var key in jsonListKeys) {
            var property = jsonListKeys[key];
            entityList[property] = jsonList[property];
        }


        return entityList;
    }

}

