import { RegexSelectors } from '../RegexSelectors';

export class SharedLogisticsSelectors extends RegexSelectors {

    public static readonly SharedLogisticsTab="[id='GeneralMHSharedLogistics']"
    public static readonly SharedLogisticsSettings='[data-cy="Settings"]'
    public static readonly ActivationWizard='[data-cy="Activation Wizard"]'
    public static readonly ActivateSharedLogistics='[data-cy="Activate Shared Logistics"]'
    public static readonly ActivateWebAccess='[data-cy="Activate Web Access"]'
    public static readonly ActivateMobile='[data-cy="Activate Mobile"]'
    public static readonly SendLinkInEmailMessagesToYourPartners='[data-cy="Send Link in email messages to your partners"]'
    public static readonly DisplayDocumentsAndEventsInMessagesLink='[data-cy="Display Documents & Events in messages link_input"]'   
    public static readonly EnableMastersDocumentsLinkForAgents='[data-cy="Enable Masters Documents Link for Agents"]'
    public static readonly EventsPermissions='[data-cy="Events Permissions"]'
    public static readonly DocumentsPermissions='[data-cy="Documents Permissions"]'
    public static readonly PartnersPermissions='[data-cy="Partners Permissions"]'
    public static readonly MoneyPermissions='[data-cy="Money Permissions"]'
    public static readonly AirManifestDoc='[data-cy="Air Manifest"]'
    public static readonly AirWaybillLabelsDoc='[data-cy="Air waybill- Labels"]'
    public static readonly ArrivalNoticeDoc='[data-cy="Arrival Notice"]'
    public static readonly Shipper='[data-cy="Shipper_input"]'
    public static readonly Consignee='[data-cy="Consignee_input"]'
    public static readonly Agent='[data-cy="Agent_input"]'
    public static readonly ShipperNotExporter='[data-cy="Shipper Not Exporter_input"]'
    public static readonly ConsigneeNotImporter='[data-cy="Consignee Not Importer_input"]'
    public static readonly Notify1='[data-cy="Notify 1_input"]'
    public static readonly Notify2='[data-cy="Notify 2_input"]'
    public static readonly FreightForwarder='[data-cy="Freight Forwarder_input"]'
    public static readonly Coloader='[data-cy="Coloader_input"]'
    public static readonly InvoicesMenu='[data-cy="Invoices menu_input"]'
    public static readonly MoneyTab='[data-cy="Money tab_input"]'
    public static readonly AmountInLocalCurrencyColumn='[data-cy="Amount in Local Currency column_input"]'
    public static readonly InviteCustomers='[data-cy="Invite Customers"]'
    public static readonly FirstCustomer='[id="row0col0"]'
    public static readonly NewContact='[data-cy="New Contact"]'
    public static readonly Invite='[data-cy="Invite"]'
    public static readonly  Message='[data-cy="Message"]'
    public static readonly BackBottun='[class="BackBottun"]'
    public static readonly NotInvitedCustomersCount='[data-cy="NotInvitedCustomersCount"]'
    public static readonly InvitedCustomersCount='[data-cy="InvitedCustomersCount"]'
    public static readonly CustomerCode='[data-cy="CustomerCode"]'
    public static readonly Search='[placeholder="Search names/ vat.#/ City/ Country"]'
    public static readonly row0='[id="LogGrid_0_1row0"]'
    public static readonly CellContent='[class="CellContent"]'
}