export class WarehousesSelectors {

   public static readonly MaintenanceItem = "#MaintenanceItemMTWH"
   public static readonly SaveButton = "#Warehouse-Save"
   public static readonly SaveCloseButton = "#Warehouse-SaveClose"
   public static readonly CompanyName = "#Address_Name"
   public static readonly City = "#Address_City"
   public static readonly Country = "#Address_CountryId"
   public static readonly Code = "#Address_CardCode"
   public static readonly Notes = "#Warehouse_Notes"
   public static readonly BankName = "#Warehouse_BankName"
   public static readonly VatNumber = "#Warehouse_VatNumber"
   public static readonly IBANNumber = "#Warehouse_IBANNumber"
   public static readonly BillingTab = "#WarehouseTHBilling"
   public static readonly EventsTab = "#WarehouseTHEvents"
   public static readonly Type = "#Warehouse_TypeCode"
   public static readonly TerminalCode = "#Warehouse_FirmCode"
   public static readonly InactiveCheckBox = "#Warehouse_InActive"
   public static readonly MyWarehouseCheckBox = "#Warehouse_MyWarehouse"
   public static readonly Swift = "#Warehouse_Swift"
   public static readonly BankAddress = "#Warehouse_BankAddress"
}