//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 08/09/2014 18:08:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace Unifreight.Data.AmitalModel.EntityPOCOs
{

    /// <summary>
    /// There are no comments for Unifreight.Data.AmitalModel.GNDCARD in the schema.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    public partial class GNDCARD : INotifyPropertyChanged    {

        public GNDCARD()
        {
        }

        #region Properties
    
        /// <summary>
        /// There are no comments for CARDID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string CARDID
        {
            get
            {
                return _CARDID;
            }
            set
            {
                if (_CARDID != value)
                {
                    _CARDID = value;
                    OnPropertyChanged("CARDID");
                }
            }
        }
        private string _CARDID;

    
        /// <summary>
        /// There are no comments for NAMEHEB in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string NAMEHEB
        {
            get
            {
                return _NAMEHEB;
            }
            set
            {
                if (_NAMEHEB != value)
                {
                    _NAMEHEB = value;
                    OnPropertyChanged("NAMEHEB");
                }
            }
        }
        private string _NAMEHEB;

    
        /// <summary>
        /// There are no comments for NAMEENG in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string NAMEENG
        {
            get
            {
                return _NAMEENG;
            }
            set
            {
                if (_NAMEENG != value)
                {
                    _NAMEENG = value;
                    OnPropertyChanged("NAMEENG");
                }
            }
        }
        private string _NAMEENG;

    
        /// <summary>
        /// There are no comments for SHNAMEHEB in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string SHNAMEHEB
        {
            get
            {
                return _SHNAMEHEB;
            }
            set
            {
                if (_SHNAMEHEB != value)
                {
                    _SHNAMEHEB = value;
                    OnPropertyChanged("SHNAMEHEB");
                }
            }
        }
        private string _SHNAMEHEB;

    
        /// <summary>
        /// There are no comments for GROUPID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Nullable<int> GROUPID
        {
            get
            {
                return _GROUPID;
            }
            set
            {
                if (_GROUPID != value)
                {
                    _GROUPID = value;
                    OnPropertyChanged("GROUPID");
                }
            }
        }
        private global::System.Nullable<int> _GROUPID;

    
        /// <summary>
        /// There are no comments for SHNAMEENG in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string SHNAMEENG
        {
            get
            {
                return _SHNAMEENG;
            }
            set
            {
                if (_SHNAMEENG != value)
                {
                    _SHNAMEENG = value;
                    OnPropertyChanged("SHNAMEENG");
                }
            }
        }
        private string _SHNAMEENG;

    
        /// <summary>
        /// There are no comments for BLOCKRECORD in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string BLOCKRECORD
        {
            get
            {
                return _BLOCKRECORD;
            }
            set
            {
                if (_BLOCKRECORD != value)
                {
                    _BLOCKRECORD = value;
                    OnPropertyChanged("BLOCKRECORD");
                }
            }
        }
        private string _BLOCKRECORD;

    
        /// <summary>
        /// There are no comments for OLDCARD in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string OLDCARD
        {
            get
            {
                return _OLDCARD;
            }
            set
            {
                if (_OLDCARD != value)
                {
                    _OLDCARD = value;
                    OnPropertyChanged("OLDCARD");
                }
            }
        }
        private string _OLDCARD;

    
        /// <summary>
        /// There are no comments for APPLE in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLE
        {
            get
            {
                return _APPLE;
            }
            set
            {
                if (_APPLE != value)
                {
                    _APPLE = value;
                    OnPropertyChanged("APPLE");
                }
            }
        }
        private string _APPLE;

    
        /// <summary>
        /// There are no comments for APPLI in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLI
        {
            get
            {
                return _APPLI;
            }
            set
            {
                if (_APPLI != value)
                {
                    _APPLI = value;
                    OnPropertyChanged("APPLI");
                }
            }
        }
        private string _APPLI;

    
        /// <summary>
        /// There are no comments for APPLM in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLM
        {
            get
            {
                return _APPLM;
            }
            set
            {
                if (_APPLM != value)
                {
                    _APPLM = value;
                    OnPropertyChanged("APPLM");
                }
            }
        }
        private string _APPLM;

    
        /// <summary>
        /// There are no comments for APPLR in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLR
        {
            get
            {
                return _APPLR;
            }
            set
            {
                if (_APPLR != value)
                {
                    _APPLR = value;
                    OnPropertyChanged("APPLR");
                }
            }
        }
        private string _APPLR;

    
        /// <summary>
        /// There are no comments for APPLH in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLH
        {
            get
            {
                return _APPLH;
            }
            set
            {
                if (_APPLH != value)
                {
                    _APPLH = value;
                    OnPropertyChanged("APPLH");
                }
            }
        }
        private string _APPLH;

    
        /// <summary>
        /// There are no comments for APPLT in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLT
        {
            get
            {
                return _APPLT;
            }
            set
            {
                if (_APPLT != value)
                {
                    _APPLT = value;
                    OnPropertyChanged("APPLT");
                }
            }
        }
        private string _APPLT;

    
        /// <summary>
        /// There are no comments for APPLQ in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLQ
        {
            get
            {
                return _APPLQ;
            }
            set
            {
                if (_APPLQ != value)
                {
                    _APPLQ = value;
                    OnPropertyChanged("APPLQ");
                }
            }
        }
        private string _APPLQ;

    
        /// <summary>
        /// There are no comments for APPLC in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLC
        {
            get
            {
                return _APPLC;
            }
            set
            {
                if (_APPLC != value)
                {
                    _APPLC = value;
                    OnPropertyChanged("APPLC");
                }
            }
        }
        private string _APPLC;

    
        /// <summary>
        /// There are no comments for APPLS in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLS
        {
            get
            {
                return _APPLS;
            }
            set
            {
                if (_APPLS != value)
                {
                    _APPLS = value;
                    OnPropertyChanged("APPLS");
                }
            }
        }
        private string _APPLS;

    
        /// <summary>
        /// There are no comments for APPLF in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLF
        {
            get
            {
                return _APPLF;
            }
            set
            {
                if (_APPLF != value)
                {
                    _APPLF = value;
                    OnPropertyChanged("APPLF");
                }
            }
        }
        private string _APPLF;

    
        /// <summary>
        /// There are no comments for APPLJ in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLJ
        {
            get
            {
                return _APPLJ;
            }
            set
            {
                if (_APPLJ != value)
                {
                    _APPLJ = value;
                    OnPropertyChanged("APPLJ");
                }
            }
        }
        private string _APPLJ;

    
        /// <summary>
        /// There are no comments for APPLK in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLK
        {
            get
            {
                return _APPLK;
            }
            set
            {
                if (_APPLK != value)
                {
                    _APPLK = value;
                    OnPropertyChanged("APPLK");
                }
            }
        }
        private string _APPLK;

    
        /// <summary>
        /// There are no comments for APPLN in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLN
        {
            get
            {
                return _APPLN;
            }
            set
            {
                if (_APPLN != value)
                {
                    _APPLN = value;
                    OnPropertyChanged("APPLN");
                }
            }
        }
        private string _APPLN;

    
        /// <summary>
        /// There are no comments for PROFID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string PROFID
        {
            get
            {
                return _PROFID;
            }
            set
            {
                if (_PROFID != value)
                {
                    _PROFID = value;
                    OnPropertyChanged("PROFID");
                }
            }
        }
        private string _PROFID;

    
        /// <summary>
        /// There are no comments for COMPANYID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string COMPANYID
        {
            get
            {
                return _COMPANYID;
            }
            set
            {
                if (_COMPANYID != value)
                {
                    _COMPANYID = value;
                    OnPropertyChanged("COMPANYID");
                }
            }
        }
        private string _COMPANYID;

    
        /// <summary>
        /// There are no comments for OLDCARDAUTOCREATED in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string OLDCARDAUTOCREATED
        {
            get
            {
                return _OLDCARDAUTOCREATED;
            }
            set
            {
                if (_OLDCARDAUTOCREATED != value)
                {
                    _OLDCARDAUTOCREATED = value;
                    OnPropertyChanged("OLDCARDAUTOCREATED");
                }
            }
        }
        private string _OLDCARDAUTOCREATED;

    
        /// <summary>
        /// There are no comments for APPLL in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string APPLL
        {
            get
            {
                return _APPLL;
            }
            set
            {
                if (_APPLL != value)
                {
                    _APPLL = value;
                    OnPropertyChanged("APPLL");
                }
            }
        }
        private string _APPLL;

    
        /// <summary>
        /// There are no comments for BLOCKREASON in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string BLOCKREASON
        {
            get
            {
                return _BLOCKREASON;
            }
            set
            {
                if (_BLOCKREASON != value)
                {
                    _BLOCKREASON = value;
                    OnPropertyChanged("BLOCKREASON");
                }
            }
        }
        private string _BLOCKREASON;

    
        /// <summary>
        /// There are no comments for EXPORTCOMPANYID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string EXPORTCOMPANYID
        {
            get
            {
                return _EXPORTCOMPANYID;
            }
            set
            {
                if (_EXPORTCOMPANYID != value)
                {
                    _EXPORTCOMPANYID = value;
                    OnPropertyChanged("EXPORTCOMPANYID");
                }
            }
        }
        private string _EXPORTCOMPANYID;

    
        /// <summary>
        /// There are no comments for REMARKS in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string REMARKS
        {
            get
            {
                return _REMARKS;
            }
            set
            {
                if (_REMARKS != value)
                {
                    _REMARKS = value;
                    OnPropertyChanged("REMARKS");
                }
            }
        }
        private string _REMARKS;


        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
