//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 9/24/2021 6:23:09 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace Unifreight.Data.AmitalModel.EntityPOCOs
{
    [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    public partial class RTBPORT : INotifyPropertyChanged
    {

        public RTBPORT()
        {
            OnCreated();
        }

        #region Properties

        [System.Runtime.Serialization.DataMember]
        public virtual string PORTID
        {
            get
            {
                return _PORTID;
            }
            set
            {
                if (_PORTID != value)
                {
                    _PORTID = value;
                    OnPropertyChanged("PORTID");
                }
            }
        }
        private string _PORTID;

        [System.Runtime.Serialization.DataMember]
        public virtual string SEARCHENG
        {
            get
            {
                return _SEARCHENG;
            }
            set
            {
                if (_SEARCHENG != value)
                {
                    _SEARCHENG = value;
                    OnPropertyChanged("SEARCHENG");
                }
            }
        }
        private string _SEARCHENG;

        [System.Runtime.Serialization.DataMember]
        public virtual string NAMEHEB
        {
            get
            {
                return _NAMEHEB;
            }
            set
            {
                if (_NAMEHEB != value)
                {
                    _NAMEHEB = value;
                    OnPropertyChanged("NAMEHEB");
                }
            }
        }
        private string _NAMEHEB;

        [System.Runtime.Serialization.DataMember]
        public virtual string NAMEENG
        {
            get
            {
                return _NAMEENG;
            }
            set
            {
                if (_NAMEENG != value)
                {
                    _NAMEENG = value;
                    OnPropertyChanged("NAMEENG");
                }
            }
        }
        private string _NAMEENG;

        [System.Runtime.Serialization.DataMember]
        public virtual string COUNTRYID
        {
            get
            {
                return _COUNTRYID;
            }
            set
            {
                if (_COUNTRYID != value)
                {
                    _COUNTRYID = value;
                    OnPropertyChanged("COUNTRYID");
                }
            }
        }
        private string _COUNTRYID;

        [System.Runtime.Serialization.DataMember]
        public virtual string AGENTID
        {
            get
            {
                return _AGENTID;
            }
            set
            {
                if (_AGENTID != value)
                {
                    _AGENTID = value;
                    OnPropertyChanged("AGENTID");
                }
            }
        }
        private string _AGENTID;

        [System.Runtime.Serialization.DataMember]
        public virtual string BLOCKRECORD
        {
            get
            {
                return _BLOCKRECORD;
            }
            set
            {
                if (_BLOCKRECORD != value)
                {
                    _BLOCKRECORD = value;
                    OnPropertyChanged("BLOCKRECORD");
                }
            }
        }
        private string _BLOCKRECORD;

        [System.Runtime.Serialization.DataMember]
        public virtual string TIMEZONE
        {
            get
            {
                return _TIMEZONE;
            }
            set
            {
                if (_TIMEZONE != value)
                {
                    _TIMEZONE = value;
                    OnPropertyChanged("TIMEZONE");
                }
            }
        }
        private string _TIMEZONE;

        #endregion

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
