//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> ShipmentClassesGenerator.tt
//---
using System;
using System.Threading.Tasks;
using System.Data.Entity.ModelConfiguration;
using POCO = AmitalCloud.Shipment.Domain.EntityPOCOs;
 
namespace AmitalCloud.Shipment.Domain.EntityMapping
{
 
    public class CustomsTransferTypeMap : EntityTypeConfiguration<POCO.CustomsTransferType>
    {
	    string dbms;
        public CustomsTransferTypeMap()
        { 
				this.ToTable("CustomsTransferTypes");
		
		    this.HasKey(t => new { t.Code });
	 
            this.Property(t => t.Code).HasColumnName("Code").HasMaxLength(4).IsUnicode(false);

            this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(40).IsUnicode(false);

            this.Property(t => t.SearchFields).HasColumnName("SearchFields").HasMaxLength(1000).IsUnicode(true);
        }
    }
}
	 