//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using AmitalCloud.Infrastructure.Domain.BaseClasses;
using AmitalCloud.Infrastructure.Domain.EntityPOCOs;
namespace AmitalCloud.Infrastructure.Domain.EntityPOCOs
{
    public class TenantManagementLicense : BaseEntity
	{
		
        [Key]
        [Column("Id")]
	    public string Id { get; set; }
        [Column("Tenant")]
	    public int Tenant { get; set; }
        [Column("PackageCode")]
	    public string PackageCode { get; set; }
        [Column("NumberOfUsers")]
	    public int? NumberOfUsers { get; set; }
        [Column("FreeUsers")]
	    public int? FreeUsers { get; set; }
        [Column("Price")]
	    public double? Price { get; set; }
        [Column("TotalPrice")]
	    public double? TotalPrice { get; set; }
    }
}
	 