// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Logitude.ShipmentTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PUTShipmentDirectExportAirFeature : object, Xunit.IClassFixture<PUTShipmentDirectExportAirFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "APIPUTShipmentDirectExportAir.feature"
#line hidden
        
        public PUTShipmentDirectExportAirFeature(PUTShipmentDirectExportAirFeature.FixtureData fixtureData, Logitude_ShipmentTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "PUT Shipment Direct Export Air", "\tThe API updates a Direct Export Air shipment details, adds packages, \r\n\tpayables" +
                    ", receivables and creates a new agent as a partner.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PUT Shipment Direct Export Air")]
        [Xunit.TraitAttribute("FeatureTitle", "PUT Shipment Direct Export Air")]
        [Xunit.TraitAttribute("Description", "PUT Shipment Direct Export Air")]
        [Xunit.TraitAttribute("Category", "Smoke")]
        [Xunit.TraitAttribute("Category", "Release")]
        public void PUTShipmentDirectExportAir()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke",
                    "Release"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PUT Shipment Direct Export Air", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "Value"});
                table16.AddRow(new string[] {
                            "Quantity",
                            "200"});
                table16.AddRow(new string[] {
                            "Length",
                            "100"});
                table16.AddRow(new string[] {
                            "Width",
                            "100"});
                table16.AddRow(new string[] {
                            "Weight",
                            "200"});
                table16.AddRow(new string[] {
                            "Height",
                            "100"});
#line 7
 testRunner.Given("a direct package with the following properties", ((string)(null)), table16, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "Value"});
                table17.AddRow(new string[] {
                            "ChargesTypeName",
                            "Air Freight"});
                table17.AddRow(new string[] {
                            "ChargesType",
                            "AFT"});
                table17.AddRow(new string[] {
                            "Measurement",
                            "GRWT"});
                table17.AddRow(new string[] {
                            "UnitPrice",
                            "60"});
                table17.AddRow(new string[] {
                            "Currency",
                            "EUR"});
                table17.AddRow(new string[] {
                            "ShipmentPayableLineStatus",
                            "OAMT"});
#line 14
 testRunner.And("a direct payable with the following properties", ((string)(null)), table17, "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "Value"});
                table18.AddRow(new string[] {
                            "ChargesTypeName",
                            "Air Freight"});
                table18.AddRow(new string[] {
                            "ChargesType",
                            "AFT"});
                table18.AddRow(new string[] {
                            "Measurement",
                            "GRWT"});
                table18.AddRow(new string[] {
                            "Currency",
                            "EUR"});
                table18.AddRow(new string[] {
                            "ShipmentReceivableLineStatusCode",
                            "OAMT"});
#line 22
 testRunner.And("a direct receivable with the following properties", ((string)(null)), table18, "And ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "Value"});
                table19.AddRow(new string[] {
                            "PartnerType",
                            "AG"});
                table19.AddRow(new string[] {
                            "EnglishName",
                            "TestAgent"});
                table19.AddRow(new string[] {
                            "Country",
                            "US"});
#line 29
 testRunner.And("a partners with the following properties", ((string)(null)), table19, "And ");
#line hidden
#line 34
 testRunner.And("a direct shipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
 testRunner.When("update a direct shipment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.Then("the direct should update successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PUTShipmentDirectExportAirFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PUTShipmentDirectExportAirFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
