//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logitude.HybridTest.CardContactServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardContactPM", Namespace="http://schemas.datacontract.org/2004/07/Logitude.BL.CommonDataModel.EntityPMs")]
    [System.SerializableAttribute()]
    public partial class CardContactPM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Logitude.HybridTest.CardContactServiceReference.CardContactAdditionalServicePM[] CardContactAdditionalServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Logitude.HybridTest.CardContactServiceReference.CardContactProductPM[] CardContactProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InternetAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAirExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAirImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAllField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCustomsImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHybridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInlandDomesticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInlandExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInlandImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOceanExportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOceanImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Logitude.HybridTest.CardContactServiceReference.CardContactAdditionalServicePM[] CardContactAdditionalServices {
            get {
                return this.CardContactAdditionalServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.CardContactAdditionalServicesField, value) != true)) {
                    this.CardContactAdditionalServicesField = value;
                    this.RaisePropertyChanged("CardContactAdditionalServices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Logitude.HybridTest.CardContactServiceReference.CardContactProductPM[] CardContactProducts {
            get {
                return this.CardContactProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardContactProductsField, value) != true)) {
                    this.CardContactProductsField = value;
                    this.RaisePropertyChanged("CardContactProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIdField, value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactIdField, value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InternetAccess {
            get {
                return this.InternetAccessField;
            }
            set {
                if ((this.InternetAccessField.Equals(value) != true)) {
                    this.InternetAccessField = value;
                    this.RaisePropertyChanged("InternetAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAirExport {
            get {
                return this.IsAirExportField;
            }
            set {
                if ((this.IsAirExportField.Equals(value) != true)) {
                    this.IsAirExportField = value;
                    this.RaisePropertyChanged("IsAirExport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAirImport {
            get {
                return this.IsAirImportField;
            }
            set {
                if ((this.IsAirImportField.Equals(value) != true)) {
                    this.IsAirImportField = value;
                    this.RaisePropertyChanged("IsAirImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAll {
            get {
                return this.IsAllField;
            }
            set {
                if ((this.IsAllField.Equals(value) != true)) {
                    this.IsAllField = value;
                    this.RaisePropertyChanged("IsAll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustomsImport {
            get {
                return this.IsCustomsImportField;
            }
            set {
                if ((this.IsCustomsImportField.Equals(value) != true)) {
                    this.IsCustomsImportField = value;
                    this.RaisePropertyChanged("IsCustomsImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHybrid {
            get {
                return this.IsHybridField;
            }
            set {
                if ((this.IsHybridField.Equals(value) != true)) {
                    this.IsHybridField = value;
                    this.RaisePropertyChanged("IsHybrid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInlandDomestic {
            get {
                return this.IsInlandDomesticField;
            }
            set {
                if ((this.IsInlandDomesticField.Equals(value) != true)) {
                    this.IsInlandDomesticField = value;
                    this.RaisePropertyChanged("IsInlandDomestic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInlandExport {
            get {
                return this.IsInlandExportField;
            }
            set {
                if ((this.IsInlandExportField.Equals(value) != true)) {
                    this.IsInlandExportField = value;
                    this.RaisePropertyChanged("IsInlandExport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInlandImport {
            get {
                return this.IsInlandImportField;
            }
            set {
                if ((this.IsInlandImportField.Equals(value) != true)) {
                    this.IsInlandImportField = value;
                    this.RaisePropertyChanged("IsInlandImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOceanExport {
            get {
                return this.IsOceanExportField;
            }
            set {
                if ((this.IsOceanExportField.Equals(value) != true)) {
                    this.IsOceanExportField = value;
                    this.RaisePropertyChanged("IsOceanExport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOceanImport {
            get {
                return this.IsOceanImportField;
            }
            set {
                if ((this.IsOceanImportField.Equals(value) != true)) {
                    this.IsOceanImportField = value;
                    this.RaisePropertyChanged("IsOceanImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLoginDate {
            get {
                return this.LastLoginDateField;
            }
            set {
                if ((this.LastLoginDateField.Equals(value) != true)) {
                    this.LastLoginDateField = value;
                    this.RaisePropertyChanged("LastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tenant {
            get {
                return this.TenantField;
            }
            set {
                if ((this.TenantField.Equals(value) != true)) {
                    this.TenantField = value;
                    this.RaisePropertyChanged("Tenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardContactAdditionalServicePM", Namespace="http://schemas.datacontract.org/2004/07/Logitude.BL.CommonDataModel.EntityPMs")]
    [System.SerializableAttribute()]
    public partial class CardContactAdditionalServicePM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalServiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Logitude.HybridTest.CardContactServiceReference.ChangeSetOperation ChangeSetOpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalServiceId {
            get {
                return this.AdditionalServiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalServiceIdField, value) != true)) {
                    this.AdditionalServiceIdField = value;
                    this.RaisePropertyChanged("AdditionalServiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalServiceName {
            get {
                return this.AdditionalServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalServiceNameField, value) != true)) {
                    this.AdditionalServiceNameField = value;
                    this.RaisePropertyChanged("AdditionalServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardContactId {
            get {
                return this.CardContactIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardContactIdField, value) != true)) {
                    this.CardContactIdField = value;
                    this.RaisePropertyChanged("CardContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIdField, value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Logitude.HybridTest.CardContactServiceReference.ChangeSetOperation ChangeSetOp {
            get {
                return this.ChangeSetOpField;
            }
            set {
                if ((this.ChangeSetOpField.Equals(value) != true)) {
                    this.ChangeSetOpField = value;
                    this.RaisePropertyChanged("ChangeSetOp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactIdField, value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tenant {
            get {
                return this.TenantField;
            }
            set {
                if ((this.TenantField.Equals(value) != true)) {
                    this.TenantField = value;
                    this.RaisePropertyChanged("Tenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardContactProductPM", Namespace="http://schemas.datacontract.org/2004/07/Logitude.BL.CommonDataModel.EntityPMs")]
    [System.SerializableAttribute()]
    public partial class CardContactProductPM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Logitude.HybridTest.CardContactServiceReference.ChangeSetOperation ChangeSetOpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardContactId {
            get {
                return this.CardContactIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardContactIdField, value) != true)) {
                    this.CardContactIdField = value;
                    this.RaisePropertyChanged("CardContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Logitude.HybridTest.CardContactServiceReference.ChangeSetOperation ChangeSetOp {
            get {
                return this.ChangeSetOpField;
            }
            set {
                if ((this.ChangeSetOpField.Equals(value) != true)) {
                    this.ChangeSetOpField = value;
                    this.RaisePropertyChanged("ChangeSetOp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductTypeCode {
            get {
                return this.ProductTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeCodeField, value) != true)) {
                    this.ProductTypeCodeField = value;
                    this.RaisePropertyChanged("ProductTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductTypeName {
            get {
                return this.ProductTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeNameField, value) != true)) {
                    this.ProductTypeNameField = value;
                    this.RaisePropertyChanged("ProductTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tenant {
            get {
                return this.TenantField;
            }
            set {
                if ((this.TenantField.Equals(value) != true)) {
                    this.TenantField = value;
                    this.RaisePropertyChanged("Tenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeSetOperation", Namespace="http://schemas.datacontract.org/2004/07/Simplog.Server.Infrastructure")]
    public enum ChangeSetOperation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardContactServiceReference.ICardContactWcfService")]
    public interface ICardContactWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardContactWcfService/Upsert", ReplyAction="http://tempuri.org/ICardContactWcfService/UpsertResponse")]
        Logitude.Server.Tools.Response Upsert(Logitude.HybridTest.CardContactServiceReference.CardContactPM entityPM, bool batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardContactWcfService/Upsert", ReplyAction="http://tempuri.org/ICardContactWcfService/UpsertResponse")]
        System.Threading.Tasks.Task<Logitude.Server.Tools.Response> UpsertAsync(Logitude.HybridTest.CardContactServiceReference.CardContactPM entityPM, bool batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardContactWcfService/Delete", ReplyAction="http://tempuri.org/ICardContactWcfService/DeleteResponse")]
        Logitude.Server.Tools.Response Delete(string contactExternalId, string cardCode, int tenant, bool batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardContactWcfService/Delete", ReplyAction="http://tempuri.org/ICardContactWcfService/DeleteResponse")]
        System.Threading.Tasks.Task<Logitude.Server.Tools.Response> DeleteAsync(string contactExternalId, string cardCode, int tenant, bool batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardContactWcfService/GetCardContactPM", ReplyAction="http://tempuri.org/ICardContactWcfService/GetCardContactPMResponse")]
        Logitude.HybridTest.CardContactServiceReference.GetCardContactPMResponse GetCardContactPM(Logitude.HybridTest.CardContactServiceReference.GetCardContactPMRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardContactWcfService/GetCardContactPM", ReplyAction="http://tempuri.org/ICardContactWcfService/GetCardContactPMResponse")]
        System.Threading.Tasks.Task<Logitude.HybridTest.CardContactServiceReference.GetCardContactPMResponse> GetCardContactPMAsync(Logitude.HybridTest.CardContactServiceReference.GetCardContactPMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardContactPM", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardContactPMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string contactExternalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cardCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public Logitude.Server.Tools.Response response;
        
        public GetCardContactPMRequest() {
        }
        
        public GetCardContactPMRequest(string contactExternalId, string cardCode, int tenant, Logitude.Server.Tools.Response response) {
            this.contactExternalId = contactExternalId;
            this.cardCode = cardCode;
            this.tenant = tenant;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardContactPMResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardContactPMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Logitude.HybridTest.CardContactServiceReference.CardContactPM GetCardContactPMResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Logitude.Server.Tools.Response response;
        
        public GetCardContactPMResponse() {
        }
        
        public GetCardContactPMResponse(Logitude.HybridTest.CardContactServiceReference.CardContactPM GetCardContactPMResult, Logitude.Server.Tools.Response response) {
            this.GetCardContactPMResult = GetCardContactPMResult;
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICardContactWcfServiceChannel : Logitude.HybridTest.CardContactServiceReference.ICardContactWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardContactWcfServiceClient : System.ServiceModel.ClientBase<Logitude.HybridTest.CardContactServiceReference.ICardContactWcfService>, Logitude.HybridTest.CardContactServiceReference.ICardContactWcfService {
        
        public CardContactWcfServiceClient() {
        }
        
        public CardContactWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardContactWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardContactWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardContactWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Logitude.Server.Tools.Response Upsert(Logitude.HybridTest.CardContactServiceReference.CardContactPM entityPM, bool batch) {
            return base.Channel.Upsert(entityPM, batch);
        }
        
        public System.Threading.Tasks.Task<Logitude.Server.Tools.Response> UpsertAsync(Logitude.HybridTest.CardContactServiceReference.CardContactPM entityPM, bool batch) {
            return base.Channel.UpsertAsync(entityPM, batch);
        }
        
        public Logitude.Server.Tools.Response Delete(string contactExternalId, string cardCode, int tenant, bool batch) {
            return base.Channel.Delete(contactExternalId, cardCode, tenant, batch);
        }
        
        public System.Threading.Tasks.Task<Logitude.Server.Tools.Response> DeleteAsync(string contactExternalId, string cardCode, int tenant, bool batch) {
            return base.Channel.DeleteAsync(contactExternalId, cardCode, tenant, batch);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logitude.HybridTest.CardContactServiceReference.GetCardContactPMResponse Logitude.HybridTest.CardContactServiceReference.ICardContactWcfService.GetCardContactPM(Logitude.HybridTest.CardContactServiceReference.GetCardContactPMRequest request) {
            return base.Channel.GetCardContactPM(request);
        }
        
        public Logitude.HybridTest.CardContactServiceReference.CardContactPM GetCardContactPM(string contactExternalId, string cardCode, int tenant, ref Logitude.Server.Tools.Response response) {
            Logitude.HybridTest.CardContactServiceReference.GetCardContactPMRequest inValue = new Logitude.HybridTest.CardContactServiceReference.GetCardContactPMRequest();
            inValue.contactExternalId = contactExternalId;
            inValue.cardCode = cardCode;
            inValue.tenant = tenant;
            inValue.response = response;
            Logitude.HybridTest.CardContactServiceReference.GetCardContactPMResponse retVal = ((Logitude.HybridTest.CardContactServiceReference.ICardContactWcfService)(this)).GetCardContactPM(inValue);
            response = retVal.response;
            return retVal.GetCardContactPMResult;
        }
        
        public System.Threading.Tasks.Task<Logitude.HybridTest.CardContactServiceReference.GetCardContactPMResponse> GetCardContactPMAsync(Logitude.HybridTest.CardContactServiceReference.GetCardContactPMRequest request) {
            return base.Channel.GetCardContactPMAsync(request);
        }
    }
}
