update EntityStatus set DisplayName = 'Pending Import Formalities' where Code = 'CERT'
update EntityStatus set DisplayName = 'Created' where Code = 'CSCR'
update EntityStatus set DisplayName = 'Declaration Data Approved' where Code = 'DDAP'
update EntityStatus set DisplayName = 'Declaration Data Denied' where Code = 'DDDE'
update EntityStatus set DisplayName = 'Delivered to Customs Agent' where Code = 'DTCA'
update EntityStatus set DisplayName = 'Export Custom Clearance' where Code = 'ECCL'
update EntityStatus set DisplayName = 'Import Custom Clearance' where Code = 'ICCL'
update EntityStatus set DisplayName = 'In Progress' where Code = 'INPR'
update EntityStatus set DisplayName = 'In Progress' where Code = 'INPS'
update EntityStatus set DisplayName = 'In Warehouse' where Code = 'INWH'
update EntityStatus set DisplayName = 'On Carriage Departed' where Code = 'ONCD'
update EntityStatus set DisplayName = 'Pre Carriage Arrived' where Code = 'PRCA'
update EntityStatus set DisplayName = 'Available for Delivery' where Code = 'SAFD'
update EntityStatus set DisplayName = 'Leg 1 Arrived' where Code = 'SAR2'
update EntityStatus set DisplayName = 'Leg 2 Arrived' where Code = 'SAR3'
update EntityStatus set DisplayName = 'Leg 3 Arrived' where Code = 'SAR4'
update EntityStatus set DisplayName = 'On Carriage Arrived' where Code = 'SAR5'
update EntityStatus set DisplayName = 'Arrived at Destination' where Code = 'SARR'
update EntityStatus set DisplayName = 'Leg 1 Departed' where Code = 'SDE2'
update EntityStatus set DisplayName = 'Leg 2 Departed' where Code = 'SDE3'
update EntityStatus set DisplayName = 'Leg 3 Departed' where Code = 'SDE4'
update EntityStatus set DisplayName = 'Pre Carriage Departed' where Code = 'SDE5'
update EntityStatus set DisplayName = 'Departed' where Code = 'SDEP'
update EntityStatus set DisplayName = 'Delivery Arranged' where Code = 'SDL2'
update EntityStatus set DisplayName = 'Delivered' where Code = 'SDLD'
update EntityStatus set DisplayName = 'Delivery Departed' where Code = 'SDLY'
update EntityStatus set DisplayName = 'Cleared' where Code = 'SHCL'
update EntityStatus set DisplayName = 'In Transit' where Code = 'SHIT'
update EntityStatus set DisplayName = 'On Hand' where Code = 'SHON'
update EntityStatus set DisplayName = 'Order' where Code = 'SHOR'
update EntityStatus set DisplayName = 'Pick Up Arranged' where Code = 'SHP2'
update EntityStatus set DisplayName = 'Picked Up' where Code = 'SHPK'



