// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Logitude.CrossDockTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "Pre-Prepare-Entry")]
    public partial class CreateCrossDocksFeature : object, Xunit.IClassFixture<CreateCrossDocksFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "Pre-Prepare-Entry"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateCrossDocks.feature"
#line hidden
        
        public CreateCrossDocksFeature(CreateCrossDocksFeature.FixtureData fixtureData, Logitude_CrossDockTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Create Cross Docks", "    With pre-prepared entry data\r\n\tWe want to create entry and release cross dock" +
                    "s.", ProgrammingLanguage.CSharp, new string[] {
                        "Pre-Prepare-Entry"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create entry cross dock")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Cross Docks")]
        [Xunit.TraitAttribute("Description", "Create entry cross dock")]
        public virtual void CreateEntryCrossDock()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create entry cross dock", null, tagsOfScenario, argumentsOfScenario);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "Value"});
                table1.AddRow(new string[] {
                            "Direction",
                            "Export"});
                table1.AddRow(new string[] {
                            "TransportMode",
                            "Air"});
                table1.AddRow(new string[] {
                            "ChargeableWeightUnitCode",
                            "KG"});
                table1.AddRow(new string[] {
                            "GrossWeightUnitCode",
                            "KG"});
                table1.AddRow(new string[] {
                            "DimensionsUnitCode",
                            "Cm"});
                table1.AddRow(new string[] {
                            "VolumeUnitCode",
                            "CBM"});
                table1.AddRow(new string[] {
                            "StatusCode",
                            "CREA"});
#line 7
 testRunner.Given("an entry cross dock with the following properties", ((string)(null)), table1, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Quantity",
                            "Length",
                            "Width",
                            "Height",
                            "Weight"});
                table2.AddRow(new string[] {
                            "70",
                            "10",
                            "20",
                            "30",
                            "40"});
                table2.AddRow(new string[] {
                            "50",
                            "",
                            "",
                            "",
                            ""});
#line 16
 testRunner.And("packages details", ((string)(null)), table2, "And ");
#line hidden
#line 20
 testRunner.When("create entry cross dock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
 testRunner.Then("the entry cross dock should create successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create release cross dock")]
        [Xunit.TraitAttribute("FeatureTitle", "Create Cross Docks")]
        [Xunit.TraitAttribute("Description", "Create release cross dock")]
        public virtual void CreateReleaseCrossDock()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create release cross dock", null, tagsOfScenario, argumentsOfScenario);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "Value"});
                table3.AddRow(new string[] {
                            "ChargeableWeightUnitCode",
                            "KG"});
                table3.AddRow(new string[] {
                            "GrossWeightUnitCode",
                            "KG"});
                table3.AddRow(new string[] {
                            "DimensionsUnitCode",
                            "Cm"});
                table3.AddRow(new string[] {
                            "VolumeUnitCode",
                            "CBM"});
                table3.AddRow(new string[] {
                            "StatusCode",
                            "CREA"});
#line 24
 testRunner.Given("a release cross dock with the following properties", ((string)(null)), table3, "Given ");
#line hidden
#line 31
 testRunner.And("an entry cross dock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
 testRunner.When("create release cross dock", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
 testRunner.Then("the release cross dock should create successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateCrossDocksFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateCrossDocksFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
