<!ELEMENT LOGICOMMDEC (LogitudeCommDecFile*)>
<!ELEMENT LogitudeCommDecFile (CustomFileNo?, Id?, DeclarationOfficeCode?, FileState?, AgentId?, CustomerId?, TransportModeId?, CreatedByUserId?, ReferentUserId?, DepartmentId?, MAWB?, DealId?, HAWB?, ManifestNumber?, LoadingPortCode?, OriginCountryCode?, CargoDescription?, PackageTypeCode?, PackageMeasureQualifierCode?, PackageQuantity?, GrossMassMeasure?, VendorId?, ImporterId?, Tenant?, GrantDate?, ManifestDate?, ArrivalDateTime?, Mode?, EnglishName?, HebrewName?, ISLASTRELEASEFROMWAREHOUS?, EntryFile?, OriginCountryId?, WarehouseId?, TransferImporterId?, ImporterEntitlementTypeCode?, INVOICE*, PACKAGES*, agent_fee?, agent_fee_currency?, CustomsDocuments*, TaxationDateTime?, CarrierPrefix?, IsAutonomy?, SiteCode?, CrateNumber?, shopId?)>
<!ELEMENT CustomFileNo (#PCDATA)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT DeclarationOfficeCode (#PCDATA)>
<!ELEMENT FileState (#PCDATA)>
<!ELEMENT AgentId (#PCDATA)>
<!ELEMENT CustomerId (#PCDATA)>
<!ELEMENT TransportModeId (#PCDATA)>
<!ELEMENT CreatedByUserId (#PCDATA)>
<!ELEMENT ReferentUserId (#PCDATA)>
<!ELEMENT DepartmentId (#PCDATA)>
<!ELEMENT MAWB (#PCDATA)>
<!ELEMENT DealId (#PCDATA)>
<!ELEMENT HAWB (#PCDATA)>
<!ELEMENT ManifestNumber (#PCDATA)>
<!ELEMENT LoadingPortCode (#PCDATA)>
<!ELEMENT OriginCountryCode (#PCDATA)>
<!ELEMENT CargoDescription (#PCDATA)>
<!ELEMENT PackageTypeCode (#PCDATA)>
<!ELEMENT PackageMeasureQualifierCode (#PCDATA)>
<!ELEMENT PackageQuantity (#PCDATA)>
<!ELEMENT GrossMassMeasure (#PCDATA)>
<!ELEMENT VendorId (#PCDATA)>
<!ELEMENT ImporterId (#PCDATA)>
<!ELEMENT Tenant (#PCDATA)>
<!ELEMENT GrantDate (#PCDATA)>
<!ELEMENT ManifestDate (#PCDATA)>
<!ELEMENT ArrivalDateTime (#PCDATA)>
<!ELEMENT Mode (#PCDATA)>
<!ELEMENT EnglishName (#PCDATA)>
<!ELEMENT HebrewName (#PCDATA)>
<!ELEMENT ISLASTRELEASEFROMWAREHOUS (#PCDATA)>
<!ELEMENT EntryFile (#PCDATA)>
<!ELEMENT OriginCountryId (#PCDATA)>
<!ELEMENT WarehouseId (#PCDATA)>
<!ELEMENT TransferImporterId (#PCDATA)>
<!ELEMENT ImporterEntitlementTypeCode (#PCDATA)>
<!ELEMENT INVOICE (INVOICELINENO?, ACCOUNTTYPE?, INVOICENUMBER?, VENDORNUMBER?, CURRENCYCODE?, INVOICEAMOUNT?, ISSUEDATE?, ISSUECOUNTRYCODE?, TRANSP_VALUE?, TRANSP_VALUE_CURR?, INSURANCE_AMNT?, INSURANCE_PERCENT?, INSURANCE_VALUE?, INSURANCE_CURR?, INCOTERM_ID?, INVOICEITEMS*, TRANSP_VALUE_LIST*, IS_PREFERENCE?, TRADE_AGREEMENT?)>
<!ELEMENT INVOICELINENO (#PCDATA)>
<!ELEMENT ACCOUNTTYPE (#PCDATA)>
<!ELEMENT INVOICENUMBER (#PCDATA)>
<!ELEMENT VENDORNUMBER (#PCDATA)>
<!ELEMENT CURRENCYCODE (#PCDATA)>
<!ELEMENT INVOICEAMOUNT (#PCDATA)>
<!ELEMENT ISSUEDATE (#PCDATA)>
<!ELEMENT ISSUECOUNTRYCODE (#PCDATA)>
<!ELEMENT TRANSP_VALUE (#PCDATA)>
<!ELEMENT TRANSP_VALUE_CURR (#PCDATA)>
<!ELEMENT INSURANCE_AMNT (#PCDATA)>
<!ELEMENT INSURANCE_PERCENT (#PCDATA)>
<!ELEMENT INSURANCE_VALUE (#PCDATA)>
<!ELEMENT INSURANCE_CURR (#PCDATA)>
<!ELEMENT INCOTERM_ID (#PCDATA)>
<!ELEMENT INVOICEITEMS (ITEMLINENO?, CLASSIFICATIONCODE?, TRADEAGREEMENTCODE?, QUANTITY?, UNIT?, QUANTITY_STS?, QUANTITY_TYPE?, ITEMPRICE?, ITEMORIGINCOUNTRY?, ITEMCODE?, ACTUALINVOICELINES?, CURRENCY?, ITEM_COUNTERKEY?, PREFERENCEDOCUMENTNUMBER?, TAXEXEMPTCODE?, PROCESSTYPE?, StatisticQuantityType?, CERTIFICATES*, POINTERS*, CARS*)>
<!ELEMENT ITEMLINENO (#PCDATA)>
<!ELEMENT CLASSIFICATIONCODE (#PCDATA)>
<!ELEMENT TRADEAGREEMENTCODE (#PCDATA)>
<!ELEMENT QUANTITY (#PCDATA)>
<!ELEMENT UNIT (#PCDATA)>
<!ELEMENT QUANTITY_STS (#PCDATA)>
<!ELEMENT QUANTITY_TYPE (#PCDATA)>
<!ELEMENT ITEMPRICE (#PCDATA)>
<!ELEMENT ITEMORIGINCOUNTRY (#PCDATA)>
<!ELEMENT ITEMCODE (#PCDATA)>
<!ELEMENT ACTUALINVOICELINES (#PCDATA)>
<!ELEMENT CURRENCY (#PCDATA)>
<!ELEMENT ITEM_COUNTERKEY (#PCDATA)>
<!ELEMENT PREFERENCEDOCUMENTNUMBER (#PCDATA)>
<!ELEMENT TAXEXEMPTCODE (#PCDATA)>
<!ELEMENT PROCESSTYPE (#PCDATA)>
<!ELEMENT StatisticQuantityType (#PCDATA)>
<!ELEMENT CERTIFICATES (SerialNo?, Ordinal?, ItemLine?, LineNo?, RESPONSECONFIRMATIONTYPECODE?, CERTIFICATENUMBER?, CERTIFICATEEXEMPTIONTYPE?, ATTACHMENTTYPECODE?, REQUESTCONFIRMATIONTYPECODE?, CUSTOMSATTACHMENTID?)>
<!ELEMENT SerialNo (#PCDATA)>
<!ELEMENT Ordinal (#PCDATA)>
<!ELEMENT ItemLine (#PCDATA)>
<!ELEMENT LineNo (#PCDATA)>
<!ELEMENT RESPONSECONFIRMATIONTYPECODE (#PCDATA)>
<!ELEMENT CERTIFICATENUMBER (#PCDATA)>
<!ELEMENT CERTIFICATEEXEMPTIONTYPE (#PCDATA)>
<!ELEMENT ATTACHMENTTYPECODE (#PCDATA)>
<!ELEMENT REQUESTCONFIRMATIONTYPECODE (#PCDATA)>
<!ELEMENT CUSTOMSATTACHMENTID (#PCDATA)>
<!ELEMENT POINTERS (SERIAL_NO?, ORD?, ITEM_LINE?, LINE_NO?, DECLARATIONID?, COUNTERKEY?, LINENUMBER?, STATISTICQUANTITY?, QTY_UNIT?)>
<!ELEMENT SERIAL_NO (#PCDATA)>
<!ELEMENT ORD (#PCDATA)>
<!ELEMENT ITEM_LINE (#PCDATA)>
<!ELEMENT LINE_NO (#PCDATA)>
<!ELEMENT DECLARATIONID (#PCDATA)>
<!ELEMENT COUNTERKEY (#PCDATA)>
<!ELEMENT LINENUMBER (#PCDATA)>
<!ELEMENT STATISTICQUANTITY (#PCDATA)>
<!ELEMENT QTY_UNIT (#PCDATA)>
<!ELEMENT CARS (SITEM_LINE?, COUNTER?, MODEL?, CHASSIS?, ENGINE?, WINDOW?, FOB?, VEHICLE_FILE?, EXEMPT_TYPE?)>
<!ELEMENT SITEM_LINE (#PCDATA)>
<!ELEMENT COUNTER (#PCDATA)>
<!ELEMENT MODEL (#PCDATA)>
<!ELEMENT CHASSIS (#PCDATA)>
<!ELEMENT ENGINE (#PCDATA)>
<!ELEMENT WINDOW (#PCDATA)>
<!ELEMENT FOB (#PCDATA)>
<!ELEMENT VEHICLE_FILE (#PCDATA)>
<!ELEMENT EXEMPT_TYPE (#PCDATA)>
<!ELEMENT TRANSP_VALUE_LIST (TRANSP_VALUE_L?, TRANSP_VALUE_CURR_L?)>
<!ELEMENT TRANSP_VALUE_L (#PCDATA)>
<!ELEMENT TRANSP_VALUE_CURR_L (#PCDATA)>
<!ELEMENT IS_PREFERENCE (#PCDATA)>
<!ELEMENT TRADE_AGREEMENT (#PCDATA)>
<!ELEMENT PACKAGES (PackTypeId?, PackQuantity?, PackWeight?, SignNum?)>
<!ELEMENT PackTypeId (#PCDATA)>
<!ELEMENT PackQuantity (#PCDATA)>
<!ELEMENT PackWeight (#PCDATA)>
<!ELEMENT SignNum (#PCDATA)>
<!ELEMENT agent_fee (#PCDATA)>
<!ELEMENT agent_fee_currency (#PCDATA)>
<!ELEMENT CustomsDocuments (Entname?, DocumentTypeCode?, Blocked?, FromDeclartion?, COM_ID?, SerialNum?)>
<!ELEMENT Entname (#PCDATA)>
<!ELEMENT DocumentTypeCode (#PCDATA)>
<!ELEMENT Blocked (#PCDATA)>
<!ELEMENT FromDeclartion (#PCDATA)>
<!ELEMENT COM_ID (#PCDATA)>
<!ELEMENT SerialNum (#PCDATA)>
<!ELEMENT TaxationDateTime (#PCDATA)>
<!ELEMENT CarrierPrefix (#PCDATA)>
<!ELEMENT IsAutonomy (#PCDATA)>
<!ELEMENT SiteCode (#PCDATA)>
<!ELEMENT CrateNumber (#PCDATA)>
<!ELEMENT shopId (#PCDATA)>

