//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> Amital\EntityDataMappingsGenerator.tt from AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using AmitalCloud.Infrastructure.Domain.Interfaces;
using AmitalCloud.Infrastructure.Domain.Enums;
using POCO = AmitalCloud.Infrastructure.Domain.EntityPOCOs ;
using AmitalCloud.Infrastructure.Domain.EntityPMs ;
using AmitalCloud.Infrastructure.Domain.EntityLists ;
using AmitalCloud.Infrastructure.Domain;


namespace AmitalCloud.Infrastructure.Data.EntityDataMappings
{
   
   public partial class NumberFormatDataMapping: IMapping<NumberFormatPM, POCO.NumberFormat ,NumberFormatList >
   {

        public void CustomPMToPOCO(NumberFormatPM entityPM, POCO.NumberFormat entityPOCO)
        {
            //throw new NotImplementedException();
        }

        public void CustomPOCOToPM(NumberFormatPM entityPM, POCO.NumberFormat entityPOCO)
        {
            //throw new NotImplementedException();
        }
   }


}
   