
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
 
namespace AmitalCloud.Infrastructure.Application.CloseTables
{
    public struct CommunicationStatusTypeValues
    {   
       public const string Done = "D";  
       public const string Fail = "F";  
       public const string InProgress = "P";  
       public const string Waiting = "W";  
       public const string Timeout = "T";  
       public const string Processing = "C";  
       public const string Demo = "E";  
    }
}

