<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/LOGICOURIERSTATUS" elementFormDefault="qualified" targetNamespace="http://tempuri.org/LOGICOURIERSTATUS" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="LOGICOURIERSTATUS">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="LogitudeCourierStatus" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LogitudeCourierStatus">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="DeclarationId" />
        <xs:element minOccurs="0" maxOccurs="1" ref="CustomFileNo" />
        <xs:element minOccurs="0" maxOccurs="1" ref="LastMileStatus" />
        <xs:element minOccurs="0" maxOccurs="1" ref="LastMileStatusDate" />
        <xs:element minOccurs="0" maxOccurs="1" ref="LastMileStatusRemarks" />
        <xs:element minOccurs="0" maxOccurs="1" ref="Param" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="DeclarationId" type="xs:string" />
  <xs:element name="CustomFileNo" type="xs:string" />
  <xs:element name="LastMileStatus" type="xs:string" />
  <xs:element name="LastMileStatusDate" type="xs:string" />
  <xs:element name="LastMileStatusRemarks" type="xs:string" />
  <xs:element name="Param" type="xs:string" />
</xs:schema>