SELECT [Id_Number]  as [Key]
      ,[English Name]
      ,[Local Name]
      ,[Code]
      ,[Transport Mode] as [Move Type Transport Mode]
      ,[Source Tenant] as [Tenant]
  FROM [dbo].[DIM_MoveTypes]