//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> C:\LWC\Logitude\Logitude.Customs.MetaData\AutoGenerators\CustomClassesGenerator.tt
//------------------------------------------------------------------------------

export class CustomsDocumentList {
   
	Tenant: number;
	DocumentsFilingId: string;
	CustomsDocId: string;
	DocumentStatusCode: string;
	DocumentRemarks: string;
	DocumentStatusName: string;
	Extension: string;
	FileSize: number;
	Name: string;
	DocumentTypeCode: string;
	DocumentTypeName: string;
	IsPartOfDeclaration: boolean;
	OcrScore: number;
	OcrStatusCode: string;
	OcrReference: string;
	OcrNotConnect: boolean;
	OcrId: string;
	
}
 