//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> C:\amital_main\Logitude\Logitude.Customs.MetaData\AutoGenerators\CustomClassesGenerator.tt
//------------------------------------------------------------------------------

export class NotificationList {
   
	Id: string;
	Tenant: number;
	NotificationDefinitionCode: string;
	CreateDate: Date;
	AssigneToId: string;
	AssigneToNotificationTypeCode: string;
	DeclarationOfficeCode: string;
	EntityId: string;
	ObjectTableId: string;
	IsClosedBCustomOffice: boolean;
	IsClosedByAssignee: boolean;
	DueDate: Date;
	IsSeenByAssignee: boolean;
	ResponseNotes: string;
	CreatedByRequestID: string;
	SearchFields: string;
	ObjectTableName: string;
	NotificationDefinitionName: string;
	AssigneToName: string;
	IsHandledByCustomOffice: boolean;
	Reference1Number: string;
	Reference2Number: string;
	DepartmentId: string;
	ClosedByCustomOfficeUserId: string;
	Description: string;
	DepartmentName: string;
	ClosedByAssignee: string;
	CustomerName: string;
	BadjCount: boolean;
	ClosedByCustomOfficeUserName: string;
	ClosedByAssigneeName: string;
	CustomerId: string;
	ResponseToMessage: string;
	
}
 