using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AmitalCustomsWindowsService.Tester
{
    public partial class Oracle2SQL
    {

        public void SCHEMA()
        {
            //find text  Schema="Customs"  C:\log2004\Logitude\Logitude.Customs.MetaData\DBTables\  
            string d =
//Code	File	Line	Column
@"            this.ToTable(""AcceptanceStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AcceptanceStatusMap.cs	22	6
			  this.ToTable(""AccumalationStates"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AccumalationStateMap.cs 22  6
			  this.ToTable(""ActionCodes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ActionCodeMap.cs    22  6
			  this.ToTable(""AddressContactStates"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AddressContactStateMap.cs   22  6
			  this.ToTable(""AddressPurposes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AddressPurposeMap.cs    22  6
			  this.ToTable(""AgentTalkBackTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AgentTalkBackTypeMap.cs 22  6
			  this.ToTable(""AmedmentTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmedmentTypeMap.cs  22  6
			  this.ToTable(""AmendCancellRequestInitiators"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmendCancellRequestInitiatorMap.cs  22  6
			  this.ToTable(""AmendmentFieldReasonTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmendmentFieldReasonTypeMap.cs  22  6
			  this.ToTable(""AmendmentFieldStatusTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmendmentFieldStatusTypeMap.cs  22  6
			  this.ToTable(""AmendmentRequestStatuses"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmendmentRequestStatusMap.cs    22  6
			  this.ToTable(""AmendmentStatuses"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmendmentStatusMap.cs   22  6
			  this.ToTable(""AmendmentTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmendmentTypeMap.cs 22  6
			  this.ToTable(""AmendRequestRejectReasonTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmendRequestRejectReasonTypeMap.cs  22  6
			  this.ToTable(""AmountTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AmountTypeMap.cs    22  6
			  this.ToTable(""ApprovedProfessions"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ApprovedProfessionMap.cs    22  6
			  this.ToTable(""AssigneeNotificationTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AssigneeNotificationTypeMap.cs  22  6
			  this.ToTable(""AttachmentTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AttachmentTypeMap.cs    22  6
			  this.ToTable(""Authorities"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AuthorityMap.cs 22  6
			  this.ToTable(""AuthorizedSignerPermits"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AuthorizedSignerPermitMap.cs    22  6
			  this.ToTable(""AutonomyRegionTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AutonomyRegionTypeMap.cs    22  6
			  this.ToTable(""AutonomyTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\AutonomyTypeMap.cs  22  6
			  this.ToTable(""Banks"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\BankMap.cs  22  6
			  this.ToTable(""BuyerRoleTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\BuyerRoleTypeMap.cs 22  6
			  this.ToTable(""CancellationReasonRequestTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CancellationReasonRequestTypeMap.cs 22  6
			  this.ToTable(""CancellationRequestStatuses"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CancellationRequestStatusMap.cs 22  6
			  this.ToTable(""CancelRequestRejectReasonTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CancelRequestRejectReasonTypeMap.cs 22  6
			  this.ToTable(""CargoIdentifireTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CargoIdentifireTypeMap.cs   22  6
			  this.ToTable(""CargoIdentityQualifiers"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CargoIdentityQualifierMap.cs    22  6
			  this.ToTable(""CargoSealIdentifiers"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CargoSealIdentifierMap.cs   22  6
			  this.ToTable(""CargoSeals"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CargoSealMap.cs 22  6
			  this.ToTable(""CargoSplitRequestStatuses"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CargoSplitRequestStatusMap.cs   22  6
			  this.ToTable(""CargoStatuses"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CargoStatusMap.cs   22  6
			  this.ToTable(""CargoTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CargoTypeMap.cs 22  6
			  this.ToTable(""CertificateExemptionTypes"", ""Customs""); C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CertificateExemptionTypeMap.cs	22	6
			  this.ToTable(""CertificatesStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CertificatesStatusMap.cs	22	6
			  this.ToTable(""CheckEntityTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CheckEntityTypeMap.cs	22	6
			  this.ToTable(""CheckEssenceLookups"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CheckEssenceLookupMap.cs	22	6
			  this.ToTable(""CheckQueueTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CheckQueueTypeMap.cs	22	6
			  this.ToTable(""CheckRepresentativeTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CheckRepresentativeTypeMap.cs	22	6
			  this.ToTable(""CheckTypeLookups"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CheckTypeLookupMap.cs	22	6
			  this.ToTable(""Cities"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CityMap.cs	22	6
			  this.ToTable(""ClaimEntities"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimEntityMap.cs	22	6
			  this.ToTable(""ClaimExplanationCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimExplanationCodeMap.cs	22	6
			  this.ToTable(""ClaimImporterDeclarsP3Lois"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimImporterDeclarsP3LoiMap.cs	22	6
			  this.ToTable(""ClaimImporterDeclarsPage3As"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimImporterDeclarsPage3AMap.cs	22	6
			  this.ToTable(""ClaimImporterDeclarsPage3Bs"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimImporterDeclarsPage3BMap.cs	22	6
			  this.ToTable(""ClaimImporterDeclarsPage3s"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimImporterDeclarsPage3Map.cs	22	6
			  this.ToTable(""Claims"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimMap.cs	22	6
			  this.ToTable(""ClaimReasonTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimReasonTypeMap.cs	22	6
			  this.ToTable(""ClaimsRelatedEntitiesAmounts"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimsRelatedEntitiesAmountMap.cs	22	6
			  this.ToTable(""ClaimsRelatedEntitiesReasons"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimsRelatedEntitiesReasonMap.cs	22	6
			  this.ToTable(""ClaimsRelatedEntitiesRefunds"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimsRelatedEntitiesRefundMap.cs	22	6
			  this.ToTable(""ClaimsRelatedEntitiesSeizures"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimsRelatedEntitiesSeizureMap.cs	22	6
			  this.ToTable(""ClaimsRelatedEntities"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimsRelatedEntityMap.cs	22	6
			  this.ToTable(""ClaimsRelatedEntsExpDeclars"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimsRelatedEntsExpDeclarMap.cs	22	6
			  this.ToTable(""ClaimsRelatedEntsReasonsExps"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClaimsRelatedEntsReasonsExpMap.cs	22	6
			  this.ToTable(""ClassificationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClassificationTypeMap.cs	22	6
			  this.ToTable(""ClientAddresses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClientAddressMap.cs	22	6
			  this.ToTable(""ClientDrivingLicenses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClientDrivingLicenseMap.cs	22	6
			  this.ToTable(""ClientDrivingLicenseTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClientDrivingLicenseTypeMap.cs	22	6
			  this.ToTable(""Clients"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClientMap.cs	22	6
			  this.ToTable(""ClientsAddressCommTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClientsAddressCommTypeMap.cs	22	6
			  this.ToTable(""ClientsPoas"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClientsPoaMap.cs	22	6
			  this.ToTable(""ClosedTableStatus"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ClosedTableStatusMap.cs	22	6
			  this.ToTable(""CollateralAnswerStatus"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CollateralAnswerStatusMap.cs	22	6
			  this.ToTable(""CollateralAnswerTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CollateralAnswerTypeMap.cs	22	6
			  this.ToTable(""CollateralRequestStatus"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CollateralRequestStatusMap.cs	22	6
			  this.ToTable(""CollateralsRequestFileConds"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CollateralsRequestFileCondMap.cs	22	6
			  this.ToTable(""CollateralTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CollateralTypeMap.cs	22	6
			  this.ToTable(""CommercialSales"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CommercialSaleMap.cs	22	6
			  this.ToTable(""CommunicationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CommunicationTypeMap.cs	22	6
			  this.ToTable(""ConfirmationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConfirmationTypeMap.cs	22	6
			  this.ToTable(""ConsignmentInternalTransitions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConsignmentInternalTransitionMap.cs	22	6
			  this.ToTable(""Consignments"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConsignmentMap.cs	22	6
			  this.ToTable(""ConsignmentPackages"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConsignmentPackageMap.cs	22	6
			  this.ToTable(""ConsignmentPackDangers"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConsignmentPackDangerMap.cs	22	6
			  this.ToTable(""ConstraintApprovalDecisions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConstraintApprovalDecisionMap.cs	22	6
			  this.ToTable(""ConstraintProcessTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConstraintProcessTypeMap.cs	22	6
			  this.ToTable(""ConstraintStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConstraintStatusMap.cs	22	6
			  this.ToTable(""ConstraintTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConstraintTypeMap.cs	22	6
			  this.ToTable(""ContactRoleTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ContactRoleTypeMap.cs	22	6
			  this.ToTable(""ContainerizationHataraStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ContainerizationHataraStatusMap.cs	22	6
			  this.ToTable(""Containerizations"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ContainerizationMap.cs	22	6
			  this.ToTable(""ContainerizationStatusCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ContainerizationStatusCodeMap.cs	22	6
			  this.ToTable(""ContainerTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ContainerTypeMap.cs	22	6
			  this.ToTable(""ContinuousMessagesTypeCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ContinuousMessagesTypeCodeMap.cs	22	6
			  this.ToTable(""ContinuousRequestTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ContinuousRequestTypeMap.cs	22	6
			  this.ToTable(""ConverterTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ConverterTypeMap.cs	22	6
			  this.ToTable(""CoolingReportingMethods"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CoolingReportingMethodMap.cs	22	6
			  this.ToTable(""CountryGroups"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CountryGroupMap.cs	22	6
			  this.ToTable(""CourierCustomStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierCustomStatusMap.cs	22	6
			  this.ToTable(""CourierDeclarations"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierDeclarationMap.cs	22	6
			  this.ToTable(""CourierDeclarationStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierDeclarationStatusMap.cs	22	6
			  this.ToTable(""CourierManifestStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierManifestStatusMap.cs	22	6
			  this.ToTable(""CourierMasters"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierMasterMap.cs	22	6
			  this.ToTable(""CourierPaymentStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierPaymentStatusMap.cs	22	6
			  this.ToTable(""CourierPendingReasons"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierPendingReasonMap.cs	22	6
			  this.ToTable(""CourierStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourierStatusMap.cs	22	6
			  this.ToTable(""CouriersVats"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CouriersVatMap.cs	22	6
			  this.ToTable(""CourtInstances"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CourtInstanceMap.cs	22	6
			  this.ToTable(""CurrencyTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CurrencyTypeMap.cs	22	6
			  this.ToTable(""CurrencyTypeTenants"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CurrencyTypeTenantMap.cs	22	6
			  this.ToTable(""CustomBanks"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomBankMap.cs	22	6
			  this.ToTable(""CustomBanksCards"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomBanksCardMap.cs	22	6
			  this.ToTable(""CustomDocumentTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomDocumentTypeMap.cs	22	6
			  this.ToTable(""CustomDocumentTypeMetaData"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomDocumentTypeMetaDataMap.cs	22	6
			  this.ToTable(""CustomerActivityTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomerActivityTypeMap.cs	22	6
			  this.ToTable(""CustomerClassificationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomerClassificationTypeMap.cs	22	6
			  this.ToTable(""CustomerIdentificationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomerIdentificationTypeMap.cs	22	6
			  this.ToTable(""CustomerIdentifyTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomerIdentifyTypeMap.cs	22	6
			  this.ToTable(""CustomerIndicationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomerIndicationTypeMap.cs	22	6
			  this.ToTable(""CustomerRoleTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomerRoleTypeMap.cs	22	6
			  this.ToTable(""CustomerTypeGenerals"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomerTypeGeneralMap.cs	22	6
			  this.ToTable(""CustomMetaDataTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomMetaDataTypeMap.cs	22	6
			  this.ToTable(""CustomsAddressTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsAddressTypeMap.cs	22	6
			  this.ToTable(""CustomsAirlines"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsAirlineMap.cs	22	6
			  this.ToTable(""CustomsAutonomyKeywords"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsAutonomyKeywordMap.cs	22	6
			  this.ToTable(""CustomsBooks"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsBookMap.cs	22	6
			  this.ToTable(""CustomsBookTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsBookTypeMap.cs	22	6
			  this.ToTable(""CustomsBranches"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsBranchMap.cs	22	6
			  this.ToTable(""CustomsClosedTables"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsClosedTableMap.cs	22	6
			  this.ToTable(""CustomsCollaterals"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsCollateralMap.cs	22	6
			  this.ToTable(""CustomsCollateralsAnswers"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsCollateralsAnswerMap.cs	22	6
			  this.ToTable(""CustomsCollateralsConditions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsCollateralsConditionMap.cs	22	6
			  this.ToTable(""CustomsCountries"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsCountryMap.cs	22	6
			  this.ToTable(""CustomsDocuments"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsDocumentMap.cs	22	6
			  this.ToTable(""CustomsDocumentMetaDataValues"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsDocumentMetaDataValueMap.cs	22	6
			  this.ToTable(""CustomsDocumentPointers"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsDocumentPointerMap.cs	22	6
			  this.ToTable(""CustomsDocumentsDefinitions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsDocumentsDefinitionMap.cs	22	6
			  this.ToTable(""CustomsDocumentStatusTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsDocumentStatusTypeMap.cs	22	6
			  this.ToTable(""CustomsDocumentsTickets"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsDocumentsTicketMap.cs	22	6
			  this.ToTable(""CustomsDocumentUploads"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsDocumentUploadMap.cs	22	6
				this.ToTable(""CustomsEnvironmentSettings"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsEnvironmentSettingMap.cs	22	5
			  this.ToTable(""CustomsEnvoirmentTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsEnvoirmentTypeMap.cs	22	6
			  this.ToTable(""CustomsExchangeRates"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsExchangeRateMap.cs	22	6
				this.ToTable(""CustomsGenerals"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsGeneralMap.cs	22	5
			  this.ToTable(""CustomsHouseTypeAdditionals"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsHouseTypeAdditionalMap.cs	22	6
			  this.ToTable(""CustomsHouseTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsHouseTypeMap.cs	22	6
			  this.ToTable(""CustomsInsuranceCompanies"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsInsuranceCompanyMap.cs	22	6
			  this.ToTable(""CustomsItemDetailsHistorys"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsItemDetailsHistoryMap.cs	22	6
			  this.ToTable(""CustomsItems"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsItemMap.cs	22	6
			  this.ToTable(""CustomsPartnerFtps"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsPartnerFtpMap.cs	22	6
			  this.ToTable(""CustomsPartnersItems"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsPartnersItemMap.cs	22	6
			  this.ToTable(""CustomsPaymentTerms"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsPaymentTermsMap.cs	22	6
			  this.ToTable(""CustomsRequestsSheets"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsRequestsSheetMap.cs	22	6
			  this.ToTable(""CustomsRequestsSheetStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsRequestsSheetStatusMap.cs	22	6
			  this.ToTable(""CustomsRequiredFields"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsRequiredFieldMap.cs	22	6
			  this.ToTable(""CustomsSettings"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsSettingMap.cs	22	6
			  this.ToTable(""CustomsShips"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsShipMap.cs	22	6
			  this.ToTable(""CustomsTransportModes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsTransportModeMap.cs	22	6
			  this.ToTable(""CustomsVendors"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsVendorMap.cs	22	6
			  this.ToTable(""CustomsVerificationStatusTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\CustomsVerificationStatusTypeMap.cs	22	6
			  this.ToTable(""DangerousGoodsPackingReqs"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DangerousGoodsPackingReqMap.cs	22	6
			  this.ToTable(""DBMigrationLines"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DBMigrationLineMap.cs	22	6
			  this.ToTable(""DBMigrations"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DBMigrationMap.cs	22	6
			  this.ToTable(""DebtNotificationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DebtNotificationTypeMap.cs	22	6
			  this.ToTable(""DecCargoSplitCargoIdentifiers"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DecCargoSplitCargoIdentifierMap.cs	22	6
			  this.ToTable(""DecCargoSplitCons"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DecCargoSplitConMap.cs	22	6
			  this.ToTable(""DecCargoSplitConsItems"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DecCargoSplitConsItemMap.cs	22	6
			  this.ToTable(""DecCargoSplitConsPackDets"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DecCargoSplitConsPackDetMap.cs	22	6
			  this.ToTable(""DecDangersContacts"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DecDangersContactsMap.cs	22	6
			  this.ToTable(""DecisionTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DecisionTypeMap.cs	22	6
			  this.ToTable(""DeclarationCargoSplits"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationCargoSplitMap.cs	22	6
			  this.ToTable(""DeclarationCasualDetailses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationCasualDetailsMap.cs	22	6
			  this.ToTable(""DeclarationConsAcceptances"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationConsAcceptanceMap.cs	22	6
			  this.ToTable(""DeclarationConstraints"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationConstraintMap.cs	22	6
			  this.ToTable(""DeclarationCourierStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationCourierStatusMap.cs	22	6
			  this.ToTable(""DeclarationErrorMappings"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationErrorMappingMap.cs	22	6
			  this.ToTable(""DeclarationExportRecipients"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationExportRecipientMap.cs	22	6
			  this.ToTable(""DeclarationMamanSpecialActions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationMamanSpecialActionMap.cs	22	6
			  this.ToTable(""Declarations"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationMap.cs	22	6
			  this.ToTable(""DeclarationPayments"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationPaymentMap.cs	22	6
			  this.ToTable(""DeclarationPaymentMethods"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationPaymentMethodMap.cs	22	6
			  this.ToTable(""DeclarationPaymentProtests"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationPaymentProtestMap.cs	22	6
			  this.ToTable(""DeclarationPendings"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationPendingMap.cs	22	6
			  this.ToTable(""DeclarationReferantDatas"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationReferantDataMap.cs	22	6
			  this.ToTable(""DeclarationStatementTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationStatementTypeMap.cs	22	6
			  this.ToTable(""DeclarationStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationStatusMap.cs	22	6
			  this.ToTable(""DeclarationStatusTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationStatusTypeMap.cs	22	6
			  this.ToTable(""DeclarationTaxes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeclarationTaxMap.cs	22	6
			  this.ToTable(""DeficitConnFileParagraphTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeficitConnFileParagraphTypeMap.cs	22	6
			  this.ToTable(""DeficitDecisions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeficitDecisionMap.cs	22	6
			  this.ToTable(""Deficits"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeficitsMap.cs	22	6
			  this.ToTable(""DeliverySiteTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeliverySiteTypeMap.cs	22	6
			  this.ToTable(""DeliveryTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DeliveryTypeMap.cs	22	6
			  this.ToTable(""DemanderTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DemanderTypeMap.cs	22	6
			  this.ToTable(""DepositConditions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DepositConditionMap.cs	22	6
			  this.ToTable(""DepositCustomerActivities"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DepositCustomerActivityMap.cs	22	6
			  this.ToTable(""DepositEssenceTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DepositEssenceTypeMap.cs	22	6
			  this.ToTable(""DepositFileTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DepositFileTypeMap.cs	22	6
			  this.ToTable(""Deposits"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DepositMap.cs	22	6
			  this.ToTable(""DocumentRejectTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DocumentRejectTypeMap.cs	22	6
			  this.ToTable(""DocumentTypeCustomsData"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\DocumentTypeCustomsDataMap.cs	22	6
			  this.ToTable(""EntitlementTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\EntitlementTypeMap.cs	22	6
			  this.ToTable(""EntityTypeLookups"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\EntityTypeLookupMap.cs	22	6
			  this.ToTable(""ExceptionReasons"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExceptionReasonMap.cs	22	6
			  this.ToTable(""ExportDeclarationClosingDatas"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExportDeclarationClosingDataMap.cs	22	6
			  this.ToTable(""ExportDeliveryDocumentMessages"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExportDeliveryDocumentMessageMap.cs	22	6
			  this.ToTable(""ExporterRoleTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExporterRoleTypeMap.cs	22	6
			  this.ToTable(""ExportLogisticPermitActions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExportLogisticPermitActionMap.cs	22	6
			  this.ToTable(""ExportReferences"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExportReferenceMap.cs	22	6
			  this.ToTable(""ExportStorages"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExportStorageMap.cs	22	6
			  this.ToTable(""ExternalFieldMappings"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ExternalFieldMappingMap.cs	22	6
			  this.ToTable(""FacilitationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\FacilitationTypeMap.cs	22	6
			  this.ToTable(""FaultInspectionTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\FaultInspectionTypeMap.cs	22	6
			  this.ToTable(""FclLclCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\FclLclCodeMap.cs	22	6
			  this.ToTable(""FreightPaymentMethods"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\FreightPaymentMethodMap.cs	22	6
			  this.ToTable(""FuelTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\FuelTypeMap.cs	22	6
			  this.ToTable(""FullnessCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\FullnessCodeMap.cs	22	6
			  this.ToTable(""GatepassRequests"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GatepassRequestMap.cs	22	6
			  this.ToTable(""GatepassReturnCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GatepassReturnCodeMap.cs	22	6
			  this.ToTable(""Genders"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GenderMap.cs	22	6
			  this.ToTable(""GovernmentProcedureTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GovernmentProcedureTypeMap.cs	22	6
				this.ToTable(""GTBFUSTATUS"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GTBFUSTATUMap.cs	22	5
			  this.ToTable(""GuaranteeCertificateTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GuaranteeCertificateTypeMap.cs	22	6
			  this.ToTable(""GuaranteeConditions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GuaranteeConditionMap.cs	22	6
			  this.ToTable(""GuaranteeCustomerActivities"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GuaranteeCustomerActivityMap.cs	22	6
			  this.ToTable(""Guarantees"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\GuaranteeMap.cs	22	6
			  this.ToTable(""HandingCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\HandingCodeMap.cs	22	6
			  this.ToTable(""HazardousSubstances"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\HazardousSubstanceMap.cs	22	6
			  this.ToTable(""ImporterDeclarationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ImporterDeclarationTypeMap.cs	22	6
			  this.ToTable(""ImporterDespositions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ImporterDespositionMap.cs	22	6
			  this.ToTable(""ImporterPeriodicDeclarStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ImporterPeriodicDeclarStatusMap.cs	22	6
			  this.ToTable(""ImporterTypeForClaims"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ImporterTypeForClaimMap.cs	22	6
			  this.ToTable(""IncotemrsFileValidations"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\IncotemrsFileValidationMap.cs	22	6
			  this.ToTable(""InterfaceManagements"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\InterfaceManagementMap.cs	22	6
			  this.ToTable(""InterfaceSendOptions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\InterfaceSendOptionMap.cs	22	6
			  this.ToTable(""InterfaceTenantDefinitions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\InterfaceTenantDefinitionMap.cs	22	6
			  this.ToTable(""InternalBorderSiteTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\InternalBorderSiteTypeMap.cs	22	6
			  this.ToTable(""InternationalSites"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\InternationalSiteMap.cs	22	6
			  this.ToTable(""InvoiceTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\InvoiceTypeMap.cs	22	6
			  this.ToTable(""ItemGovernmentProcedureTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ItemGovernmentProcedureTypeMap.cs	22	6
			  this.ToTable(""LastReleaseFromWarehouses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LastReleaseFromWarehouseMap.cs	22	6
			  this.ToTable(""LeadDocumentExceptionTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LeadDocumentExceptionTypeMap.cs	22	6
			  this.ToTable(""LeadDocumentTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LeadDocumentTypeMap.cs	22	6
			  this.ToTable(""LoadingSiteTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LoadingSiteTypeMap.cs	22	6
			  this.ToTable(""LogisticActionRequests"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LogisticActionRequestMap.cs	22	6
			  this.ToTable(""LogisticActionRequestTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LogisticActionRequestTypeMap.cs	22	6
			  this.ToTable(""LogisticActionResponseReqSes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LogisticActionResponseReqSMap.cs	22	6
			  this.ToTable(""LogisticPermits"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LogisticPermitMap.cs	22	6
			  this.ToTable(""LogisticsReferenceTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\LogisticsReferenceTypeMap.cs	22	6
			  this.ToTable(""MamanSpecialActions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\MamanSpecialActionMap.cs	22	6
			  this.ToTable(""MamanSpecialActionStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\MamanSpecialActionStatusMap.cs	22	6
			  this.ToTable(""MamanStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\MamanStatusMap.cs	22	6
			  this.ToTable(""ManifestCargoStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ManifestCargoStatusMap.cs	22	6
			  this.ToTable(""MAWBTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\MAWBTypeMap.cs	22	6
			  this.ToTable(""MeasureQualifier"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\MeasureQualifierMap.cs	22	6
			  this.ToTable(""MeasurmentUnits"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\MeasurmentUnitMap.cs	22	6
			  this.ToTable(""ModificationAndDiscountTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ModificationAndDiscountTypeMap.cs	22	6
			  this.ToTable(""MorningMessageTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\MorningMessageTypeMap.cs	22	6
			  this.ToTable(""NbcDeclarationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\NbcDeclarationTypeMap.cs	22	6
			  this.ToTable(""NDMessageActionCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\NDMessageActionCodeMap.cs	22	6
			  this.ToTable(""NotificationDefinitions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\NotificationDefinitionMap.cs	22	6
			  this.ToTable(""Notifications"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\NotificationMap.cs	22	6
			  this.ToTable(""NotificationReplies"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\NotificationReplyMap.cs	22	6
			  this.ToTable(""NotificationTenantDefinition"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\NotificationTenantDefinitionMap.cs	22	6
			  this.ToTable(""NotificationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\NotificationTypeMap.cs	22	6
			  this.ToTable(""OrganizationUnitTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\OrganizationUnitTypeMap.cs	22	6
			  this.ToTable(""PackageMeasureQualifiers"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PackageMeasureQualifierMap.cs	22	6
			  this.ToTable(""PackingTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PackingTypeMap.cs	22	6
			  this.ToTable(""ParagraphTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ParagraphTypeMap.cs	22	6
			  this.ToTable(""PartyRelationshipTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PartyRelationshipTypeMap.cs	22	6
			  this.ToTable(""PassportTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PassportTypeMap.cs	22	6
			  this.ToTable(""PayerActivityTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PayerActivityTypeMap.cs	22	6
			  this.ToTable(""PayerTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PayerTypeMap.cs	22	6
			  this.ToTable(""PaymentMethodStatus"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentMethodStatusMap.cs	22	6
			  this.ToTable(""PaymentMethodTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentMethodTypeMap.cs	22	6
			  this.ToTable(""PaymentOrderConnectionTables"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentOrderConnectionTableMap.cs	22	6
			  this.ToTable(""PaymentOrderLines"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentOrderLineMap.cs	22	6
			  this.ToTable(""PaymentOrders"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentOrderMap.cs	22	6
			  this.ToTable(""PaymentOrderMethods"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentOrderMethodMap.cs	22	6
			  this.ToTable(""PaymentOrderProtestReasons"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentOrderProtestReasonMap.cs	22	6
			  this.ToTable(""PaymentOrderStatus"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentOrderStatusMap.cs	22	6
			  this.ToTable(""PaymentOrderTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentOrderTypeMap.cs	22	6
			  this.ToTable(""PaymentProcesses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentProcessMap.cs	22	6
			  this.ToTable(""PaymentProtestTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentProtestTypeMap.cs	22	6
			  this.ToTable(""PaymentTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PaymentTypeMap.cs	22	6
			  this.ToTable(""PendingByKeywords"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PendingByKeywordMap.cs	22	6
			  this.ToTable(""PendingErrorPlaces"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PendingErrorPlaceMap.cs	22	6
			  this.ToTable(""PhysicalChecks"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PhysicalCheckMap.cs	22	6
			  this.ToTable(""PhysicalCheckOperations"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PhysicalCheckOperationMap.cs	22	6
			  this.ToTable(""PhysicalCheckSearchResultTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PhysicalCheckSearchResultTypeMap.cs	22	6
			  this.ToTable(""PhysicalCheckStatusMessages"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PhysicalCheckStatusMessageMap.cs	22	6
			  this.ToTable(""PoaAuthorizationTypeLookups"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PoaAuthorizationTypeLookupMap.cs	22	6
			  this.ToTable(""PoaStatusTypeLookUps"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PoaStatusTypeLookUpMap.cs	22	6
			  this.ToTable(""PointerLevels"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PointerLevelMap.cs	22	6
			  this.ToTable(""ProceduralFaultInProcessTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProceduralFaultInProcessTypeMap.cs	22	6
			  this.ToTable(""ProceduralFaultInSourceTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProceduralFaultInSourceTypeMap.cs	22	6
			  this.ToTable(""ProceduralFaultsConnEntities"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProceduralFaultsConnEntityMap.cs	22	6
			  this.ToTable(""ProceduralFaults"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProceduralFaultsMap.cs	22	6
			  this.ToTable(""ProceduralFaultStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProceduralFaultStatusMap.cs	22	6
			  this.ToTable(""ProceduralFaultTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProceduralFaultTypeMap.cs	22	6
			  this.ToTable(""ProcessingReasons"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProcessingReasonMap.cs	22	6
			  this.ToTable(""ProductIdentificationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProductIdentificationTypeMap.cs	22	6
			  this.ToTable(""ProductNameTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ProductNameTypeMap.cs	22	6
			  this.ToTable(""PropertiesDetailsHistorys"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\PropertiesDetailsHistoryMap.cs	22	6
			  this.ToTable(""RansomViolationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\RansomViolationTypeMap.cs	22	6
			  this.ToTable(""ReferantExceptions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ReferantExceptionMap.cs	22	6
			  this.ToTable(""ReferantTeams"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ReferantTeamMap.cs	22	6
			  this.ToTable(""ReferenceInputTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ReferenceInputTypeMap.cs	22	6
			  this.ToTable(""ReferenceStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ReferenceStatusMap.cs	22	6
			  this.ToTable(""RefundCustomerActivityTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\RefundCustomerActivityTypeMap.cs	22	6
			  this.ToTable(""RegisteredWarehouseSiteTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\RegisteredWarehouseSiteTypeMap.cs	22	6
			  this.ToTable(""ReleaseMessageTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ReleaseMessageTypeMap.cs	22	6
			  this.ToTable(""RequestStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\RequestStatusMap.cs	22	6
			  this.ToTable(""RequestTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\RequestTypeMap.cs	22	6
			  this.ToTable(""RequiredGuaranteeTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\RequiredGuaranteeTypeMap.cs	22	6
			  this.ToTable(""ReturnConditions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ReturnConditionMap.cs	22	6
			  this.ToTable(""SalesTaxExemptionTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SalesTaxExemptionTypeMap.cs	22	6
			  this.ToTable(""SealCompleteness"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SealCompletenesMap.cs	22	6
			  this.ToTable(""SealTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SealTypeMap.cs	22	6
			  this.ToTable(""SealUpdateReasonTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SealUpdateReasonTypeMap.cs	22	6
			  this.ToTable(""SecurityClearenceTypeCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SecurityClearenceTypeCodeMap.cs	22	6
			  this.ToTable(""SeizureFactorTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SeizureFactorTypeMap.cs	22	6
			  this.ToTable(""SeizureMethodTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SeizureMethodTypeMap.cs	22	6
			  this.ToTable(""SignatureTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SignatureTypeMap.cs	22	6
			  this.ToTable(""SiteLookups"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SiteLookupMap.cs	22	6
			  this.ToTable(""SiteTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SiteTypeMap.cs	22	6
			  this.ToTable(""SpecialActionDescriptionTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SpecialActionDescriptionTypeMap.cs	22	6
			  this.ToTable(""SpecializationTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SpecializationTypeMap.cs	22	6
			  this.ToTable(""SplitOrMergeReasons"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SplitOrMergeReasonMap.cs	22	6
			  this.ToTable(""StatusFieldTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\StatusFieldTypeMap.cs	22	6
			  this.ToTable(""StorageMessageTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\StorageMessageTypeMap.cs	22	6
			  this.ToTable(""StorageStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\StorageStatusMap.cs	22	6
			  this.ToTable(""StorageStatusTables"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\StorageStatusTableMap.cs	22	6
			  this.ToTable(""StuffingSiteTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\StuffingSiteTypeMap.cs	22	6
			  this.ToTable(""SubCountries"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SubCountryMap.cs	22	6
			  this.ToTable(""SuppInvoiceItemsAbachStatement"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SuppInvoiceItemsAbachStatementMap.cs	22	6
			  this.ToTable(""SupplierInvioceItemCertificats"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvioceItemCertificatMap.cs	22	6
			  this.ToTable(""SupplierInvoiceFreightAmounts"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceFreightAmountMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItems"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemModVehicles"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemModVehicleMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemProcesTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemProcesTypeMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsConDeclars"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsConDeclarMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsDescripts"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsDescriptMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsLevies"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsLevyMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsMods"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsModMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsPrices"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsPriceMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsProdIdents"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsProdIdentMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsSerialNums"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsSerialNumMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemsTaxes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemsTaxMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemVehicleAdds"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemVehicleAddMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemVehicles"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemVehicleMap.cs	22	6
			  this.ToTable(""SupplierInvoiceItemVehicleMods"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceItemVehicleModMap.cs	22	6
			  this.ToTable(""SupplierInvoices"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceMap.cs	22	6
			  this.ToTable(""SupplierInvoiceModifications"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceModificationMap.cs	22	6
			  this.ToTable(""SupplierInvoicePayments"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoicePaymentMap.cs	22	6
			  this.ToTable(""SupplierInvoiceUCRs"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierInvoiceUCRMap.cs	22	6
			  this.ToTable(""SupplierPartyTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\SupplierPartyTypeMap.cs	22	6
			  this.ToTable(""TapagConnectionTables"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TapagConnectionTableMap.cs	22	6
			  this.ToTable(""Tapags"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TapagMap.cs	22	6
			  this.ToTable(""TapagTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TapagTypeMap.cs	22	6
			  this.ToTable(""TermsOfSaleTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TermsOfSaleTypeMap.cs	22	6
			  this.ToTable(""TPGFileTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TPGFileTypeMap.cs	22	6
			  this.ToTable(""TradeAgreements"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TradeAgreementMap.cs	22	6
			  this.ToTable(""TradeAgreementProtocols"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TradeAgreementProtocolMap.cs	22	6
			  this.ToTable(""TradeLevyExamptTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TradeLevyExamptTypeMap.cs	22	6
			  this.ToTable(""TransactionNatureTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TransactionNatureTypeMap.cs	22	6
			  this.ToTable(""TransferCargoMethodTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TransferCargoMethodTypeMap.cs	22	6
			  this.ToTable(""TransportMeansTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TransportMeansTypeMap.cs	22	6
			  this.ToTable(""TreatmentWays"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\TreatmentWayMap.cs	22	6
			  this.ToTable(""UIMessageAdditionals"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\UIMessageAdditionalMap.cs	22	6
			  this.ToTable(""UIMessages"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\UIMessageMap.cs	22	6
			  this.ToTable(""UnloadingSiteType"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\UnloadingSiteTypeMap.cs	22	6
			  this.ToTable(""UpdateCodes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\UpdateCodeMap.cs	22	6
			  this.ToTable(""ValidCustomsItems"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\ValidCustomsItemMap.cs	22	6
			  this.ToTable(""VehicleManufacturers"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleManufacturerMap.cs	22	6
			  this.ToTable(""Vehicles"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleMap.cs	22	6
			  this.ToTable(""VehicleOwners"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleOwnerMap.cs	22	6
			  this.ToTable(""VehiclePoolTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehiclePoolTypeMap.cs	22	6
			  this.ToTable(""VehiclePriceListType"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehiclePriceListTypeMap.cs	22	6
			  this.ToTable(""VehicleReductionTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleReductionTypeMap.cs	22	6
			  this.ToTable(""VehicleSafeAccessoryInstlTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleSafeAccessoryInstlTypeMap.cs	22	6
			  this.ToTable(""VehicleSafetyAccessories"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleSafetyAccessoryMap.cs	22	6
			  this.ToTable(""VehicleSafetyAccessoryTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleSafetyAccessoryTypeMap.cs	22	6
			  this.ToTable(""VehicleStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleStatusMap.cs	22	6
			  this.ToTable(""VehicleTecnologyTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleTecnologyTypeMap.cs	22	6
			  this.ToTable(""VehicleTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VehicleTypeMap.cs	22	6
			  this.ToTable(""VendorCommissions"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VendorCommissionMap.cs	22	6
			  this.ToTable(""VendorCommunications"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VendorCommunicationMap.cs	22	6
			  this.ToTable(""VendorStatuses"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VendorStatusMap.cs	22	6
			  this.ToTable(""VendorTransactionTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VendorTransactionTypeMap.cs	22	6
			  this.ToTable(""VendorTypes"", ""Customs"");	C:\log2004\Logitude\Logitude.Customs.Data\EntityMapping\VendorTypeMap.cs	22	6

";

            var lines=d.Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);
            Debug.WriteLine("CREATE SCHEMA Customs;  ");
            foreach (var line in lines)
            {
				//this.ToTable(""AcceptanceStatuses"
				int pos = line.IndexOf("this.ToTable(");
				string table = line.Substring(pos+"this.ToTable(".Length + 1);
				pos = table.IndexOf('"');
				table= table.Substring(0, pos);
				Debug.WriteLine($"ALTER SCHEMA Customs TRANSFER OBJECT::dbo.{table/*.ToUpper()*/};  ");
				///Debug.WriteLine($"ALTER SCHEMA dbo TRANSFER OBJECT::dbo.{table/*.ToUpper()*/};  ");
			}
        }
    }
}
