

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
 
namespace Logitude.Customs.BL.CloseTables
{
    public struct ConfirmationTypeValues
    {   
       public const string אישוראגףניהולמשאביתשתיות = "1001";  
       public const string רשיוןע"פצומתןרשיונותיבוא193910 = "1002";  
       public const string אישורהשירותהוטרינרי = "101";  
       public const string אישורהגנתהצומח = "102";  
       public const string אנרגיהאטומית = "1020";  
       public const string הממונהעלצוהפיקוחעלהמצרכים = "1021";  
       public const string צוהפיקוחעלהיצואבתחוםהכימי = "1022";  
       public const string אישורטיבמספוא = "103";  
       public const string אישורמיכוןוטכנולוגיה = "104";  
       public const string אישוראגףהדייג = "105";  
       public const string אישורהמרכזסחרחוץ = "106";  
       public const string אישורהמנכ"ל = "107";  
       public const string אישוראחר = "108";  
       public const string רישיוןהמרכזלסחרחוץ = "109";  
       public const string הרשותלתכנוןחקלאותוכלכלה = "110";  
       public const string תעודתהכשר = "1101";  
       public const string רשיוןע"פצומתןרשיונותיבוא193911 = "1102";  
       public const string רשיוןע"פצי"ח2(ד)מכסות = "111";  
       public const string רשיוןאוטונומיה = "112";  
       public const string רשיוןע"פצומתןרשיונותיבוא1939 = "113";  
       public const string רשיוןהמרכזלסחרחוץ = "120";  
       public const string אישורביטחוןפנים = "1201";  
       public const string רשיוןע"פצומתןרשיונותיבוא193912 = "1202";  
       public const string רשיוןאגףלפיקוחורשויכליירייה = "1203";  
       public const string אישורשירותיםוטרינריים = "121";  
       public const string אישורשירותיםלהגנתהצומח = "122";  
       public const string רשיוןהמרכזסחרחוץ = "123";  
       public const string אישורתקשורת = "1301";  
       public const string רשיוןע"פצומתןרשיונותיבוא193913 = "1302";  
       public const string רשיוןע"פצומתןרשיונותיבוא193914 = "1402";  
       public const string אישורמנכ"ל2 = "1403";  
       public const string אישורמנכ"לחינוך = "1501";  
       public const string רשיוןע"פצומתןרשיונותיבוא193915 = "1502";  
       public const string אישורמנכ"להמדעהתרבותוהספורט = "1601";  
       public const string אישוריבואמשרדהתרבותוהספורט = "1602";  
       public const string רשיוןע"פצומתןרשיונותיבוא193916 = "1603";  
       public const string אישורמנכ"לבינויושיכון = "1801";  
       public const string רשיוןע"פצומתןרשיונותיבוא193917 = "1802";  
       public const string רשיוןיבוא = "1901";  
       public const string רשיוןע"פצומתןרשיונותיבוא193918 = "1902";  
       public const string אישורמנכ"ל3 = "2001";  
       public const string אישוראגףהרכבושרותיתחזוקה-יבואמסחרי = "201";  
       public const string מעבדהלרכב = "204";  
       public const string מת"ימכוחתקנות = "205";  
       public const string טכניוןמכוחתקנות = "206";  
       public const string אישורמנכ"לתחבורה = "207";  
       public const string 2ג2-פטורמרישיון = "208";  
       public const string הועדההביןמשרדיתלהתקניתנועה = "209";  
       public const string רשיוןאגףהרכבושרותיתחזוקה-יבואמסחרי = "210";  
       public const string אישוררשותהעתיקות = "2101";  
       public const string רישיוןלסחרבמוצריתעבורה = "212";  
       public const string אישוריצוא = "2120";  
       public const string רישיוןלסחרבמערכותגפ"מלרכב = "213";  
       public const string רישיוןלסחרבצמיגים = "214";  
       public const string רשיוןאוטונומיה2 = "215";  
       public const string רשיוןע"פצומתןרשיונותיבוא19392 = "216";  
       public const string רישיוןאגףהרכבושרותיתחזוקה-יבואאישי = "217";  
       public const string אישוראגףהרכבושרותיתחזוקה-יבואאישי = "218";  
       public const string רשיוןיצוא(משרדהתחבורה) = "220";  
       public const string רשיוןאגףהרכבושירותיתחזוקה-צמ"ה = "221";  
       public const string אישור2ג2 = "301";  
       public const string אישורמידותומשקלות = "302";  
       public const string אישורמנכ"ל = "303";  
       public const string מב72 = "304";  
       public const string אישורתמ"ת = "305";  
       public const string אישורהמפקחעלהילומים = "307";  
       public const string רישיוןצי"חמנהלמוצריצריכה = "308";  
       public const string רישיוןצי"חמנהלהיהלומים = "309";  
       public const string רישיוןצי"חמחוזהמרכזבתמ"ת = "310";  
       public const string רישיוןמינהלסביבהופיתוחברקיימא = "311";  
       public const string 2ג2-פטורמרשיון = "313";  
       public const string רשיוןצי"ח2(ד)מכסותוהטליסחר = "314";  
       public const string רישיוןארצותאסורות-פקודתהמסחרעםהאויב = "315";  
       public const string רשיוןאוטונומיה3 = "316";  
       public const string רשיוןע"פצומתןרשיונותיבוא19393 = "317";  
       public const string אישורמפקח = "318";  
       public const string רשיוןיצוא-מינהלסביבהופיתוחברקיימא = "320";  
       public const string רשיוןדושימושי = "321";  
       public const string רשיוןהמפקחעלהיהלומים = "322";  
       public const string רשיוןתמ"תMTCR = "323";  
       public const string רשיוןתמ"תאב"כ = "324";  
       public const string אישורהמפקחעלהיהלומים = "325";  
       public const string אישורתמ"תמיוחד = "339";  
       public const string אישורלשחרור = "402";  
       public const string אישורמפמ"כ = "403";  
       public const string רשיוןע"פצומתןרשיונותיבוא19394 = "404";  
       public const string רשיוןיצוא(מכוןהתקנים) = "420";  
       public const string רשיוןהממונהעלהקרינה(מכוןהתקנים) = "421";  
       public const string אישורמנהל = "501";  
       public const string רשיוןע"פצומתןרשיונותיבוא19395 = "502";  
       public const string רישיוןיבואלפט"מ = "503";  
       public const string בדיקה = "504";  
       public const string אישורחומריםמסוכנים = "602";  
       public const string אישורממונהעלהקרינה = "603";  
       public const string תרשוםע"פתקנותתכשריםלהדברה = "604";  
       public const string רשיוןלתכשירלפיצותכשירים = "605";  
       public const string רשיוןע"פצומתןרשיונותיבוא19396 = "606";  
       public const string אישורמנכ"למשרדלהגנתהסביבה = "607";  
       public const string רשיוןהממונהעלהקרינה(הגנתהסביבה) = "620";  
       public const string אישורשירותהמזון = "701";  
       public const string אישוראגףהרוקחות = "702";  
       public const string אישוראמ"ר = "703";  
       public const string רשיוןאגףהרוקחות = "704";  
       public const string אישורשחרורתחנתמעבר = "705";  
       public const string אגףהרוקחות-רשיוןע"פצוהתמרוקים = "706";  
       public const string אישורמכשיריקרינה = "708";  
       public const string אישורמנכ"לבריאות = "709";  
       public const string אישוראגףהרוקחות-סמים = "710";  
       public const string רשיוןיבואמלשכתהבריאותבנפתרמלה = "711";  
       public const string רשיוןע"פצומתןרשיונותיבוא19397 = "712";  
       public const string אישור2ג2–אגףהרוקחות = "713";  
       public const string 2ג2–פטורמרישיוןאגףהרוקחות = "714";  
       public const string אישורביטחון = "801";  
       public const string אישורמנכ"לביטחון = "802";  
       public const string רשיוןע"פצומתןרשיונותיבוא19398 = "803";  
       public const string רשיוןלפיחוקהפיקוחעליצואבטחוני(ציודלחימה) = "820";  
       public const string רשיוןלפיחוקהפיקוחעליצואבטחוני(ציודMTCR) = "821";  
       public const string רשיוןלפיחוקהפיקוחעליצואבטחוני(דושימושימפוקח) = "822";  
       public const string רשיוןלפיחוקהפיקוחעליצואבטחוני(דושימושימפוקחהמועברלשטחיהאחריותהאזרחיתהפלשתינית) = "823";  
       public const string רשיוןלפיצוהפיקוחעלמצרכיםושירותים(עיסוקבאמצעיהצפנה) = "824";  
       public const string אישורוועדהלאנרגיהאטומית = "901";  
       public const string רשיוןע"פצומתןרשיונותיבוא19399 = "902";  
    }
}

