using System;
using System.ComponentModel.DataAnnotations;

namespace Simplog.Data.ShipmentsModel.EntityPOCOs
{
    public class DigitalShipmentsDataView
    {
        [Key]
        public string Id { get; set; }
        public int Tenant { get; set; }
        public double? ChargeableWeight { get; set; }
        public double? GrossWeight { get; set; }
        public double? Volume { get; set; }
        public double? ValueOfGoods { get; set; }
        public int? NumberOfPackages { get; set; }
        public string SalesmanUserId { get; set; }
        public string InlandDomesticFromZipCode { get; set; }
        public string InlandDomesticToZipCode { get; set; }
        public string InlandDomesticFromCity { get; set; }
        public string InlandDomesticToCity { get; set; }
        public string InlandDomesticFromCountryId { get; set; }
        public string InlandDomesticToCountryId { get; set; }
        public string InlandDomesticFromTypeCode { get; set; }
        public string InlandDomesticToTypeCode { get; set; }
        public string ShipmentLevelCode { get; set; }
        public string ShipmentLevelName { get; set; }
        public string ShipmentTypeId { get; set; }
        public string ShipmentTypeName { get; set; }
        public DateTime? Transshipment3ATD { get; set; }
        public DateTime? Transshipment3ATA { get; set; }
        public DateTime? Transshipment3ETD { get; set; }
        public DateTime? Transshipment3ETA { get; set; }
        public string Transshipment3FromPortId { get; set; }
        public string Transshipment3ToPortId { get; set; }
        public string Transshipment2FromPortId { get; set; }
        public string Transshipment1CarrierNumber { get; set; }
        public bool IsOperationalClosed { get; set; }
        public bool IsAccountingClosed { get; set; }
        public string Transshipment2ToPortId { get; set; }
        public string Transshipment2CarrierNumber { get; set; }
        public DateTime? Transshipment2ATD { get; set; }
        public DateTime? Transshipment2ATA { get; set; }
        public DateTime? Transshipment2ETD { get; set; }
        public DateTime? Transshipment2ETA { get; set; }
        public DateTime LastUpdateDate { get; set; }

        public string Transshipment1FromPortId { get; set; }
        public string Transshipment1ToPortId { get; set; }
        public DateTime? Transshipment1ATD { get; set; }
        public DateTime? Transshipment1ATA { get; set; }
        public DateTime? Transshipment1ETD { get; set; }
        public DateTime? Transshipment1ETA { get; set; }
        public string IncotermCode { get; set; }
        public string MainCarriageFinalDestinationCountryCode { get; set; }
        public string MainCarriageFinalDestinationCountryName { get; set; }

        public string ShipmentNumber { get; set; }
        public string CustomerReference1 { get; set; }
        public string CustomerReference2 { get; set; }
        public string CustomerReference3 { get; set; }
        public string ShipmentSubTypeId { get; set; }
        public string ShipmentSubTypeName { get; set; }
        public bool IsStandalonePickupDelivery { get; set; }
        public DateTime? CarrierLastStatusDate { get; set; }
        public string CustomerId { get; set; }
        public string AgentId { get; set; }
        public string TransportModeName { get; set; }
        public string DirectionName { get; set; }
        public string Master { get; set; }
        public bool IsCancelled { get; set; }
        public string ConsigneeId { get; set; }
        public string ShipperId { get; set; }
        public string ShipperCountryCode { get; set; }
        public string ConsigneeCountryCode { get; set; }
        public string DescriptionOfGoods { get; set; }
        public string DirectionId { get; set; }
        public DateTime CreateDateTime { get; set; }
        public DateTime? FirstPickupETA { get; set; }
        public DateTime? FirstPickupETD { get; set; }
        public string MainCarriageToPortName { get; set; }
        public string MainCarriageFromPortName { get; set; }
        public string MainCarriageFromPortCountryCode { get; set; }
        public string MainCarriageFromPortCountryName { get; set; }
        public DateTime? MainCarriageATD { get; set; }
        public DateTime? MainCarriageATA { get; set; }
        public DateTime? MainCarriageETD { get; set; }
        public DateTime? MainCarriageETA { get; set; }

        public string InlandDomesticToAddress1 { get; set; }
        public string InlandDomesticToAddress2 { get; set; }

        public string InlandDomesticToPhone { get; set; }
        public string InlandDomesticToFax { get; set; }
        public string InlandDomesticToStateName { get; set; }
        public string InlandDomesticToStateId { get; set; }
        public string InlandDomesticFromAddress1 { get; set; }
        public string InlandDomesticFromAddress2 { get; set; }
        public string InlandDomesticFromPhone { get; set; }
        public string InlandDomesticFromFax { get; set; }
        public string InlandDomesticFromStateName { get; set; }
        public string InlandDomesticFromStateId { get; set; }
        public int? NumberOfTransshipments { get; set; }
        public string Transshipments { get; set; }
        public DateTime? PreForwardingETD { get; set; }
        public DateTime? PreForwardingATD { get; set; }
        public DateTime? PreForwardingETA { get; set; }
        public DateTime? PreForwardingATA { get; set; }
        public DateTime? PreCarriageETD { get; set; }
        public DateTime? PreCarriageATD { get; set; }
        public DateTime? PreCarriageETA { get; set; }
        public DateTime? PreCarriageATA { get; set; }
        public DateTime? OnForwardingETD { get; set; }
        public DateTime? OnForwardingATD { get; set; }
        public DateTime? OnForwardingETA { get; set; }
        public DateTime? OnForwardingATA { get; set; }
        public DateTime? OnCarriageETD { get; set; }
        public DateTime? OnCarriageATD { get; set; }
        public DateTime? OnCarriageETA { get; set; }
        public DateTime? OnCarriageATA { get; set; }
        public string TransportModeId { get; set; }
        public string ShipperName { get; set; }
        public string ConsigneeName { get; set; }
        public string Transshipment1FromPortCountryCode { get; set; }
        public string Transshipment1FromPortCountryName { get; set; }
        public string Transshipment2FromPortCountryCode { get; set; }
        public string Transshipment2FromPortCountryName { get; set; }
        public string Transshipment3FromPortCountryCode { get; set; }
        public string Transshipment3FromPortCountryName { get; set; }
        public string Transshipment1ToPortCountryCode { get; set; }
        public string Transshipment1ToPortCountryName { get; set; }
        public string Transshipment2ToPortCountryCode { get; set; }
        public string Transshipment2ToPortCountryName { get; set; }
        public string Transshipment3ToPortCountryCode { get; set; }
        public string Transshipment3ToPortCountryName { get; set; }
        public string MainCarriageCarrierName { get; set; }
        public string MainCarriageCarrierCode { get; set; }
        public string Transshipment1CarrierName { get; set; }
        public string Transshipment1CarrierCode { get; set; }
        public string Transshipment2CarrierName { get; set; }
        public string Transshipment2CarrierCode { get; set; }
        public string Transshipment3CarrierName { get; set; }
        public string Transshipment3CarrierCode { get; set; }
        public string AccountManagerUserId { get; set; }
        public string AccountManagerUserName { get; set; }
        public string SalesmanUserName { get; set; }
        public string CreatedByUserName { get; set; }
        public string NextLegName { get; set; }
        public string NextLegCode { get; set; }
        public string MainCarriageFromCity { get; set; }
        public string MainCarriageToCity { get; set; }
        public DateTime? NextETD { get; set; }
        public DateTime? NextETA { get; set; }
        public DateTime? StatusDate { get; set; }
        public string ShipmentType { get; set; }
        public string FromPortId { get; set; }
        public string ToPortId { get; set; }
        public string FromPort { get; set; }
        public string FromPortName { get; set; }
        public string ToPort { get; set; }
        public string ToPortName { get; set; }
        public string CarrierNumber { get; set; }
        public DateTime? MainCarriageExpectedOrActual { get; set; }
        public string MainCarriageETAOrATA { get; set; }
        public string StatusId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int? StatusWeight { get; set; }
        public string StatusName { get; set; }
        public string StatusCode { get; set; }
        public string StatusLocation { get; set; }
        public string LongMaster { get; set; }
        public string MainCarriageFromPortId { get; set; }
        public string MainCarriageToPortId { get; set; }

        public string ShipperReference1 { get; set; }
        public string ShipperReference2 { get; set; }
        public string ConsigneeReference1 { get; set; }
        public string ConsigneeReference2 { get; set; }
        public string MainCarriageCarrierNumber { get; set; }
        public string MainCarriageCarrierId { get; set; }
        public string House { get; set; }
        public string AgentName { get; set; }

        public string CustomAgentImportName { get; set; }
        public string CustomerName { get; set; }

        public string MainCarriageFromPortCode { get; set; }
        public string MainCarriageToPortCode { get; set; }
        public string MainCarriageToPortCountryCode { get; set; }
        public string MainCarriageToPortCountryName { get; set; }
        public string MainCarriageFromPartnerId { get; set; }
        public string MainCarriageToPartnerId { get; set; }
        public string ToPortCountryCode { get; set; }
        public string FromPortCountryCode { get; set; }
        public string IncotermId { get; set; }
        public string FromPortCountryName { get; set; }
        public string ToPortCountryName { get; set; }
        public string ToPortCode { get; set; }
        public string FromPortCode { get; set; }
        public string MainCarriageFromCountryCode { get; set; }
        public string MainCarriageToCountryCode { get; set; }
        public string MainCarriageFromAddressId { get; set; }
        public string MainCarriageToAddressId { get; set; }
        public DateTime? MainCarriageFinalDestinationETA { get; set; }
        public DateTime? MainCarriageFinalDestinationATA { get; set; }
        public DateTime? DepartureArrivalFromDate { get; set; }
        public DateTime? DepartureArrivalToDate { get; set; }
        public string FromCountryCode { get; set; }
        public string ToCountryCode { get; set; }
        public string MasterShipmentDataId { get; set; }
        public bool IsCustomerArchived { get; set; }
    }
}