using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using Simplog.Data.QuoteModel.EntityPOCOs;

namespace Simplog.Data.QuoteModel.Mapping
{
    public class QuoteMap : EntityTypeConfiguration<Quote>
    {
        public QuoteMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id).IsRequired().HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.QuoteNumber).IsRequired().HasMaxLength(20).IsUnicode(false);
            this.Property(t => t.ShipperReference1).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.QuoteTemplateId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ShipperReference2).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.ConsigneeReference1).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.ConsigneeReference2).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.LastVersionNumber).IsRequired();
            this.Property(t => t.Notes).HasMaxLength(500).IsUnicode(true);
            this.Property(t => t.DescriptionOfGoods).HasMaxLength(512).IsUnicode(false);
         
            //#if ORACLE_DB
            string dbms = System.Configuration.ConfigurationManager.AppSettings.Get("DBMS");
            if (dbms == "oracle")
            {
                this.Property(t => t.LastModified).IsRequired().IsFixedLength().HasMaxLength(8);
            }
            //#else
            else
            {
                this.Property(t => t.LastModified).IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion();
            }
//#endif
            //.IsRowVersion();

            this.Property(t => t.Field1).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field2).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field3).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field4).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field5).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field6).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field7).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field8).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field9).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field10).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.DimensionsUnitCode).HasMaxLength(3).IsUnicode(false);          
            this.Property(t => t.GrossWeightUnitCode).HasMaxLength(3).IsUnicode(false);           
            this.Property(t => t.VolumeUnitCode).HasMaxLength(3).IsUnicode(false);
            this.Property(t => t.ShipmentTypeId).HasMaxLength(4).IsUnicode(false);
            this.Property(t => t.ShipperId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ConsigneeId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ShipperContactId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ConsigneeContactId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.FromPortId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ToPortId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.IncotermId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.SalesmanUserId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.CreatedByUserId).IsRequired().HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.DirectionId).IsRequired().IsFixedLength().HasMaxLength(1).IsUnicode(false);
            this.Property(t => t.TransportModeId).IsRequired().IsFixedLength().HasMaxLength(1).IsUnicode(false);
            this.Property(t => t.BranchId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.DepartmentId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.PackageType1Id).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.PackageType2Id).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.PackageType3Id).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.PackageType4Id).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.PackageType5Id).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.QuoteTypeCode).IsRequired().HasMaxLength(1).IsUnicode(false);
            this.Property(t => t.MainCarriageCarrierId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.CustomerId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.CustomerContactId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.CustomerReference1).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.CustomerReference2).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.QuoteCustomerTypeCode).IsRequired().HasMaxLength(4).IsUnicode(false);
            this.Property(t => t.CustomerName).IsRequired().HasMaxLength(100).IsUnicode(true);
            this.Property(t => t.SaleCurrencyId).IsRequired().HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ShipperName).HasMaxLength(100).IsUnicode(true);
            this.Property(t => t.ConsigneeName).HasMaxLength(100).IsUnicode(true);
            this.Property(t => t.PickUpAddress).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.DeliveryAddress).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.SearchFields).HasMaxLength(1500).IsUnicode(true);
            this.Property(t => t.ChargeableWeightUnitCode).HasMaxLength(3).IsUnicode(false);
            this.Property(t => t.ConcurrencyGUID).IsRequired().HasMaxLength(40).IsUnicode(false);
            this.Property(t => t.FromPartnerId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ToPartnerId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.FromPartnerAddressId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ToPartnerAddressId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.FromAddressId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.FromAddressCountryId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.FromAddressCity).HasMaxLength(25).IsUnicode(true);
            this.Property(t => t.FromAddressZipCode).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ToAddressId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ToAddressCountryId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ToAddressCity).HasMaxLength(25).IsUnicode(true);
            this.Property(t => t.ToAddressZipCode).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.QuoteClosingReasonCode).HasMaxLength(2).IsUnicode(false);
            this.Property(t => t.FreelancerAddressId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.FreelancerId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.FreelancerContactId).HasMaxLength(15).IsUnicode(false);
            this.Property(d => d.BusinessUnitId).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.Subject).HasMaxLength(200).IsUnicode(true);
            this.Property(d => d.StageId).IsRequired().HasMaxLength(15).IsUnicode(false);
            this.Property(d => d.RatingCode).IsRequired().HasMaxLength(1).IsUnicode(false);
            this.Property(d => d.LastActivityTypeCode).HasMaxLength(2).IsUnicode(false);
            this.Property(d => d.NextActivityTypeCode).HasMaxLength(2).IsUnicode(false);
            this.Property(d => d.LastActivitySubject).HasMaxLength(255).IsUnicode(true);
            this.Property(d => d.NextActivitySubject).HasMaxLength(255).IsUnicode(true);
            this.Property(t => t.OpportunityId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.UpdatedByUserId).IsRequired().HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ProductCode).HasMaxLength(2).IsUnicode(false);
            this.Property(t => t.TransitTime).HasMaxLength(30).IsUnicode(true);
            this.Property(t => t.DepartureFrequency).HasMaxLength(30).IsUnicode(true);
            this.Property(t => t.AgentId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.AgentAddressId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.AgentContactId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.AgentReference1).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.AgentReference2).HasMaxLength(50).IsUnicode(false);
            this.Property(t => t.MoveTypeId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.ValueOfGoodsCurrencyId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.QuotationSections).HasMaxLength(500).IsUnicode(false);
            this.Property(t => t.NotifyId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.NotifyAddressId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.NotifyContactId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.QuoteHTMLDocumentId).HasMaxLength(15).IsUnicode(false);
            this.Property(t => t.Field11).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field12).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field13).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field14).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field15).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field16).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field17).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field18).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field19).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.Field20).HasMaxLength(250).IsUnicode(true);
            this.Property(t => t.CountryForStatisticsId).HasMaxLength(15).IsUnicode(false);

            // Table & Column Mappings
            this.ToTable("Quotes");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.Tenant).HasColumnName("Tenant");
            this.Property(t => t.QuoteNumber).HasColumnName("QuoteNumber");
            this.Property(t => t.ShipperReference1).HasColumnName("ShipperReference1");
            this.Property(t => t.ShipperReference2).HasColumnName("ShipperReference2");
            this.Property(t => t.ConsigneeReference1).HasColumnName("ConsigneeReference1");
            this.Property(t => t.ConsigneeReference2).HasColumnName("ConsigneeReference2");
            this.Property(t => t.OpenDate).HasColumnName("OpenDate");
            this.Property(t => t.Notes).HasColumnName("Notes");
            this.Property(t => t.DescriptionOfGoods).HasColumnName("DescriptionOfGoods");
            this.Property(t => t.IsClosed).HasColumnName("IsClosed");
            this.Property(t => t.ChargeableWeight).HasColumnName("ChargeableWeight");
            this.Property(t => t.GrossWeight).HasColumnName("GrossWeight");
            this.Property(t => t.ChargeableWeightInKG).HasColumnName("ChargeableWeightInKG");
            this.Property(t => t.VolumeInCBM).HasColumnName("VolumeInCBM");
            this.Property(t => t.LastModified).HasColumnName("LastModified");
            this.Property(t => t.Field1).HasColumnName("Field1");
            this.Property(t => t.Field2).HasColumnName("Field2");
            this.Property(t => t.Field3).HasColumnName("Field3");
            this.Property(t => t.Field4).HasColumnName("Field4");
            this.Property(t => t.Field5).HasColumnName("Field5");
            this.Property(t => t.Field6).HasColumnName("Field6");
            this.Property(t => t.Field7).HasColumnName("Field7");
            this.Property(t => t.Field8).HasColumnName("Field8");
            this.Property(t => t.Field9).HasColumnName("Field9");
            this.Property(t => t.Field10).HasColumnName("Field10");
            this.Property(t => t.DimensionsUnitCode).HasColumnName("DimensionsUnitCode");
            this.Property(t => t.GrossWeightUnitCode).HasColumnName("GrossWeightUnitCode");
            this.Property(t => t.Volume).HasColumnName("Volume");
            this.Property(t => t.NumberOfContainers).HasColumnName("NumberOfContainers");
            this.Property(t => t.NumberOfPackages).HasColumnName("NumberOfPackages");
            this.Property(t => t.Ratio).HasColumnName("Ratio");
            this.Property(t => t.DimFactor).HasColumnName("DimFactor");
            this.Property(t => t.VolumeUnitCode).HasColumnName("VolumeUnitCode");
            this.Property(t => t.ShipmentTypeId).HasColumnName("ShipmentTypeId");
            this.Property(t => t.ShipperId).HasColumnName("ShipperId");
            this.Property(t => t.ConsigneeId).HasColumnName("ConsigneeId");
            this.Property(t => t.ShipperContactId).HasColumnName("ShipperContactId");
            this.Property(t => t.ConsigneeContactId).HasColumnName("ConsigneeContactId");
            this.Property(t => t.FromPortId).HasColumnName("FromPortId");
            this.Property(t => t.ToPortId).HasColumnName("ToPortId");
            this.Property(t => t.IncotermId).HasColumnName("IncotermId");
            this.Property(t => t.SalesmanUserId).HasColumnName("SalesmanUserId");
            this.Property(t => t.CreatedByUserId).HasColumnName("CreatedByUserId");
            this.Property(t => t.DirectionId).HasColumnName("DirectionId");
            this.Property(t => t.TransportModeId).HasColumnName("TransportModeId");
            this.Property(t => t.IsDangerous).HasColumnName("IsDangerous");
            this.Property(t => t.ExpirationDays).HasColumnName("ExpirationDays");
            this.Property(t => t.ExpirationDate).HasColumnName("ExpirationDate");
            this.Property(t => t.StartDate).HasColumnName("StartDate");
            this.Property(t => t.VolumetricWeight).HasColumnName("VolumetricWeight");
            this.Property(t => t.BranchId).HasColumnName("BranchId");
            this.Property(t => t.DepartmentId).HasColumnName("DepartmentId");
            this.Property(t => t.PackageType1Id).HasColumnName("PackageType1Id");
            this.Property(t => t.PackageType2Id).HasColumnName("PackageType2Id");
            this.Property(t => t.PackageType3Id).HasColumnName("PackageType3Id");
            this.Property(t => t.PackageType4Id).HasColumnName("PackageType4Id");
            this.Property(t => t.PackageType5Id).HasColumnName("PackageType5Id");
            this.Property(t => t.PackageType1Quantity).HasColumnName("PackageType1Quantity");
            this.Property(t => t.PackageType2Quantity).HasColumnName("PackageType2Quantity");
            this.Property(t => t.PackageType3Quantity).HasColumnName("PackageType3Quantity");
            this.Property(t => t.PackageType4Quantity).HasColumnName("PackageType4Quantity");
            this.Property(t => t.PackageType5Quantity).HasColumnName("PackageType5Quantity");
            this.Property(t => t.IsByKG).HasColumnName("IsByKG");
            this.Property(t => t.IsByContainer).HasColumnName("IsByContainer");
            this.Property(t => t.QuoteTypeCode).HasColumnName("QuoteTypeCode");
            this.Property(t => t.EstimateProfit).HasColumnName("EstimateProfit");
            this.Property(t => t.EstimateProfitEdited).HasColumnName("EstimateProfitEdited");
            this.Property(t => t.MinimumFreightCost).HasColumnName("MinimumFreightCost");
            this.Property(t => t.MinimumFreightSale).HasColumnName("MinimumFreightSale");
            this.Property(t => t.MainCarriageCarrierId).HasColumnName("MainCarriageCarrierId");
            this.Property(t => t.IsFreightBySteps).HasColumnName("IsFreightBySteps");
            this.Property(t => t.IsCancelled).HasColumnName("IsCancelled");
            this.Property(t => t.CustomerId).HasColumnName("CustomerId");
            this.Property(t => t.CustomerContactId).HasColumnName("CustomerContactId");
            this.Property(t => t.CustomerReference1).HasColumnName("CustomerReference1");
            this.Property(t => t.CustomerReference2).HasColumnName("CustomerReference2");
            this.Property(t => t.QuoteCustomerTypeCode).HasColumnName("QuoteCustomerTypeCode");
            this.Property(t => t.CustomerName).HasColumnName("CustomerName");
            this.Property(t => t.SaleCurrencyId).HasColumnName("SaleCurrencyId");
            this.Property(t => t.ExchangeRate).HasColumnName("ExchangeRate");
            this.Property(t => t.ShipperName).HasColumnName("ShipperName");
            this.Property(t => t.ConsigneeName).HasColumnName("ConsigneeName");
            this.Property(t => t.PickUpAddress).HasColumnName("PickUpAddress");
            this.Property(t => t.DeliveryAddress).HasColumnName("DeliveryAddress");
            this.Property(t => t.IsFixedPrice).HasColumnName("IsFixedPrice");
            this.Property(t => t.IsSaleCurrencySameAsCost).HasColumnName("IsSaleCurrencySameAsCost");
            this.Property(t => t.SearchFields).HasColumnName("SearchFields");
            this.Property(t => t.ChargeableWeightUnitCode).HasColumnName("ChargeableWeightUnitCode");
            this.Property(t => t.ConcurrencyGUID).HasColumnName("ConcurrencyGUID");
            this.Property(t => t.FromPartnerId).HasColumnName("FromPartnerId");
            this.Property(t => t.ToPartnerId).HasColumnName("ToPartnerId");
            this.Property(t => t.FromPartnerAddressId).HasColumnName("FromPartnerAddressId");
            this.Property(t => t.ToPartnerAddressId).HasColumnName("ToPartnerAddressId");
            this.Property(t => t.IncludePickUp).HasColumnName("IncludePickUp");
            this.Property(t => t.FromAddressId).HasColumnName("FromAddressId");
            this.Property(t => t.FromAddressCountryId).HasColumnName("FromAddressCountryId");
            this.Property(t => t.FromAddressCity).HasColumnName("FromAddressCity");
            this.Property(t => t.FromAddressZipCode).HasColumnName("FromAddressZipCode");
            this.Property(t => t.IncludeDelivery).HasColumnName("IncludeDelivery");
            this.Property(t => t.ToAddressId).HasColumnName("ToAddressId");
            this.Property(t => t.ToAddressCountryId).HasColumnName("ToAddressCountryId");
            this.Property(t => t.ToAddressCity).HasColumnName("ToAddressCity");
            this.Property(t => t.ToAddressZipCode).HasColumnName("ToAddressZipCode");
            this.Property(t => t.QuoteTemplateId).HasColumnName("QuoteTemplateId");
            this.Property(t => t.UsageCount).HasColumnName("UsageCount");
            this.Property(t => t.LastUsageDate).HasColumnName("LastUsageDate");
            this.Property(t => t.QuoteClosingReasonCode).HasColumnName("QuoteClosingReasonCode");
            this.Property(t => t.SentDate).HasColumnName("SentDate");
            this.Property(t => t.AcceptedDate).HasColumnName("AcceptedDate");
            this.Property(t => t.DeclinedDate).HasColumnName("DeclinedDate");
            this.Property(t => t.FreelancerId).HasColumnName("FreelancerId");
            this.Property(t => t.FreelancerAddressId).HasColumnName("FreelancerAddressId");
            this.Property(t => t.FreelancerContactId).HasColumnName("FreelancerContactId");
            this.Property(t => t.BusinessUnitId).HasColumnName("BusinessUnitId");
            this.Property(t => t.Subject).HasColumnName("Subject");
            this.Property(t => t.IsSubjectEdited).HasColumnName("IsSubjectEdited");
            this.Property(t => t.StageId).HasColumnName("StageId");
            this.Property(t => t.StageDueDate).HasColumnName("StageDueDate");
            this.Property(t => t.RatingCode).HasColumnName("RatingCode");
            this.Property(t => t.LastActivityTypeCode).HasColumnName("LastActivityTypeCode");
            this.Property(t => t.LastActivitySubject).HasColumnName("LastActivitySubject");
            this.Property(t => t.NextActivityTypeCode).HasColumnName("NextActivityTypeCode");
            this.Property(t => t.NextActivitySubject).HasColumnName("NextActivitySubject");
            this.Property(t => t.LastActivityDate).HasColumnName("LastActivityDate");
            this.Property(t => t.NextActivityDate).HasColumnName("NextActivityDate");
            this.Property(t => t.OpportunityId).HasColumnName("OpportunityId");
            this.Property(t => t.IsAutomaticallyClosed).HasColumnName("IsAutomaticallyClosed");
            this.Property(t => t.AutomaticallyCloseDate).HasColumnName("AutomaticallyCloseDate");
            this.Property(t => t.AutomaticallyCloseDays).HasColumnName("AutomaticallyCloseDays");
            this.Property(t => t.UpdateDate).HasColumnName("UpdateDate");
            this.Property(t => t.UpdatedByUserId).HasColumnName("UpdatedByUserId");
            this.Property(t => t.ProductCode).HasColumnName("ProductCode");
            this.Property(t => t.TransitTime).HasColumnName("TransitTime");
            this.Property(t => t.DepartureFrequency).HasColumnName("DepartureFrequency");
            this.Property(t => t.ETD).HasColumnName("ETD");
            this.Property(t => t.ETA).HasColumnName("ETA");
            this.Property(t => t.LastStageDate).HasColumnName("LastStageDate");
            this.Property(t => t.AgentId).HasColumnName("AgentId");
            this.Property(t => t.AgentAddressId).HasColumnName("AgentAddressId");
            this.Property(t => t.AgentContactId).HasColumnName("AgentContactId");
            this.Property(t => t.AgentReference1).HasColumnName("AgentReference1");
            this.Property(t => t.AgentReference2).HasColumnName("AgentReference2");
            this.Property(t => t.MoveTypeId).HasColumnName("MoveTypeId");
            this.Property(t => t.TEU).HasColumnName("TEU");
            this.Property(t => t.ValueOfGoods).HasColumnName("ValueOfGoods");
            this.Property(t => t.ValueOfGoodsCurrencyId).HasColumnName("ValueOfGoodsCurrencyId");
            this.Property(t => t.IsChargesByVAT).HasColumnName("IsChargesByVAT");
            this.Property(t => t.TotalPerContainer).HasColumnName("TotalPerContainer");
            this.Property(t => t.IsQuoteDataExternal).HasColumnName("IsQuoteDataExternal");
            this.Property(t => t.IsQuoteDocumentExternal).HasColumnName("IsQuoteDocumentExternal");
            this.Property(t => t.QuotationSections).HasColumnName("QuotationSections");
            this.Property(t => t.GrossWeightInKG).HasColumnName("GrossWeightInKG");
            this.Property(t => t.GrossWeightPerTon).HasColumnName("GrossWeightPerTon");
            this.Property(t => t.NotifyId).HasColumnName("NotifyId");
            this.Property(t => t.NotifyAddressId).HasColumnName("NotifyAddressId");
            this.Property(t => t.NotifyContactId).HasColumnName("NotifyContactId");
            this.Property(t => t.NumberOfFollowUps).HasColumnName("NumberOfFollowUps");
            this.Property(t => t.GrossWeightEdited).HasColumnName("GrossWeightEdited");
            this.Property(t => t.ChargeableWeightEdited).HasColumnName("ChargeableWeightEdited");
            this.Property(t => t.QuoteHTMLDocumentId).HasColumnName("QuoteHTMLDocumentId");
            this.Property(t => t.Field11).HasColumnName("Field11");
            this.Property(t => t.Field12).HasColumnName("Field12");
            this.Property(t => t.Field13).HasColumnName("Field13");
            this.Property(t => t.Field14).HasColumnName("Field14");
            this.Property(t => t.Field15).HasColumnName("Field15");
            this.Property(t => t.Field16).HasColumnName("Field16");
            this.Property(t => t.Field17).HasColumnName("Field17");
            this.Property(t => t.Field18).HasColumnName("Field18");
            this.Property(t => t.Field19).HasColumnName("Field19");
            this.Property(t => t.Field20).HasColumnName("Field20");
            this.Property(t => t.CountryForStatisticsId).HasColumnName("CountryForStatisticsId");
            this.Property(t => t.RequestDate).HasColumnName("RequestDate");
            this.Property(t => t.EstimatedProfitInLocal).HasColumnName("EstimatedProfitInLocal");
            this.Property(t => t.EstimatedProfitInProfit).HasColumnName("EstimatedProfitInProfit");

            // Relationships
            this.HasOptional(t => t.FromPartnerAddress).WithMany().HasForeignKey(d => d.FromPartnerAddressId);
            this.HasOptional(t => t.ToPartnerAddress).WithMany().HasForeignKey(d => d.ToPartnerAddressId);
            this.HasOptional(t => t.Branch).WithMany().HasForeignKey(d => d.BranchId);
            this.HasOptional(t => t.ConsigneeCard).WithMany().HasForeignKey(d => d.ConsigneeId);
            this.HasOptional(t => t.ShipperCard).WithMany().HasForeignKey(d => d.ShipperId);
            this.HasOptional(t => t.CustomerCard).WithMany().HasForeignKey(d => d.CustomerId);
            this.HasOptional(t => t.FromPartnerCard).WithMany().HasForeignKey(d => d.FromPartnerId);
            this.HasOptional(t => t.MainCarriageCarrierCard).WithMany().HasForeignKey(d => d.MainCarriageCarrierId);
            this.HasOptional(t => t.ToPartnerCard).WithMany().HasForeignKey(d => d.ToPartnerId);
            this.HasOptional(t => t.ConsigneeContact).WithMany().HasForeignKey(d => d.ConsigneeContactId);
            this.HasOptional(t => t.ShipperContact).WithMany().HasForeignKey(d => d.ShipperContactId);
            this.HasOptional(t => t.CustomerContact).WithMany().HasForeignKey(d => d.CustomerContactId);
            this.HasRequired(t => t.SaleCurrency).WithMany().HasForeignKey(d => d.SaleCurrencyId);
            this.HasOptional(t => t.Department).WithMany().HasForeignKey(d => d.DepartmentId);
            this.HasOptional(t => t.Incoterm).WithMany().HasForeignKey(d => d.IncotermId);
            this.HasOptional(t => t.PackageType2).WithMany().HasForeignKey(d => d.PackageType2Id);
            this.HasOptional(t => t.PackageType3).WithMany().HasForeignKey(d => d.PackageType3Id);
            this.HasOptional(t => t.PackageType4).WithMany().HasForeignKey(d => d.PackageType4Id);
            this.HasOptional(t => t.PackageType5).WithMany().HasForeignKey(d => d.PackageType5Id);
            this.HasOptional(t => t.PackageType1).WithMany().HasForeignKey(d => d.PackageType1Id);
            this.HasOptional(t => t.FromPort).WithMany().HasForeignKey(d => d.FromPortId);
            this.HasOptional(t => t.ToPort).WithMany().HasForeignKey(d => d.ToPortId);
            this.HasRequired(t => t.CreatedByUser).WithMany().HasForeignKey(d => d.CreatedByUserId);
            this.HasOptional(t => t.ShipmentType).WithMany().HasForeignKey(d => d.ShipmentTypeId);
            this.HasOptional(t => t.SalesmanUser).WithMany().HasForeignKey(d => d.SalesmanUserId);
            this.HasOptional(t => t.PickUpAddressEntity).WithMany().HasForeignKey(d => d.FromAddressId);
            this.HasOptional(t => t.DeliveryAddressEntity).WithMany().HasForeignKey(d => d.ToAddressId); 
            this.HasOptional(t => t.FromAddressCountry).WithMany().HasForeignKey(d => d.FromAddressCountryId);            
            this.HasOptional(t => t.ToAddressCountry).WithMany().HasForeignKey(d => d.ToAddressCountryId);
            this.HasOptional(t => t.QuoteTemplate).WithMany().HasForeignKey(d => d.QuoteTemplateId);
            this.HasOptional(t => t.QuoteClosingReason).WithMany().HasForeignKey(d => d.QuoteClosingReasonCode);
            this.HasOptional(t => t.FreelancerCard).WithMany().HasForeignKey(d => d.FreelancerId);
            this.HasOptional(t => t.FreelancerContact).WithMany().HasForeignKey(d => d.FreelancerContactId);
            this.HasOptional(t => t.FreelancerAdress).WithMany().HasForeignKey(d => d.FreelancerAddressId);
            this.HasRequired(t => t.BusinessUnit).WithMany().HasForeignKey(d => d.BusinessUnitId);

            this.HasRequired(t => t.Stage).WithMany().HasForeignKey(d => d.StageId);
            this.HasRequired(t => t.Rating).WithMany().HasForeignKey(d => d.RatingCode);

            this.HasRequired(t => t.UpdatedByUser).WithMany().HasForeignKey(d => d.UpdatedByUserId);
            this.HasOptional(t => t.AgentCard).WithMany().HasForeignKey(d => d.AgentId);
            this.HasOptional(t => t.AgentContact).WithMany().HasForeignKey(d => d.AgentContactId);
            this.HasOptional(t => t.AgentAddress).WithMany().HasForeignKey(d => d.AgentAddressId);
            this.HasOptional(t => t.MoveType).WithMany().HasForeignKey(d => d.MoveTypeId);
            this.HasOptional(t => t.ValueOfGoodsCurrency).WithMany().HasForeignKey(d => d.ValueOfGoodsCurrencyId);

            this.HasOptional(t => t.NotifyCard).WithMany().HasForeignKey(d => d.NotifyId);
            this.HasOptional(t => t.NotifyAddress).WithMany().HasForeignKey(d => d.NotifyAddressId);
            this.HasOptional(t => t.NotifyContact).WithMany().HasForeignKey(d => d.NotifyContactId);

            this.HasOptional(t => t.QuoteHTMLDocument).WithMany().HasForeignKey(d => d.QuoteHTMLDocumentId);
            this.HasOptional(t => t.CountryForStatistics).WithMany().HasForeignKey(d => d.CountryForStatisticsId);
        }
    }
}
